### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#1]
After install the framework with wordpress default theme twentyfifteen Found this fatal error !!

Fatal error: Can't use method return value in write context in F:\xammp\htdocs\lab\wp-content\themes\twentyfifteen\cs-framework\fields\icon\icon.php on line 20

**Comment by Codestar** [comment]
Hi,

Thanks for report issue, hmm i made an update on dev branch. Download dev branch via https://github.com/Codestar/codestar-framework/archive/dev.zip and tell me the result. if it is ok i will update on master ;)

Regards, Codestar

**Comment by devariya** [comment]
Yes the fatal error is gone :)

**Comment by Codestar** [comment]
Oh nice ;)
