### ISSUE TITLE
A couple of questions about the framework

### ISSUE THREAD

**Issue by binaryfire** [Codestar/codestar-framework#100]
Hi guys

I'm interested in getting the pro version but had a couple of questions. 

1. Does your Customizer feature include postmessage support?

2. Does your Customizer feature support all normal Customizer hooks and filters? For example https://developer.wordpress.org/reference/hooks/customize_save_after/ 

3. On your demo I only see **px** and **em** in your fields. Do you have a **rem** option as well? And if yes, can it be used in _all_ your field types (eg. typography)? New CSS frameworks like Tailwind use rem for everything.

4. ACF includes support for showing options pages on the frontend. Is it possible to display Codestar options pages on the front end too?

5. Can options be saved as both arrays (single entry in wp_options) or separate entries?

6. Can we specify the wp_options field name ourselves? For example if we want to map a field to an existing option for another plugin.

Thanks!

**Comment by Codestar** [comment]
Hi,

Thanks for interested the framework.

1. **Yes**: It's possible. ([take a look](http://codestarframework.com/documentation/#/faq?id=how-to-use-customizer-js))
2. **Yes**: You can use that filters.
3. **Yes**. It's possible with unit => 'em' parameter.
4. **No**: It's not possible.
5. **No**: It's not possible.
6. **Yes/No**: This question looks similar 5th. Let me give detail, wp_options option db name is unique and set by yourself. Each field can not be separately, all fields are saves inside one wp_options table as serialize.

Regards, Codestar

**Comment by binaryfire** [comment]
@Codestar Thank for replying so quickly!

For question (3) you said "It's possible with unit => 'em' parameter."  Did you mean to say unit => '**rem**' parameter? I'd like to use rem for everything, not em.

Is it possible to use tabs (http://codestarthemes.com/plugins/codestar-framework/wp-admin/admin.php?page=csf-demo#tab=combine-fields/tabbed) inside the Customizer?

And also I wanted to confirm: in an admin settings page with lots of sub-menus and tabs, only fields which have changed will be saved. Is that correct?

**Comment by Codestar** [comment]
Hi,

You're welcome ;)

- Ups yes, **unit => 'px', 'em', 'rem', '%'** are available.

- Yes of course, all fields are compatible with the customizer. Also all fields can be used every framework type (metabox, nav menu, taxonomy, profile, widget, comment, shortcode frameworks as well. This is one of the most important feature of framework).

- No, All options are saving at the same time when you click to save. Actually, you know it's only css tab system, in background all are combined. I didn't get any issue about this till now. It's saves to db fastly.

Regards

**Comment by binaryfire** [comment]
My users will mostly access wp-admin on mobile.

I noticed problems with mobile responsiveness in your demo. The CSF menu disappears on mobile (which is fine). But then the links in the WP admin menu stop working. Could you fix this?

Could you add an option to disable the side menu completely? I'd like to create some frameworks using all tabbed sections or accordians. I'm going for a minimalistic look, and this will also be better for mobile.

**Comment by Codestar** [comment]
Hi,

 - Hmm, yes there is a minor-bug. CSF menu disappears it's normal but wp admin menu stop works isn't normal. I noted and will fix it in the next update.
 - Yes, there is an option like this: **'menu_hidden' => true** but don't miss each frameworks has own unique db option name. I mean **get_option** calling will different for each frameworks. You can not seperate one framework to custom sub menus. ( try it on free-version )

Regards

**Comment by binaryfire** [comment]
Great! That's all the questions I have for the moment. Thanks for fixing the wp-admin menu problem in the next update.

I'll close this issue now. Will be buying the premium version soon :)

**Comment by Codestar** [comment]
Cheers, have a nice day... :+1:
