### ISSUE TITLE
Request: size for background option

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#101]
Hi, 

Could you please add <b>background-size</b> field for background option. Sometimes we need add this:

<pre>background-size: cover</pre>

**Comment by Codestar** [comment]
Hi,

Oh yes, also i need this. Ok follow updates.

```
background-size: auto|length|cover|contain|initial|inherit;
```

coming this options.  I noted this.

**Comment by Theme20** [comment]
Thanks :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by Codestar** [comment]
Btw, you can use this gist until update framework. take a look 

```cs-framework/fields/background/background.php``` https://gist.github.com/Codestar/73bc88aa7d902bdbcdb5#file-background-php-L92-L112

**Comment by Theme20** [comment]
Thanks man :+1: Excellent

In next release improve style of this option in customizer: https://docs.google.com/file/d/0B7q-ingsr5hKSjdXYlFSNzhJRUU/edit

**Comment by Codestar** [comment]
Yes, also i am improve background option in customizer. it will be useful for users :wink:

**Comment by Codestar** [comment]
Hey btw i want to show this for customizer, i am using this idea in my theme customizer backgrounds settings <a href="https://db.tt/TVmSdhxa">https://db.tt/TVmSdhxa</a> this is easy-understand for beginner clients.

**Comment by Theme20** [comment]
:+1: nice, this is much better understandable

**Comment by Codestar** [comment]
:+1:

**Comment by Codestar** [comment]
Hi @Codevz 

Background size option added for next update see https://github.com/Codestar/codestar-framework/commit/c7bb2cd0a170ff43f01a43049f184f91b3f51a5b

Have a nice day.

**Comment by Codevz** [comment]
HI @Codestar 

Thanks man this is what i needed :tada: :+1:

**Comment by Codestar** [comment]
You're welcome :tada:
