### ISSUE TITLE
Show message and do not save and hang

### ISSUE THREAD

**Issue by ali110309** [Codestar/codestar-framework#101]
Hello
When I click on the "Save" button, a message is displayed below and the page hangs by clicking "OK"

message:

function(){return u(n),r.apply(this,arguments)}

I am using the free version, please help.

**Comment by Codestar** [comment]
Hi,

You can try to disable ajax save. Add below parameter to your framework initial config.

```php
'ajax_save' => false,
```

The page will refresh when every click to save.

Regards

**Comment by 1910521702** [comment]
这个问题非常简单， 你的防火墙屏蔽了post过滤，把他关闭即可
