### ISSUE TITLE
Typography: font-style not Working

### ISSUE THREAD

**Issue by HeyMehedi** [Codestar/codestar-framework#102]
**I can see the Label for font-weight is showing 'Font Style',**

![image](https://user-images.githubusercontent.com/43073560/115337343-9e825100-a1c2-11eb-970b-a5c39a7a028f.png)

_Here is my code:_
```php
array(
  'id'              => 'typo_body',
  'type'            => 'typography',
  'title'           => esc_html__( 'Body', 'dlawyers' ),
  'text_align'      => false,
  'letter_spacing'  => false,
  'color'           => false,
  'word_spacing'    => false,
  'subset'          => false,
  'text_transform'  => false,
  'font_style'      => true,
  'default'         => array(
	  'font-family' => 'Nunito Sans',
	  'font-weight' => '400',
	  'font-size'   => '16',
	  'line-height' => '28',
	  'font-style'  => 'normal',
  ),
),
```

**Comment by Codestar** [comment]
The "style" word coming google webfonts. for eg:

Weight only mean 400,500,700 etc. But there is "italic" setting. that is why "font style"...

![image](https://user-images.githubusercontent.com/1313301/115383210-39d4ef80-a1de-11eb-9dee-70ff3413974f.png)

**Comment by Codestar** [comment]
btw, `'font-style'  => 'normal',` is default already. when you set it as `'font-style'  => 'italic',` you will see the different in output css.
