### ISSUE TITLE
Request: checkbox list scroll

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#102]
Hi, 

For example sometimes we need to add option for select tags or categories and we have a lot of options, so is better if big lists comes in the box with scroll: https://docs.google.com/file/d/0B7q-ingsr5hKVDlmdjNNQi1DMkU/

**Comment by Codestar** [comment]
Hi,

Yes it is easy. i added it now. waiting for update on github. btw, ```max-height: 300px``` is enough ?

**Comment by Theme20** [comment]
Thanks, Yes its good.

**Comment by Codestar** [comment]
Done, you will see it next commit :wink:
