### ISSUE TITLE
Q: Add new config file to another plugin

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#103]
Hi CodeStar, 

Is there anyway to add metabox config file inside another plugin ?

For example i have cs-framework + override config file inside theme folder but i want add another new config file for metabox inside my CPT's plugin, is it possible at this time ?! if yes how ?

Thanks

**Comment by Codestar** [comment]
Hi,

Yes why not, it is possible. You do not need a extra metabox config file, only you will use filter ```cs_metabox_options``` let's see an example:

```php
// put this code your CPT's plugin php file anywhere
if ( ! function_exists( 'cs_cpt_metabox_options' ) ) {
  function cs_cpt_metabox_options( $options ) {

    // CPT's Metabox Options
    $options[]    = array(
      'id'        => '_cpt_post_options',
      'title'     => 'CPT Options',
      'post_type' => 'your_cpt_post_type_name', // here is important for eg 'post' 'page' 'cpt'
      'context'   => 'normal',
      'priority'  => 'default',
      'sections'  => array(

        array(
          'name'   => 'section_100',
          'fields' => array(

            array(
              'id'    => 'section_100_text',
              'type'  => 'text',
              'title' => 'Text Field',
            ),

          ),
        ),

      ),
    );

    return $options;

  }
  add_filter( 'cs_metabox_options', 'cs_cpt_metabox_options' );
}
```

**Comment by Theme20** [comment]
Wow thanks, works like a charm! :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by codecans** [comment]
Hi,
I think i couldn't explain.
now trying to explain my issue.
we developed 2 plugin with codestar framework. But if i activate 2 plugin at a time then 1 plugin metabox function is work only, see screenshot: http://prntscr.com/fefzp3
and another one metabox is hide, see screenshot: http://prntscr.com/fefzws

user use 1 plugin individually so i should call framework for each plugin.

please need solution codestar team.

1. https://wordpress.org/plugins/amazing-hover-effects/
2. https://wordpress.org/plugins/team-member-showcase/

avobe two plugin made by using codestar framework and you may activate 2 plugin at a time and see 1 metabox isn't working.
