### ISSUE TITLE
Dependency item disappearing in widget after click save

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#104]
Hello!
Dependency item disappearing in widget after click save.
![capture](https://cloud.githubusercontent.com/assets/7956101/7782884/4dbd7648-014e-11e5-8afe-5afe1b6ffa3a.PNG)
But coming back after refreshing the page
![capture2](https://cloud.githubusercontent.com/assets/7956101/7782881/47429f96-014e-11e5-8cc9-0ec5f81be45d.PNG)

**Comment by Codestar** [comment]
Hi,

Yes yes, i saw it now. let me try to fix it :wink:

**Comment by Codestar** [comment]
Hi, I made an update about this issue, can you try it and tell me if it is ok ? updated js files as you see here 9b648b3c210fddc53ccfec3995264de0db039b0a

**Comment by sabuz** [comment]
Hello!
Yeah! This is working fine!
Thank You!

**Comment by Codestar** [comment]
You're welcome :+1:
