### ISSUE TITLE
User-added color palettes

### ISSUE THREAD

**Issue by binaryfire** [Codestar/codestar-framework#104]
Hi there

Is it possible to achieve something like this with Codestar? https://d33v4339jhl8k0.cloudfront.net/docs/assets/55192029e4b0221aadf23f55/images/5fad214dcff47e00160b92e8/file-wMImR2ZaCz.png

I think it'd be a combination of the color palette field, color group field and the repeater field. The idea is users can add and save their own palettes. The palette colours would be set by the color group field. 

Thanks!

PS. Are your Customizer settings saved in wp_options or theme_options? Can we choose?

**Comment by Codestar** [comment]
Hi,

Un no, it's not possible.

Regards

**Comment by binaryfire** [comment]
@Codestar Ok thanks. Is it possible to extend Codestar by adding our own fields?

**Comment by Codestar** [comment]
Yes of course. take a look doc: [How to add a new field ?](http://codestarframework.com/documentation/#/faq?id=how-to-add-a-new-field-)
