### ISSUE TITLE
How to  build  custom  siderbar? 

### ISSUE THREAD

**Issue by burncode** [Codestar/codestar-framework#105]
How to  build  custom  siderbar? 
like this:
![12](https://cloud.githubusercontent.com/assets/2592734/7784439/0c61614c-0198-11e5-95d3-ff44b021d4e3.png)

**Comment by Codestar** [comment]
You can use group option field for custom sidebar ? for eg:

```php
array(
  'id'              => 'custom_sidebars',
  'type'            => 'group',
  'title'           => 'Custom Sidebars',
  'button_title'    => 'Add Sidebar',
  'accordion_title' => 'Add Sidebar',
  'fields'          => array(

    array(
      'id'          => 'sidebar_name',
      'type'        => 'text',
      'title'       => 'Sidebar Name',
    ),

  )
),
```

```php
// and use it for create sidebar
echo cs_get_option( 'custom_sidebars' );
```

btw, you can check my custom sidebar option on my Route WordPress Theme, watch it https://www.youtube.com/watch?v=kfikJ7PmFv8

**Comment by burncode** [comment]
Thanks！I really like this options frame.Because it's too easy to understand and use.I come from China.
Have the opportunity to play in Beijing

**Comment by sabuz** [comment]
Hello @burncode !
Maybe you are looking for this:

$sidebars = cs_get_option('custom_sidebars');
		
	if(!empty($sidebars) ){
		foreach ($sidebars as $sidebar) {
			if( !empty($sidebar['name']) ) {
				register_sidebar(array(
					'name' => $sidebar['name'],
					'id' => sanitize_title($sidebar['name']),
					'description' => $sidebar['description'],
					'before_widget' => $before_widget,
			                'after_widget' => $after_widget,
			                'before_title' => $before_title,
			                'after_title' => $after_title,
				));
			}
		}
	}

**Comment by Codestar** [comment]
Yes, also we was talked about this with @sabuz  take a look this issue #57 for more useful functions.

**Comment by burncode** [comment]
Thanks！

**Comment by Codestar** [comment]
You're welcome :+1:
