### ISSUE TITLE
Chosen with allow_single_deselect: true

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#106]
Hello!
How to do chosen with allow_single_deselect: true for typography?

**Comment by Codestar** [comment]
Hi,

Actually, ```allow_single_deselect: true``` is already defined. but if there is not empty option, this option disabling automatically from choosen script. but you can enable it with this action.

```php
if( ! function_exists( 'empty_option_for_typography_family' ) ) {
  function empty_option_for_typography_family() {
    echo '<option value=""></option>';
  }
  add_action( 'cs_typography_family', 'empty_option_for_typography_family' );
}
```

but i do not advise it. because typography is a required option field. you know :smiley:

**Comment by sabuz** [comment]
Thanks @Codestar for reply.
Yeah! typography is required option. But in case of custom typography, sometime it needs to be empty. 
Suppose, I've declared css code in a css file and I want to give user the power to change the typography option dynamically. Only if the user fill the custom typography option, the dynamic code will be applied, else predefined css code will be used. Then what will be the solution?

**Comment by Codestar** [comment]
Oh yes, you are right. hmm, this action not solution for you ? i did not understand, sorry my english.

**Comment by sabuz** [comment]
![capture](https://cloud.githubusercontent.com/assets/7956101/7842337/62d00950-04c4-11e5-8686-947fabd48fd1.PNG)
Have a look on this image. It's Newspaper theme by tagdiv.
This is their custom typography option. If you select a font for a particular item, the custom typograhpy will be applied. If you keep blank, the default typography will be applied.

**Comment by Codestar** [comment]
Hmm, yes i am understanding. but this is custom option field. you can create it by yourself easy. for eg i created a custom typography field for you. take a look https://gist.github.com/Codestar/5a670a4623519ba5d079 this example similar for your screenshot :wink:

**Comment by sabuz** [comment]
Thanks a lot!

**Comment by Codestar** [comment]
You're welcome :+1:
