### ISSUE TITLE
Useful fields: Sidebar - RevSlider - MasterSlider

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#108]
Hi, 

Just want share some usefull fields, 

- Sidebar select
- Revolution Slider select
- Master Slider select

Copy from here: https://gist.github.com/Theme20/fe6cb7d42d58c49c423c

Create new folder inside fields folder example with name "custom" and create new php file inside it "custom.php" and paste codes, done.

Cheers

**Comment by Codestar** [comment]
Hi,

Ow, thanks for your tips. Also i was planing to create same things for my themes. i will use it ;)

btw, my idea is this about this sliders.

```php
// a helper function for get revslider before include framework
if ( ! function_exists( 'cs_get_revsliders' ) ) {
  function cs_get_revsliders() {

    if ( class_exists( 'RevSliderAdmin' ) ) {
      $slider  = new RevSlider();
      $options = $slider->getArrSlidersShort();
    }

    if( empty( $options ) ) {
      $options = array( 'No Sliders Found' );
    }

    return $options;

  }
}

```

```php
// a select option field
// ------------------------------------
array(
  'id'           => 'revslider',
  'type'         => 'select',
  'title'        => 'RevSlider',
  'options'      => cs_get_revsliders(),
),
```

I think this way is easy than core edit. but your way is good for framework experience :wink: 

Cheers :+1:

**Comment by Theme20** [comment]
Hi CodeStar, 

Thanks, I also think with function is better :+1:
