### ISSUE TITLE
When does Codestar init actually?

### ISSUE THREAD

**Issue by lahmacun** [Codestar/codestar-framework#109]
Hello, It's me, again :sweat_smile:

I'm having an interesting issue while developing Speed Booster Pack (https://github.com/optimocha/speed-booster-pack)

We are trying to create a metabox for all custom post types but when we run `CSF::createMetabox`, only core post types are returning from `get_post_types()` method. Also we are having similar issue with `CSF::createSection` method.

When we try to run `CSF::createSection` attached to the hook `admin_init`, we get `Not Allowed` error on page.

So, I'm wondering, how can I make Codestar instantiate with little bit delay? For example, I need to create my plugin options page after custom post types are created.

Could you please help us with that? Do you have any idea about this situation?

Greetings,
Zahid.

**Comment by Codestar** [comment]
Hi, I get happy hear from you. :)

The framework runs `init` action and `priority` is **10**. Maybe you can try to create post types in `init` action `priority` **9** ?

If that way not solve, please give me further detail I can try something.

Regards
