### ISSUE TITLE
Can't get fields to work separately from the default options page and sections.

### ISSUE THREAD

**Issue by stefanciorici** [Codestar/codestar-framework#11]
Hi,

I am trying to use the fields for a separate AJAX call result, using the CSF::field method to create the actual content of the fields. While I managed to get the fields to show properly, no JavaScript is running and repeat fields are not working and there is no way to add new ones as the button does not respond. Are they linked somehow?

Thanks!

**Comment by Codestar** [comment]
Hi,

CSF Fields can be used only inside framework.

Regards, Codestar
