### ISSUE TITLE
Group option type not working on customizer

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#111]
Hi CodeStar, 

Please check group option type in customizer, it seems it does some bugs, 1. after adding new item save button not showing. 2. finally after clicking on save and refresh, group items not saving. 

Cheers

**Comment by Codestar** [comment]
Hi Theme20,

WP Customizer is complex a little. Customizer trigger checking only one form element. ( for eg, input, textarea, checkbox etc ) and imagine, group option have a lot of dynamic form elements. it will be difficult to integration :smile: for eg. WordPress wrote a lot of code for Customizer Widgets integration. maybe i can find a solution in next updates.

**Comment by Theme20** [comment]
Ok. Thanks man, Actually i moved all of my theme options fields to customizer and just need group for sidebar generation. 
i think, i should use text field option then user can add sidebars like: <code>sidebar-1,sidebar2</code> then convert it to array.

**Comment by Codestar** [comment]
Yes you can use your way it :wink: wp customizer requires extra js effort for eg. if you want to use multiple checkbox, you will need extra js code for trigger and save options. i will try to integrate my all fields at odd times.

**Comment by Codestar** [comment]
Comign Soon :smile:  See:

![support_20160817114522](https://cloud.githubusercontent.com/assets/1313301/17730208/6ad80384-6470-11e6-98c8-7b61a3532f14.gif)

**Comment by Codevz** [comment]
@Codestar Wow great, thanks man ;)

**Comment by NoahjChampion** [comment]
![image](https://cloud.githubusercontent.com/assets/6123260/17730785/694fc9b2-6438-11e6-9614-498000167253.png)

**Comment by Codestar** [comment]
You're welcome :+1: and all of option fields integrated for customizer.. :wink:

**Comment by ariona** [comment]
@codestar any update for this issue? it seem it has not been fixed. The publish button still disabled when changing the value within the group
