### ISSUE TITLE
Image select not saving sometime in group field

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#112]
Hello!
Image select option sometime not saving in group field. And sometime it's saving but not showing the selected value until refresh the page.

**Comment by Codestar** [comment]
Hi, I am testing it now and yes i saw it. hmm, radio checked=checked is issue on clone sortable. hmm oke i made an update for this issue, can you update files and try it ? d346af18685bda7f2041a44458071aa841bc1b94
