### ISSUE TITLE
How to use Codestar Framework with WPML?

### ISSUE THREAD

**Issue by KayahanKahriman** [Codestar/codestar-framework#112]
Hi, old version had an array option ( like [field_name][en] ) to make Codestar Framework multilingual. I've read about something wpml-config.xml but couldnt figure it out. I've duplicated everything with WPML but i cant see fields in other languages.
Can you make this subject clear? Thanks in advance.

**Comment by Codestar** [comment]
Hi, Yes right. I removed that featured, because it was issue for complex fields. You must use [wpml-config.xml](https://wpml.org/documentation/support/language-configuration-files/) idea for your project.

**Comment by KayahanKahriman** [comment]
So how do we use wpml-config.xml? Could you make a basic example please?

**Comment by Codestar** [comment]
Hi,

Suppose your option framework id is "kayahan" and you have some footer texts. you should to set wpml-config.xml like this:

```xml
<wpml-config>
  <admin-texts>
    <key name="kayahan">
      <key name="copyright_text"/>
      <key name="header_text"/>
      <key name="something_option_name"/>
    </key>
  </admin-texts>
</wpml-config>
```

Only this. for more information go wpml documentation.
