### ISSUE TITLE
Multi select categories

### ISSUE THREAD

**Issue by doukali** [Codestar/codestar-framework#114]
hey thanks for the framework
i wana to use the multiselect categeorie in the loop 
howa can i do it ?

**Comment by ariona** [comment]
Let's continue the discussion here :)

Okay first lets create a multiple select option, here i create multiple select for my customizer settting

```
array(
	'name'    => 'multiple_category',
	'default' => '',
	'control' => array(
		'type'    => 'cs_field',
		'options' => array(
			'type'       => 'select',
			'title'      => 'Select Field for Posts',
			'options'    => 'categories',
			'query_args' => array(
			'orderby'    => 'name',
			'order'      => 'ASC',
		),
		'attributes' => array(
			'multiple' => 'multiple',
		),
		'default_option' => 'Select a category',
		)
	)
),
```

For retrieving the value we use `cs_get_customize_option("multiple_category"); ` it will return an array of categori IDs we have selected like this:

```
Array ( [0] => 19 [1] => 29 )
```

Then we can pass it to query args like so:
```
$args = array(
	'posts_per_page'   => 20,
	'category__in' => cs_get_customize_option("multiple_category"), 
);
$multicat = new WP_Query( $args);

while ( $multicat->have_posts() ) : $multicat->the_post();
    echo '<li>';
    the_title();
    echo '</li>';
endwhile;
```

hope this will help.  😊

**Comment by Codestar** [comment]
Hi,

Yes follow @ariona also another usages:

```
// single select
array(
  'id'             => 'option_id_101',
  'type'           => 'select',
  'title'          => 'Select Category',
  'options'        => 'categories',
  'default_option' => 'Select a category'
),

// multiple select
array(
  'id'          => 'option_id_102',
  'type'        => 'select',
  'title'       => 'Select Categories',
  'options'     => 'categories',
  'attributes'  => array(
     'multiple' => 'multiple',
   ),
),

// multiple select with chosen
array(
  'id'             => 'option_id_101113',
  'type'           => 'select',
  'title'          => 'Select Categories1111',
  'options'        => 'categories',
  'attributes'     => array(
     'multiple'    => 'multiple',
    'style'        => 'width: 200px;'
   ),
  'class'          => 'chosen',
  'default_option' => 'Select categories',
),
```

So, it is easy.

**Comment by doukali** [comment]
thanks thanks thanks : :+1:

**Comment by doukali** [comment]
thnaks its work . can i ask another question the upload type how can i add  preview i mean when i upload 
![capture4](https://cloud.githubusercontent.com/assets/12788233/8077411/7c0d5678-0f4d-11e5-9a72-f90addb79b54.PNG)
 it became like this 
![capture5](https://cloud.githubusercontent.com/assets/12788233/8077552/a03a6dbe-0f4e-11e5-90f7-f13da342a0c7.png)
like the image type ?

**Comment by Codestar** [comment]
Hi,

You can use this option fields?

```php
array(
  'id'        => 'image_1',
  'type'      => 'image',
  'title'     => 'Image',
),
```

**Comment by doukali** [comment]
when u use the image type i cant get the link of image :/

**Comment by Codestar** [comment]
hmm, yes it is true, because this option field returning id of image. hmm there is not any field for image & link both return option. you can manage it by yourself :smile: or you can offer freelance work to us if you need it really :wink:

**Comment by doukali** [comment]
ok thanks i have onother question : i groupe type i want to display 5 post form . howa can i get value from groupe fields like switcher or  select in groupe type ?

**Comment by Codestar** [comment]
i have not any idea, maybe you will need custom code for this.
