### ISSUE TITLE
Beautiful looking framework

### ISSUE THREAD

**Issue by cmwwebfx** [Codestar/codestar-framework#116]
This may be the framework I have been searching for, especially since it offers both Options page as well as customizer all in one. Do all the fields available in the options page work in customizer? Such as image radio? Does the image radio work as a trigger for dependency?

**Comment by Codestar** [comment]
Hi,

Thanks for interested, All options working on options page and metabox page. BUT in customizer. you know it is required extra effort for adaptation. because customizer working as key=value model. but a lot of options fields working on customizer. i can write a list for available options fields:

```
// this option fields ---working--- in customizer
Text
Textarea
Checkbox
Radio
Select
Number
Icons
Image
Upload
Gallery
Wysiwyg
Switcher
Color Picker
Checkbox Image Select
Radio Image Select
Heading
Sub Heading
Notice
```

```
// this option fields ---waiting for develop/improve--- for customizer
// because this fields have multiple form elements.
Group
Sorter
Wysiwyg
Multi Checkbox
Background
Typography
Backup
Fieldset
```

**Comment by cmwwebfx** [comment]
I am feeling this is possibly a better solution than that heavy weight Redux. Here we have customizer support, metaboxes support, options page support and free. 

With the WP Theme Review Team coming out a few weeks back now suggesting all themes to use customizer only for submitted themes to the repo it makes me wonder what  benefit options pages have. Ideally I will focus on using this for customizer, whilst having an options page for some custom things like CSS page, and metaboxes.

Can we control the position of the metaboxes to be in the normal position, or in the side position in the editor page? Can they be in an order we choose from setting 1 -10?

Would it help to see how they have used [Mie framework](http://mie.alispx.me/) or even Kirki to achieve what you want on the customizer things still outstanding?

**Comment by Codestar** [comment]
Yes all things is free. So framework is living with donations :) Actually i am planning same, i will move my all settings from option page to customizer panel. i am trying to adaptation all fields because i needed it for my next projects.

And yes, you can manage position of the metaboxes. if you install framework as default settings you can see it. for eg:

**Side Metabox**
![screenshot-1](http://codestarframework.com/assets/images/framework/screenshot-4.png)

**Normal Metabox**
![screenshot-2](http://codestarframework.com/assets/images/framework/screenshot-5.png)

Hmm, i checked Mie Framework, yes it is nice. my customizer is similar :wink: said as me. both framework have simple option fields for framework.

**Comment by cmwwebfx** [comment]
Once I get my first product ready I will make a generous donation to help along this project since it is really a lovely framework. Another framework I have used that is easy to use is [APF](https://github.com/michaeluno/admin-page-framework) because of some of the lovely features like repeater and sortable group, and tabbed metaboxes. 

Do you plan to have a code editor in the framework?

I love the idea of having all the options like what you have here in Codestar Framework at the fingertips.

Ciaran

**Comment by cmwwebfx** [comment]
Oops... I see in the  last image you have tabbed metabox. WOW ... stunning. Love it.

**Comment by Codestar** [comment]
Yes sure, I am planning code editor. js and css code editor coming soon :wink: and thanks for your nice words :+1: Hey, install it on a empty wordpress. you will see all features. In default config, there is all option fields demos...

**Comment by cmwwebfx** [comment]
Do you have a default starter theme like some of the other frameworks out there so we can learn direct from you on something like 2015 with Codestar Framework installed and some options controlling some elements? This is always a great place for some low level devs to look at how you did it.

**Comment by Codestar** [comment]
Hmm, actually here is a dev branch for framework develop https://github.com/Codestar/codestar-framework/tree/dev you can download it and extract it on themes folder.

**Comment by cmwwebfx** [comment]
I will give it a go.. Do you have options for someone like myself to update your docs site to add screenshots of each feature to the docs?

**Comment by cmwwebfx** [comment]
Installed and incredible. Love it. Absolutely loving this already

**Comment by Codestar** [comment]
Haha, yes it is simple. not mixed. So you do not need to read documentation for to use it, only play with it a little.  :wink:

**Comment by cmwwebfx** [comment]
I will be happy to update your docs with the images I think it needs. Many low end devs look for what the field should do, and that seems the only thing missing in the docs.

**Comment by Codestar** [comment]
Yes i will do it :+1:

**Comment by jahir07** [comment]
yes background is not working perfectly in customizer.. I have made another fields called "typography-set". It works perfectly in theme option and return value perfectly.
http://d.pr/i/drOr
http://d.pr/i/10J0w
But in customizer 1st value saved but others fieldset not working..

**Comment by Codestar** [comment]
@jahir07 yes it is right. some option fields not working perfectly in customizer. i will do some updates about this issue in framework version 2

**Comment by jahir07** [comment]
great. Thanks
