### ISSUE TITLE
Sub section doesn't work in metabox.

### ISSUE THREAD

**Issue by HelloAlberuni** [Codestar/codestar-framework#117]
Subsection works great for global options. Please check this screenshot https://i.imgur.com/JYjHLwl.png

I need same type of the subsection support into the metaboxes. According to the documentation I didn't found any way to do this.

Is it possible?

**Comment by Codestar** [comment]
Hi, Yes right, metabox doesn't support sub sections. you can use only one level sections. maybe future I can add.

**Comment by HelloAlberuni** [comment]
Thanks for letting me know. It will be great to add support for the metaboxes. Hopefully you will add this in the future.
