### ISSUE TITLE
Option showing in admin bar for a default subscriber role user.

### ISSUE THREAD

**Issue by mehedidb** [Codestar/codestar-framework#119]
When a user signup as a subscribe, then they see the option menu in admin bar.

Example:  https://prnt.sc/22lpa6o

Hope you understand. Please fix the issue.

Thanks!

**Comment by Codestar** [comment]
Hi, Yes I understood. hmm, can you try this:

Go to this file and that line [/codestar-framework/classes/admin-options.class.php#L188](https://github.com/Codestar/codestar-framework/blob/master/classes/admin-options.class.php#L188) then add below code:

```php
if ( ! current_user_can( $this->args['menu_capability'] ) ) {
  return;
}
```

I think it will works. Please notify me, I'll add for next update.
