### ISSUE TITLE
Layout Sorter field does not reflect changes

### ISSUE THREAD

**Issue by yukijay** [Codestar/codestar-framework#119]
Hi,

I think there is an issue with the "Layour Sorter" field, CSFramework does not update the changes in the name (or id) of the sections in the sorter. For example, if I try to change the name of a section, from "Mercedes" to "Corvette" once the values were saved, CSFramework still shows the "Mercedes" name. The only way to update the name is by changing the id of the sorter field.

Any ideas? Sorry for my bad english and thanks for your amazing framework :)

**Comment by yukijay** [comment]
Another question: Is there any way to include the Group Fields in the "Layout Sorter" field or an option to  a field and automatically add it to the Sorter field? For example, this would allow to the user to create a section and manage it from the sorter field. Is this possible?

**Comment by Codestar** [comment]
Hi,

Did you try to reset options before try save it ? because default options using default option value. try to reset option, and tell me result ;)

**Comment by yukijay** [comment]
Oh, great! Yeah, it works by resetting the options. But why is this necessary? I mean, if I change any other option value (like a text field name), the change is reflected immediately without having to do a reset.

**Comment by Codestar** [comment]
Why is this necessary, Sorter using default value for settings. Btw, you will not need reset always, why you need reset here, because you created sorter field after visit framework page. because when you first visit framework all default settings saving. shortly, your clients never see this issue.

```php
// if we do not use default settings as value, we need to write so
array(
  'id'             => 'sorter_1',
  'type'           => 'sorter',
  'title'          => 'Sorter',
  'options'        => array(
    'enabled'      => array(
      'bmw'        => 'BMW',
      'mercedes'   => 'Mercedes',
      'volkswagen' => 'Volkswagen',
    ),
    'disabled'     => array(
      'ferrari'    => 'Ferrari',
      'mustang'    => 'Mustang',
    ),
  ),
  'default'        => array(
    'enabled'      => array(
      'bmw'        => 'BMW',
      'mercedes'   => 'Mercedes',
      'volkswagen' => 'Volkswagen',
    ),
    'disabled'     => array(
      'ferrari'    => 'Ferrari',
      'mustang'    => 'Mustang',
    ),
  ),
),
```

Why we will write twice? i was think, we only need one. i hope i explained it.. :smile:
