### ISSUE TITLE
How to getting value from a group field?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#12]
I want get values like below : 

<pre>
/* Custom Widgets */
$custom_sidebars = cs_get_option('custom_sidebars_list');
if ($custom_sidebars) {
 foreach($custom_sidebars as $custom_sidebar) :
 $heading = $custom_sidebar['custom_sidebar_title'];
 $own_id = preg_replace('/[^a-z]/', "-", strtolower($heading));

register_sidebar( array(
  'name' => __( $heading, 'text' ),
  'id' => $own_id,
  'description' => __( $custom_sidebar['custom_sidebar_desc'], 'text' ),
  'before_widget' => '&lt;div id=&quot;%1$s&quot; class=&quot;widget %2$s&quot;&gt;',
  'after_widget' => '&lt;/div&gt;',
  'before_title' => '&lt;h3 class=&quot;widget-title&quot;&gt;',
  'after_title' => '&lt;/h3&gt;&lt;div class=&quot;title-bar&quot;&gt;&lt;/div&gt;',
 ) );
endforeach;
}
</pre>

But, i get fatal error like below :
<img src="http://i.imgur.com/wEewRYD.png" alt="Fatal Error" />

Thanks,
Ansif

**Comment by Codestar** [comment]
Hi,

Nice idea, also i am using group option for custom sidebars, you can take a look my custom sidebar idea https://www.youtube.com/watch?v=kfikJ7PmFv8

About your question:
Can you try this code inside a init action? I am meaning this:

```
function my_custom_sidebars() {
// your code here
}
add_action( 'init', 'my_custom_sidebars', 10 ); // because framework initize after level 10
```

Try and tell me if still error.. ;)

**Comment by Ansif** [comment]
Thanks, You're Awesome! It’s Works Well!

I'm using this framework just last two days before. It’s so easy. Tons of thanks for making such a great lightweight framework! And that detailed clear documentation!

Cheers - Ansif

**Comment by Codestar** [comment]
Wow, thanks for your nice opinions ;) I get happy.
