### ISSUE TITLE
Form fields not restoring after error response from csf_{$prefix}_save_before action

### ISSUE THREAD

**Issue by RomkaLTU** [Codestar/codestar-framework#12]
Form fields not restoring after error response from csf_{$prefix}_save_before action

Inside callback function:

`wp_send_json_error( array( 'success' => false, 'error' => esc_html__( "Please fill up API credentials!", 'csf' ) ) );`

Pop-up appears ant after closing it form hangs on "Saving..."

**Comment by Codestar** [comment]
Hi,

This action using only for trigger anything before save. You can not change output of messages. I think you are trying to add a API key input field ? Hmm, why you do not using [validate](http://codestarframework.com/documentation/#/faq?id=how-to-use-validate-) option ?

Regards, Codestar

**Comment by RomkaLTU** [comment]
Well you can actually change it, but form hangs on "Saving..." state, after pop-up or success message. Anyway, we trying to validate credentials with some API, and if they fails, we don't want to save it and return error.

**Comment by RomkaLTU** [comment]
As about validate field, it will not work here, as we need 2 fields at the same time, so before_save seams  good spot for that.

**Comment by Codestar** [comment]
Hi, There is no option for this yet.
