### ISSUE TITLE
From/Input with Custom Action Functionality

### ISSUE THREAD

**Issue by arifix** [Codestar/codestar-framework#120]
First of all, thank you Codestart team for creating an awesome framework like that. I'm using it for a long time & very happy with the functionalities given.

Currently, I'm working on a plugin project. There will be some enabled options & some disabled. I want to add functionality to verify users if they have a valid activation key. So, I will take the user-inputted activation key & want to send a request on my server for verification purposes. If successful I will save a value on the wp_options table & will enable all the options for them. As I understand, that(enable/disable) can be done with conditional add/remove option item from section array. Like:

```
$options = [];
if(get_option( 'my_plugin_activated' )){
       $options = array(
          'id'    => 'test',
          'type'  => 'switcher',
          'title' => 'Test',
          'text_on'  => 'Yes',
          'text_off' => 'No',
        );
}

CSF::createSection($prefix, array(
      'title'  => 'Styling',
      'icon'   => 'fa fa-link',
      'fields' => array(
          $options
      )
));
```

I can handle request/verification-related things. I just need to know the action/filter hooks with uses, from where I can place my request/verification-related codes. Also, need to know the proper way to enable/disable options conditionally. 

I can't thank you enough. I want to know if there is any "Buy me a Coffee" option available, so I can buy you a coffee :)
Note: I know there is a premium plugin available on Codecanyon but currently, I don't need that. So, I don't want to purchase that till necessity.

Thanks again

**Comment by Codestar** [comment]
Hi,

Maybe you need something like this code:

```php
// Standard config
CSF::createSection( $prefix, array(
  'title'  => 'Styling',
  'icon'   => 'fa fa-link',
  'fields' => array(

    array(
      'id'    => 'text-color',
      'type'  => 'color',
      'title' => 'Text Color',
    ),

    array(
      'id'    => 'background-color',
      'type'  => 'color',
      'title' => 'Background Color',
    ),

  )
) );
```

```php
// Your utils.php ( or put below filter anywhere. )
function arifix_capability_save( $data ) {

  // unset specific fields if not active "my_plugin_activated"
  if ( get_option( 'my_plugin_activated' ) ) {

    $pro_field_ids = array(
      'text-color',
      'background-color',
    );

    foreach ( $pro_field_ids as $id ) {
      if ( isset( $data[ $id ] ) ) {
        unset( $data[ $id ] );
      }
    }

  }

  return $data;
}

add_filter( 'csf_{THE_FRAMEWORK_PREFIX_HERE}_save', 'arifix_capability_save' );
```

Regards, Codestar

**Comment by arifix** [comment]
Thanks for your reply.

Any guideline about sending get/post requests from Codestar admin panel?

**Comment by Codestar** [comment]
You're welcome :+1: 

Uh not yet, But yes I must to explain detailed all framework filters in the documentation. It's on progress yet and I will complete it soon: https://codestarframework.com/documentation/#/hooks

Btw, thanks for the "buy me a coffee" idea. It's in my mind :)

**Comment by arifix** [comment]
Thanks again :)

**Comment by arifix** [comment]
I managed to make purchase verification by code from Codestar admin & enable/disable sections based on Purchase. Let me paste the code here if anyone needs it in the future.

```
// CSF Sections
CSF::createSection($prefix, array(
  'title'  => 'Styling',
  'icon'   => 'fa fa-link',
  'id'     => 'section-styling',
  'fields' => array(

    // fields here
  )
));

CSF::createSection( $prefix, array(
  'title'  => 'Licensing',
  'icon'   => 'fas fa-key',
  'id'   => 'section-licensing',
  'fields' => array(
    array(
      'id'    => 'license-key',
      'type'  => 'text',
      'title' => 'License Key',
      'validate' => 'csf_validate_required',
    ),
  )
));
```

```
// Enable/Disable Sections based on Purchase
function my_plugin_enable_disable_sections($data){
  $data_ar = [];
  $plugin_data = get_option('_my_plugin_license_data');
  if(!$plugin_data){
    $pdata = json_decode($plugin_data);
    $section_ids = [
      'section-styling',
    ];

    foreach($data as $sec){
      $data_ar[$sec['id']] = $sec;
    }

    foreach($section_ids as $id){
      if(isset($data_ar[$id])){
        unset($data_ar[$id]);
      }
    }
  }

  return $data_ar ?: $data;
}
add_filter('csf__my_plugin_sections', 'my_plugin_enable_disable_sections');
```

```
// Verify Purchase
function my_plugin_verify_licensing($data){
  $plugin_data = get_option('_my_plugin_license_data');

  if(!$plugin_data){
    $key = $data['license-key'];
    if($key){
      $response = wp_remote_get('https://example.com/verify.php?key=' . $key);
      $body = wp_remote_retrieve_body($response);
      $res = json_decode($body);
      if($res->status == 'success'){
        add_option('_my_plugin_license_data', $body, '', 'yes');
      }
    }
  }
  return $data;
}
add_filter('csf__my_plugin_save', 'my_plugin_verify_licensing');
```

Thanks again to all the people behind that awesome options framework :)

**Comment by Codestar** [comment]
Wow, thanks for snippet :+1: :100:
