### ISSUE TITLE
Remove default codestar brand name from dashboard area

### ISSUE THREAD

**Issue by asmsaiff** [Codestar/codestar-framework#121]
Hi, I want to remove the default 'Codestar Framework by Codestar' text in Wordpress admin area and want to replace my won text. How can I do that ??? 

![image](https://user-images.githubusercontent.com/75557392/147830388-64f742cf-4541-491c-8865-5d172c51db29.png)

**Comment by Codestar** [comment]
Hi,

You can change it with "framework_title" param. see all parameters: https://codestarframework.com/documentation/#/configurations?id=admin-option-framework

Regards

**Comment by asmsaiff** [comment]
Thank you!

**Comment by Codestar** [comment]
You're welcome :+1:
