### ISSUE TITLE
Customizer Panels and Sections

### ISSUE THREAD

**Issue by cmwwebfx** [Codestar/codestar-framework#121]
Hi there,

I am used to using Kirki customizer as it has lovely options for grouping or building out your panels, then building out your sections per panel, then adding your controllers to each section. 

So you could make all your panels in one hit in the top of the options file, the the next set of coding could be making all the sections names, then your next group of code in that file can be the controllers, and then simply set where the controller should be sitting in which section. 

Is this something that can be done in CF? I would love to see that as an option, as it makes it very organised.

Ciaran

**Comment by Codestar** [comment]
Hi,

hmm i have not and idea, you can see Custmizer Panel and Sections settings from demo config file [customize.config.php](https://github.com/Codestar/codestar-framework/blob/master/config/customize.config.php)

**Comment by cmwwebfx** [comment]
Yes I see all the options, and have made all the panels and sections using Codestar. But I found it quite a bit longer to build than what I would do using something like Kirki. Here is an example how they do a similar but DRY type coding. I would love to see that type of coding come here in Codestar so it is all under one umbrella. 

As you see [here](https://github.com/reduxframework/kirki/blob/master/sample-config.php#L30-L43) he has created all the panels first. Then [here](https://github.com/reduxframework/kirki/blob/master/sample-config.php#L45-L197) he has created all the sections in one group. After that you can create all the controls, then you can assign the control to whichever section you like as you can see [here](https://github.com/reduxframework/kirki/blob/master/sample-config.php#L45-L197), and same way for adding Sections to Panels like [here](https://github.com/reduxframework/kirki/blob/master/sample-config.php#L45-L197)

Doing it this way makes it very organised and easy to code up a full customizer without going nuts.

I truly would love to see Codestar have this type of additional easier to use function.

**Comment by Codestar** [comment]
Yes it is can be. i noted this request. i will try to improve my config in the future :wink:

**Comment by cmwwebfx** [comment]
That would be really awesome mate. Do you have any labels or milestones running so we can tag this as a feature to make it to the next major update? 

Really looking forward to seeing where you will take this framework as I think you have done a great job on it thus far. I hope my suggestions do not come across as offensive as I have used many frameworks and so far loving this one.

**Comment by Codestar** [comment]
Yeah, when i have free-time, i am developing it. actually i am so busy :smiley:
