### ISSUE TITLE
Theme options Looks Update

### ISSUE THREAD

**Issue by arafatjamil01** [Codestar/codestar-framework#123]
I am willing to update the CSS of the **Admin Option Panel**. I would write and update the CSS  and a pull request.

**Comment by Codestar** [comment]
Hi,

Uh, I didn't get the question. can you elaborate further ?

Regards

**Comment by arafatjamil01** [comment]
The admin option framework user interface design, that comes with default Codestar framework, looks a bit dull to me. 

I am willing to redesign option panel, and make it public. My question is, 
---
Would you integrate my CSS, if I send it with a pull request.

**Comment by Codestar** [comment]
Hmm, I got, but I can't guarantee that pull request. Maybe you can send some screenshots by routewp[at]gmail[dot]com
