### ISSUE TITLE
Customizer value change effect.

### ISSUE THREAD

**Issue by templatation** [Codestar/codestar-framework#124]
Hi,

I have been playing with customizer first time, and I am stuck with something, I hope you can guide me.

I have installed cs-framework and made customizer TRUE.
Now I wrote below code in my theme's header file as well as functions file.

`echo cs_get_customize_option( 'text_option_with_default');`

Now as I go to Appearance/customize... and change value, it reflects on header.php on refresh, but doesnt reflect on functions.php.
However, If I click save/publish button, and then reload the page, functions.php file reflects it too.

So I am guessing functions.php code only fetching it once its saved in database. So how do I change this behaviour, please guide.

**Comment by Codestar** [comment]
Hi,

hmm, where and how to use ```cs_get_customize_option``` in ```functions.php``` send me code. I am trying it on header.php it is working normally ?

**Comment by templatation** [comment]
Yes, on header.php it works and changes reflected as we do them on Appearance-customise screen.

I am using exact same code on bottom of functions.php file and it doesnt reflect the change. Only reflects once save/published.

Not sure what code I send of functions.php , its same line I posted above. Can you try to put it in functions.php file yourself and see if it works for you.

**Comment by templatation** [comment]
To add further info.

I am actually creating a switch to turn off the preloader, thats why I need value of a variable on functions.php file. Its coming from database all fine, just not changing on refresh when we switch it in customizer. I hope now I am clear :)

**Comment by Codestar** [comment]
hmm, actually you can not use it on functions.php directly. you need to use a action or filter ? because framework initizing add_action level 20. for eg you can use it so.

```php
function customize_echos() {
  echo cs_get_customize_option( 'text_option_with_default');
}
add_action('init', 'customize_echos', 20);
```
BUT if you want to use it anywhere, create your own get option for customize. for eg:
```php

// here is functions.php
if ( ! function_exists( 'tt_get_customize_option' ) ) {
  function tt_get_customize_option( $option_name = '', $default = '' ) {

    $options = get_option( '_cs_customize_options' );

    if( ! empty( $option_name ) && ! empty( $options[$option_name] ) ) {
      return $options[$option_name];
    } else {
      return ( ! empty( $default ) ) ? $default : null;
    }

  }
}

echo tt_get_customize_option( 'text_option_with_default');
```

BUT, generally customize settings using for front-end. why you need it in functions.php i did not understand :smile:

**Comment by templatation** [comment]
Thanks alot for your time :)

**Comment by Codestar** [comment]
You're welcome :+1:
