### ISSUE TITLE
CSF Underscore not working

### ISSUE THREAD

**Issue by harry-mit** [Codestar/codestar-framework#125]
Hello,

I am trying to create a framework, using the plugin of yours, but it only gives me the default one. Not even the checkbox is working. I get all the files and I can’t use my prefix.

Any thoughts?

**Comment by Codestar** [comment]
Hi,

I just tested it and it works normally. what is the your prefix ? ( only type one word. for eg. xitrom )

**Comment by harry-mit** [comment]
I tried **_artia_** as a prefix, but when I tried to insert the code to functions.php I had to use the default CSF in order to work

**Comment by Codestar** [comment]
Hi,

Very interesting. It works normally. btw, the csf-underscore plugin uses your own filesystem settings. i.e. PclZip, RecursiveDirectoryIterator, RecursiveIteratorIterator classes. You can try to upload that plugin for another wordpress ( localhost or server try any platform ).

**Comment by harry-mit** [comment]
Hello,

What do you mean it works normally? I still have to use the CSF class and the csf prefix. It is not white-labeled at all.

Thank you

**Comment by Codestar** [comment]
Hi,

I mean this for it works... for eg. I have generated it as "artia". Everything prefixed by "artia"

[artia-framework.zip](https://github.com/Codestar/codestar-framework/files/7988969/artia-framework.zip)

**Comment by harry-mit** [comment]
Very weird... I tried it using Local by Flywheel but never got it to work. Using WordPress 5.9, on 2 different computers. Anyway, thank you! I assume it has something to do with Local.

**Comment by Codestar** [comment]
Yes, that is why I said try different platforms ;) You're welcome.
