### ISSUE TITLE
Subset of Google font

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#126]
Hello!
I think google font subset is needed because all  the subsets are loading when it is undefined.
Isn't it is increasing loading time?

Also same fonts are loading twice if they are used by two different field. I think overall typography field need some improvement.

**Comment by Codestar** [comment]
Hello,

Actually subsets is a different option. i am meaning, google font output is custom code and you can add subsets in custom code. For eg. I added a subset option for all fonts. i did not understand your request exactly :) explain it more.

**Comment by sabuz** [comment]
Opps! Maybe I missed something in the first part about subset.
BTW, If we use same font in different field, the same fonts are loading severally. I think this is increasing loading time.

**Comment by Codestar** [comment]
Hmm, we are talking about back-end or front-end ? In front-end, you need to write custom code. i mean this.
