### ISSUE TITLE
Multi select categories usage

### ISSUE THREAD

**Issue by osgaka** [Codestar/codestar-framework#127]
Hi i use this code in framework config but i cant use it in php file

```php
array(
  'id'          => 'option_id_102',
  'type'        => 'select',
  'title'       => 'Select Categories',
  'options'     => 'categories',
  'attributes'  => array(
     'multiple' => 'multiple',
   ),
),
// cs_get_option('option_id_102');
```

so that how can i use this ?
sorry for my bad english :/

**Comment by Codestar** [comment]
Hi, Yes you are using right ? you can select multiple categories with this config. can you explain your request more ? you are meaning chosen multiple select ? my english is same too :smile:

**Comment by osgaka** [comment]
<?php
			$args = array(
				'posts_per_page'   => 20,
				'category__in' => cs_get_option('option_id_102'), 
			);
			$multicat = new WP_Query( $args);
			while ( $multicat->have_posts() ) : $multicat->the_post();?>
			<li>
			<span class="sm_k"><?php $category = get_the_category(); echo $category[0]->cat_name;?></span>
			<a itemprop="url" href="<?php the_permalink() ?>" title="<?php the_title(); ?>">
			<?php if ( has_post_thumbnail() ) {  $resimyolu = wp_get_attachment_image_src(get_post_thumbnail_id()); ?>
			<img class="img-responsive" itemprop="image" src="<?php echo bloginfo('template_url'); ?>/thumb/timthumb.php?src=<?php echo  $resimyolu[0]; ?>&amp;w=220&amp;h=133&amp;zc=1" width="220" height="133" alt="<?php the_title(); ?>"/>
			<?php } else { ?>
				<img class="img-responsive" src="<?php echo bloginfo('template_url'); ?>/thumb/timthumb.php?src=<?php bloginfo('template_url');?>/images/ogk.jpg&amp;w=220&amp;h=133&amp;zc=1" width="220" height="133" alt="<?php the_title(); ?>"/> 
				<?php } ?>
			<h2 itemprop="name"><?php the_title(); ?></h2></a>
			</li>
			<?php endwhile;wp_reset_query() ?>

is this usage true for multiple select categories ?

**Comment by Codestar** [comment]
Yes it is true, but you can use this args.

```php
$args = array(
  'posts_per_page' => 20,
  'cats' => cs_get_option('option_id_102'), 
);
$multicat = new WP_Query( $args);
while ( $multicat->have_posts() ) : $multicat->the_post();
...
......
```
