### ISSUE TITLE
Checkbox Dependency

### ISSUE THREAD

**Issue by champsupertramp** [Codestar/codestar-framework#129]
Hi @Codestar, You're a Rockstar! I've been working with the codestar framework for almost a month now and I'm loving it. I just want to know how do i make dependency work with checkboxes.  I'm working on a task that needs to show 2 fields depending on a checked value. It works with the '=' condition but i'm not sure why it's not working when using condition 'any'.

Here's the code but it's not working as expected. 
```PHP
 array(
    'id'        => 'search',
    'type'      => 'checkbox',
    'title'     => 'Display Search',
    'options'   => array(
      'main'    => 'Main Page',
      'archive' => 'Archive Page',
      'search'  => 'Search Page'
    ),
    'default'   => 'main',
    'attributes'   => array(
        'data-depend-id' => 'dep_search',
    )
    ),

    array(
    'id'          => 'searchbox_placeholder',
    'type'        => 'text',
    'title'       => 'Placeholder',
    'default'     => 'Search Knowledge Base',
    'dependency'   => array( 'dep_search', 'any', 'main,archive,search' )
    ),

    array(
    'id'      => 'live_search',
    'type'    => 'checkbox',
    'title'   => 'Live Search',
    'label'   => 'Enable',
    'dependency'   => array( 'dep_search', 'any', 'main,archive,search' )
    )
``` 
Thanks in Advanced! I really appreciated it and have my boss buy you a mug of coffee ;)

**Comment by champsupertramp** [comment]
Hi, I've tweaked the condition in /assets/js/cs-plugins.js to make checkbox dependency work. Let me know your thoughts on this.
 
```PHP    
if((control.attr("type") == "checkbox" || control.attr("type") == "radio" ) && control.size() > 1) {
     var value = control.filter(":checked").val();
     return value;
}
```

Thank you!

**Comment by Codestar** [comment]
Hi, Oh sorry for delay, i am in holiday :) and nice update you are true :+1:
