### ISSUE TITLE
Can I use codestar framework in wordpress themes that I have prepared to sell on themeforest? Does your license allow this?

### ISSUE THREAD

**Issue by talhakaranfill** [Codestar/codestar-framework#129]
Can I use codestar framework in wordpress themes that I have prepared to sell on themeforest? Does your license allow this?

**Comment by Codestar** [comment]
Yes of course. There is no any restraint. You can use free or pro versions in your commercial projects (i.e themeforest).

**Comment by talhakaranfill** [comment]
Wonderful. So, is it necessary to buy again in every project? Or can I use it unlimitedly when I buy it once?

**Comment by Codestar** [comment]
Hi,

One license (buy) is enough for your all free or commercial themes or plugins. It's flexible ;) More purchases fuel the project for development.

Have a nice day.

**Comment by Codestar** [comment]
By the way, do not miss the discount. Ends 25 March. Hurry up! https://codecanyon.net/item/codestar-framework-a-simple-and-lightweight-wordpress-option-framework-for-themes-and-plugins/23079100
