### ISSUE TITLE
csf_validate_required - validation doesn't work

### ISSUE THREAD

**Issue by Radzio1615** [Codestar/codestar-framework#13]
Hi! When I add 'csf_validate_required' to my Text fields that are in the Group field, validation doesn't work. Any solution that will make it work?

**Comment by Codestar** [comment]
Hi,

It is not work inside a group, repeater or accordion ( shortly it not work nested fields ). Because this field values is nested-array. You should to write custom validation javascripts for this complex fields. This feature works only main fields.

Have a nice day,
Regards, Codestar
