### ISSUE TITLE
How to call same metabox in post and page?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#13]
Here is code :
<pre>
  'id'        => 'page_options',
  'title'     => 'Page Options',
  'post_type' => 'page',
  'context'   => 'normal',
  'priority'  => 'default',
</pre>

I've tried : 
<pre>
'post_type' => array('page', 'post'),
</pre>
&
<pre>
'post_type' => 'page', 'post', // i know this will not work, but i tried ;)
</pre>

Thanks,
Ansif

**Comment by Codestar** [comment]
Hi,

You can use same metabox so:
```
$options      = array();

// only use a variable for same sections.
$sections     =  array(
  'name'      => 'section_1',
  'title'     => 'Section 1',
  'icon'      => 'fa fa-cog',
  'fields'    => array(

    array(
      'id'    => 'section_1_text',
      'type'  => 'text',
      'title' => 'Text Field',
    ),

  )
);

$options[]    = array(
  'id'        => 'page_options',
  'title'     => 'Page Options',
  'post_type' => 'page',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => $sections
);

$options[]    = array(
  'id'        => 'post_options',
  'title'     => 'Post Options',
  'post_type' => 'post',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => $sections
);
```

It is ok ? btw, i did not use **'post_type' => array('page', 'post')** because you know, there is title, id, priority etc. variable method is not diffcult you can use it easy ;)

**Comment by Ansif** [comment]
This method is not working! :(

**Comment by Codestar** [comment]
Hmm, let's check it. share your metabox.config.php via https://gist.github.com/ and give link ;)

**Comment by Ansif** [comment]
Thanks for your quick response!

Here is my code :
https://gist.github.com/Ansif/fb7c3ddadf2750cdd09c

Mostly from your demo config file codes. :) Still not complete with my theme!

**Comment by Codestar** [comment]
No problem :) hmm, try this config file: https://gist.github.com/Codestar/a107005aee8a3128fb5a

**Comment by Ansif** [comment]
Thanks, it's working as expected!

**Comment by Codestar** [comment]
You're welcome :+1:
