### ISSUE TITLE
Switcher hidden input issue

### ISSUE THREAD

**Issue by champsupertramp** [Codestar/codestar-framework#131]
Hi @Codestar,

I just want to report an issue when using the 'switcher' with ajax. if you change the switcher, it doesn't update the hidden checkbox and add 'checked' to its attributes. So I've added a script to update its DOM. I hope the below info help you understand the issue. Thank you!

![codestar-switcher-issue](https://cloud.githubusercontent.com/assets/12200688/8774587/869e49c8-2f12-11e5-8e58-e9de984b7711.png)

Fixed the issue with the below code:
```javascript
$("input[data-sub-depend-id=channel-active]").on("change",function(){
if ($(this).is("[checked]")) {
        $(this).removeAttr("checked");
}else{
        $(this).attr("checked",true);
 }
});
```

**Comment by Codestar** [comment]
Hi,

Actually we do not need checked attribute ? you can check it so:

```javascript
$("input[data-sub-depend-id=channel-active]").on("change",function(){
  if ( $(this).is(":checked") ) {
    // do stuff
  }else{
    // do stuff
  }
});
```

**Comment by champsupertramp** [comment]
@Codestar - Hi buddy, i was trying to get the checkbox value if the switch is off or on, how do you check if the switch is on ? The default value is 1, but with this code ```javascript  $(this).is(":checked")  ```, it's always returning false. the checkbox is in a group form.

**Comment by Codestar** [comment]
Hi, Sorry for delay, I was in holiday :) hmmm, i have noy any idea for this.
