### ISSUE TITLE
Checkbox in widget

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#132]
Hi Codestar, 

I added checkbox option in widget but its not saving value: 

<pre>
	$a_value = esc_attr( $instance['checkbox'] );
	$a_field = array(
		'id'    => $this->get_field_name('checkbox'),
		'name'  => $this->get_field_name('checkbox'),
		'type'  => 'checkbox',
		'options'  => array(
		     'aaa'  => 'aaa',
		     'bbb'  => 'bbb',
		     'ccc'  => 'ccc',
		),
		'title'	=> __('Checkbox', CD),
	);
	echo cs_add_element( $a_field, $a_value );
</pre>

Is there any way to use checkbox or multiple select in widget ?!

Thanks.

**Comment by champsupertramp** [comment]
@Codevz I've encountered the same issue earlier. try removing the esc_attr( ) and test it. let's see if this resolves the issue.

**Comment by Codevz** [comment]
Thanks dude, problem solved :+1:

**Comment by Codestar** [comment]
Great :+1:

**Comment by aligos** [comment]
how ca i implelmentation checkbox on php

**Comment by Codestar** [comment]
You can add checkbox on php so:

```php
$a_value  = ''; // for eg array('aaa', 'bbb')
$a_field  = array(
'id'      => 'unique_id',
'name'    => 'field_name',
'title'   => 'A Checkbox',
'type'    => 'checkbox',
'options' => array(
  'aaa'   => 'aaa',
  'bbb'   => 'bbb',
  'ccc'   => 'ccc',
);

echo cs_add_element( $a_field, $a_value );
```

**Comment by aligos** [comment]
Thank's i was add checkbox on metabox, CSFramework is awesome bro

**Comment by Codestar** [comment]
You're welcome and Thanks for your opinion ;)

**Comment by Codestar** [comment]
Btw, you can see here more details about "How to use framework fields in widgets" #51

**Comment by aligos** [comment]
Thank's , maybe sometimes i will use CS form my widget.

**Comment by Codestar** [comment]
Yes why not :wink:

**Comment by aligos** [comment]
where i can get tutorials for use array checkbox to php for my custom post, sorry

**Comment by Codestar** [comment]
Check framework and metabox config files ( https://github.com/Codestar/codestar-framework/tree/master/config ) there is a lot of example for checkbox, radios, select etc.

**Comment by aligos** [comment]
<?php echo $metabox['unique_option_303']['bus']; ?> how to get value from checkbox ?

**Comment by aligos** [comment]
array(
		  'id'         => 'unique_option_303',
		  'type'       => 'checkbox',
		  'title'      => 'Facilities',
		  'options'    => array(
			'bus'      => 'Bus Pariwisata AC',
			'minibus' => 'Mini bus – Elf AC',
			'mobil'     => 'Avanza – Innova',
			'tiketpesawat' => 'Tiket Pesawat',
			'tiketka' => 'Tiket Kereta Api',
			'sopir' => 'Driver',
			'parkir' => 'Tol & Parkir',
			'bbm' => 'BBM',
			'pickup' => 'Pick Up Service to Bandara / Stasiun KA',
			'bandara' => 'Drop to Bandara / Stasiun KA',
			'makanpagi'      => 'Makan Pagi',
			'makansiang' => 'Makan Siang',
			'makanmalam'     => 'Makan Malam',
			'snack' => 'Snack',
			'welcomedrink' => 'Welcome Drinks',
			'minumtradisional' => 'Tradisional Drinks',
			'airmineral' => 'Air mineral',
			'softdrink' => 'Soft drinks',
			'barbeque' => 'Barbeque',
			'oleholeh' => 'Oleh oleh khas bandung',
			'souvenir'      => 'Souvenir',
			'spanduk' => 'Spanduk',
			'banner'     => 'Banner',
			'tshirt' => 'T-Shirt',
			'topi' => 'Topi',
			'p3k' => 'P3K / safety Equipment',
			'atk' => 'ATK',
			'bintanglima' => 'Akomodasi 5 star Hotel',
			'bintangempat' => 'Akomodasi 4 star Hotel',
			'budget' => 'Akomodasi budget / bisnis Hotel',
			'fullband'      => 'Live music full band',
			'electone' => 'Live Music electone',
			'lokalartis'     => 'Lokal artis',
			'mc' => 'MC',
			'soundsystem' => 'Sound System',
			'dancer' => 'Dancer',
			'dj' => 'Live DJ',
			'tourleader' => 'Tour Leader',
			'pajak' => 'Pajak & tax service',
			'asuransi' => 'Asuransi',
			'tiketwisata' => 'Tiket masuk Objek wisata',
			'documentasivideo' => 'Documentasi Video',
			'documentasifoto' => 'Documentasi Foto',
			'ushercrew' => 'Usher crew',
			'runnercrew' => 'Runner crew',
		  ),
		),

I use multiple checbox in page metabox.
how can I echo the output?

Here's my code


I want to write output that when user only fill 5 checkbox, in the page output, it will also shows 5 checkbox value.

**Comment by Codestar** [comment]
Hi,

Take a look this issue for how to display metabox values https://github.com/Codestar/codestar-framework/issues/3

**Comment by aligos** [comment]
i can display metabox like text area, but check box no, can you give me a sample checkbox display ... :)

**Comment by Codestar** [comment]
Output method is same for all of fields. it is not different. actually i did not understand your question.

```php
// this is checkbox example
array(
  'id'       => 'unique_id_1',
  'type'     => 'checkbox',
  'title'    => 'Checkbox Field with Options',
  'options'  => array(
    'blue'   => 'Blue',
    'green'  => 'Green',
    'yellow' => 'Yellow',
  ),
),
```

```php
// this is how to output a checkbox from metabox
$meta_data = get_post_meta( THE_POST_ID, '_custom_meta_options', true );
var_dump( $meta_data );
var_dump( $meta_data['unique_id_1'] );
```

**Comment by aligos** [comment]
Thank's it is work,

**Comment by Codestar** [comment]
Nice :+1:

**Comment by aligos** [comment]
I have two questions, 
1. How to add WordPress editor into Codestar's textarea (in metabox)?
2. Why I'm getting this error when no checkbox is defined?
Here's the error:
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\wordpress\wp-content\themes\koedihyang\single-paket.php on line 158

**Comment by Codestar** [comment]
Hi,

1. Framework have WP Editor option field. you need to use this config for editor;

```php
// two example here
array(
  'id'       => 'wysiwyg_1',
  'type'     => 'wysiwyg',
  'title'    => 'Wysiwyg',
),

array(
  'id'       => 'wysiwyg_2',
  'type'     => 'wysiwyg',
  'title'    => 'Wysiwyg with Custom Settings',
  'settings' => array(
    'textarea_rows' => 5,
    'tinymce'       => false,
    'media_buttons' => false,
  )
),
```

2. You need to add a IF checker there... for eg.

```php
// this is how to output a checkbox from metabox
$meta_data = get_post_meta( THE_POST_ID, '_custom_meta_options', true );

if( ! empty( $meta_data['unique_id_1'] ) {
  // do stuff if not empty unique_id_1
}
```

**Comment by aligos** [comment]
thank's @Codestar
