### ISSUE TITLE
Sanitize Problems!

### ISSUE THREAD

**Issue by nirweb** [Codestar/codestar-framework#134]
Hello . I submitted two plugins for publishing in the WordPress repository and both plugins were not approved due to security issues in codestar.
For example, some of the bugs they raised:

**## Variables and options must be escaped when echo'd**

There are a number of options to secure all types of content (html, email, etc). Yes, even HTML needs to be properly escaped.

https://developer.wordpress.org/plugins/security/securing-output/

Remember: You must use the most appropriate functions for the context. There is pretty much an option for everything you could echo. Even echoing HTML safely.

Example(s) from your plugin:

/option/classes/setup.class.php:556:        echo '<div class="CFSSMARTSMS-field CFSSMARTSMS-field-'. $field_type . $is_pseudo . $class . $hidden .'"'. $depend .'>';
/option/fields/link_color/link_color.php:62:      echo $this->field_after();
/option/fields/radio/radio.php:26:      echo $this->field_before();
/option/fields/radio/radio.php:35:          echo '<ul'. $inline_class .'>';
/option/views/quickstart.php:62:echo $options['opt-text']; <span>// id of field</span>
/option/views/quickstart.php:63:echo $options['opt-textarea']; <span>// id of field</span>

**## Data Must be Sanitized, Escaped, and Validated**

Remember: You must use the most appropriate functions for the context. If you’re sanitizing email, use sanitize_email(), if you’re outputting HTML, use wp_kses_post(), and so on.

An easy mantra here is this:

Sanitize early
Escape Late
Always Validate

Clean everything, check everything, escape everything, and never trust the users to always have input sane data. After all, users come from all walks of life.

Example(s) from your plugin:

/option/classes/admin-options.class.php:269: $response = ( $ajax && ! empty( $_POST['data'] ) ) ? json_decode( wp_unslash( trim( $_POST['data'] ) ), true ) : $_POST;

You have to sanitize AFTER you decode. We recommend array_walk() or array_map()

**Comment by Codestar** [comment]
Hi, 

Actually these are sanitize issues. We can not say security thing. Ok I noted and will fix these in next update :+1:
