### ISSUE TITLE
Blog images not loading

### ISSUE THREAD

**Issue by adanieli1414** [Codestar/codestar-framework#137]
Hey there. Having an issue with codestar where activating it causes featured images on blogs to disappear. Currently using codestar under the "Segovia" theme for Elementor. Any known workarounds?

Thanks in advance.

**Comment by Codestar** [comment]
Hi, 

Uh, You must ask this for theme author. Because maybe the author using older version or anything. So if there any core conflict the theme author can contact me via support service.

Regards
