### ISSUE TITLE
Wysiwyg doesn't work properly when it is placed inside a Group

### ISSUE THREAD

**Issue by rahulincedia** [Codestar/codestar-framework#138]
Wysiwyg doesn't work properly when it is placed inside a Group.
* Text is not visible.
* Visual and Text tabs don't work.
* Shortcode Generator doesn't work. Nothing happens when 'Insert Shortcode' button is clicked in Shortcode Generator.

I downloaded the latest update of Codestar framework and used with Twenty Fifteen theme to confirm the issue.

**Comment by Codestar** [comment]
Hi, Noted this issues, i will check and fix them ASAP.

**Comment by dangolprajwol** [comment]
yes i have the same issue. And i am using the latest version of codestar. Still the problem not solved?? .. Need to fix it ASAP

**Comment by Codestar** [comment]
Hi, Not solved yet, because WordPress core Wysiwyg is required a lot of js code for usage inside jquery append method. i am searching a good solution for this issue.

**Comment by dangolprajwol** [comment]
Hope, You solve this issue ASAP. Good Luck. Anyway I just liked codestar framework. It's easy to learn and use this framework. Thumbs up for This awesome framework and its developers. :)

**Comment by Codestar** [comment]
Thanks for your opinions :+1: I am happy. ok i will solve it ASAP :wink:
