### ISSUE TITLE
Sanitize save ajax not show data in realtime

### ISSUE THREAD

**Issue by LeninZapata** [Codestar/codestar-framework#14]
Hello, when you save the data and you have enabled the AJAX mode, then this has no visual effect on the fields that have Sanitize. When the browser is refreshed, the data is displayed.

**Comment by Codestar** [comment]
Hi,

Yes right. The framework offers a basic sanitize and validation system. Its not working effectifly. You should to write your custom javascript code for more ability :)

Regards, Codestar

**Comment by LeninZapata** [comment]
Ok, I'm going to write the plugin then to be able to show the data in ajax, thanks for the permission. :)

**Comment by Codestar** [comment]
:+1:
