### ISSUE TITLE
How to call meta box value form group field.

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#14]
Anyone use Codestar framework group field. I have added it as custom meta on a custom post type. 
It's sounds good but problem is when I trying to get the value form meta boxes. 
It's return a multidimensional array, can't do any thing with this array. 
As you can see I have added only one Button but the array returning me one extra array with empty values. 
Also it's gives me Illegal string offset & Illegal string offset error when i tried to var_dump it's index like so
<pre>var_dump($meta_data['_nonce']);</pre>
http://puu.sh/ftK7T/6527c98771.png

Thanks

**Comment by Codestar** [comment]
Hi,

Ops, yes i forget to ignore _nonce request from group field. I made an update for this. Can you check it now ? you can update only <a href="https://github.com/Codestar/codestar-framework/blob/master/classes/metabox.class.php">metabox.class.php</a> or re-download ;)

**Comment by wpbean** [comment]
Hi, Thanks for quick reply. I just re-download and try it. It's showing ok on var_dump but can't getting the the array value.

When I tried to var_dump the meta value like so, it's return the following arrays. Which looks perfect to me. 
<pre>var_dump($plain_slider_meta);</pre>
http://puu.sh/fwqqn/e3e799ca25.png

But when I tried to var_dump one of my array index like so 
<pre>var_dump($plain_slider_meta['plain_slider_btn']);</pre>
It's give me <b>Illegal string offset</b> & <b>Uninitialized string offset: 0 in</b> errors. Screenshot bellow. 
http://puu.sh/fwrWN/3a4fed6174.png

Can you please check it? 

Thanks

**Comment by Codestar** [comment]
Hi,

Uh! interesting. hmmm can you share with me plain-shortcode.php via https://gist.github.com and give link. i will check it for you.

**Comment by wpbean** [comment]
hi,
Here the gist link. 
https://gist.github.com/wpbean/3e3d7bf49337a5885dec

Thanks.

**Comment by Codestar** [comment]
Hi,

Hmm, I checked your shortcode, but you can not use it directy:

```
// WRONG
$plain_slider_meta = get_post_meta( $post->ID, '_plain_slider_meta', true );
var_dump( $plain_slider_meta['plain_slider_btn'] );
```

```
// RIGHT
$plain_slider_meta = get_post_meta( $post->ID, '_plain_slider_meta', true );
foreach( $plain_slider_meta as $meta ) {
 var_dump( $meta['plain_slider_btn'] );
}
// because, group option file return multilevel arrays.
```

It is ok now or still same ?

**Comment by wpbean** [comment]
Hi, Thanks man. Your support it too good. Become a huge fan of this framework. I will like to promote this to my developer friends . 
Problem was vary funny. We must call the meta value as array, But I was calling it as string. 
Now I call it as array by this 
<pre>$plain_slider_meta = get_post_meta( $post->ID, '_plain_slider_meta', false );</pre>
and it's working fine.

Thanks

**Comment by Codestar** [comment]
Hi,

Thanks for your opinions. and yes **false** is right :+1:
