### ISSUE TITLE
cannot get values from group fields in post metabox options 

### ISSUE THREAD

**Issue by shohagdatta** [Codestar/codestar-framework#141]
Hi, i like to work with codestar framework. It is really nice. At first thanks for this framework. 
I am getting some issue during working. such as i tried to add 'group field' in post metabox. i cannot get value from group field it gives error but when i use  var_dump( ); it give me all string. 

i am confused  about this. i need to use group field in this section. 
here is my code
https://gist.github.com/shohagdatta/93246b487d0c7475489d

![git2](https://cloud.githubusercontent.com/assets/13689364/9129577/696928c2-3cfb-11e5-8c52-392c7098a2fd.png)

![git](https://cloud.githubusercontent.com/assets/13689364/9129579/74d8d932-3cfb-11e5-91ff-2abe4eb1faf4.png)

**Comment by champsupertramp** [comment]
@shohagdatta 
Try this:

```PHP
$post_meta  = get_post_meta( get_the_ID(), 'post_formats', true );
$songs = ( isset( $post_meta['album_information'] ) ) && $post_meta['album_information'] && array(); 
foreach( $songs as $key => $song ){
  var_dump($song);
  echo $song['song_no_text'];
  echo $song['song_name_text'];
}          

 // Or 
var_dump( $songs[0]['song_no_text'] );

```

**Comment by shohagdatta** [comment]
thanks for your comment. I tried this. but it shows error.(Warning: Invalid argument supplied for foreach() ) . and var_dump replay null value.

**Comment by Codestar** [comment]
Hi @shohagdatta,

You can use this code for avoid warnings.

```php
$post_meta = get_post_meta( get_the_ID(), 'post_formats', true );

if( ! empty( $post_meta['album_information'] ) ) {

  $songs = $post_meta['album_information'];

  foreach( $songs as $key => $song ){
    echo $song['song_no_text'];
    echo ( isset( $song['song_name_text'] ) ) ? $song['song_name_text'] : ''; // maybe
  } 

}
```

**Comment by shohagdatta** [comment]
@Codestar 
Thanks. it works. I love this framework.

**Comment by Codestar** [comment]
You're welcome :+1:
