### ISSUE TITLE
Description field in Metabox

### ISSUE THREAD

**Issue by templatation** [Codestar/codestar-framework#143]
Hey,

I want to ask if there is a way to put descriptions for the fields in Metaboxes. I tried label but seems it works only with checkbox.

Please let me know , thanks in advance.

**Comment by templatation** [comment]
Please ignore, 

I figured desc works fine. Couldnt find it in docs though. 

thanks for awesome work.

**Comment by Codestar** [comment]
Thank for your opinion about framework :smile:
