### ISSUE TITLE
add_filter( 'csf_welcome_page', '__return_false' ); doesn't remove tools menu item

### ISSUE THREAD

**Issue by UVLabs** [Codestar/codestar-framework#145]
I tried adding the filter to remove the codestar framework menu item but it didn't remove the item. There seems to be something wrong with the condition here: https://github.com/Codestar/codestar-framework/blob/master/views/welcome.php#L17

**Comment by Codestar** [comment]
Hi,

It works only pro version.

**Comment by UVLabs** [comment]
@Codestar Can you please add this to the root framework so we don't have to edit the framework code directly? This isn't taking away from your pro product...if we're to use your framework in distribution there's no need for this menu item showing on a user's site

**Comment by UVLabs** [comment]
This also doesn't need to check for `CSF::is_active_plugin( 'codestar-framework/codestar-framework.php' )` because it's not a given that the framework would be used as a plugin, it can be used as a library
