### ISSUE TITLE
Group field doesn't work with WP 4.3 Customizer

### ISSUE THREAD

**Issue by AminulBD** [Codestar/codestar-framework#145]
Hi,

Today The goup field not working wordpress 4.3 customizer. It's nothing happen when I try to change any value of the group field.

Here is screenshot:
![problem](https://cloud.githubusercontent.com/assets/5006546/9357663/0c35d908-46aa-11e5-8552-914b0bda0f39.PNG)

Thanks!

**Comment by Codestar** [comment]
Hi,

Yes it is not working on customizer. Because it is required extra adaptation effort. Customizer is mixed a little. but i will try to adapt all options for customizer.
