### ISSUE TITLE
Unescaped variables

### ISSUE THREAD

**Issue by qriouslad** [Codestar/codestar-framework#147]
Hi,

Thank you for the wonderful framework you've created. I'm trying to use it for a plugin I'm submitting to the wordpress.org repository, but the plugin reviewer said there are unescaped variables. They give the following examples:

admin-and-site-enhancements/libs/codestar-wpenha/functions/customize.php:86:      
`echo '<li id="'. esc_attr( $id ) .'" class="'. esc_attr( $class ) .'"'. $depend .'>';`

admin-and-site-enhancements/libs/codestar-wpenha/functions/customize.php:133:      
`echo '<div class="csf-customize-field'. esc_attr( $class ) .'"'. $atts .'>';`

admin-and-site-enhancements/libs/codestar-wpenha/classes/setup.class.php:752:     
`echo '<div class="csf-field csf-field-'. $field_type . $is_pseudo . $class . $visible .'"'. $depend .'>';`

admin-and-site-enhancements/libs/codestar-wpenha/classes/setup.class.php:758:          
`echo '<h4>'. $field['title'] .'</h4>';`

They're pretty strict when it comes to security. So, the "Sanitize early. Always validate. **Escape late.**" mantra is always the requirements for plugins being accepted to the directory.

Hoping v2.2.9 will include properly escaped code.

**Comment by Codestar** [comment]
Thanks for report, I will fix it in next update.
