### ISSUE TITLE
There is a bug for Tab & Fieldset field for the taxonomy metabox (Pro) version

### ISSUE THREAD

**Issue by HelloAlberuni** [Codestar/codestar-framework#148]
**Steps to reproduce the issue:**
1. Add a tab / fieldset type field in any taxonomy
2. Navigate to "Posts" -> "Categories"
3. Click on the "Add New Category" button

You will see the fields are duplicated like the image below
<img width="806" alt="image" src="https://user-images.githubusercontent.com/4057554/200258382-f6a49a94-84c0-4f2b-96e8-51faa2079d4d.png">

**Solution:**
On line `2530` of the file `codestar-framework/assets/js/main.js`
Change the "find" method by "children" method

```
//$cloned = $this.find('.csf-field').csf_clone();  // existing code
$cloned = $this.children('.csf-field').csf_clone(); // new code
```

**Comment by Codestar** [comment]
Hi,

Thanks, it's added for next update.

Regards, Codestar
