### ISSUE TITLE
How to change title on Theme Options

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#148]
Hello,

I am developing a theme with this framework.
I like to change the title of the Theme Options page. Currently the default text is "Codestar Framework by Codestar" and I like to change it. Please guide me how to change it. I prefer not to edit any core file and like to modify it by override any config file.

Bob

**Comment by Codestar** [comment]
Hi,

Yes, i did not add any way for change title or credits because this is my promotion. But you can change it from directly php file as manually :wink:

**Comment by kwayyinfotech** [comment]
Hello,

Thanks for clarification. 

As I can see, the promotion message is already added in footer of the options:
![cs-footer](https://cloud.githubusercontent.com/assets/3161848/9563498/51c62350-4ea3-11e5-91fc-d25e071d2769.png)

So the header should show theme title instead of "Codestar Framework by Codestar" in header. Personally, I recommend you to add option under config/framework.config.php file so anyone can change the text dynamically.

Bob

**Comment by Codestar** [comment]
Hi,

Oke, i will add title settings in next updates :wink:

**Comment by ibnay1930** [comment]
Hi,

I think you missing this in your last update.... cheer's.....

**Comment by Codestar** [comment]
Now you can change it from settings.. for eg:

```php
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>', // NEW PARAM
);
```

**Comment by kwayyinfotech** [comment]
Thanks a lot :)

**Comment by Codestar** [comment]
Cheers :+1:
