### ISSUE TITLE
Use Codestar plugin in my custom plugin

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#149]
Hello,

I am using this framework to develop a new theme. It is developing very smoothly.

I am also creating a plugin which creates some custom post types with some meta boxes. I like to know how I can use this framework on this plugin.

I am already using this framework in my theme. So the plugin was giving this error:
```
Fatal error: Cannot redeclare cs_get_locale() (previously declared in D:\wamp\www\xxxx\wp-content\themes\mytheme\inc\codestar-framework\cs-framework-path.php:392) in D:\wamp\www\xxxx\wp-content\plugins\myplugin\codestar-framework\cs-framework-path.php on line 432
```

Than I added **function_exists()** to check if function already exists like this:
```
if( !function_exists('cs_get_locale') ){
	require_once PLUGIN_DIR . 'codestar-framework/cs-framework.php';
}
```

But now it's giving this error:
```
Fatal error: Class 'CSFramework_Metabox' not found in D:\wamp\www\xxxx\wp-content\plugins\myplugin\custom-post-types\portfolio.php on line 163
```

I think there is different process to use in plugin. What I want in the plugin is creating custom post type and than add meta boxes in it. Also the plugin has some options too. Please describe how can I use in plugin.

**Comment by Codestar** [comment]
Hello,

Take a look this https://github.com/Codestar/codestar-framework/issues/103 you will understand how to use it inside a plugin. you do not need copy all framework files, only use a action :wink:
