### ISSUE TITLE
Text field type

### ISSUE THREAD

**Issue by pavliukpetro** [Codestar/codestar-framework#15]
Hello,
what are the types for the text field except of 'text'?

I want to make the field as a number input. It says "This field class is not available!" if I add 'type'    => 'number'

**Comment by Codestar** [comment]
Hi,

You can use this:

```php
array(
  'id'         => 'opt-text',
  'type'       => 'text',
  'title'      => 'Text',
  'attributes' => array(
    'type'     => 'number'
  )
),
array(
  'id'         => 'opt-text',
  'type'       => 'text',
  'title'      => 'Text',
  'attributes' => array(
    'type'     => 'url'
  )
),
array(
  'id'         => 'opt-text',
  'type'       => 'text',
  'title'      => 'Text',
  'attributes' => array(
    'type'     => 'password'
  )
),
```

Allowed input types: https://www.w3schools.com/tags/att_input_type.asp

Regards, Codestar

**Comment by pavliukpetro** [comment]
@Codestar Great.
Thanks

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by Octopixell** [comment]
Maybe the documentation should be updated? https://codestarframework.com/documentation/#/fields?id=number
