### ISSUE TITLE
Q: Theme Options or Customizer ?

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#150]
Hello, 

Just want to know, is this a true way to moving all of Theme options to Customizer, like this: https://drive.google.com/file/d/0B7q-ingsr5hKNnQtVWpibFN6Nk0/view

I've moved all of options for test and everything working fine, just a bit preview loading speed is low. What do you think is good or bad ?

Cheers

**Comment by Codestar** [comment]
Hello,

Oh yes it is normal. Actually i did not used/added extra hard js code for my options. Cusromizer Framework following wordpress core. for eg. Change all options as wordpress core. It will same.

But if you found any improve / idea. share with me.  :wink: 

Cheers

**Comment by Codevz** [comment]
Hi Codestar, 

Thanks for reply :+1: I really enjoy working with codestar options in customizer, I'll continues my research about it and i'll inform you.

Also found one issue in wp 4.3 that background of options in custimizer are not #fff https://drive.google.com/file/d/0B7q-ingsr5hKaUdpLWkxSDBXcFU/view

What do you think about this: https://drive.google.com/file/d/0B7q-ingsr5hKR2xkT1EwdGxadkk/view its total theme by wpexplorer, total theme does almost all options inside customizer.

All the best, 
Codevz

**Comment by Codestar** [comment]
Hi,

Thanks for contribute, i will be happy for inform :+1: 

And yes i did not used #fff ? I am using default color. you mean option hover ? or ? can you explain it more.

Yes I know, Total Theme using all theme options inside customizer. I have not any idea about speed performance ? =) it is same or not ?

Regards, Codestar

**Comment by Codestar** [comment]
Hi,

Oh btw, let me check the performance, you can add your customizer.config.php on your google drive and share with me. or it is secret, send link via codestarhelpme[at]gmail.com

**Comment by Codevz** [comment]
Hi, 

After wp 4.3, options does not white background and just with hover its white in customizer sections. I sent file to your email. its not complete yet but currently load speed is fine. 

Total has same load speed like my current customizer with codestar, Just difference are loading preview after changing options that i think its because my theme content and assets are more than total theme in front end so when i'm changing options, preview will take a second for display changes. 

Cheers, 
Codevz

**Comment by Codestar** [comment]
Hi,

Yes load speed is fine currently. And this speed is normal, i am seeing a lot of options :wink: 

btw, I can advise this for better load speed. for eg. use transport => postMessage method for some options. for eg.

```php
// Breadcrumbs
array(
  'name'          => 's_breadcrumbs',
  'title'         => __('Breadcrumbs', CD),
  'settings'      => array(
    array(
      'name'          => 'breadcrumbs',
      'default'       => 'ON',
      'transport'     => 'postMessage',  // Default Transport type for each setting is refresh, however, if you want to create live preview customization you can change it to 'postMessage'. Take a look at the example, we added trasport type to the color picker control.
      'control'       => array(
        'type'        => 'cs_field',
        'options'     => array(
          'type'      => 'switcher',
          'title'     => __('Breadcrumbs', CD),
        ),
      ),
    ),
  ),
),
// Breadcrumbs
```

```php
// js code
;(function ( $ ) {

  if ( wp && wp.customize ) {

    api = wp.customize;

    api( 'customize_option[breadcrumbs]', function( value ) {
      value.bind( function( to ) {
        if( to == true ) {
          $('#your-sidebar-id-or-class').hide();
        }
      });
    });

  }

})( jQuery );
```

```php
// up js code enqueue method
//  [click for enqueue details](https://codex.wordpress.org/Plugin_API/Action_Reference/customize_preview_init)
if( ! function_exists( 'theme_customizer_live_preview' ) ) {
  theme_customizer_live_preview() {
    wp_enqueue_script( 'mytheme-themecustomizer', get_template_directory_uri().'/js/theme-customizer.js', array( 'jquery','customize-preview' ), '1.0', true );
  }
  add_action( 'customize_controls_enqueue_scripts', 'theme_customizer_live_preview' );
}
```

I think you know this "postMessage" method already ? for eg in Route theme, i am using postMessage for a lot of options. but some options is still usign transport => 'refresh'

Regards, Codestar

**Comment by Codevz** [comment]
Hi, 

Thanks, yes i wanna use this for colors, but as seen in your code is usable for simple class changes and text values too :+1: 

But something are wrong with your code, i've tested it seems can't detect option id from:

api( 'customize_option[breadcrumbs]', function( value ) {

my current code: 

<pre>
;(function ( $ ) {
  if ( wp && wp.customize ) {
    api = wp.customize;

    api( 'customize_option[layout_type]', function( value ) {
      value.bind( function( to ) {
        if( to ) {
          $('#layout').removeClass().addClass( to );
        }
      });
    });

  }
})( jQuery );


        array(
          'name'          => 'layout_type',
          'default'       => 'full',
          'transport'     => 'postMessage',
          'control'       => array(
            'type'        => 'cs_field',
            'options'     => array(
              'type'      => 'select',
              'title'     => __('Layout type', CD),
              'options'   => array(
                'full'        => __('Full', CD),
                'boxed'       => __('Boxed', CD),
                'boxed-margin'=> __('Boxed with margin', CD)
              ),
              'radio'     => true,
            ),
          ),
        ),
</pre>


But still not working, i checked customizer.js has loaded in customzier.

Any help would be appreciate :)

Cheers

**Comment by Codestar** [comment]
Hi,

Ups, I mixed option ID with Route. can you use this:

```php
api( '_cs_customize_options[layout_type]', function( value ) {
...
```

Regards, Codestar

**Comment by Codevz** [comment]
Hi, 

Oh sorry its my mistake should i read doc before ask question. Anyway still does not working and there is one problem, i changed code to this: 

<pre>
;(function ( $ ) {
  if ( wp && wp.customize ) {
    api = wp.customize;

    api( '_cs_customize_options[layout_type]', function( value ) {
      value.bind( function( to ) {
        $('#layout').attr('class', to);
        $('body').prepend(to);
      });
    });

  }
})( jQuery );
</pre>

Not working correctly, plz check out: http://i.imgur.com/tIOo96X.jpg

Also checked with this one: $('#layout').attr('class', to); but same result.

Cheers, 
Codevz

**Comment by Codestar** [comment]
Hi,

Uh, Also can you try this action ```customize_preview_init``` for enqueue:

```php
// up js code enqueue method
// 
if( ! function_exists( 'theme_customizer_live_preview' ) ) {
  function theme_customizer_live_preview() {
    wp_enqueue_script( 'theme-customizer', get_template_directory_uri().'/js/theme-customizer.js', array( 'jquery','customize-preview' ), '1.0', true );
  }
  add_action( 'customize_preview_init', 'theme_customizer_live_preview' );
}
```

Very interesting, wordpress core saying ```customize_controls_enqueue_scripts``` ok let's try it and tell me result.

Regards, Codestar

**Comment by Codevz** [comment]
Hi, 

Thanks man it works :+1: you're the best, I'll keep working to add other options and will inform you about future news. 

All the best, 
Codevz

**Comment by Codestar** [comment]
Hi,

You're welcome bro :+1: Yes I will be happy, when you finish it. show me :wink: 

Regards, Codestar

**Comment by pablorrr** [comment]
Hi Codestar:)
I would like to get same values either customizer and option panel from same type of options for e.g text field. Simirarly like Twenty Thirteen saved values are same in both sides. How to achieve that?
