### ISSUE TITLE
meta box text area issue

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#151]
Hi

This time i faced small issue, 

i added text area for my post (using metabox.) when i add text its show in my post, but if i add some code, (i added sound cloud share code, ) its not saving, 

Can you please help me to fix it

Thanks :)

**Comment by Codestar** [comment]
Hi,

Actually, all textarea options using sanitize. and you can disable this sanitize so:

```php
array(
  'id'       => 'textarea_1',
  'type'     => 'textarea',
  'title'    => 'Un-sanitized Textarea',
  'sanitize' => false, // take a look this param
),
```

It worked?

**Comment by WPsmart** [comment]
Thanks Very much For your Quick Help, Its working, :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by sinsky** [comment]
@WPsmart  To find a complete code for me? I found that I had no effect.

**Comment by sinsky** [comment]
@Codestar  the metabox can't woking ?

**Comment by WPsmart** [comment]
@sinsky Do you need to add text area to Meta box? or theme options page?

**Comment by sinsky** [comment]
@WPsmart  i need metabox with out sanitize

**Comment by NoahjChampion** [comment]
@sinsky 

Did you see the comments above? You can use...

```php
'sanitize' => false,
```

**Comment by sinsky** [comment]
@NoahjChampion  but i just test it more times  , is not ok ..

**Comment by NoahjChampion** [comment]
For what field? Send a gist config so I can try and tell me the result you need.

**Comment by sinsky** [comment]
metabox All field types without sanitize

**Comment by NoahjChampion** [comment]
@sinsky 

Sanitize for almost all fields should work, but I've never needed to use it. Will you email your config to Noahj at -- FearlessMode ?

**Comment by Codestar** [comment]
``` php
'sanitize' => false,
```

This is stopping sanitize exactly. i think there is a different issue.

**Comment by sinsky** [comment]
@Codestar i want  one key one value. now is sanitize
