### ISSUE TITLE
Making select field's options dependable?

### ISSUE THREAD

**Issue by mayeenulislam** [Codestar/codestar-framework#152]
I assigned two `<select>` fields, I know I can use `dependency` parameter, but it works for select fields itself, not for its options. I want to load the second select field's options to be loaded as per the selection of the first one. Is it possible in Codestar, or do I need custom AJAX function to do that?

**Comment by Codestar** [comment]
Hi,

No, it is not possible, you need to custom ajax for this operation :wink:
