### ISSUE TITLE
categories list not showing up

### ISSUE THREAD

**Issue by yukijay** [Codestar/codestar-framework#153]
Hello,

I found a problem where the "Categories" options does not display any category if the first category in the site does not have assigned posts. After Inspecting the options.cass.php file, I have noticed that this is caused by the "! empty( $categories[0] )" if statement at line #255.

**Comment by Codestar** [comment]
Hello,

Uh, i think you are using older version of files ? take a look new [options.class.php](https://github.com/Codestar/codestar-framework/blob/master/classes/options.class.php) and check your file it is same?

**Comment by yukijay** [comment]
Oh, I see! Yes, I was using an older version. Thanks! :)

**Comment by Codestar** [comment]
You're welcome :+1:
