### ISSUE TITLE
Saving meta values from script

### ISSUE THREAD

**Issue by templatation** [Codestar/codestar-framework#154]
Hi,

I am implementing CS in a theme where another meta box system was being used earlier.
So I need to convert the old values of meta to CS system.
 
So I fetched current custom field values using get_post_meta, and then saved them back to array I am using for CS meta boxes.
The new values does save to the post in same array as they should. (I verified it by doing get_post_meta and print_r again for that post).

But the problem is the new CS meta boxes doesnt load those saved values(when I refresh the page without saving it, I did save custom fields using update_post_meta, and then saved post too using wp_update_post), rather they are blank. And if we click publish here, then the above print_r function returns all blank values. (thus its proved that correct array was updated by my script.)

So is there a way to 'inform' CS framework that custom fields values were saved outside, and it fetches them ?

I hope I am clear.
Thanks in advance. :)

**Comment by templatation** [comment]
Hey,

I would appreciate your reply, let me know if you want me to send you code I have wrote.

**Comment by Codestar** [comment]
Hi,

Sorry for delay, i am in holiday. hmmm very interesting. maybe a plugin conflict there ? hmm let me check it as online. you can send me your admin informations via codestarhelpme[at]gmail[dot]com i will help you :wink:

**Comment by templatation** [comment]
Hi,

Thanks for replying, I fixed the issue myself after long line to line debugging. It happened to be probblem with my code not in CS framework. :)

I have another question though.
As I said I am applying CS meta in old project, so I created options with same ID for Page and Product cpt. ( bcuz if I use different ID for them, then need to edit alot of code). It seems its working fine, is it normal ? ID should be unique , so I am worried if there are consequences of this. 
Please suggest.

**Comment by Codestar** [comment]
Hi,

Oh nice news about saving meta :+1: 

Another question. hmm no you do not need unique id for options. Actually unique id required for multiple metaboxes. for eg. "Pages" if you use two metabox like this #40 also i am using same unique id for Posts and Page metabox in my theme. it is normal :wink:
