### ISSUE TITLE
Image upload field doesn't have Image preview option

### ISSUE THREAD

**Issue by mmaumio** [Codestar/codestar-framework#155]
I'm not sure if there's any reason you opted it out.
If not do you have any plan to add an image preview on the "upload" file?

However I see the "image" field does the job. 
However I wasn't able to make this work so far.
So I created the issue.

But now it works.

Also what's the purpose of those 2 fields "upload" and "image" which serve exactly the same purpose?

It's not an issue anymore now.

Thanks

**Comment by wpbean** [comment]
@mmaumio You may be using the field upload, use field type image for previewing image in options. 
Screenshot : http://puu.sh/klcyH/e5c8ec9406.png

Thanks

**Comment by mmaumio** [comment]
Yeah. Please check out the thread above :)
@wpbean

**Comment by mmaumio** [comment]
I knew that :)
Check the above thread now.

Thanks @wpbean

**Comment by Codestar** [comment]
Hi,

Yes said as @wpbean if you want to image preview. you need to use field type [image](http://codestarframework.com/documentation/#image)
