### ISSUE TITLE
There should be an action hook for update/reset options

### ISSUE THREAD

**Issue by sohan5005** [Codestar/codestar-framework#158]
Actually I'm packaging less compiler with my theme. Some variables are set from theme options. So, I need to execute the compiler function every time theme option is changed.

I have found this: https://github.com/Codestar/codestar-framework/issues/142

I tried your suggested method but it doesn't perfectly. Because the sanatization filter will be applied before saving the options. So, when the option is saved, the less file is compiled with older option values. It works when saving 2 times.

I've tried to go through the source and add a hook myself but cannot figure out what's happening there.

Any way to fix this?

Thanks

**Comment by Codestar** [comment]
Hi,

Hmm, actually i added a filter here after save or reset. [framework.class.php#L245](https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php#L245) i think we need to add a ```do_action``` here for your request ? did your try to add a action below this line? it working. let me check it. i can try some solutions for this request. give me your wordpress admin informations if your site is online via codestarhelpme[at]gmail[dot].com

Regards, Codestar

**Comment by sohan5005** [comment]
Hi,

Thanks for the response. As I said, I have already tried to use `'cs_validate_save'` filter to do my workout. But it doesn't do as I need.

You know, the filter is applied before the option updates. But what I really need is to do some actions after the new options are updated.

I need to compile less files with new options each time options are saved. So, when I use `'cs_validate_save'`, then the old options are used. Not the new options. Hope you got it.

Unfortunately, I don't have them live yet. Still working in localhost.

Thanks
Sohan

**Comment by Codestar** [comment]
Hi,

Actually, this ```cs_validate_save``` filter giving updated or reset options before save. for eg.

```php
your_compile_less function( $request ){

  var_dump( $request ); // this is giving saved options?

  // wrong use cs_get_option('option_name'); here.
  // right use is $request['option_name']; here.

}
add_filter( 'cs_validate_save', 'your_compile_less' );
```

BTW, if still not working, no worries about this. try two save for test. when you have live site. i can fix it quickly. you know now i can not try any code ? smile: 

Regards, Codestar

**Comment by sohan5005** [comment]
Oh, I was trying with `cs_get_option()` here. Let me try with the passed values. I will let you know if it works.

Thanks

**Comment by Codestar** [comment]
Yeah, try and tell me :+1:

**Comment by sohan5005** [comment]
Wow it worked! I never tried to see what the `$request` variable is..

I have registered my own hook like this:

```
/**
 * The option save hook
 */
if( !function_exists( 'prefix_register_option_update_hook' ) ) :
function prefix_register_option_update_hook( $request ){
    
    // Let's use the passed variable in the hook
    do_action( 'prefix_after_option_saves', $request );
    
    return $request;

}
endif;
add_filter( 'cs_validate_save', 'prefix_register_option_update_hook' );
```

Now it's working correctly :100:
Thanks for the assistance :+1:

**Comment by Codestar** [comment]
Wooow, great! You're welcome. :+1: Thanks for choose my framework. :100:
