### ISSUE TITLE
illegal string offset?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#16]
Hi Codestar,

I've added your provided code in meta box. Also, i get that value using <pre>get_post_meta( get_the_ID(), 'page_options', true );</pre> But i get error using that : 

<img src="http://i.imgur.com/GxJPU65.png" />

here is that header code : 
<pre>
$sub_title = get_post_meta( get_the_ID(), 'page_options', true );
  if ($sub_title['page_sub_title']) { 
      <? &lt;h3 class=&quot;page-sub-title&quot;&gt;&amp;lt;?php echo $sub_title['page_sub_title']; ?&amp;gt;&lt;/h3&gt; &amp;lt;?php } else { }
</pre>

Thanks,
Ansif

**Comment by Codestar** [comment]
Hi,

What is the result here:

```
$sub_title = get_post_meta( get_the_ID(), 'page_options', true );
var_dump( $sub_title );
```

try and tell me?

**Comment by santiagointeractive** [comment]
Just a gues...
Have you tried using condition like this?

<pre><code>if ( !empty($sub_title['page_sub_title']) ) { //do something }</code></pre>

**Comment by Codestar** [comment]
Yes said as @santiagointeractive and thanks for contribute. :+1:

**Comment by santiagointeractive** [comment]
Thank you @Codestar for sharing this really awesome framework with us! :smiley:
Keep up the good work! :+1:

**Comment by Codestar** [comment]
You're welcome :smiley:

**Comment by Ansif** [comment]
Awesome, @santiagointeractive & @Codestar!

<pre>if ( !empty($sub_title['page_sub_title']) ) { //do something }</pre>

It's Working!

Thanks for your contribution @santiagointeractive! :+1:
