### ISSUE TITLE
How to set default value for image type in CS ? 

### ISSUE THREAD

**Issue by dangolprajwol** [Codestar/codestar-framework#160]
```php
array(
   'id'      => 'home_banner_image',
   'type'    => 'image',
   'title'   => __('Enter Baground Banner Image','napikai'),
   'help'    => 'The Image Size Must Be 1366 x 798 For Perfection',
   'default' => get_template_directory_uri().'/assets/images/main.jpg'
)
```

This didn't worked for me . Any ideas ?

**Comment by Codestar** [comment]
You can not add default as directory image. because ```image``` field support attachment ID from database. but i will improve this fields. i noted this request.

you can use ```upload``` option field as alternative. upload field supporting directory image.

**Comment by jahir07** [comment]
Yes, you can make it by a simple change of image type. Open `image` option field and line no 27 add following code - 
`      $preview    = ($attachment) ? $attachment[0] : $value;
`
