### ISSUE TITLE
Switcher field issue

### ISSUE THREAD

**Issue by sohan5005** [Codestar/codestar-framework#161]
Hi,

Just facing a new issue with the switcher field.

When I call any switcher field with default value true like `cs_get_option( 'my_switcher_field', true )` or `cs_get_option( 'my_switcher_field', 1 )`, then it always returns true. Even if you make the option false from option panel.

I did some investigation on this and found something. I tried to dump the option field from database. Then I see, the turned off switcher fields are not saved in database. In fact those fields are totally removed when they are turned off. When they are on, they are saved with a value of `1`. But when turned off, they are removed again from the database. So, `cs_get_option()` function thinks that the field doesn't exist and returns the default hard coded value.

Currently, I'm using a custom function which works for me. But I think you should really care about this sanatization.

Anyway, thanks for the awesome framework. I'm using it for the very first time and really loving it :+1: 

Thanks
Sohan

**Comment by Codestar** [comment]
Hi,

Actually, yes you are right. but there is a logic error, you or my framework. let's talk about it.

```php
// Actually you can write here your default value?
array(
  'id'      => 'switcher_1',
  'type'    => 'switcher',
  'title'   => 'Switcher',
  'default' => true, // here is true or 1
),

// usage
$has_true = cs_get_option( 'switcher_1' ); // output will return "true"

// because, when you install active theme default values recording automatically in db.
```

```php
// Let's see your idea
array(
  'id'      => 'switcher_1',
  'type'    => 'switcher',
  'title'   => 'Switcher',
), // this array meaning, false because there is no true/1 ? if so switcher will stay on false ?

// usage
$has_true = cs_get_option( 'switcher_1', true ); // this default true will not return, because db value is false. as said me "array meaning" i am not sure how i can check it ?
```

Shortly i can say this. ```cs_get_option( 'switcher_1', true );``` alternative usage ```default => true``` this default value will auto-save when install theme. i think you missing here :wink: 

Or i am wrong, i am not sure :smile: btw, you can see here how to check default value or db value [cs-framework-path.php#L138](https://github.com/Codestar/codestar-framework/blob/master/cs-framework-path.php#L138)

Codestar

**Comment by Codestar** [comment]
You can use switcher on your theme:

```php
array(
  'id'      => 'footer',
  'type'    => 'switcher',
  'title'   => 'Show Footer',
  'default' => true,
),

// front page
if( cs_get_option( 'footer' ) ) {
  // do stuff
}
```

btw, do not forget to "restore" button. before try it. because framework saving default datas when install theme or active framework plugin. "restore" button will auto-resave default values.

Codestar

**Comment by sohan5005** [comment]
Hi,

Your every example just work fine. But if you try like this,

1. try to turn off the switcher field from options panel and save.
2. Now get the value like this `cs_get_option( 'switcher_1', true );` or `cs_get_option( 'switcher_1', 1 );`

Eventually you will get a result of `true`. Note that you made it false from the options panel.

Now, with the switcher still turned off,

1. Get the whole option field like this `$options = get_option( '_cs_options' )` or whatever option name is used
2. now debug it with a `var_dump( $options );` or `print_r( $options )`

Now, if you check the result, `'switcher_1'` key is empty. It doesn't have any false or 0 value. That's why, the true is returning from `cs_get_option();` function's default.

So, I hope the main problem is found there.

Thanks

**Comment by Codestar** [comment]
Hi,

Hmm Yes, let's try this go to your framework file [cs-framework-path.php#L138](https://github.com/Codestar/codestar-framework/blob/master/cs-framework-path.php#L138) and edit this line as : 

```php
if( ! empty( $option_name ) && isset( $options[$option_name] ) ) {
```

Try and tell me result ?

Codestar

**Comment by sohan5005** [comment]
Currently the line is same. I'm using the latest version.

But to be sure, I did try. But still it does same.

**Comment by Codestar** [comment]
Uh, i mean change this line on your framework

```php
// from
if( ! empty( $option_name ) && ! empty( $options[$option_name] ) ) {
// to
if( ! empty( $option_name ) && isset( $options[$option_name] ) ) {
```

Hey bro, said as me: ```cs_get_option( 'switcher_1', true );``` you can not get this true args. because framework saving automatically defaults.

Now, try from/to code on your files **cs-framework-path.php** and "restore" and try option output ? still same ?

Codestar
