### ISSUE TITLE
How to use options in theme and plugins both

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#162]
Hello,

I am using CS framework in my theme by using the "cs-framework-override" folder. I am using it for Theme Options, Meta Boxes and ShortCodes. All are working perfectly.

I am creating plugin that is also using cs framework. I like to know how to use CS framework to create plugin options page. Currently I used meta boxes option in the plugin and it's working perfectly but I am also going to create plugin options too. Please describe how to use it.

**Comment by Codestar** [comment]
Hi,

Uh, it is not possible. It is required modification. Actually i am thinking this feature in next theme updates. If you need it urgent, i can do it as freelance work.

BTW, You can put new options on default framework tabs "when active your plugin" for eg.

```php
/*
  Plugin Name: Your Custom Plugin
  Plugin URI:  http://yourpluginurl.com/
  Description: This plugin for Custom things
*/

// putting new options so
function prefix_custom_plugin_options( $options ) {
  $options[]    = array(
    'name'      => 'plugin_settings_section',
    'title'     => 'Plugin Settings',
    'icon'      => 'fa fa-check-circle',
    'fields'    => array(

      array(
        'id'    => 'a_plugin_setting_1',
        'type'  => 'text',
        'title' => 'Email Text',
      ),

    )
  );
  return $options;
}
add_filter( 'cs_framework_options', 'prefix_custom_plugin_options' );
```

But, said as me. if you want to a new framework panel. it required modifications.

Codestar

**Comment by kwayyinfotech** [comment]
Thanks for update. It's ok as I am also not need this feature now. I was asking for my upcoming plugin.

**Comment by Codestar** [comment]
Noted this request :+1:
