### ISSUE TITLE
Metaboxes deleting other metaboxes

### ISSUE THREAD

**Issue by jaredbrandon** [Codestar/codestar-framework#164]
I'm having an issue where when I add metaboxes to a page it is deleting others that were previously published. We've updated to the latest Codestar version but it didn't fix it.

**Comment by Codestar** [comment]
Uh, actually, i am using core function ```save_post``` for metabox saving https://codex.wordpress.org/Plugin_API/Action_Reference/save_post Let me check your metabox system. is your site online ? you can send me admin informations via codestarhelpme[at]gmail[dot].com
