### ISSUE TITLE
Group field doesn't work in shortcode dialog.

### ISSUE THREAD

**Issue by DeathMark** [Codestar/codestar-framework#167]
I'm trying to add group field into shortcode parameters but it doesn't add anything when I click Add New button.
I think shortcode doesn't support group field. Is it right?

**Comment by Codestar** [comment]
Hi,

Shortcode dialog system is different than framework system. You know there is using [shortcode] tag attributes. But i created another idea for clone things. Please check default [shortcode.config.php#L390-L489](https://github.com/Codestar/codestar-framework/blob/master/config/shortcode.config.php#L390-L489) see dublicate shortcode examples. this is same with group field :wink:

**Comment by DeathMark** [comment]
Thank you :+1: 
I think it would be nicer if we can collapse clone section like group field :)

**Comment by Codestar** [comment]
You're welcome :+1:
