### ISSUE TITLE
No option to reset ALL options

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#170]
Hello,

The Theme Options has two buttons "Save" and "Restore" button.
When I click on "Restore" button than it reset for current section only and not all options (in all sections). So I like to know is there any way to reset all option (for all sections).

Thanks,
Bob

**Comment by Codestar** [comment]
Hi,

Yes it is possible with a small modification. see this line: [framework.class.php#L365](https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php#L365) and change line as:

```php
submit_button( __( 'Reset', 'cs-framework' ), 'secondary cs-restore cs-reset-confirm', $this->unique .'[resetall]', false );
```

or you can add this line after Restore button :+1:  like this:

```php
submit_button( __( 'Restore', 'cs-framework' ), 'secondary cs-restore cs-reset-confirm', $this->unique .'[reset]', false );
submit_button( __( 'Reset', 'cs-framework' ), 'secondary cs-restore cs-reset-confirm', $this->unique .'[resetall]', false );
```

You know :wink:

**Comment by kwayyinfotech** [comment]
Yes this is working perfectly. Thanks :)

Just like to recommend you, this is a required option (at least for me) so I recommend you to add this in next version. You can hide it by default via some settings. So if anyone (like me) want this button than just write a small PHP or any other code to make it visible. That should help us a lot as we don't need to edit file everytime I update framework.

Thanks,
Bob

**Comment by Codestar** [comment]
You're welcome, Yes. I will add it as optional on default settings :+1: it is easy.
