### ISSUE TITLE
WYSIWYG type not working in shortcode window

### ISSUE THREAD

**Issue by MrHunter** [Codestar/codestar-framework#171]
I can't seem to get the WYSIWYG editor to work when used in the shortcode window even, here is what I get with it:
![screen shot 2015-11-26 at 2 18 55 pm](https://cloud.githubusercontent.com/assets/5040696/11429650/0a7937da-9449-11e5-989b-29d75857bffd.png)

I can click the "Text" side however it won't go back to the Visual side and I get this error in the console:

Uncaught TypeError: Cannot read property 'canvas' of undefined

**Comment by Codestar** [comment]
Hi, Yes Visual Editor issue in some javascript append system, i am planing to integration this for next updates. because it is required some javascript. btw, we are talking about this here #30 and #76

**Comment by roscabgdn** [comment]
Any updates ?

**Comment by stefan25w** [comment]
For my project I created a reload function for tinymce fields within a group field. It's not perfect, but it does the trick for the visual editor. You can put the code in cs-framework.js and run it with:
 `$('.cs-groups').CSFRAMEWORK_RELOAD_WYSIWYG();`

I hope @Codestar can use it.

        // ======================================================
        // RELOAD WYSIWYG FIELDS
        // ------------------------------------------------------
        $.fn.CSFRAMEWORK_RELOAD_WYSIWYG = function() {
          var group_wysiwyg           = this.find('.cs-field-wysiwyg');

          if( group_wysiwyg && group_wysiwyg.length ) {

            group_wysiwyg.each(function(){

              if( jQuery(this).find('.mce-tinymce').length <= 0 ) {
                var field_group_i         = jQuery(this).closest('.cs-group').index();
                var default_wysiwyg_id    = jQuery(this).find('textarea').attr('id');
                var group_wysiwyg_id      = default_wysiwyg_id + '_' + field_group_i;
                var tmp_wysiwyg_settings  = tinyMCEPreInit.mceInit[default_wysiwyg_id];

                jQuery(this).find('textarea').attr('id', group_wysiwyg_id);
                jQuery(this).find('.wp-media-buttons .add_media').data('editor', group_wysiwyg_id);
                jQuery(this).find('.wp-editor-tabs .wp-switch-editor').attr('data-wp-editor-id', group_wysiwyg_id);

                tinymce.init(tmp_wysiwyg_settings); 
                tinyMCE.execCommand('mceAddEditor', false, group_wysiwyg_id); 

              }

            });

          }
        };

        // ======================================================
        // RELOAD FRAMEWORK PLUGINS
        // ------------------------------------------------------
        $.fn.CSFRAMEWORK_RELOAD_PLUGINS = function() {
          return this.each(function() {
            $('.chosen', this).CSFRAMEWORK_CHOSEN();
            $('.cs-field-image-select', this).CSFRAMEWORK_IMAGE_SELECTOR();
            $('.cs-field-image', this).CSFRAMEWORK_IMAGE_UPLOADER();
            $('.cs-field-gallery', this).CSFRAMEWORK_IMAGE_GALLERY();
            $('.cs-field-sorter', this).CSFRAMEWORK_SORTER();
            $('.cs-field-upload', this).CSFRAMEWORK_UPLOADER();
            $('.cs-field-typography', this).CSFRAMEWORK_TYPOGRAPHY();
            $('.cs-field-color-picker', this).CSFRAMEWORK_COLORPICKER();
            $('.cs-help', this).CSFRAMEWORK_TOOLTIP();
            $('.cs-groups').CSFRAMEWORK_RELOAD_WYSIWYG();
          });
        };

**Comment by quangpro1610** [comment]
@stefan25w Thank you very much !
