### ISSUE TITLE
Call function AFTER saving "Theme Options" 

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#173]
Hello,

Recently I opened an issue for ["Call function on saving Theme Options"](https://github.com/Codestar/codestar-framework/issues/142)   and it's working perfectly. But this code is working "before" saving Theme Options. But I need to call function "after" saving Theme Options so I can process based on new Theme Options.

Please guide me on this.

**Comment by Codestar** [comment]
Hi,

Actually this code meaning after saving theme options.

```php
if( ! function_exists( 'my_after_saving_options' ) ) {
  function my_after_saving_options( $options ) {

    // $options meaning final options before save. but also this is meaning after save.. 
    // because you will see $options this after save.. it is same.
    // you can imagine this "after saving"

    return $options;
  }
  add_filter( 'cs_validate_save', 'my_after_saving_options' );
}
```

What you are trying? explain me more.

**Comment by kwayyinfotech** [comment]
Hello,

Oh I got it. Actually what I am doing it generating dynamic.css file based on theme options like background, element colors etc. I was using global option (which had old values instead of new values) to get option values. But actually the $options has all the new values of options so I just need to use $options instead of global option variable.

Thanks for clarification.  CodeStar rocks :)

**Comment by Codestar** [comment]
Hi,

Acutally, you can get current options any-where. for eg:

```php
// you can use this if you do not change this line [cs-framework-path.php#L11](https://github.com/Codestar/codestar-framework/blob/master/cs-framework-path.php#L11)
// i think you did not change and you can use this.

function your_any_function(){
  $all_of_options = get_option( '_cs_options' );
  var_dump( $all_of_options );
}

// or any-where
$all_of_options = get_option( '_cs_options' );
var_dump( $all_of_options );

```

Btw, if you need any trigger for after save. you can use this method.. i am using this for generate dynamic.css

```php
// anywhere
if( ! function_exists( 'my_after_saving_options' ) ) {
  function my_after_saving_options( $options ) {
    update_option( 'prefix_options_saved', true );
    return $options;
  }
  add_filter( 'cs_validate_save', 'my_after_saving_options' );
}

// generate one-time css
$prefix_options_saved == get_option( 'prefix_options_saved' );
if( $prefix_options_saved ) {
  
  // generate.css one-time code here.

  // updating as false because for one-time check
  update_option( 'prefix_options_saved', false );
}
```

I hope, i explain it :+1:  i am not sure..

Enjoy :smile:
