### ISSUE TITLE
How to add icon label option to wp nav menu ?

### ISSUE THREAD

**Issue by osgaka** [Codestar/codestar-framework#175]
Hi,
i mean using icon in wp nav-menus. http://postimg.org/image/fsrumgdb9/

How can add icon option to there ?

**Comment by Codestar** [comment]
Hi,

Oh, this is not a request or issue for framework. This is a custom feature. You need to add it by yourself. or you can offer as freelance work. :wink:

**Comment by Ansif** [comment]
Hi Mate,

It would be nice that option within our framework itself. Because doing by core api code is most difficult i think. :)

Thanks! :+1:

**Comment by Codestar** [comment]
Hi,

Yes it is can be, but it is a custom thing. maybe i can create a tutorial for how to use framework field on wp nav menu. ok i will do :wink:

**Comment by Ansif** [comment]
Yes, please.

Can't wait to get that option within my projects! :)

Also, it should helpful for all of us! :+1:
