### ISSUE TITLE
Sorter not working in customize

### ISSUE THREAD

**Issue by developerzinan** [Codestar/codestar-framework#176]
Hi, I tried to integrate the sorter in customize section . All the sorter groups are showing but i can't save it, means when i rearrange the groups then the save button does not working and i was unable to save it. Is Codestar sorter support in customize ? if so then where is the problem in my code ... Importantly other fields are working fine but not sorter . Can I get the solution ?

```php
<?php

  $options[]            = array(
    'name'              => 'imax_customize_fields',
    'title'             => 'Homepage Sections',
    'settings'          => array(
      array(
        'name'           => 'iamx_section_sorter',
        'default'        => array(
          'enabled'      => array(
            'about'      => 'About',
            'video'      => 'Video',
            'resume'     => 'Resume',
            'skills'     => 'Skills',
          )
        ),               
        'control'       => array(
          'type'        => 'cs_field',
          'options'     => array(
            'type'      => 'sorter',
            'desc'      => 'Rearrange the order of sections here',
            'title'     => 'Homepage Section Sorter',
            'enabled_title'  => 'Active Sections',
            'disabled_title' => 'Deactive Sections',             
          ),
        ),
      ),    
    ),

  );

?>

**Comment by Codestar** [comment]
Hi,

Yes it is true, Because WP Customizer javascript working complex. I need to spend some time for this option field integration. All Framework fields not working on Customizer, but %80 fields is working correctly. 

And i will fully compatible all fields in next framework updates :wink:

**Comment by developerzinan** [comment]
Thanks for the confirmation . Eagerly waiting for next update. Hopefully we will get that soon . :+1:

**Comment by Codestar** [comment]
Yes, it will come ASAP :+1:

**Comment by developerzinan** [comment]
Also please take care of group repeat fields. I think it is not supported as well.

**Comment by Codestar** [comment]
Yes, all option fields will supported :wink:

**Comment by shimion** [comment]
Hi, is there any update regarding  repeat and sorter  fields... Thanks
