### ISSUE TITLE
How to fetch the gallery description ?

### ISSUE THREAD

**Issue by shankhadevpadam** [Codestar/codestar-framework#177]
I have configure the gallery using the framework, then i have successfully fetch the image also but i am unable to fetch that image description.

**Comment by Codestar** [comment]
Uh, i did not understand request. you mean gallery option field? if so, gallery fields returns media attachment ids for which images selected. in front-end you can get this ids and use images.

You will need this https://codex.wordpress.org/Function_Reference/wp_get_attachment_metadata
