### ISSUE TITLE
icon field sorting.

### ISSUE THREAD

**Issue by templatation** [Codestar/codestar-framework#178]
Hi,

I am trying to put  my own icons in icon field metabox. 
I was able to do it using this guide https://github.com/Codestar/codestar-framework/issues/10 ( please be informed that you have typo in cs_add_icons in your code on that page. )

Now, my icons appear, but after FA icons, so the user has to browse down a lot to find those icons and there is no information on top that below other icons can be found.
So is there a way I can move my icons on top of FA icons? 

As always, Thanks in advance.

**Comment by Codestar** [comment]
Hi,

Yes it is possible with one line modification. Now, this ```cs_add_icons``` action calling from here and move this line [functions/actions.php#L37](https://github.com/Codestar/codestar-framework/blob/master/functions/actions.php#L37) to (above 13) [functions/actions.php#L12](https://github.com/Codestar/codestar-framework/blob/master/functions/actions.php#L12)

It will load before FA icons.

You're welcome :wink:

**Comment by templatation** [comment]
Hi,

Ofcourse I could do that, but I wanted an update friendly  method. Is it too much problem for you to add
do_action( 'cs_add_icons_before_FA' );
on the top. ;)

**Comment by Codestar** [comment]
Hi,

Yes ok, no problem. i added this action for you... add this:

```php
if( ! function_exists( 'cs_get_icons' ) ) {
  function cs_get_icons() {

    do_action( 'cs_add_icons_before' ); // add this on your file. i will update repo next time.

    $jsons = glob( CS_DIR . '/fields/icon/*.json' );

    if( ! empty( $jsons ) ) {

      ...
      ...
      ...

    }

    do_action( 'cs_add_icons' );

    die();
  }
  add_action( 'wp_ajax_cs-get-icons', 'cs_get_icons' );
}
```

Action name is ```cs_add_icons_before``` because there is another icons. icomoon, line-icons etc.

**Comment by templatation** [comment]
Hey,

Thanks, you are really a Star :)

You said there are line-icons etc too, so how do I enable them, or do you mean they are included in that long list of icons ?

**Comment by Codestar** [comment]
You're welcome :smiley: This icons is not included. because it is custom things. for eg: you can include any icon packages.

https://github.com/thesabbir/simple-line-icons
https://icomoon.io/
http://fontello.com/

and much more. Actually i can add this icons as extension of framework. i will think it for next updates :wink:
