### ISSUE TITLE
Shortcode isn't working inside Options Framework

### ISSUE THREAD

**Issue by Irfan-git** [Codestar/codestar-framework#179]
Hi,

Thanks for a great framework. I'm already in love with this framework.
And just started to using it in my projects.

But it seems shortcode isn't working inside options framework. I'm using contact form 7 plugin and put it's shortcode inside a metabox of my options framework and it's returning the shortcode text instead of contact form.

I mean if I input shortcode inside a metabox of options framework like:
>[contact-form-7 id="2992" title="subscribe"]

It's output the same in front-end:
>[contact-form-7 id="2992" title="subscribe"]

I've also noticed that shortcode framework also outputting the shortcode in front-end..
Is there any way to solve the problem??

Thanks in advance,
Irfan

**Comment by Codestar** [comment]
Hi,

Thanks for for your opinions about framework. i am happy. hmm Uh, i did not understand issue. this is a custom things. Framework storing values for backend to frontend.

I mean, you need to use this for run shortcode. for eg:

```php
$cf7 = cs_get_option( 'your_option_id' );
echo do_shortcode( $cf7 );
```

```do_shortcode``` is wordpress core you know =) OR i did not understand issue?

**Comment by Irfan-git** [comment]
Thanks for coming back to me.
Sorry for the unclear description.
Yeah, you are right about the contact form 7 shortcode and it solved my problem with contact form 7 shortcode.

But I've also notice the shortcode framework's shortcode isn't showing any results.For example:
>If I add basic shortcode 1 like the image in wp mce editor:

![shortcode in dashboard](https://cloud.githubusercontent.com/assets/16193247/11658200/a567ad70-9deb-11e5-9302-8880c76531a4.png)


>It's showing up the same shortcode in frontend:


![frontend display](https://cloud.githubusercontent.com/assets/16193247/11658070/ef7e0fcc-9dea-11e5-98b0-06da5a460538.png)

**Comment by Codestar** [comment]
I have not any idea really, it is interesting. i am seeing this first-time.
