### ISSUE TITLE
Calling shortcode dialog to edit generated shortcodes from tinymce

### ISSUE THREAD

**Issue by santiagointeractive** [Codestar/codestar-framework#18]
Is there a way I can use cs-shortcode-dialog to edit existing generated shorcodes from the editor?

I'm trying to use some visual rendering for the shortcodes into editor, and I would like to call cs-shortcode-dialog and populate it's fields with shortcode's current values for easy editing.

Something like this: https://github.com/dtbaker/wordpress-mce-view-and-shortcode-editor, but calling framework's shortcode dialog window, instead of tinymce popup window.

Any clues where to start?
Thanks!

**Comment by Codestar** [comment]
Hi,

Hmm no, only supporting dialog window. because you know i am using it for textarea, html mode, tinymice mode. maybe future, i can do it :) actually shortcode generators outdated. we are using Visual Composer, Live Composer etc. for edit page. but i noted this ;)

**Comment by santiagointeractive** [comment]
Hi,

I know visual composers can do all I want to do but sometimes, on some specific projects, you don't need all that fancy complex composers, just some simple inline shortcodes inside classic page content, directly into the editor. That's why I am searching for a solution to make easier editing shortcodes attributes that are already generated in there. I think this will be massive for the users out there if would be able to do something like that.

I will give it a try and if I succeed I will share the solution for this.
Cheers!

**Comment by Codestar** [comment]
Hi,

Yeah, if you found any solution share with me :+1:

**Comment by santiagointeractive** [comment]
Hi,
I have done something regarding this issue: https://gist.github.com/santiagointeractive/eb533bb8a39ddc51b7a0

So, basically this can render shortcode attributes, or just a box with shortcode name. Transforms that ugly shortcode code into something more human readable and pretty.

Then you can edit or remove the shortcode, on click event. Editing will open CS Framework modal window and will populate fields with current shortcode values. After editing and hit insert shortcode button, that ugly shortcode code changes and you are good to go.

This have sense for me using some complex shortcodes with lots of attributes. So, if I need to change something on some shortcode is very easy this way.

You can improve, modify or include it into the framework if you like.
Feel free to comment if you have any questions or suggestions on this gist.

All the best,
SI

**Comment by Codestar** [comment]
Hi,

Nicee, forked code, let me try it :+1:  and thanks for your codes ;)

**Comment by santiagointeractive** [comment]
Your welcome ! :+1:

**Comment by santiagointeractive** [comment]
Here you go some stylesheet for shortcode rendering as box with title: https://gist.github.com/santiagointeractive/a40333b1e420f67e1451

**Comment by santiagointeractive** [comment]
I have made some changes on https://gist.github.com/santiagointeractive/eb533bb8a39ddc51b7a0

When you have s shortcode multple times into editor, after editing one of them but without updating the page, there was an issue with populating uncompleted fields in the other shortcode with values from the first. I added a reset function to trigger before adding proper values.

Tested and works nicely with simple fields like: input, textarea, switcher, select, select-chosen, color picker, upload input, checkbox. Not tested for grouped fields. I will improve this as I go more deep into creating shortcodes for the project I am implementing this kind of function.

You can refork the gist. The extension works better now.

**Comment by Codestar** [comment]
Yeah looking very good, i am thinking on this subject ;) forked new code
