### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by prionkor** [Codestar/codestar-framework#180]
At a first look it looks promising. Can you add composer support?

**Comment by Codestar** [comment]
Hi,

Yes sure, why not, i can add it. this ```composer.json``` is enough ? can you test it ?
```php
{
  "name": "codestar/codestar-framework",
  "version": "1.0.0",
  "type": "wordpress-plugin",
  "description": "A Lightweight and easy-to-use WordPress Options Framework.",
  "homepage": "http://codestarframework.com",
  "license": "GPL",
  "keywords": ["wordpress", "options", "framework", "metabox", "customizer", "shortcodes", "plugin", "codestar"],
  "authors": [{
    "name": "Codestar",
    "email": "info@codestarlive.com"
  }],
  "autoload": {
    "files": ["cs-framework.php"]
  }
}
```

It you say ok, i can add it on repo.

**Comment by kingRayhan** [comment]
This issue should be closed :smile:

**Comment by prionkor** [comment]
I see, the framework is built as a plugin. I will prefer it as a php library that I can pull into any project (theme or plugin). I guess I will maintain a fork of this project :)

**Comment by Codestar** [comment]
Yeah you can do it :smiley:
