### ISSUE TITLE
Needed Fields!

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#182]
Hi Mate,

Here i've listed some of missed filed options, from my opinion : 
1. Color Field : Normal, Hover, Active, Focus
2. Typography Field. font-(Color, Size, Style, Variant), letter-spacings, line-height, text-decoration, text-transform.
3. Box Shadow field.
4. Background field => background-size option.

I'm enjoying this plugin, you've done a great job. :+1:

**Comment by Codestar** [comment]
Hi,

Yes I will add more options in the future updates. Coming a lot of new fields soon :wink: :+1:

**Comment by Ansif** [comment]
Thanks a lot! :)

Important : Here after i'm going to use this framework for my projects. Do you support this framework regularly?

**Comment by Codestar** [comment]
Yes, I am updating framework regularly. because i am using this framework for my premium themes. I need to develop it always :+1:

**Comment by Ansif** [comment]
That's Great! :+1:
