### ISSUE TITLE
Override template folder in different location?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#183]
Hi mate,

Can you please let me know how to change, the override template folder path?

Now it's working like : 
theme_name/cs-framework-override
i want like : 
theme_name/inc/theme-options/cs-framework-override

How can i achieve this?

**Comment by Codestar** [comment]
Hi,

Yes it is possible. we have a action as ```cs_framework_override``` and usage:

```php
function my_custom_cs_framework_override() {
  return 'inc/theme-options/cs-framework-override'; // default is "cs-framework-override"
}
add_filter( 'cs_framework_override', 'my_custom_cs_framework_override' );
```

I think you need this ? :smile:

**Comment by Ansif** [comment]
Yes, i need this!

You're Awesome! :+1:

**Comment by Codestar** [comment]
:+1:
