### ISSUE TITLE
How to get values from sorter fields?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#184]
Hi Mate,

How to get field values from sorter?

<pre>
array(
          'id'             => 'sorter_2',
          'type'           => 'sorter',
          'title'          => 'Sorter',
          'default'        => array(
            'enabled'      => array(
              'blue'       => 'Blue',
              'green'      => 'Green',
              'red'        => 'Red',
              'yellow'     => 'Yellow',
              'orange'     => 'Orange',
              'ocean'      => 'Ocean',
            ),
            'disabled'     => array(
              'black'      => 'Black',
              'white'      => 'White',
            ),
          ),
          'enabled_title'  => 'Active Colors',
          'disabled_title' => 'Deactive Colors',
        ),
      ),
</pre>

Thanks! :)

**Comment by Codestar** [comment]
Hi,

Hmm for eg:

```php
$sorter_data = cs_get_option( 'sorter_2' );

if( ! empty ( $sorter_data ) ) {
  $enabled = $sorter_data['enabled'];
  $disabled = $sorter_data['disabled'];
}

// debug
var_dump( $sorter_data ); // you will see here how to return data. 
```

**Comment by Ansif** [comment]
Thanks, i'll play with it. :+1:

**Comment by Codestar** [comment]
You're welcome :wink:
