### ISSUE TITLE
Do you've any idea about Radium One Click Install?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#185]
Hi Mate,

Do you've any idea about comparable with radium one click install?
https://github.com/FrankM1/radium-one-click-demo-install

It's already support by : OptionTree and Redux.

Thanks! :+1:

**Comment by Codestar** [comment]
Hi,

Actually it is easy. Only 1-2 line add. Go to [radium-importer.php#L417](https://github.com/FrankM1/radium-one-click-demo-install/blob/master/importer/radium-importer.php#L417) and add this:

```php
...
....
.....
} elseif( $this->theme_options_framework == 'codestar-framework' ) {

  // support for codestar-framework
  $data = cs_decode_string( $data );
  $this->theme_option_name = defined( 'CS_OPTION' ) ? CS_OPTION : '_cs_options';
  
} else {
...
....
.....
```

And, do not forget to set ```init.php``` to ```$theme_options_framework = 'codestar-framework';``` I think you know it.

BTW, i will create a pull-request in radium repo :+1: 

You're welcome :+1:

**Comment by Ansif** [comment]
Thanks a lot! :+1:

Just pull request to their radium plugin repository. So, users will get that already working copy. :)

**Comment by Codestar** [comment]
Yeah, i will fork and add this code on radium repo asap :wink:

**Comment by Ansif** [comment]
Sorry for many questions!

Do you've any idea about integrate radium framework page into our own section tab?

![codestar-import](https://cloud.githubusercontent.com/assets/5621180/11809335/3590f734-a34c-11e5-837b-def69f85f482.jpg)

**Comment by Codestar** [comment]
Haha, no, it is not 1-2 line code. you need to write some php code for this :)

**Comment by Ansif** [comment]
:D Ok fine.

I just thought you've any shortcuts. :P

**Comment by Codestar** [comment]
:smile:
