### ISSUE TITLE
Is framework all options automatically available in customizer?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#186]
Hi Bro,

Is there any way to have all framework fields in customizer too?

I've seen redux framework all options available from framework to customizer the same options and same field id.

Thanks! :+1:

**Comment by Ansif** [comment]
Also, do you've any suggestions to improve user experience of using customizer and theme options framework.

What are the fields you like to use in customizer and framework - In your own projects?

**Comment by Codestar** [comment]
Hi bro,

There is some fields not support for customizer for eg group field, sorter field.. but 80% fields is supported. I am planing to support all fields for next updates. I am working on a new theme now, when i finish it. i will update framework, because i will need this group sorter fields in my new theme surely. Let's wait a little :smiley:

**Comment by Ansif** [comment]
Ok Great! :+1:

**Comment by Codestar** [comment]
:+1:

**Comment by Ansif** [comment]
Hi Mate,

I've seen your Route theme youtube videos.

TopBar :
https://www.youtube.com/watch?v=ixa2qN1RfaY&index=4&list=PLnJdp9u3mMdWoQJe74kp5zNbWuwgK22bN

Typography : 
https://www.youtube.com/watch?v=O20zpuAoXLE&index=12&list=PLnJdp9u3mMdWoQJe74kp5zNbWuwgK22bN

I like that part of you using Topbar and Typography sections. Which you utilized very well :+1: 

Can i use it same method and same fields in my theme too? Can i inspire settings like you've in your framework options like in that video?

**Comment by Codestar** [comment]
Hi,

Yes sure, you can use same idea :+1: It is no problem for me. Credit is enough for me in item description :smile:

**Comment by Ansif** [comment]
Yeah, that's sure! :+1:

**Comment by filipeleira** [comment]
@Codestar any news about sorter fields in customizer? I need this feature too..

**Comment by Codestar** [comment]
@filipeleira yes, it is on the way. i will add it asap :wink: also i am thinking my all options move to customizer. i will integrate all fields :+1:

**Comment by filipeleira** [comment]
@Codestar i'm doing the same! Customizer has a good user experience anyway :stuck_out_tongue_winking_eye:

**Comment by Codestar** [comment]
@filipeleira Sure, it will come ASAP :tada: :smile:
