### ISSUE TITLE
How to work with only one shortcode?

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#188]
![Image of Shortcode generator](https://cloud.githubusercontent.com/assets/7611746/11831489/d718f278-a3d8-11e5-931a-fc2a55757776.png)

Codestar-framework shortcode generator contains a dropdown option for using multiple shortcode. It's really awesome but my problem is,
I'm developing a plugin which need not multiple shortcode.
I want just one shortcode. 
How can I do that?
How can I remove that shortcode switcher dropdown button?

**Comment by kingRayhan** [comment]
Hope that I could make you understand my question.

**Comment by Codestar** [comment]
Actually yes it is possible with a js tricks. for eg:

```js
/**
 *
 * Work with only one shortcode
 *
 */
;(function ( $ ) {
  'use strict';

  $(document).ready( function() {

    $('body').on('click', '.cs-shortcode', function( e ) {

      e.preventDefault();

      var shortcode_id = 'cs_advanced_1'; // put your shortcode id.

      var $this     = $(this),
          $dialog   = $('#cs-shortcode-dialog'),
          $selector = $dialog.find('.cs-dialog-select'),
          $header   = $dialog.find('.cs-dialog-header');

      $dialog.outerHeight( $dialog.outerHeight() - $header.outerHeight() );
      $header.hide();

      $selector.val( shortcode_id ).trigger( 'change' );

    });

  });

})( jQuery );
```

Copy this js code on your custom admin panel js. it is clear?

**Comment by kingRayhan** [comment]
I'm not so much experienced. Can you please explain me where should I put this code?
I'm developing a plugin,How can I use this code in my plugin files?

**Comment by kingRayhan** [comment]
Sorry for coming back.

Actually I'm newbie developer.
Can you please explain me how can I use this code?
This is my [shortcode config file](https://gist.github.com/kingRayhan/2f23cbebe400a71f051a)

Should I enqueue your given code snippet in my plugin?

Please look at my `shortcode config file` and tell me what name I have to place in `cs_advanced_1`

**Comment by SantiagoInteractive** [comment]
Hi there,
Your shortcode name seems to be <code>wp_tab</code>.

As I seen there you are trying to generate group options. The right way to do that is explained here: http://codestarframework.com/documentation/#group
I don't understand what you mean by these lines key definition:
<pre>
'view'        => 'clone',
'clone_id'    => 'wp_tab_content',
'clone_title' => 'Add new tab Item',
</pre>
These doesn't seem to be keys from Codestar Framework.
Please correct me if I'm wrong @Codestar.

**Comment by Codestar** [comment]
@SantiagoInteractive Actually the request is single usage shortcode. shortly he do not know "selectbox". when click add shortcode button, only shortcode will show popup directly without selectbox. i understand this, maybe i am wrong, i do not know :smile: 

@kingRayhan 
If i understand your request correctly, you can follow this steps for only one shortcode usage:

Actually yes it is possible with a js tricks. for eg:

```js
/**
 *
 * Work with only one shortcode
 *
 */
;(function ( $ ) {
  'use strict';

  $(document).ready( function() {

    $('body').on('click', '.cs-shortcode', function( e ) {

      e.preventDefault();

      var shortcode_id = 'cs_advanced_1'; // put your shortcode id.

      var $this     = $(this),
          $dialog   = $('#cs-shortcode-dialog'),
          $selector = $dialog.find('.cs-dialog-select'),
          $header   = $dialog.find('.cs-dialog-header');

      $dialog.outerHeight( $dialog.outerHeight() - $header.outerHeight() );
      $header.hide();

      $selector.val( shortcode_id ).trigger( 'change' );

    });

  });

})( jQuery );
```

Copy this js code on your custom admin panel js. it is clear?Actually yes it is possible with a js tricks. for eg:

```js
// create this file on your  themename/js/cs-modify.js
;(function ( $ ) {
  'use strict';

  $(document).ready( function() {

    $('body').on('click', '.cs-shortcode', function( e ) {

      e.preventDefault();

      var shortcode_id = 'wp_tab'; // your shortcode id.

      var $this     = $(this),
          $dialog   = $('#cs-shortcode-dialog'),
          $selector = $dialog.find('.cs-dialog-select'),
          $header   = $dialog.find('.cs-dialog-header');

      $dialog.outerHeight( $dialog.outerHeight() - $header.outerHeight() );
      $header.hide();

      $selector.val( shortcode_id ).trigger( 'change' );

    });

  });

})( jQuery );
```

```php
// copy-paste this code on your themename/functions.php (below framework load code)
if( ! function_exists( 'cs_modify_enqueue_script' ) ) {
  function cs_modify_enqueue_script() {
    wp_enqueue_script( 'cs-modify',  get_template_directory_uri() .'/js/cs-modify.js',  array( 'cs-framework' ), '1.0.0', true );
  }
  add_action( 'admin_enqueue_scripts', 'cs_modify_enqueue_script' );
}
```

I think you need this :smile:

**Comment by kingRayhan** [comment]
My problem solved :smile:
You're very helpful.
I fall in love with Codestar Framework :heart_eyes:

**Comment by Codestar** [comment]
Thanks, love you too :wink:  :+1:

**Comment by SantiagoInteractive** [comment]
@Codestar Yes, I know what was the case here.

My concern was off-topic seeing his code and didn't understand what <code>'view'</code>, <code>'clone_id'</code> and <code>'clone_title'</code> suppose to do and if those are Codestar Framework native keys because I haven't found those into the documentation.

But if it works that's great.
Cheers! :smile:

**Comment by Codestar** [comment]
Cheers! :smile:

**Comment by haqueamirul** [comment]
Please how to display duplicate group shortcode
