### ISSUE TITLE
Do you have any plan to add Ace editor field in Options?

### ISSUE THREAD

**Issue by muntasirm** [Codestar/codestar-framework#189]
The title says it all. :)

Do you have a plan to integrate Ace Editor as an option type in Codestar?

Thanks

**Comment by Codestar** [comment]
Yes, it is coming v1.1 i will update it ASAP :wink:

**Comment by muntasirm** [comment]
Thank You :)

**Comment by JoeSz** [comment]
Hello everyone!

So I had a little time and implemented ACE editor. Maybe not the perfect way, but untill somebody come up with a better one, I thought, I share it. 

Get the following files:

ace-load.js
ace.js
ext-language_tools.js
ext-searchbox.js
ext-textarea.js
ext-themelist.js
ext-whitespace.js
mode-css.js
mode-javascript.js
theme-chrome.js
worker-css.js
worker-javascript.js

and the snippets folder if you want

from src or src-min from https://github.com/ajaxorg/ace-builds/tree/2268d21c5893320330c9daf10b70b1973ca45eba
and copy them to cs-framework\assets\js\vendor\ for example.

Then enqueue them: 

cs-framework\functions\enqueue.php 
```php
// ACE scripts
wp_enqueue_script( 'cs-vendor-ace', CS_URI .'/assets/js/vendor/ace.js', array(), '1.0.0', true );
wp_enqueue_script( 'cs-vendor-ace-mode', CS_URI .'/assets/js/vendor/mode-css.js', array( 'cs-vendor-ace' ), '1.0.0', true );
wp_enqueue_script( 'cs-vendor-ace-language_tools', CS_URI .'/assets/js/vendor/ext-language_tools.js', array( 'cs-vendor-ace' ), '1.0.0', true );
// You do not need to use a separate file if you do not like.
wp_enqueue_script( 'cs-vendor-ace-load', CS_URI .'/assets/js/vendor/ace-load.js', array( 'cs-vendor-ace' ), '1.0.0', true );
```

Create ACE Editor field. You need to create this folder and file.

cs-framework\fields\aceeditor\aceeditor.php
```php
<?php if ( ! defined( 'ABSPATH' ) ) die; // Cannot access pages directly.
/**
 *
 * Field: ACE Editor
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_aceeditor extends CSFramework_Options {

    public function __construct( $field, $value = '', $unique = '' ) {
        parent::__construct( $field, $value, $unique );
    }

    public function output() {

        echo $this->element_before();
        echo '<div class="ace-editor-wrapper">';
        echo '<textarea name="'. $this->element_name() .'"'. $this->element_class() . '>'. $this->element_value() .'</textarea>';
        echo '<div class="ace-editor-container" ' . $this->element_attributes() .'></div>';
        echo '</div>';
        echo $this->element_after();

    }

}
```

Add some CSS

cs-framework\assets\css\cs-framework.css
```css
/* ACE Editor */
.cs-field-aceeditor > .ace-editor-wrapper {
    position: relative;
    width:100%;
    height:600px;
    border: 1px solid #ccc;
}
.cs-field-aceeditor .ace-editor-container {
    position: absolute;
    top:0;
    bottom:0;
    left:0;
    right:0;
}
.ace-editor-wrapper > textarea {
    opacity: 0;
}
```
Initiate ACE Editor
I did enqueue this in separate file (ace-load.js).
```javascript
;(function( $ ) {
    "use strict";

    $( document ).ready(function() {

        // Iterate cs-field-aceeditors
        $( '.cs-field-aceeditor' ).each(function(index) {

            var $editorContainer = $( this ).find( '.ace-editor-container' );

            // Get textarea to get/save data
            var $editorTextarea = $editorContainer.prev( 'textarea' );

            // Add ID to ace-editor-container
            $editorContainer.attr( 'id', 'aceeditor' + index );

            // Get theme and language
            var editorTheme = $editorContainer.data( 'theme' );
            var editorMode = $editorContainer.data( 'mode' );

            // Inicialize ACE editor
            var editor = ace.edit( 'aceeditor' + index );

            // Set editor settings
            editor.setTheme( 'ace/theme/' + editorTheme );
            editor.getSession().setMode( 'ace/mode/' + editorMode );

            editor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });

            // Save data in textarea on ACE editor change
            editor.getSession().on( 'change', function () {
                $editorTextarea.val( editor.getSession().getValue() );
            });

            // Get data on load
            editor.getSession().setValue( $editorTextarea.val() );

        });

    });

}(jQuery));
```

Then add the field(s).

cs-framework\config\framework.config.php
```php
array(
    'id'     => 'unique-id',
    'type'   => 'aceeditor',
    'attributes'  => array(
        'data-theme'    => 'chrome',  // the theme for ACE Editor
        'data-mode'     => 'css',     // the language for ACE Editor
    ),
),
```
More from ACE Editor: https://github.com/ajaxorg/ace/wiki/

Have fun! :)

**Comment by Codestar** [comment]
Thanks JoeSz :100:

**Comment by buraksahin59** [comment]
> Hello everyone!
> 
> So I had a little time and implemented ACE editor. Maybe not the perfect way, but untill somebody come up with a better one, I thought, I share it.
> 
> Get the following files:
> 
> ace-load.js
> ace.js
> ext-language_tools.js
> ext-searchbox.js
> ext-textarea.js
> ext-themelist.js
> ext-whitespace.js
> mode-css.js
> mode-javascript.js
> theme-chrome.js
> worker-css.js
> worker-javascript.js
> 
> and the snippets folder if you want
> 
> from src or src-min from https://github.com/ajaxorg/ace-builds/tree/2268d21c5893320330c9daf10b70b1973ca45eba
> and copy them to cs-framework\assets\js\vendor\ for example.
> 
> Then enqueue them:
> 
> cs-framework\functions\enqueue.php
> 
> ```
> // ACE scripts
> wp_enqueue_script( 'cs-vendor-ace', CS_URI .'/assets/js/vendor/ace.js', array(), '1.0.0', true );
> wp_enqueue_script( 'cs-vendor-ace-mode', CS_URI .'/assets/js/vendor/mode-css.js', array( 'cs-vendor-ace' ), '1.0.0', true );
> wp_enqueue_script( 'cs-vendor-ace-language_tools', CS_URI .'/assets/js/vendor/ext-language_tools.js', array( 'cs-vendor-ace' ), '1.0.0', true );
> // You do not need to use a separate file if you do not like.
> wp_enqueue_script( 'cs-vendor-ace-load', CS_URI .'/assets/js/vendor/ace-load.js', array( 'cs-vendor-ace' ), '1.0.0', true );
> ```
> 
> Create ACE Editor field. You need to create this folder and file.
> 
> cs-framework\fields\aceeditor\aceeditor.php
> 
> ```
> <?php if ( ! defined( 'ABSPATH' ) ) die; // Cannot access pages directly.
> /**
>  *
>  * Field: ACE Editor
>  *
>  * @since 1.0.0
>  * @version 1.0.0
>  *
>  */
> class CSFramework_Option_aceeditor extends CSFramework_Options {
> 
>     public function __construct( $field, $value = '', $unique = '' ) {
>         parent::__construct( $field, $value, $unique );
>     }
> 
>     public function output() {
> 
>         echo $this->element_before();
>         echo '<div class="ace-editor-wrapper">';
>         echo '<textarea name="'. $this->element_name() .'"'. $this->element_class() . '>'. $this->element_value() .'</textarea>';
>         echo '<div class="ace-editor-container" ' . $this->element_attributes() .'></div>';
>         echo '</div>';
>         echo $this->element_after();
> 
>     }
> 
> }
> ```
> 
> Add some CSS
> 
> cs-framework\assets\css\cs-framework.css
> 
> ```css
> /* ACE Editor */
> .cs-field-aceeditor > .ace-editor-wrapper {
>     position: relative;
>     width:100%;
>     height:600px;
>     border: 1px solid #ccc;
> }
> .cs-field-aceeditor .ace-editor-container {
>     position: absolute;
>     top:0;
>     bottom:0;
>     left:0;
>     right:0;
> }
> .ace-editor-wrapper > textarea {
>     opacity: 0;
> }
> ```
> 
> Initiate ACE Editor
> I did enqueue this in separate file (ace-load.js).
> 
> ```js
> ;(function( $ ) {
>     "use strict";
> 
>     $( document ).ready(function() {
> 
>         // Iterate cs-field-aceeditors
>         $( '.cs-field-aceeditor' ).each(function(index) {
> 
>             var $editorContainer = $( this ).find( '.ace-editor-container' );
> 
>             // Get textarea to get/save data
>             var $editorTextarea = $editorContainer.prev( 'textarea' );
> 
>             // Add ID to ace-editor-container
>             $editorContainer.attr( 'id', 'aceeditor' + index );
> 
>             // Get theme and language
>             var editorTheme = $editorContainer.data( 'theme' );
>             var editorMode = $editorContainer.data( 'mode' );
> 
>             // Inicialize ACE editor
>             var editor = ace.edit( 'aceeditor' + index );
> 
>             // Set editor settings
>             editor.setTheme( 'ace/theme/' + editorTheme );
>             editor.getSession().setMode( 'ace/mode/' + editorMode );
> 
>             editor.setOptions({
>                 enableBasicAutocompletion: true,
>                 enableSnippets: true,
>                 enableLiveAutocompletion: true
>             });
> 
>             // Save data in textarea on ACE editor change
>             editor.getSession().on( 'change', function () {
>                 $editorTextarea.val( editor.getSession().getValue() );
>             });
> 
>             // Get data on load
>             editor.getSession().setValue( $editorTextarea.val() );
> 
>         });
> 
>     });
> 
> }(jQuery));
> ```
> 
> Then add the field(s).
> 
> cs-framework\config\framework.config.php
> 
> ```
> array(
>     'id'     => 'unique-id',
>     'type'   => 'aceeditor',
>     'attributes'  => array(
>         'data-theme'    => 'chrome',  // the theme for ACE Editor
>         'data-mode'     => 'css',     // the language for ACE Editor
>     ),
> ),
> ```
> 
> More from ACE Editor: https://github.com/ajaxorg/ace/wiki/
> 
> Have fun! :)

Thank you :)
