### ISSUE TITLE
Sinitize in fields

### ISSUE THREAD

**Issue by LeninZapata** [Codestar/codestar-framework#19]
Hello, the plugin does not use functions of 'sanitize' of wordpress, this gives just so they can hack.

![image](https://user-images.githubusercontent.com/42600954/55970895-10c01280-5c46-11e9-823a-f9a48aeb0926.png)

![image](https://user-images.githubusercontent.com/42600954/55971225-a6f43880-5c46-11e9-8bf8-eecf332fb805.png)

**Comment by Codestar** [comment]
There is no default value. Because the developers using this fields multi-purpose. You should to use sanitize methods in output ( for eg: wp_kses, esc_attr, esc_html, etc )

**Comment by mainpart** [comment]
as far as i can see 'sanitize' property is used when you saving data to database. What option i need to use when outputting value in textarea editor. Any textarea tag inside my text breaking html output. 

I want to store data in database unescaped but i want to output it sanitized
