### ISSUE TITLE
Switcher Field with Default

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#19]
If i change the default value of Switcher Field ON to OFF then hit save then it's not saving ,it's remain with default value !!

**Comment by Codestar** [comment]
Ops yes you are right. i fixed it now. update this two files * SHA: 4151eb44883368809645fe72c49f9397c81d12e2

**Comment by devariya** [comment]
Thanks man but there is another problem ,if i set the default value true and after saving the switcher off value then if i hit reset button then it not display the default value true .

**Comment by devariya** [comment]
Default options restored for switcher filed not working

**Comment by Codestar** [comment]
Uh, i had tested only for false :) i forget to test for default true. hmm no worries tomorrow i will fix it ;)

**Comment by devariya** [comment]
Thank man , you are awesome :)

**Comment by Codestar** [comment]
Hi,

I made an update for this issue, can you check it ? changed: 274c9bb6702de307a5cd22afe19f7ebdba62c216

**Comment by devariya** [comment]
Perfect and it's working ! Thanks man :D

**Comment by Codestar** [comment]
You're welcome :D
