### ISSUE TITLE
Date and Time option needed

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#190]
Codestar framework is extremely cool. But It hasn't date and time option.
Do you have a plan to add Date and Time option?

**Comment by Codestar** [comment]
Thanks for your opinion, yes this field coming in v1.1

**Comment by Codevz** [comment]
Hi Codestar, 

Thanks for your attention at requests, i also need date time picker field. Can't wait for new update :+1: 

Cheers

**Comment by Codestar** [comment]
Yes, i will do it asap :+1:
