### ISSUE TITLE
How to change "Add Shortcode" label ?

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#191]
How can I change `Add Shortcode` label?
![screenshot_2015_12_19_at_19_22_43](https://cloud.githubusercontent.com/assets/7611746/11913204/a483bcc0-a686-11e5-9032-0ebcb0002c37.png)

![](https://cloud.githubusercontent.com/assets/7611746/11913196/40c16fe8-a686-11e5-8567-6e93fd31fbc2.png)

**Comment by Codestar** [comment]
You can change it from here [shortcode.class.php#L90](https://github.com/Codestar/codestar-framework/blob/master/classes/shortcode.class.php#L90)

**Comment by kingRayhan** [comment]
Thanks :smile:

**Comment by Codestar** [comment]
You're welcome :smile:

**Comment by kingRayhan** [comment]
Sorry for disturbing you again.
How to change this label?
![](https://cloud.githubusercontent.com/assets/7611746/11913204/a483bcc0-a686-11e5-9032-0ebcb0002c37.png)

**Comment by Codestar** [comment]
Take a look this lines for shortcode dialog static text translate:

[shortcode.class.php#L82](https://github.com/Codestar/codestar-framework/blob/master/classes/shortcode.class.php#L82)
[shortcode.class.php#L90](https://github.com/Codestar/codestar-framework/blob/master/classes/shortcode.class.php#L90)
[shortcode.class.php#L108](https://github.com/Codestar/codestar-framework/blob/master/classes/shortcode.class.php#L108)

Btw, i will try to a setting option for quicky change it :wink: 

You're welcome :+1:
