### ISSUE TITLE
Is there any way to make editable shortcode?

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#192]
I'm making a shortcode plugin which contain huge shortcode attributes. If there is any method to create editable shortcode then my plugin will be more comfortable for user.

Can you suggest me a way?

**Comment by Codestar** [comment]
Take a look, it will come soon https://github.com/Codestar/codestar-framework/issues/50

**Comment by kingRayhan** [comment]
wo Really :heart_eyes:
I'm waiting for the feature

**Comment by Codestar** [comment]
Yes, everybody want it and i will add surely :wink:
