### ISSUE TITLE
wysiwyg editor not saving data when Ajax save is enabled

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#193]
Hello,

The wysiwyg type box's data is not saved if ajax_save is enabled. I enabled ajax_save from framework.config.php file:
```php
$settings      = array(
  'menu_title' => 'Framework',
  'menu_type'  => 'add_menu_page',
  'menu_slug'  => 'cs-framework',
  'ajax_save'  => true,
);
```
Here is my element code:
```php
array(
	'id'       => 'wysiwyg_1',
	'type'     => 'wysiwyg',
	'title'    => 'Wysiwyg',
),
```

Can you please look at it and let me know if I am doing anything wrong. I tested it with default WordPress theme and using Codestar as plugin.

**Comment by Codestar** [comment]
Hi,

Oh yes, it is not working in ajax save option. hmm there is a trigger option for this. can you try it. go to here [cs-framework.js#L623(]https://github.com/Codestar/codestar-framework/blob/master/assets/js/cs-framework.js#L623) and put this code

```js
if( typeof tinyMCE === 'object' ) {
  tinyMCE.triggerSave();
}
```

and tell me result? if it works, i'll add it :smile:

**Comment by kwayyinfotech** [comment]
Yes this works perfectly. Please add this in core :)

**Comment by Codestar** [comment]
Nice, you will not see this issue again :+1:
