### ISSUE TITLE
Fatal error: Class 'CSFramework_Customize' not found?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#194]
Hi,

I create new file with same code of customize.config.php file. But i receive an error in that file : 
Fatal error: Class 'CSFramework_Customize' not found in /theme-customizer.php on line 463

That line code is : CSFramework_Customize::instance( $options );

How to fix this?

**Comment by Ansif** [comment]
Here is that code : 
<script src="https://gist.github.com/Ansif/b70c096a8b9fa70bddc6.js"></script>

**Comment by Codestar** [comment]
Hi,

Hmm, because theme files loading in action level 1, hmm you can try this. 

```php
if( ! function_exists( 'cs_customize_framework_init' ) ) {
  function cs_customize_framework_init() {
    
    // $options
    CSFramework_Customize::instance( $options );
    
  }
  add_action( 'init', 'cs_customize_framework_init', 10 ); // 10 or 11 try it.
}
```

**Comment by Ansif** [comment]
Hi Mate,

Thanks a lot! :+1: 

I followed second option, because i'm using same option for theme options too.

**Comment by Codestar** [comment]
You're welcome :+1:
