### ISSUE TITLE
I want to add fields in WordPress default customizer sections?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#195]
Hi,

I want to add color picker field in : <strong>title_tagline</strong> section in WordPress customizer - Which is default WordPress section called : Site Identity.

Please let me know the solution?

**Comment by Codestar** [comment]
Hi,

Hmm, it is not posibble, you need to remove title_tagline section and create your own. I have not any idea about this :smiley:

**Comment by Ansif** [comment]
Ok, No Problem. :)

**Comment by Codestar** [comment]
Yes why not :+1:
