### ISSUE TITLE
Please add class attribute for all fields?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#196]
Hi,

Can you please add support for class attribute to all fields : 

```php
array(
  'type'    => 'heading',
  'class'   => 'custom-class',
  'content' => __('Color Options', 'vt_admin_text'),
),
```

This is not supporting now!

**Comment by Codestar** [comment]
Hi,

Actually, 90% fields support for class attribute but some fields do not have any form field. BUT you can use this already. ```wrap_class``` similar with ```class``` :smile: 

```php
array(
  'type'    => 'heading',
  'wrap_class'   => 'custom-class',
  'content' => __('Color Options', 'vt_admin_text'),
),
```

**Comment by Ansif** [comment]
Awesome! :+1: 

I don't know how i missed <code>wrap_class</code>. Thanks! :smile:

**Comment by Codestar** [comment]
You're welcome :smile:
