### ISSUE TITLE
Group option type is not working in shortcode generator

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#197]
![tab](https://cloud.githubusercontent.com/assets/7611746/11972917/329cf23a-a97d-11e5-8841-ab04a307d21a.png)

Group option type is not working in shortcode generator :grimacing:
Is there any way to make work group option type in shortcode generator?

**Comment by Ansif** [comment]
Hi,

Check example code, shortcode.config.php : 
<a href="https://github.com/Codestar/codestar-framework/blob/master/config/shortcode.config.php#L393">shortcode.config.php#L393</a>

And make sure you've called correctly. Each field options needs unique id. If ids are same that'll not work!

**Comment by kingRayhan** [comment]
@Ansif I checked carefully ,
It's work well in framework.config.php file but not working in shortcode generator :cry:

**Comment by Codestar** [comment]
Shortcode manager do not support group option field. but you do not need it, we are using ```clone``` system for tab-toggle-accordion things. check this [shortcode.config.php#L390-L463](https://github.com/Codestar/codestar-framework/blob/master/config/shortcode.config.php#L390-L463)

**Comment by kingRayhan** [comment]
I tried `clone` system. It's cool but I need drag-able section

**Comment by Codestar** [comment]
Yes, it is not drag-able. maybe next updates i can add this feature ;)

**Comment by kingRayhan** [comment]
Time and Date picker are also extremely needed.

**Comment by kingRayhan** [comment]
When will you release version 1.1 ?

**Comment by Codestar** [comment]
Yes yes, i will add. but you know time is issue :smile: i am working on a new theme and i have not free-time, yet. it will came ASAP :wink:

**Comment by Ansif** [comment]
Hi @Codestar,

Just curious, when you release your next theme? And is it multi purpose?

**Comment by Codestar** [comment]
Hi,

I am planing to end of 2016 and yes it is multi-purpose. because it is most wanted :smile:

**Comment by Ansif** [comment]
Oh Awesome! End of 2016. I'm sure you'll get great success! :trophy:

**Comment by Codestar** [comment]
Yeah, let's hope so. thanks for wishes :+1:

**Comment by kingRayhan** [comment]
@Ansif I think you are from Bangladesh. Right?

**Comment by Ansif** [comment]
@kingRayhan No, i'm from india. :smile:

**Comment by kingRayhan** [comment]
@Ansif 
If you don't mind , can you come in my facebook?
https://www.facebook.com/rayhan095
