### ISSUE TITLE
how to retrieve value?

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#198]
How can I retrieve value from metabox and theme option?
Actually I'm newbie developer, would you please give me a code snippet ?

**Comment by Ansif** [comment]
Hi @kingRayhan,

For theme options, use following code : 
<pre>echo cs_get_option( 'your_field_id' );</pre>

For metabox, use following code : 
<pre>echo get_post_meta( $post->ID, 'your_field_id', true );</pre>

All detailed explanations are in : <br />
http://codestarframework.com/documentation

**Comment by kingRayhan** [comment]
@Ansif 

Thanks brother :smile:

**Comment by Ansif** [comment]
You're Welcome! :) :+1:

**Comment by Codestar** [comment]
:+1:
