### ISSUE TITLE
How to get section tab link using id?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#199]
Hi,

After activating my theme, i'll redirect to framework page particular section. The link should like this :  <br /> admin.php?page=cs-framework#cs-tab-sanitize_section

Currently it's not working. :(

Please let me know how to do it?

**Comment by Codestar** [comment]
Hi,

Hmm, you can try this:

```
admin.php?page=cs-framework&cs-section=cs-tab-sanitize_section
```

**Comment by Ansif** [comment]
Hi,

It's not working. :(

It's redirect to framework page. But not show inside that tab options. Just a blank tab shows without our preferred tab selection!

**Comment by Codestar** [comment]
Hi,

It is working normally with demo config ? for eg i am going to this :+1: 
```
admin.php?page=cs-framework&cs-section=text_options
```

and opening directly  ```Options -> Text``` maybe you are writing wrong section id ? try this ```sanitize_section``` or another ?

**Comment by Ansif** [comment]
Cool! :+1: 

It's working fine! Thanks a lot! :)

**Comment by Codestar** [comment]
Cheers :+1:
