### ISSUE TITLE
Icon Field Not Working (Type Error)

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#2]
Icon Field Not Working For Type Error 
http://prntscr.com/5o1qmb

**Comment by Codestar** [comment]
Hi,

Oh yes, i saw it. thanks for report.. and i made an update for this issue. can you re-download and check it ? it is ok now?

**Comment by devariya** [comment]
:D it's working ,Thanks for the fix and i will also check other fields if i found any error i will let you know .Great work :)

**Comment by Codestar** [comment]
Hi,

Nice. Yes of course, report me if you found anything ;)

Have a nice day.
Thanks.
