### ISSUE TITLE
Image Select not working with dependency?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#20]
Here you can see, that issue : 
http://www.dropshots.com/ansif/date/2015-02-11/02:23:55

Also, how i get sidebars like pages, post list in your wp_query?

Thanks,
Ansif

**Comment by Ansif** [comment]
Also, two more dependency is not working in same field?

<pre>
'dependency' => array( 'title_bg_type', '==', 'type_image' && 'select_header_type', '==', 'header_slider')
</pre>

How to do two more dependency for a same field?

Thanks!

**Comment by Ansif** [comment]
#16 I get same error here using following code : 

<pre>
if (!empty($header_type['select_header_type'] === 'header_title')) {
</pre>

This is select field :
$header_type['select_header_type']

How i set if that value is selected?

Thanks,
Ansif

**Comment by Ansif** [comment]
I've tried this way :
<pre>
if (isset($header_type['select_header_type']) && $header_type['select_header_type'] == 'header_title') {
</pre>

It's working fine! Is there no problem to use isset?

Thanks!

**Comment by Codestar** [comment]
Hi,

1. Multiple dependency not supporting yet, maybe in the future i can add it ;)
2. About Image select dependency, try this:

```
'dependency' => array( 'select_page_layout', '==', 'select_page_layout_left_sidebar'),
```

because, you know select page have a multiple names. you need to add <code>select_page_layout_(VALUE_NAME)<code>

3. Oh no you can not use this, this is not coming framework, this is php issue. can not be write == inside empty() function.

```
if (!empty($header_type['select_header_type'] === 'header_title')) {}
```

correct way:

```
if ( ! empty( $header_type['select_header_type'] ) && $header_type['select_header_type'] == 'header_title' ) ) {}
```

**Comment by Ansif** [comment]
:+1: 

Thanks for your quick response!

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by Ansif** [comment]
Hi again,

I've asked in this first thread about : 
"Also, how i get sidebars like pages, post list in your wp_query?"

I want what you've done in custom sidebar selection :
https://www.youtube.com/watch?v=kfikJ7PmFv8

Thanks,
Ansif

**Comment by Codestar** [comment]
Hi,

I am using this method for get sidebars. create a custom function for getting all sidebars

```
function cs_get_custom_sidebars() {

  global $wp_registered_sidebars;

  $sidebars = array();

  if( ! empty( $wp_registered_sidebars ) ) {
    foreach ($wp_registered_sidebars as $key => $value) {
      $sidebars[$key] = $value['name'];
    }
  }

  return array_reverse( $sidebars );

}
```

and config array:

```
array(
  'id'             => 'sidebar_field_id',
  'type'           => 'select',
  'options'        => cs_get_custom_sidebars(),
  'default_option' => 'Choose a custom sidebar',
)
```

You need this?

**Comment by Ansif** [comment]
Yes. I need it!

**Comment by Codestar** [comment]
Nice :+1:

**Comment by Codestar** [comment]
```
// Image Select Dependency
// ------------------------------------
array(
  'id'           => 'dep_6',
  'type'         => 'image_select',
  'title'        => 'If check <u>Blue box</u>',
  'options'      => array(
    'green'      => 'green.png',
    'red'        => 'red.png',
    'yellow'     => 'yellow.png',
    'blue'       => 'blue.png',
    'gray'       => 'gray.png',
  ),
),

array(
  'id'           => 'dummy_6',
  'type'         => 'notice',
  'class'        => 'info',
  'content'      => 'Blue box selected!',
  'dependency'   => array( 'dep_6_blue', '==', 'true' ),
  //'dependency' => array( '{ID}_{VALUE}', '==', 'true' ),
),
// ------------------------------------
```
