### ISSUE TITLE
Shortcode it is added globally 

### ISSUE THREAD

**Issue by LeninZapata** [Codestar/codestar-framework#20]
Buy the Pro version, I'm doing a plugin with the framework, I have CSF activated in conjunction with my new plugin, but I see that the CSF Shortcode example is mixing with the editor inside my plugin, why does this happen? I do not want that button to be shown in the plugin editor of my instance.
![image](https://user-images.githubusercontent.com/42600954/56173270-94656080-5fb2-11e9-8ce4-11e9159a0bfd.png)

**Comment by Codestar** [comment]
Yes, default `CSF Shortcode` config adding this for all editors. But it is optional. Actually I didn't get the issue exactly. Another framework instance can add a shortcode framework, it is normal.

If still you don't want to show this button. Try to hide it hardly. for eg.

```php
array(
  'id'    => 'opt-wp-editor-1',
  'type'  => 'wp_editor',
  'title' => 'WP Editor',
  'class' => 'hide-shortcode-button',
),
```

```css
.hide-shortcode-button .csf-shortcode-button{ display: none; }
```

Have a nice day.
