### ISSUE TITLE
How to call public functions within our section?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#200]
Hi,

I've lots of functions and contents that need to show like public function. How can i show that within our section tab?

Public Function from another file : 
```php
// Public Function in Different File
public function demo_page() {
	$output  = '<h2>Main Heading</h2>';
	$output .= '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi illum eum voluptatum quo deserunt architecto fugiat sit, assumenda sed dolores!</p>;';
	return $output;
}
```

Our config file : 
````php
// Want to call public function within our tab
$options[]   = array(
	'name'     => 'demo_page_section',
	'title'    => 'Demo Page',
	'icon'     => 'fa fa-heart',
	'fields'   => array(

	  array(
	    'type'    => 'content',
	    'content' => demo_page(),
	  ),

	)
);
```

As you may know already, it gives me an error! :worried:

**Comment by Codestar** [comment]
Actually, your method is right, you can call custom function with your method. ? is it not works?

**Comment by Ansif** [comment]
No, it gives me an Parse error.

Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /Users/../inc/init.php on line 27

Same code above mentioned!

**Comment by Codestar** [comment]
But this is a public function. you need to call it like this:

```php
$myClass = new ClassName();
...
....
$options[]   = array(
    'name'     => 'demo_page_section',
    'title'    => 'Demo Page',
    'icon'     => 'fa fa-heart',
    'fields'   => array(

      array(
        'type'    => 'content',
        'content' => $myClass->demo_page(); // or ClassName::demo_page();
      ),

    )
);
```

But may not be sufficient this code, search about "php class call public/static methods"

**Comment by Ansif** [comment]
Still same error. Ok, i'll try to search in google.

If you get that way, please share. :blush:

**Comment by Codestar** [comment]
Yeah do it :smile:

**Comment by Ansif** [comment]
Thanks. :+1:
