### ISSUE TITLE
Two question about group option

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#201]
Hi, 

1. Is there anyway to add group option inside another group option ?! 

2. Is there anyway to add "Duplicate" button for each group items ?!

Thank you.

**Comment by Codestar** [comment]
Hi,

1. Hmm no it is not possible, because there is some conflict with inside another group option. maybe i can improve it future :wink: 

2. Hmm, also this is not possible yet, when i need it, i will add this option :smile:
