### ISSUE TITLE
Select placeholder not working for class chosen

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#202]
Hello, 

in this code: 

<pre>
              array(
                'id'      => 'artist',
                'type'    => 'select',
                'title'   => __('Artist(s)', 'cdz'),
                'options' => 'posts',
                'class'   => 'chosen',
                'query_args'  => array(
                  'post_type' => 'artists',
                  'orderby'   => 'title',
                  'order'     => 'ASC',
                  'posts_per_page' => -1,
                ),
                'attributes' => array(
                  'placeholder' => 'Select Artist', // <---- not working this value
                  'multiple' => 'multiple',
                  'style'    => 'width: 200px;'
                )
              ),
</pre>

placeholder not working with metabox

i added "Select Artist" but it displays "Select Some Option"

Cheers

**Comment by Codevz** [comment]
Its my mistake sorry, changed to data-placeholder and working :)

**Comment by Codestar** [comment]
Great :+1: :smile:
