### ISSUE TITLE
How to save option to "theme_mod"

### ISSUE THREAD

**Issue by colourstheme** [Codestar/codestar-framework#203]
Hi,

1. Could you save data of theme option by set_theme_mod($key, $value) ?

2. Or create an action hook, ex: 
do_action( 'cs_before_save_option', $option_name, $value );

Thanks!

**Comment by Codestar** [comment]
Hi,

1. I am using wordpress core [Settings API](https://codex.wordpress.org/Settings_API) for framework save options. and there is not option for ```set_theme_mod``` if you want set_theme_mod let's go your 2. question.

2. You can use this action for custom ```set_theme_mod``` saving. required a little php coding for this :wink: 

You're welcome..
