### ISSUE TITLE
codestar conflict

### ISSUE THREAD

**Issue by fiqhid** [Codestar/codestar-framework#204]
hello ... I create a theme using CS framework in my local server, I m using xampp and one plugin that also uses cs framework, but when the plugin active theme options panel and metabox is not showing, I think there has been a conflict between the themes and plugins using  cs framework at the same time. is there a way to overcome them. sorry I was a beginner.

**Comment by Codestar** [comment]
Hello,

Yes it is right, you can not use framework multiple. but i will improve it asap.

**Comment by Codevz** [comment]
Hi, 

Actually i think if you add your options via custom function like following code, it should be work when also plugin does cs-framwork.

<pre>
function prefix_options( $options ) {

	$options[]   = array(
	  'name'     => 'post_type_settings_section',
	  'title'    => __('Post Types Settings', 'cdz'),
	  'icon'     => 'fa fa-wrench',
	  'fields'   => array()
	);

	return $options;
}
add_filter( 'cs_framework_options', 'prefix_options', 11 );
</pre>

Ofcourse in this case your config file or plugin config file should be does this code:

<pre>
CSFramework::instance( $settings, $options );
</pre>

Cheers

**Comment by Codestar** [comment]
Yes, Sure, I am thinking same, but this method is correct for your OWN theme and OWN Plugin. both. for eg. it is dangereus for different author's plugin and different author's theme. For eg. you do not need include framework files on plugin. becuse all files located in theme.. but said as me this is correct for both theme/plugin ideas.
