### ISSUE TITLE
I need some advice for creating custom menu fields using codestar fields?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#205]
Hi Mate,

Sorry, for asking this questions. If it's a simple method to integrate code star fields to WordPress menu custom fields. Please advice me to work that.

Thanks a lot for this framework! :+1:

**Comment by Codestar** [comment]
Hi,

Yes you asked it already here :smile: How to add icon label option to wp nav menu ? #175

**Comment by Ansif** [comment]
Hi Bro,

I finally added your framework fields in WordPress menu API, with some of my custom style :sparkles:
![mega-menu](https://cloud.githubusercontent.com/assets/5621180/12030878/347b6fc0-ae2b-11e5-93dd-9b45ee3163ef.jpg)

Core API referrance from, this old plugin : https://wordpress.org/plugins/sweet-custom-menu/

1. First i take a copy of WordPress core file : wp-admin/includes/class-walker-nav-menu-edit.php
2. Then, i copied html code of your fields from framework theme options. Inspect element that field and Copy outer HTML in browser. :wink:
3. Added that code using custom action in different file. That custom action code added in : class-walker-nav-menu-edit.php Under navigation label field, as shown in above screenshot.

Still i would like to add icon field. But no luck, it's not saving properly & field popup is fine but input texts are showing. I just searching solution. If it's easy let me know. Otherwise leave it, i'll take care.

I also, would like to add dependency option. I think here we've only the way to do in custom jQuery codes. I already did some code for post format select option. If you choose image post format, then your metabox fields automatically load that related options only.

Like Following : 
<pre>
function toggle_metaboxes() {

  var format = $("input[name='post_format']:checked").val();
  $('.element-standard-image').hide();

  if (format == 'image') {
    $('').slideUp('fast');
    $('.element-standard-image').slideDown('slow');
  }
}

toggle_metaboxes(); // Execute on document ready
$('#post-formats-select input[type="radio"]').click(toggle_metaboxes);
</pre>

If you've better method in your mind, please let me know. :blush:

Thanks for your awesome support! :+1:

**Comment by Ansif** [comment]
Leave it!

I done with some minimal option and used some css. :+1:

**Comment by Codestar** [comment]
Oh nice great :+1:
