### ISSUE TITLE
meta_query not working with array comes from codestar meta_box

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#207]
Hi, 

I have some meta_box for Events post_type and output is: ( key is prefix_events_meta )

```php
array(
    'event_date' => '2017/01/18 21:00',
    'event_venue' => 'STc Paris',
    'country' => 'france'
)
```

and i want to order events by meta_query with events date time, so my code is: 

```php
$query = new WP_Query( array(
    'post_type'     => 'events',
    'order'            => 'DSC',
    'meta_key'     => 'prefix_events_meta',
    'meta_query' => array(
	array(
		'key' => 'prefix_events_meta',
		'value' => date('Y/m/d H:i'),
		'compare' => '>='
	)
    ),
    'orderby'        => 'meta_value_num'
) );
```

query not working because meta_key and also meta_query can't get value array of meta_box. It just can get string. 

I think its an problem in codestar meta_box feature and should be solve asap.

Also i asked my question here: http://wordpress.stackexchange.com/questions/213215/get-posts-by-meta-key-from-inside-key-of-post-meta 

Regards

**Comment by Codevz** [comment]
I think each meta_box should be save separately.

**Comment by Codestar** [comment]
Hi,

Actually problem is serialize save data. All frameworks using this serialize method. We can not save all metabox files as saved separately.

Now using this method:

```php
<input type="text" name="prefix_events_meta[event_date]">
<input type="text" name="prefix_events_meta[event_venue]">
```
separately method is ( we do not using this )
```php
<input type="text" name="prefix_events_meta_event_date">
<input type="text" name="prefix_events_meta_event_venue">
```

And here is problem, ```WP_Query - > meta_query -> value``` in this value forcing serialize data. can returning null. i mean. value is supporting static string. for eg here is saying it is not possible http://wordpress.stackexchange.com/questions/16709/meta-query-with-meta-values-as-serialize-arrays there is a idea, but i do not advise :)

Let's think a better idea. I think you can find a solution with TWO QUERY ?

**Comment by Codestar** [comment]
Hi,

For eg:

```php
$current = date('Y/m/d H:i');

$pages = get_posts( array(
  'post_type' => 'events',
  'posts_per_page' => -1,
  'sort_order' => 'desc'
));

foreach ( $pages as $page ) {

  $meta = get_post_meta( $page->ID, 'prefix_events_meta', true );

  // ENDING EVENT
  if ( ! empty( $meta['event_date'] ) && $meta['event_date'] <= $current ) {
    var_dump( $meta );
  }

  // ONCOMING EVENT
  if ( ! empty( $meta['event_date'] ) && $meta['event_date'] >= $current ) {
    var_dump( $meta );
  }

}
```

**Comment by Codevz** [comment]
Hey man, 

Thanks for your attention, I thought about it with using foreach but what happening when site does more than 5000 posts.

It's possible but the overhead wouldn't be worth it. You're talking about 1 possibly huge database query to get all posts, 1 loop through the possibly huge amount of posts to make another database query to get the post_meta array and put it into a separate possibly huge related array, then another loop to actually sort that possibly huge amount of data on one specific key. 

What about adding filter just for events with "<b>cs_save_post</b>" for duplicate one or some metaboxes to new rows, somethings like this:

<pre>
function save_new_metabox( $post_id, $post, $update ) {

    if ( 'events' == $post->post_type ) {
          $get_event_date = $_POST['page_meta[event_date]'];
          add_post_meta( $post_id, 'event_date', $get_event_date );
    }

}
add_filter( 'cs_save_post', 'save_new_metabox', 11 );
</pre>


PS: ofcourse i'm not really sure if its good or bad for using foreach for getting all posts then sorting them by date. Please let me know which way is better.

Thanks.

**Comment by Codevz** [comment]
Another way for getting posts with meta_key is using <b>wpdb</b> but unfortunately i'm not really familiar with it, i think we need somethings like this: 

<pre>
global $wpdb; 

$search = serialize('event_date').serialize(50);

$query = $wpdb->prepare("SELECT `post_id`
FROM `wp_postmeta`
WHERE `post_id` IN (SELECT `ID` FROM `wp_posts` WHERE `post_type` = 'events')
AND `meta_key` = 'page_meta'
AND `meta_value` LIKE '%s'",'%'.$search.'%');

$ids = $wpdb->get_col($query);

$args = array(
    'post__in' => $ids,
    'post_type' => 'events' //add the type because the default will be 'post'
);

$posts = get_posts($args);
</pre>

**Comment by Codestar** [comment]
Yeah, nice ways, if you make a performance test, share with us :+1:

**Comment by Codevz** [comment]
Finally i decided to update new post meta after saving each post, with following functions: 

<pre>
function prefix_update_meta_box( $post_id, $post ) {

	if (isset($post->post_status) && 'auto-draft' == $post->post_status) {
		return;
	}
	
	if ( 'events' == $post->post_type ) {
		$meta = get_post_meta( $post_id, 'prefix_page_meta', true );
		update_post_meta( $post_id, 'prefix_event_date', $meta['date'] );
	}

}
add_action( 'save_post', 'prefix_update_meta_box', 11, 3 );
</pre>

Regards

**Comment by Codestar** [comment]
Nice bro, also i noted this idea. i will need this in my projects :wink: Great. :+1:

**Comment by sinsky** [comment]
That how to modify it?
Modify the time you can not see the value?

**Comment by baturkacamak** [comment]
Any news about this feature?

Sorting the meta data from codestar is impossible right now

**Comment by Codevz** [comment]
@baturkacamak Only way is using of `save_post` action, then in your query for sorting posts by date / time, you should use your new meta key. 

Please see my previous comment, After checking post type you can update new meta key with your date / time field. example

`update_post_meta( $post_id, 'new_single_event_date_meta_key', $meta['date'] );`

And inside query example

```PHP
$args = array(
	'post_type'		=> 'events',
	'order'			=> 'ASC',
	'orderby'		=> 'meta_value',
	'meta_key'		=> 'new_single_event_date_meta_key',
	'meta_query' 	=> array(
		'key'			=> 'new_single_event_date_meta_key',
		'value' 		=> current_time('Y/m/d H:i'),
		'type' 			=> 'DATETIME',
		'compare' 		=> '>='
	)
);
```
