### ISSUE TITLE
How to echo custom styles in css format?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#209]
Hi Mate,

I'm usually do dynamic-style.php file for making dynamic css codes from theme options, shortcode, customizer and all others.

But, you may already know it'll slow down our site speed. I would highly target to have custom style format in our header or footer echo like within : style tag.

Also, searching for hover option within our shortcode it self? I done that by adding fields. But, little confusion about how to echo hover within our style="" itself.

If you've better method, please let me know. It would really helpful for me.

Thanks! :+1:

**Comment by OmarAtta** [comment]
Hi @Ansif ,
### Create a jQuery Plugin
To make hover effect you can create a simple jQuery plugin to change color on mouse over
```javascript
$.fn.hoverEffect = function() {
	return this.each( function() {
		var hover_color = $(this).attr("data-hover-color");
		$(this).hover(
			function() {
				$(this).css("color", hover_color);
			}, function() {
				$(this).css("color", '');
			}
		);
	});
}
```

In html file
```html
<!-- You can use hex, rgb or rgba colors -->
<p class="hover-color" data-hover-color="blue">Hello World!</p>
<p class="hover-color" data-hover-color="rgba(0,0,0,0.5)">Hello World!</p>
<p class="hover-color" data-hover-color="#e74c3c">Hello World!</p>
```

```javascript
$('.hover-color').hoverEffect();
```

Live preview : https://jsfiddle.net/suarweb/nz40kLf5/

### Using Wordpress wp_add_inline_style() function
https://codex.wordpress.org/Function_Reference/wp_add_inline_style

**Comment by Ansif** [comment]
Hi @OmarAtta,

Thanks for your suggestion.

It's good method. But i try to achieve that within php. Mostly, WordPress related things are done with PHP that's why.

If we get small error in jQuery then this will not work. Also, php have more control do to within that. Like if conditions.

Thanks! :+1:

**Comment by Codestar** [comment]
@Ansif yeah, if you get any idea about this subject, share with us :+1:
