### ISSUE TITLE
This field class is not available!

### ISSUE THREAD

**Issue by RomanMUG** [Codestar/codestar-framework#21]
Hi :)

I get this error-message on every field in the Framework tab...so I cant use the Framework...what did I wrong?
I use WP 4.1, and installed the Framework into a fresh Blank-Theme (JointsWP) for testing.
Framework folder is "options" and I added this lines to the theme-functions file:

// Load Theme Options
require_once dirname( __FILE__ ) .'/options/cs-framework.php';

define( 'CS_ACTIVE_FRAMEWORK',  true  ); // default true
define( 'CS_ACTIVE_METABOX',    false ); // default true
define( 'CS_ACTIVE_SHORTCODE',  false ); // default true
define( 'CS_ACTIVE_CUSTOMIZE',  false ); // default true

Sorry about my bad english and thanks for your help!

**Comment by Codestar** [comment]
Hi,

I tested it now, with JointsWP it is working correctly? If still you have same issue i can send my tested zip file ;)

**Comment by RomanMUG** [comment]
Hiho...not working :(

I made a complete reset and installed erverything new...
![cmframework](https://cloud.githubusercontent.com/assets/10967925/6314685/2e3bd53c-b9e9-11e4-99b3-192211390ea0.jpg)

**Comment by Codestar** [comment]
It is interesting, hmm share with me your JointsWP with Codestar Framework files, upload anywhere and give me a link for download. i can test it for you ;) because i tested it when you open this issue. it is working correctly.

**Comment by Codestar** [comment]
Also, i created a tutorial for you. take a look  https://www.screenr.com/t0EN i can not see any problem :)

**Comment by RomanMUG** [comment]
Crazy...I did exactly what you did in the video...nothing more nothing less...crazy.

You installed it local, right? I tested it live...
I checked my webspace settings:
PHP 5.6
mySQL 5.5.41

I have no clue what's wrong...I will look tomorrow again...maybe with an other Blank Theme.

Thank you for your help!

**Comment by Codestar** [comment]
Yes, it is simple. i am seeing thia issue fisrt time. try to it on another server or platform :+1:

**Comment by devariya** [comment]
Some of clients also mention about this problem also they also report me about icon not showing and Error ! can not load json file

**Comment by Codestar** [comment]
Yes, i know this issue but we have two option for load json file. 1th ```wp_remote_get``` and 2th ```file_get_contents``` firstly i started ```wp_remote_get``` for load json file. but i saw some issue for this method. and currently i am using ```file_get_contents```

Now, can you check this line <a href="https://github.com/Codestar/codestar-framework/blob/master/functions/actions.php#L18">actions.php#L18</a> it is same with your file ? if not, update it. my old method was this <a href="https://github.com/Codestar/codestar-framework/blob/86e0e14d3b278bf04d44a9c7c925f3584c0d62e4/functions/actions.php#L18">actions.php#L18</a> and please report me the result.

**Comment by devariya** [comment]
json problem is solved but what about This field class is not available! !! any idea ,
i didn't find anything from my local server and online server but my client server still has it .is it a problem for php version !!

**Comment by Codestar** [comment]
```This field class is not available!``` hmm hmm, where issue, hmm. i think problem can be <a href="https://github.com/Codestar/codestar-framework/blob/e531784fed307107759c09d0b7d570c86330d8f1/functions/helpers.php#L179">helpers.php#L179</a> ```glob``` function. but json load already using ```glob``` how did you solve it ? btw, can you send me your client wp-admin informations via routewp@gmail.com ? i can check it quickly for you.

**Comment by Codestar** [comment]
Nice, I got your mail, i will check it morning ;)

**Comment by devariya** [comment]
Thank you :)

**Comment by Codestar** [comment]
Oh, i found my issue, i changed my glob function from 
```
foreach ( glob( CS_DIR .'/fields/*/*.{php}', GLOB_BRACE ) as $cs_field ) {}
```
to
```
foreach ( glob( CS_DIR .'/fields/*/*.php' ) as $cs_field ) {}
```

Ok, i will not use ```GLOB_BRACE``` also i will update github codes now ;) thanks for share admin and report.

**Comment by devariya** [comment]
Your are welcome ,Can you make a update log and also Thumbs up for great fast response :+1:

**Comment by Codestar** [comment]
Yes, I will start to update/change log after version 1.1.0 now can say beta-test for framework. Next month i am planing to update version 1.1.0 and after next version, i will write all changes on change log :+1:

**Comment by ibnay1930** [comment]
Hi Codestar,

I am got issue "This field class is not available!" too. I am try to make new option field that there are not  available yet in default option type.
Let say it, 'new_option' type.
I create folder (e.g. new_option) in override dir. and also put new_option.php inside the folder.
When i execute in framework.config, the issue appear.
I am trying to add whole of new_option folder in fields folder on cs_framework plugin. and it work.

I think you have set your plugin to give an easy access to add new field option without touching the plugin.
And i am take a look for your helper function. I think the problem is in "cs_load_option_fields" function.
Take a look for this line.....

```
cs_locate_template( str_replace(  CS_DIR .'-override', '', $override_field ) );
```
i change it into 
```
cs_locate_template( str_replace(  $override_dir, '/fields', $override_field ) );
```
and it's work. I have no to add new field folder inside the plugin. 

Thanks

**Comment by Codestar** [comment]
Hi,

Wow, thanks for contribute. you are right totally. and i updated it right now https://github.com/Codestar/codestar-framework/commit/116f6e18d261e081367a5deee0802dcb727e0c4b and i tested it and working correctly. :100: :+1: 

Regards, Codestar

**Comment by mayeenulislam** [comment]
Pardon me. I'm using Codestar Framework the latest master version
But having the same issue.
Backup field is showing the message

>This field class is not available!

I'm using the `cs_framework_options` filter method. Is there any predefined settings, that is required for having the `backup` field to work?

If I disable my filter the default backup field is not visible also.

**Comment by Codestar** [comment]
Hi,

Hmm, it is working normally in my settings. also i tried it on ```cs_framework_options``` filter. no any issue. hmm write your config array for only backup and filter method here. let me check it. maybe there is a clerical error.

**Comment by mayeenulislam** [comment]
Thank you for your response, and congratulation on the awesome work you've made. Codestar is **the** lightweight framework I've seen so far. :+1: 

Here is my code (I made it to minimal for testing now):

```php
<?php
function imc_theme_options_settings( $settings ) {

    $settings      = array(
        'menu_title' => __( 'Theme Options', 'text-domain' ),
        'menu_type'  => 'add_theme_page',
        'menu_slug'  => 'imc-options',
        'ajax_save'  => false,
    );

    return $settings;
}
add_filter( 'cs_framework_settings', 'imc_theme_options_settings' );


function imc_theme_options( $options ) {
    $options      = array(); // remove old options

    $options[]    = array(
        'name'      => 'other_settings',
        'title'     => __( 'Other Settings', 'text-domain' ),
        'icon'      => 'fa fa-gear',
        'fields'    => array(
                            array(
								'type'  => 'backup',
								'title' => 'Backup Field',
							),
                        )
                    );

    return $options;
}
add_filter( 'cs_framework_options', 'imc_theme_options' );
```

And here's what I got:
![admin_theme_options](https://cloud.githubusercontent.com/assets/4551598/11336158/1c1b92fa-920d-11e5-96cb-4d032306c9ed.png)

**Comment by Codestar** [comment]
Wow, thanks for nice opinion. I was motivated :wink: hmm now i did copy-paste this code on my localhost. and result is:

![support_14-17-25](https://cloud.githubusercontent.com/assets/1313301/11336341/2f2f8434-91ed-11e5-8385-c8e1aa64dbe8.png)

Uh, can you check file directly ```theme-name/cs-framework/fields/backup/backup.php``` ? btw, only this field not working ? another fields is o ? btw, can you try copy php codes from ```backup.php``` to ```theme-name/cs-framework/fields/text/text.php``` append after text class. maybe "backup" name blocking by server or anything ? i am not sure. it is interesting.

**Comment by mayeenulislam** [comment]
Only the backup thing was not working, rest others are working just fine.

Yes, that the whole `backup` (`cs-framework/fields/backup/`) folder thing is missing here, I don't know how. I've taken it from the fresh repo and it's working like a charm. Thanks a lot. Everything is fine.

Just keep up the good work. You can close the issue with love. :+1:

**Comment by Codestar** [comment]
Oh goood. I am relax, i was think there is a bug.. Ok all is good :+1:  when you need any help find me :wink:  You're welcome, Enjoy :smile:
