### ISSUE TITLE
Show the option value name

### ISSUE THREAD

**Issue by pavliukpetro** [Codestar/codestar-framework#21]
Hello.
Do you have the config to show the option value name for the current option in the Option panel.
For example, add it next to the option
![Снимок экрана 2019-04-16 в 17 38 10](https://user-images.githubusercontent.com/11602610/56218956-90971400-606e-11e9-9975-ae448b54d786.png)

**Comment by Codestar** [comment]
Hi,

Uh, there is no option for this... there is only `before` and `after` params.

Regards, Codestar

**Comment by pavliukpetro** [comment]
Ok, thanks.
It would be really cool to show the option name in after param))

**Comment by Codestar** [comment]
Hi,

Actually it's easy with a few modificaiton. For eg.

```php
// codestar-framework/classes/field.class.php line 78 change it from:
return $output;
// to
return apply_filters( 'csf_field_after', $output, $this->field, $this );
```

Then, we can create a filter for show to option name in after.

```php
if( ! function_exists( 'show_option_name_after_field' ) ) {
  function show_option_name_after_field( $output, $field ) {

    if( ! empty( $field['id'] ) ) {
      $output .= '<p>'. $field['id'] .'</p>';
    }

    return $output;
  }
  add_filter( 'csf_field_after', 'show_option_name_after_field', 10, 2 );
}
```

Is this what you need ?

Regards, Codestar
