### ISSUE TITLE
Metabox Group Information Trouble

### ISSUE THREAD

**Issue by geniusmode** [Codestar/codestar-framework#210]
Greetings,

I hope all is well, I've spent some time to go through previous posts to see if there was an example for displaying information from arrays on the front end. Nothing seemed to work and I hope you can help me as I'm fairly new to this functionality.

here's my code:

```php
$meta_groups = get_post_meta( $post->ID, 'metabox_section_name', false ); 
if( ! empty( $meta_groups ) ) {
    foreach( $meta_groups as $meta_group) {  ?>

[list item start]
    <?php var_dump($meta_group['metabox_group']);?> /* group id */
    <?php echo ['metabox_group_title']);?>/* group item */
    <?php echo ['metabox_group_description']);?>/* group item*/
    <?php echo ['metabox_group_etc']);?>/* group item */
[list item end]
} }
```

I need the fields to duplicate as list items with the added content from each entry. I really love this framework and it's exactly what I need! If you can help me with a general template to study, I'd greatly appreciate it.

**Comment by SantiagoInteractive** [comment]
Hi,
Try this:

```
<?php $meta_groups = get_post_meta( $post->ID, 'metabox_section_name', false );
if ( !empty($meta_groups) ) {
   foreach ( $meta_groups as $meta_group ) {
      echo $meta_group['metabox_group_title'];
      echo $meta_group['metabox_group_description'];
      echo $meta_group['metabox_group_etc'];
   }
} ?>
```
Hope this will help you understand it better.

**Comment by geniusmode** [comment]
Thank you for the quick reply!!! 

I changed your example to reflect the IDs I'm using code, but still can't get the entered information to display.

This returns nothing:
<?php $meta_groups = get_post_meta( $post->ID, 'post_options_group_display', false );
        if ( !empty($meta_groups) ) {
            foreach ( $meta_groups as $meta_group ) {
                echo $meta_group['post_options_group_text'];
                echo $meta_group['post_options_group_textarea'];
                echo $meta_group['post_options_group_icon'];
            }
        } ?>


But if i use var_dump: 
<?php var_dump($meta_data['post_options_group_display']);?>

I get: 

array(4) { [3]=> array(3) { ["post_options_group_text"]=> string(19) "Strategic Discovery" ["post_options_group_textarea"]=> string(57) "Vivamus pretium tortor non risus vel commodo condimentum." ["post_options_group_icon"]=> string(13) "fa fa-comment" } [4]=> array(3) { ["post_options_group_text"]=> string(22) "Research & Development" ["post_options_group_textarea"]=> string(44) "Sed sit amet nibh sed felis commodo feugiat." ["post_options_group_icon"]=> string(15) "fa fa-clipboard" } [2]=> array(3) { ["post_options_group_text"]=> string(18) "Interactive Design" ["post_options_group_textarea"]=> string(35) " Quisque placerat tincidunt tellus." ["post_options_group_icon"]=> string(11) "fa fa-users" } [1]=> array(3) { ["post_options_group_text"]=> string(21) "WordPress Development" ["post_options_group_textarea"]=> string(22) "Etiam eu mattis nulla." ["post_options_group_icon"]=> string(15) "fa fa-wordpress" } }

So the information is there inside of 'post_options_group_display'. Everything is placed within the loop, am I missing an important step?

**Comment by SantiagoInteractive** [comment]
Ah, sorry, my mistake.

You should use <code>get_post_meta</code> with <code>$single</code> parameter set to <code>true</code> like this:
<code>$meta_groups = get_post_meta( $post->ID, 'post_options_group_display', true );</code>

So your entire code should look like this:

```
<?php $meta_groups = get_post_meta( $post->ID, 'post_options_group_display', true );
if ( !empty($meta_groups) ) {
   foreach ( $meta_groups as $meta_group ) {
      echo $meta_group['post_options_group_text'];
      echo $meta_group['post_options_group_textarea'];
      echo $meta_group['post_options_group_icon'];
   }
} ?>
```
Try it now and it should work just fine.
Cheers!

**Comment by geniusmode** [comment]
Thank you for your help!! I was able to get this working for the fieldset type instead of a group! I'll keep working at it though!!

**Comment by Codestar** [comment]
Thanks @SantiagoInteractive 

And guys, if you need any update for core, i am ready :smile:
