### ISSUE TITLE
Shortcode button and visual composer editor

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#211]
Hi, 

Inside visual composer text editor element, i seeing this error: Notice: Trying to get property of non-object in <code>C:\wamp\www\wp\wp-content\plugins\myplugin\cs-framework\classes\shortcode.class.php on line 79</code>

https://drive.google.com/file/d/0B7q-ingsr5hKendhNnhna053Wnc/view

Shortcode button working fine on other editors, just does problem in visual composer.

Could you please help me to fix this. Thanks

Regards

**Comment by Codestar** [comment]
Hi,

Yes sure, let's try this codes. Open ```plugins\myplugin\cs-framework\classes\shortcode.class.php``` and go ```line 79``` replace code:

```php
$post_type = ( is_object( $post ) ) ? $post->post_type : '';
```

if still same, try this:

```php
$post_type = ( is_object( $post ) && isset( $post->post_type ) ) ? $post->post_type : '';
```

and tell me which one is works :smile:

**Comment by Codevz** [comment]
Hey man,  Thanks for quick response, Yes problem solved, both working :smile:  :+1:

**Comment by Codestar** [comment]
You're welcome :wink: yeah, I added this fixes for framework update, you will not see it again :+1: thanks for report :smile:
