### ISSUE TITLE
Media Gallery Grid View is vanished conflicting with `cs-plugins.js`

### ISSUE THREAD

**Issue by mayeenulislam** [Codestar/codestar-framework#213]
### Scenario
The problem first appeared in one of my live site, the theme was made with CS framework only for options panel ([nano progga v.3.0.0](https://github.com/nanodesigns/nano-progga/releases/tag/3.0.0)). I've deleted all other files except `framework.config.php` in `cs-framework/config/`. I enabled the options field using filter hook (`cs_framework_options`).

But I failed generating the same in localhost. So I thought it's causing by server somehow.

But today, I found the same issue in another project (where the same methods were applied for the same purpose), and it's happening in localhost too.

### What's happening?
In WordPress Media Gallery in grid mode (`/wp-admin/upload.php?mode=grid`) nothing is visible. The browser console is saying:

> Uncaught Error: `selector` option must be specified when initializing tooltip on the window.document object!

It's pointing to `cs-framework/assets/js/cs-plugins.js` on [line number `2074`](https://github.com/Codestar/codestar-framework/blob/master/assets/js/cs-plugins.js#L2073-L2075)

And after that, 7 occurrences of the same message:

> Uncaught TypeError: Cannot read property 'hasClass' of undefined

And this one is pointing to concatenated scripts (so I can't figure out where).

But the media files are visible using the list view (`?mode=list`), with the first error message in console. The second error message is not in the `list` view.

P.S.: I'm using the unreleased `Codestar Framework 1.0.0`.

**Comment by Codestar** [comment]
Hi,

Hmm, interesting, i installed your theme on my localhost now, and i can not see this error message in console log.

![support_14-08-23](https://cloud.githubusercontent.com/assets/1313301/12233112/0155108c-b86d-11e5-8f6d-155679205f75.png)

Hmmm let me check it on your wordpress, you can send admin informations via routewp[at]gmail.com

**Comment by Codestar** [comment]
I received information, but you need to switch administrator for my account, because i can not try to disable plugins or change code on framework.

**Comment by mayeenulislam** [comment]
Thank you. You've pointed me to the right thing, I forgot (as a developer I shouldn't). Disabled and enabled plugin one by one, and found the conflicting one.

I found the issue. It's conflicting with [WP Smush - plugin WP MU Dev.](https://wordpress.org/plugins/wp-smushit/)

Primarily I disabled the WP Smush. And I'm gonna post a support ticket to them also.

But I'd love if you both can check back in your code to resolve the conflict by any easy way. :)

Thank you for your prompt support.

**Comment by Codestar** [comment]
Hehe :smile: Yes, first way is disable/enable plugin for conflicts :+1: 

You're welcome, when you need help again, find me here.

**Comment by mayeenulislam** [comment]
I'm reopening the issue, I'm afraid.

I [contacted](https://wordpress.org/support/topic/conflicting-with-codestar-framework-in-media-gallery-grid-view) to WP Smush plugin support.

And then we've speculated the thing in my dev version, giving them the admin and FTP credentials.

Mr. Umesh Kumar, the designated support assistant, did an excellent job on his end, found that, it's a CSS issue. Though we can't find any direct class/id interference to that page.
![CSS issue](https://cloud.githubusercontent.com/assets/4551598/12550498/4b6d2228-c38e-11e5-868e-0ce977617798.png)


But in my POV it's the CSS issue resulting from some kind of JS conflict or **even can occur on `str_replace()` on any HTML output**. I'm sharing one of my code for thinking about the hypothesis:

This is a working code changing the Featured Image text for my CPT:
````
function img_ins( $content ) {

    global $current_screen;

    if( is_admin() && 'cpt' === $current_screen->post_type ) {

        $content = str_replace(
                    esc_attr__('Set featured image', 'textdomain'),
                    esc_attr__('Set CPT Image', 'textdomain'),
                    $content
                );
    }

    return $content;
}
add_filter( 'admin_post_thumbnail_html', 'img_ins' );
````

But when I switched to Multisite, I found the code is buggy. I can select and add an image for featured image, but the image on featured image meta box doesn't show up. But the featured image is updated successfully, and everything is fine, except the preview after addition. I figured out the solution and the working code was:

````
function img_ins( $content ) {

    global $post;

    if( is_admin() && 'cpt' === get_post_type( $post ) ) {

        $content = str_replace(
                    esc_attr__('Set featured image', 'textdomain'),
                    esc_attr__('Set CPT Image', 'textdomain'),
                    $content
                );
    }

    return $content;
}
add_filter( 'admin_post_thumbnail_html', 'img_ins' );
````

I'm afraid I cannot help you why this was happening, because I even couldn't find that. But I found that, my string replace caused the JS to not function properly.

I'm opening the issue again, because as we are blaming WP Smush for it, it can also occur for Codestar, so it's a vice versa. In WordPress' point-of-view both Codestar and WP Smush is plugin. If we can check deactivating WP Smush, we can check deactivating Codestar too.

So, when I commented out the require line for Codestar but activate WP Smush, it's working fine. So we cannot point out WP Smush for the occurrence. And on the first report the console was actually pointing to Codestar.

I'm here with all sort of things and cooperation, because I love both the plugins very much. So I'll provide all the assistance possible from me solving the issue. I invited Mr. Umesh Kumar to join the discussion with his findings. I hope he can provide some light on this issue. Thank you both the team for the awesome support.

**Comment by Codestar** [comment]
Hi,

I did try to explain main issue here https://wordpress.org/support/topic/conflicting-with-codestar-framework-in-media-gallery-grid-view?replies=7 yes there is a conflict. i am thinking to replace my bootstrap tooltip plugin name. let's try it. wait i will update files. :+1:

**Comment by Codestar** [comment]
```php
/assets/js/cs-plugins.js
/assets/js/cs-framework.js
```
Ok. update this js files and tell me result :)

**Comment by UmeshSingla** [comment]
@Codestar @mayeenulislam  Hey, Awesome job in here, debugging the issue. It never occurred to me that it could be as simple as that. Thanks a lot for figuring that out.

How important is Bootstrap tooltip in your plugin? If it is an important part of your plugin, I don't mind replacing the tooltip in Smush plugin, as we use it at very fewer places only.

But if it is otherwise, I can leave the jQuery tooltip in the plugin.

**Comment by Codestar** [comment]
@UmeshSingla thanks for your opinions, also i liked your plugin, i will advise it for my clients.

Yes, I changed plugin name for this conflict, because i respect for 300k+ user avticated. Actually i am thinking after your message, it is important for me? hmm no, it is not important also i think i can use css3 tooltip yes. why not :smiley: 

Hey bro, No switch to Bootstrap tooltip because in bootstrap v4.0 changin tooltip script see http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/ 

<pre>Improved auto-placement of tooltips and popovers
thanks to the help of a library called Tether.</pre>

I think jQuery UI tooltip more stable than bootstrap, also js library predefined in wp core :+1: 

But as you know <pre>$.tooltip();</pre> is very global, we need to avoid any future conflicts. I will try css3 tooltip or a minor 1kb custom $.my_name_space_tooltip()

Best wishes.

**Comment by mayeenulislam** [comment]
Thank you soooo much for the collaborative support from both the plugins. It's awesome. :+1: 

I updated the two files mentioned above, in `cs-framework`:
`/assets/js/`[`cs-plugins.js`](https://raw.githubusercontent.com/Codestar/codestar-framework/master/assets/js/cs-plugins.js)
`/assets/js/`[`cs-framework.js`](https://raw.githubusercontent.com/Codestar/codestar-framework/master/assets/js/cs-framework.js)

And the following path is working fine in both Chrome and Firefox in local version.
`http://localhost/project/wp-admin/upload.php?mode=grid`

And with this I think it's time to have a [good release](https://github.com/Codestar/codestar-framework/releases).

**Comment by UmeshSingla** [comment]
@Codestar Yeah, the jQuery UI being available in core was the main reason for using it in first place, so I should stick to it.
>thanks for your opinions, also i liked your plugin, i will advise it for my clients.

That'd be awesome of you :)

Best wishes for the framework release.

Cheers, Umesh Kumar

**Comment by Codestar** [comment]
Cheers :+1:

**Comment by lokenthapa** [comment]
@Codestar please help me to fix this bug.....
Uncaught TypeError: Cannot read property 'thumbnail' of undefined
in 
var thumbnail  = ( typeof attributes.sizes.thumbnail !== 'undefined' ) ? attributes.sizes.thumbnail.url : attributes.url;
so edit gallery doesnt show images
