### ISSUE TITLE
meta box not work

### ISSUE THREAD

**Issue by partharoy** [Codestar/codestar-framework#214]
Hi I am trying to get meta value from metabox. Here is my code

```php
if (!empty($subtitle['subtitle-post'])) {
  $subtitle = get_post_meta( $post->ID, '_custom_meta_options', false );
  var_dump( $subtitle['subtitle-post'] );
}
```

But it returns nothing. I have tried another process but it shows offset string. what to do?

**Comment by SantiagoInteractive** [comment]
Hi,

Please see this issue answer right here: https://github.com/Codestar/codestar-framework/issues/210#issuecomment-169108090
I have explained there how you can get post meta values the right way.

Cheers!

**Comment by partharoy** [comment]
@SantiagoInteractive I have used your code. bit it shows offset again. I have using var_dum but it shows null. Would you please review my code?
<?php 
                                $meta_groups = get_post_meta( $post->ID, '_custom_post_options', true );
                                    if ( !empty($meta_groups) ) {
                                       foreach ( $meta_groups as $meta_group ) {
                                          echo $meta_group['posts-subtitle'];
                                       }
                                    }
                             ?>

**Comment by SantiagoInteractive** [comment]
Hi,
Nothing to review on your code. Seems correct.

Can you please paste your <code>metabox.config.php</code> file content or provide with more information about how you are building the meta fields?

Is <code>_custom_post_options</code> your meta correct name?

Also, take a look at this reference in the documentation: http://codestarframework.com/documentation/#metabox-configure. Check if you're following the right procedures explained there.

**Comment by partharoy** [comment]
@SantiagoInteractive : Hi,
here is my metabox.config.php code for post type
$options      = array();
$options[]    = array(
  'id'        => '_custom_post_options',
  'title'     => 'Custom Post Options',
  'post_type' => 'post',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => array(

    array(
      'name'   => 'Subtitle Section',
      'fields' => array(

        array(
          'id'    => 'posts-subtitle',
          'type'  => 'text',
          'title' => 'Add Your Subtitle',
        ),
      ),
    ),

  ),
);
CSFramework_Metabox::instance( $options );

**Comment by SantiagoInteractive** [comment]
In this case you should use it like this:

```
<?php
if (have_posts()) : while (have_posts()) : the_post();

   $meta_data = get_post_meta( $post->ID, '_custom_post_options', true );

   if ( !empty($meta_data) ) {
      $subtitle = $meta_data['posts-subtitle'];
   }

   if ($subtitle) {
      echo $subtitle;
   }

endwhile;
endif;
?>
```

You don't have group meta data (http://codestarframework.com/documentation/#group) so you don't need to use <code>foreach</code> in your case.

**Comment by partharoy** [comment]
@SantiagoInteractive : Hi,
Nothing happened. here is my full code with loop

<?php if(have_posts()): while(have_posts()):the_post() ?>
                <div class="post-preview">
                    <a href="<?php the_permalink(); ?>">
                        <h2 class="post-title">
                            <?php the_title() ?>
                        </h2>
                        <h3 class="post-subtitle">
                          <?php
                               $meta_data = get_post_meta( $post->ID, '_custom_post_options', true );

                               if ( !empty($meta_data) ) {
                                  $subtitle = $meta_data['posts-subtitle'];
                               }

                               if ($subtitle) {
                                  echo $subtitle;
                               }

 
                            ?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#"><?php the_author(); ?></a> on <?php the_time('F j, Y'); ?></p>
                </div>
                <hr>
            <?php  endwhile;endif ?>

**Comment by Codestar** [comment]
@partharoy 

```php
// what you see when run this code?
$meta_groups = get_post_meta( $post->ID, '_custom_post_options', true );
var_dump( $meta_groups );
```

```php
// btw , you can try this
$meta_data = get_post_meta( $post->ID, '_custom_post_options', true );
echo ( ! empty( $meta_data ) && ! empty( $meta_data['posts-subtitle'] ) ) ? $meta_data['posts-subtitle'] : '';
```

**Comment by SantiagoInteractive** [comment]
Hi,

I'm guessing you are trying to get <code>$post->ID</code> outside <code>single.php</code> template.
Maybe on <code>archive.php</code> or a custom page template. Is that correct?

Add: <code>var_dump($post->ID);</code> inside your loop.
If nothing returns then try use get_post_meta replacing <code>$post->ID</code> with <code>get_the_ID()</code>.
```
$meta_data = get_post_meta( get_the_ID(), '_custom_post_options', true );
```

**Comment by Codestar** [comment]
Yes I agree with @SantiagoInteractive

**Comment by partharoy** [comment]
Hi @Codestar Here is my return of code: 
![capture](https://cloud.githubusercontent.com/assets/7724972/12302741/f7e664f2-ba50-11e5-8647-843715684683.PNG)

@SantiagoInteractive  yes I am call it in index.php file? Is that occur because of that? Ok I will follow your instruction. Thanks for your support. I am glad.

**Comment by Codestar** [comment]
Hi,

Hmm, we can not see ```posts-subtitle``` data. Metabox saving is working correctly in admin panel ? I have not any idea really :) maybe there is conflict with a plugin or another thing.

**Comment by partharoy** [comment]
ok I will apply this code in another theme.

**Comment by Codestar** [comment]
Actually, i can check it for you, if you send me your admin informations via routewp@gmail.com

**Comment by partharoy** [comment]
My theme is in localhost. or I can send you the theme file. this is a pretty basic theme.

**Comment by Codestar** [comment]
Yes, why not, you can do :wink:

**Comment by Codestar** [comment]
Solved.

btw @SantiagoInteractive there is no any issue. this guy did try it another wordpress and and it is working normally, i mean your all codes was working correctly :smile:

**Comment by SantiagoInteractive** [comment]
Great. Thanks @Codestar for the clarification.
Good day you all !

**Comment by Codestar** [comment]
Have a nice day :+1:

**Comment by partharoy** [comment]
Thank You All for your effort. :100:

**Comment by Codestar** [comment]
You're welcome :wink:

**Comment by canberkyildirim** [comment]
thank u!
