### ISSUE TITLE
Group Option for Widgets

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#215]
Hi Codestar

I also need to Add Group Option for Widgets, But i dont know how, Can you help me?

Thanks

**Comment by Codestar** [comment]
Hi,

It is not available, yet. but i will add this feature in next updates :+1:

**Comment by WPsmart** [comment]
Thanks Very much for your Great Framework and Fast reply, can i know your next update releasing date? 

Thanks

**Comment by Codestar** [comment]
You're welcome, and thanks. Actually, i will added a lot of features after finish my new theme. because i am so busy. So i am planing to group, typography, sorter etc fields for widgets and customizer both :wink:

**Comment by WPsmart** [comment]
Thanks Very much :) Good Luck for your  Next Theme

**Comment by Codestar** [comment]
Thank you :)

**Comment by devariya** [comment]
Don't forget to add one click import option

**Comment by Codestar** [comment]
Yes sure :+1:

**Comment by WPsmart** [comment]
Thanks Codestar :+1:

**Comment by tiberiur** [comment]
This is the last thing I need.

Do you have any update with this feature?

Thanks for your work.

**Comment by malek1316** [comment]
At first very very thanks for released latest version 1.0.2 on Dec 19, 2017 , but not appear gruop field type in widget & customize. it is so need for us. We are waiting for it.

We are pleased to you for build up a nice and excellent framework for us.
