### ISSUE TITLE
pleas i need your help in Groups metabox

### ISSUE THREAD

**Issue by amrhussien2** [Codestar/codestar-framework#216]
this code in file metabox.config.php
i need code display the value in single file
I reviewed all the tickets but the result was negative

```php
// -----------------------------------------
// Post Metabox Options                    -
// -----------------------------------------
$options[]    = array(
  'id'        => 'post_options_group_display',
  'title'     => 'Custom Post Options',
  'post_type' => 'post',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => array(

    array(
      'name'   => 'titlemetabox',
      'fields' => array(

              array(
          'id'              => 'meta_groups',
          'type'            => 'group',
          'title'           => ' text inputs',
          'button_title'    => ' new input ',
          'accordion_title' => ' input title',
          'fields'          => array(

            array(
              'id'          => 'textinput',
              'type'        => 'text',
              'title'       => 'text here ',
            ),

          )

        ),
      ),
    ),
  ),
);
```

**Comment by SantiagoInteractive** [comment]
Hi,
See https://github.com/Codestar/codestar-framework/issues/214 and https://github.com/Codestar/codestar-framework/issues/210. You have all you need in there to get started.

Also you can check the documentation here:
http://codestarframework.com/documentation/#metabox-configure

Cheers!

**Comment by amrhussien2** [comment]
iam used this code

$meta_groups = get_post_meta( $post->ID, 'post_options_group_display', true );
if ( !empty($meta_groups) ) {
   foreach ( $meta_groups as $meta_group ) {
      echo $meta_group['post_options_group_text'];
      echo $meta_group['post_options_group_textarea'];
      echo $meta_group['post_options_group_icon'];
   }
}


but not working
empty value

**Comment by SantiagoInteractive** [comment]
Your <code>'id' => 'textinput'</code> should match <code>post_options_group_text</code>.

For your code:

```php
        array(
          'id'          => 'textinput', // the ID for this setting
          'type'        => 'text',
          'title'       => 'text here ',
        ),
```

You should use it like this:

```php
$meta_groups = get_post_meta( $post->ID, 'post_options_group_display', true );
if ( !empty($meta_groups) ) {
   foreach ( $meta_groups as $meta_group ) {
      echo $meta_group['textinput']; // match the ID from your setting
   }
}
```

**Comment by amrhussien2** [comment]
i now this 
i attached a file to you understand what I mean
and sorry for my english i now is so bad :)

**Comment by amrhussien2** [comment]
http://www.mediafire.com/download/2zojgyuzpnanr64/file.zip

**Comment by SantiagoInteractive** [comment]
```php
$meta_data = get_post_meta( $post->ID, '_custom_meta_options', true );

if ( !empty($meta_data) ) {

   $meta_groups = $meta_data['meta_groups'];

   if ( !empty($meta_groups) ) {

      foreach ( $meta_groups as $meta_group ) {
         echo $meta_group['textinput'];
      }

   }

}
```

**Comment by amrhussien2** [comment]
it's worked
relly thank you so much

**Comment by SantiagoInteractive** [comment]
No problem! Have fun! :+1:

**Comment by Codestar** [comment]
Niceeee. @SantiagoInteractive :+1:
