### ISSUE TITLE
Show metabox on certain page/post/CPT

### ISSUE THREAD

**Issue by tiberiur** [Codestar/codestar-framework#217]
Hi Codestar,

First of all, codestar framework rocks and _4 in 1_ thing is awesome! Great work!

**Question**
Is there any way to display metaboxes on certain page based on id/slug (or range ids, eg: cmb2)?

Thanks,

**Comment by Codestar** [comment]
Hi,

Yes it is possible with some modification. for eg:

[/classes/metabox.class.php#L54](https://github.com/Codestar/codestar-framework/blob/master/classes/metabox.class.php#L54) update this line to:

```php
$post_id = ( ! empty( $value['post_id'] ) ) ? $value['post_id'] : '';
if( $post_type == $value['post_type'] && get_the_ID() == $post_id ) {
```

and you can set post id from config [/config/metabox.config.php#L15](https://github.com/Codestar/codestar-framework/blob/master/config/metabox.config.php#L15) only add extra line to:

```php
'post_type' => 'page',
'post_id'   => '12',
```

I did try it, it is worked :+1:

**Comment by tiberiur** [comment]
Yep, it's work.

Thank you!

**Comment by Codestar** [comment]
Great :+1:

**Comment by hahmmed** [comment]
Dear Codestar, I really need your suggestion. I've checking exact the line in the file metabox.config.php#54 below is code. Could you please suggest me where i should update or if you could just give me the code :)

public function add_meta_box( $post_type ) {

    foreach ( $this->options as $value ) {
      add_meta_box( $value['id'], $value['title'],
          array( &$this, 'render_meta_box_content' ), $value['post_type'], $value['context'], $value['priority'], $value );
    }
  }

I really need to show different page meta in different page (backend). Thanks again for your great framework. God bless you.

**Comment by proscriptsell** [comment]
Hi @hahmmed 
please check bellow is you solution ....
`$options      = array();

for ($x = 0; $x <= 2; $x++) {
		$options[]    = array(
		  'id'        => '_edsproject_info_'.$x,
		  'title'     => 'Information',
		  'post_type' => 'page',
		  'context'   => 'normal',
		  'priority'  => 'default',
		  'sections'  => array(
		  
			// end: a section
			array(
			  'name'   => 'section_4',
			  'fields' => array(
				// begin: fields
					array(
					  'id'    => '_edsproject_client',
					  'type'  => 'text',
					  'title' => 'Client',
					),
					array(
					  'id'    => '_edsproject_stated_date',
					  'type'  => 'text',
					  'title' => 'Stated Date',
					),
				 // end: fields
			  ),
			),
			// end: a section
		
		  ),
		);
} 
CSFramework_Metabox::instance( $options );`

**Comment by proscriptsell** [comment]
Hi
Bellow is you code solve , you can use any where of function.php file or metabox.class.php

`$options      = array();
for ($x = 0; $x <= 2; $x++) {
	$options[]    = array(
	'id'        => '_edsproject_info_'.$x,
	'title'     => 'Information',
	'post_type' => 'page',
	'context'   => 'normal',
	'priority'  => 'default',
	'sections'  => array(
		// end: a section
		array(
		  'name'   => 'section_4',
		  'fields' => array(
			// begin: fields
				array(
				  'id'    => '_edsproject_client',
				  'type'  => 'text',
				  'title' => 'Client',
				),
				array(
				  'id'    => '_edsproject_stated_date',
				  'type'  => 'text',
				  'title' => 'Stated Date',
				),
			 // end: fields
		  ),
		),
		// end: a section
		),
	);
} 
CSFramework_Metabox::instance( $options );`


Thanks

**Comment by proscriptsell** [comment]
Hi @hahmmed 
Please check bellow code your solution . and you can add anywhere of function.php or metabox.class.php, 
it's up to you 
`$options      = array();
for ($x = 0; $x <= 2; $x++) {
	$options[]    = array(
	'id'        => '_edsproject_info_'.$x,
	'title'     => 'Information',
	'post_type' => 'page',
	'context'   => 'normal',
	'priority'  => 'default',
	'sections'  => array(
		// end: a section
		array(
		  'name'   => 'section_4',
		  'fields' => array(
			// begin: fields
				array(
				  'id'    => '_edsproject_client',
				  'type'  => 'text',
				  'title' => 'Client',
				),
				array(
				  'id'    => '_edsproject_stated_date',
				  'type'  => 'text',
				  'title' => 'Stated Date',
				),
			 // end: fields
		  ),
		),
		// end: a section
		),
	);
} 
CSFramework_Metabox::instance( $options );`
Thanks

**Comment by hahmmed** [comment]
@proscriptsell  thank you very much, I should try with that.

**Comment by Codestar** [comment]
@hahmmed 

Did you try it ?

**Comment by hahmmed** [comment]
@Codestar No, i still waiting for your help :)

**Comment by dumketo** [comment]
@Codestar @tiberiur @hahmmed Please help me with this. I don't understand how to use this code. Please Help me out from this problem.

**Comment by dumketo** [comment]
@hahmmed Use like this. its working

public function add_meta_box( $post_type ) {
      foreach ( $this->options as $value ) {
          $post_id = ( ! empty( $value['post_id'] ) ) ? $value['post_id'] : '';
          if( $post_type == $value['post_type'] && get_the_ID() == $post_id ) {
              add_meta_box( $value['id'], $value['title'], array( &$this, 'render_meta_box_content' ), $value['post_type'], $value['context'], $value['priority'], $value );
          }else{
              add_meta_box( $value['id'], $value['title'], array( &$this, 'render_meta_box_content' ), $value['post_type'], $value['context'], $value['priority'], $value );
          }
      }  
  }
