### ISSUE TITLE
Defaults does not work in Customizer

### ISSUE THREAD

**Issue by rahulnever2far** [Codestar/codestar-framework#219]
I have a color picker field with `#ffbc00` as the default color.
```php
array(
  'name'      => 'color_option_1',
  'default'   => '#ffbc00',
  'control'   => array(
    'type'    => 'cs_field',
    'options' => array(
      'type'  => 'color_picker',
      'title' => 'Color Option 1',
    ),
  ),
),
```
`cs_get_customize_option( 'color_option_1' )` returns nothing unless I manually change color in color picker and save it.

**Comment by Codestar** [comment]
I did check it again now, i am getting color code normally, i think there is another thing? maybe a conflict? try it on a clean wordpress. and tell me again.

**Comment by rahulnever2far** [comment]
I have just tried it again with Twenty Sixteen on a fresh WordPress install.

Defaults don't work unless settings are saved in the customizer at least once.

**Comment by Codestar** [comment]
I have not any idea really, i checked it twice, no any issue. hmm add this on front end for debug, what you see?

```php
var_dump( get_option( CS_CUSTOMIZE' ) ); // see output
```

Can you see "color_option_1" ?

**Comment by rahulnever2far** [comment]
With `var_dump( get_option( CS_CUSTOMIZE ) );`, it says `bool(false)`. Once I go into the Customizer and Save settings it sarts saying `array(1) { ["color_option_1"]=> string(7) "#ffbc00" }`


Here's how you can replicate the issue on your system:
1 - Download master branch of Codestar Framework and add it as a plugin in WordPress and activate it.
2 - At the end of `functions.php` add the following code:
```php
define( 'CS_ACTIVE_FRAMEWORK', false );
define( 'CS_ACTIVE_METABOX', false );
define( 'CS_ACTIVE_SHORTCODE', false );
define( 'CS_ACTIVE_CUSTOMIZE', true );

function extra_cs_framework_options( $options ) {

  $options = array(); // remove old options

  $options[] = array(
    'name'        => 'panel_test_1',
    'title'       => 'Test Panel',
    'description' => 'Test Panel description.',
    'sections'    => array(
      array(
        'name'     => 'section_test_1',
        'title'    => 'Test Section 1',
        'settings' => array(
          array(
            'name'      => 'color_option_1',
            'default'   => '#ffbc00',
            'control'   => array(
              'type'    => 'cs_field',
              'options' => array(
                'type'  => 'color_picker',
                'title' => 'Color Option 1',
              ),
            ),
          ),
        ),
      ),
    ),
  );

  return $options;
}
add_filter( 'cs_customize_options', 'extra_cs_framework_options' );
```
3 - In `header.php`, add the following code just above `</header><!-- .site-header -->`
```php
<?php echo 'color: ' . cs_get_customize_option( 'color_option_1' ) ?>
```
4 - We didn't visit the Customizer even once. We just added the code. Now open the home page. Output would be
```
color:
```

**Comment by Codestar** [comment]
Hi,

Very interesting, I followed your steps in my localhost, and the result is:

![support_17-15-22](https://cloud.githubusercontent.com/assets/1313301/12753679/c0cca6c2-c9d0-11e5-864a-2bc0b24e4c88.png)

Your site is online? make it online and give me wordpress admin information via routewp[at]gmail.com

**Comment by Codestar** [comment]
Oh i understand it finally, it is working on customizer but when you visit homepage without save option, it is return false. hmmm. actually this is same for core customizer. you can not get default value without save. but i added a default option on function for solution this. You can use this:

```php
cs_get_customize_option( 'color_option_1', '#ffbc00' );
```
