### ISSUE TITLE
Sanitize, Validate they do not work as subfields

### ISSUE THREAD

**Issue by LeninZapata** [Codestar/codestar-framework#22]
Hello, this is something that must be solved, sanitize or validate does not work when the field is within a group, fieldset, tab, etc ...

![image](https://user-images.githubusercontent.com/42600954/56267038-4edc8c80-60b3-11e9-9961-c59ec917a05a.png)

You must implement a recursive function to reach the deepest field and validate or sanitize it.

**Note:** the same would happen in the metaboxes

**Comment by Codestar** [comment]
Hi,

Uh yes. it is normal. Sanitize and validation options are works only top level fields. Nested type fields doesn't supports sanitize/validation ( i.e. group, repeater, tabbed etc fields ). It's very complex to compatibility sanitize/validate for these fields.

Regards, Codestar

**Comment by LeninZapata** [comment]
Temporarily I had to do it, right in this block that you have
![image](https://user-images.githubusercontent.com/42600954/56299095-ffb94a80-60f8-11e9-9ee0-edce41b070ed.png)

replace it with a function
![image](https://user-images.githubusercontent.com/42600954/56299207-2f685280-60f9-11e9-851d-265b7c1bb7e3.png)

and this is the function
![image](https://user-images.githubusercontent.com/42600954/56299296-5d4d9700-60f9-11e9-9bab-777f7d10838d.png)

for the moment this is true, I hope that in the future you can implement a similar function to validate fields at least 1 sub-level more

**Comment by Codestar** [comment]
Yeah, It looks good. I noted this for next updates.

**Comment by dbjpanda** [comment]
> Uh yes. it is normal. Sanitize and validation options are works only top level fields. Nested type fields doesn't supports sanitize/validation ( i.e. group, repeater, tabbed etc fields ). It's very complex to compatibility sanitize/validate for these fields.

@Codestar If it is normal, please remove these parameters from the documentation. It is unnecessarily creating confusion. https://codestarframework.com/documentation/#/fields?id=group
