### ISSUE TITLE
Some features and field request

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#22]
Hi, 
I would like to have some more features and new fields.
1.  Front-end admin menu framework tab support. You can see <a href="http://puu.sh/fZZbj/33b0d8e9ea.png" target="_blank">this</a> following for example.
2. Multiple image upload field.
3. Inline text field. Example <a href="http://puu.sh/fZZuZ/f423a4351d.png" target="_blank">here</a> .

Thanks  in advance.

**Comment by Codestar** [comment]
Hi,

1. This request, you know this is a custom request. i mean you can can add it by yourself easyly. I did not add custom requests because why this framework lightweight :)

For eg, try this by yourself:
```
function cs_admin_bar_menu( $admin_bar ) {

  // adding main menu
  $admin_bar->add_menu( array(
    'id'     => 'cs-framework',
    'title'  => 'Codestar Framework',
    'href'   => '#',
  ));

  // adding a sub menu inside main menu
  $admin_bar->add_menu( array(
    'parent' => 'cs-framework', // using parent array id
    'id'     => 'some_id_1',
    'title'  => 'Text Options',

    // only important this line
    // "text_options" is important
    // this must be same with your section name.
    'href'   => admin_url( 'admin.php?page=cs-framework&cs-section=text_options' ),
  ));

  // another submenu
  $admin_bar->add_menu( array(
    'parent' => 'cs-framework',
    'id'     => 'some_id_2',
    'title'  => 'Textarea Options',
    'href'   => admin_url( 'admin.php?page=cs-framework&cs-section=textarea_options' ),
  ));

}
add_action( 'admin_bar_menu', 'cs_admin_bar_menu', 100 );
```

This is what you need :100: 

2. Yes, Multiple image upload field on the way ;)
3. Yes, Also this field on the way ;)

**Comment by Codestar** [comment]
Notice: Multiple Image field added ;)

**Comment by wpbean** [comment]
Thanks @Codestar

**Comment by Codestar** [comment]
You're welcome :+1:
