### ISSUE TITLE
Feature request: Grid option type

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#221]
Hi, 

How are you ?!

I think grid option type would be really helpfull for all, examples with grid feature user can change different size of header, footer, content, etc. columns like page builders. 

Examples: http://imgur.com/a/DsMgq

* Not sure if there is another easy way for doing this, if you have any suggestion please share with us. 

Thank you.

**Comment by Codestar** [comment]
Hi,

I am fine, thanks you ?

Hmm, actually yes it is nice idea. I will try to add this feature :wink: Also i will need this option type in my themes yeah.

**Comment by Codevz** [comment]
Thanks man ;) Yes this option would be great for some sections and we can create a lot of different demos for themes with this option :+1: I am waiting for a new version :)

**Comment by Codestar** [comment]
Cheers :+1:

**Comment by Ansif** [comment]
Hi,

This option is needed for my theme. Can you please advice me to make this possible? Or this option is one the way in CS framework?

Thanks! :+1:

**Comment by varunsridharan** [comment]
@Codevz i am looking for the same kind of feature. do u mind sharing from where u took the pic. because i am able to check that. may be i can create a field.

**Comment by Codevz** [comment]
@varunsridharan Unfortunately, I don't remember where I seen that :( If you want spend your time on header or footer builder try to create something like this: https://www.youtube.com/watch?v=YE-lOavbrjU
