### ISSUE TITLE
cs_elements and Visual Composer

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#222]
Hi, 

Is there any way to activate cs_elements script on visual composer params ?! 

I tried but no luck. First i added new param to VC ( example upload field from cs-framework ): 

```PHP
add_shortcode_param( 'my_param', 'my_param_settings_field' );
function my_param_settings_field( $settings, $value ) {
	return '
		<input type="text" name="'. esc_attr( $settings['param_name'] ) .'" value="'. esc_attr( $value ) .'" class="'.esc_attr( $settings['param_name'] ) .' '. esc_attr( $settings['type'] ) .'"/>
		<a href="#" class="button cs-add" data-frame-title="Upload" data-upload-type="image" data-insert-title="Use Image">Upload</a>
	';
}
```

Then added cs framework .js file to vc_map as following code:

```PHP
vc_map( array(
	'category' => 'CDZ',
	'base' => 'cdz_base',
	'admin_enqueue_js' => array( 
		CDZ_PLG_URI . 'cs-framework/assets/js/cs-framework.js',
		CDZ_PLG_URI . 'cs-framework/assets/js/cs-plugins.js'
	),
	'name' => __( 'Title CDZ', 'cdz' ),
	'params' => array(
		'type' => 'my_param',
		'heading' => __('my_param', 'cdz'),
		'param_name' => 'my_param'
	),
));
```

In admin area visual composer are loading upload option type with above details but upload button not working. 

Any help would be appreciate. 

Thanks.

**Comment by Ansif** [comment]
Hi,

I'm also exactly looking that. I've tried switcher in visual composer custom params. But it's not working as expected. It's not saving. I've asked support to visual composer support center. Support members not know in detailed development side.

They mentioned to ask support in their google forum group. Need to ask there one more time in developers group.

@Codevz, please let me know if you found any solution! :+1: 

Thanks, Bro!

**Comment by Codevz** [comment]
@Ansif It seems about 4 hours ago VC author updated "Create new param" page and changed `add_shortcode_param` to `vc_add_shortcode_param` so now we can add custom js files easier than before:

`vc_add_shortcode_param('my_param', 'my_param_settings_field', CDZ_PLG_URI . 'cs-framework/assets/js/cs-framework.js');`

So, Yaaay! now its working for me :smile: Just for saving value you should make sure your input does this class `wpb_vc_param_value`

`class="wpb_vc_param_value '.esc_attr( $settings['param_name'] ) .' '. esc_attr( $settings['type'] ) .'"`

**Comment by Codevz** [comment]
Another way for adding existed cs_element to visual composer via `vc_add_shortcode_param`

```PHP
vc_add_shortcode_param('cs_upload', 'my_param_func', CDZ_PLG_URI . 'cs-framework/assets/js/cs-framework.js');
function my_param_func( $settings, $value ) {
	$value = esc_attr( $value );
	$field = array(
		'id'    => esc_attr( $settings['param_name'] ),
		'name'  => esc_attr( $settings['param_name'] ),
		'type'  => 'upload',
		'title' => 'Upload',
		'attributes' => array(
			'class' => 'wpb_vc_param_value '.esc_attr( $settings['param_name'] ) .' '. esc_attr( $settings['type'] ).''
		)
	);
	return cs_add_element( $field, $value );
}
```

**Comment by Codevz** [comment]
@Codestar Is there any way to save / get checkbox value as string and not array ?!

**Comment by Ansif** [comment]
@Codevz! :+1: 

This is awesome! :100: 

Upload field is working as expected, but i still have same problem using new VC method with Checkbox.

Here is my code : 
<pre>
/* Custom Params */
vc_add_shortcode_param('my_param', 'my_param_func', THEMEROOT_URI . '/inc/theme-options/cs-framework/assets/js/cs-framework.js');
function my_param_func( $settings, $value ) {
    $value = esc_attr( $value );
    $field = array(
        'id'    => esc_attr( $settings['param_name'] ),
        'name'  => esc_attr( $settings['param_name'] ),
        'type'  => 'switcher',
        'title' => 'Switcher',
        'attributes' => array(
            'class' => 'wpb_vc_param_value '.esc_attr( $settings['param_name'] ) .' '. esc_attr( $settings['type'] ).''
        )
    );
    return cs_add_element( $field, $value );
}
</pre>

It's loading fine in backend. But it's not getting value of turn On and Off.

The process : 
1. Edit that shortcode. Click On.
2. Save it.
3. Then edit that shortcode. Click Off.
4. Save it.
5. Edit that shortcode. It's still in ON. It's not get the value of Off. :)

Hope you understand! :+1:

**Comment by Codevz** [comment]
Hi @Ansif 

As i checked a lot of option types are not working with VC and they just saving NULL or 1

Its a bit weird, Gallery option type with multiple values working fine but multiple checkbox and switcher not working :( So far as i checked just this options are working: 

- [x] upload
- [x] image
- [x] gallery
- [x] text
- [x] textarea

@Codestar Any help on this would be appreciate. 

Thank you.

**Comment by Codevz** [comment]
@Ansif this js code will fix switcher saving issue in VC. But still counldn't find any solution for other options.

```javascript
(function ( $ ) {
	vc.atts.switcher = {
		parse: function ( param ) {
			var arr, newValue;

			arr = [];
			newValue = '';
			$( 'input[name=' + param.param_name + ']', this.content() ).each( function () {
				var self;

				self = $( this );
				if ( this.checked ) {
					arr.push( self.attr( 'value' ) );
				}
			} );
			if ( 0 < arr.length ) {
				newValue = arr.join( ',' );
			}
			return newValue;
		},
		defaults: function ( param ) {
			return ''; // needed for saving - without this default value for param will be first value in array
		}
	};
})( window.jQuery );
```
In above code `switcher` should be same as your option type name.
