### ISSUE TITLE
WYSIWYG Editor in shortcode popup

### ISSUE THREAD

**Issue by roscabgdn** [Codestar/codestar-framework#225]
Hy,
I have created a shortcode, inside it i have added a wysiwyg editor (printscreen) but when i want to switch from text to visual i get 
**TypeError: ed is undefined qt._close('', ed.canvas, ed);**

Error is located in /wp-includes/js/quicktags.js line 606 
`qt._close('', ed.canvas, ed);`

After all fileds are filled in and and i insert the shortcode, the wysiwyg field is not printed.

Thx and keep up the good work!

	
![shortcode](https://cloud.githubusercontent.com/assets/3717680/13219436/ad843f00-d978-11e5-8a9f-1b3caf7ae887.png)

**Comment by roscabgdn** [comment]
Any updates ?

**Comment by Codestar** [comment]
No any updates, but i did not close this issue, i will add this feature asap, i am busy a little :smiley:  :+1:
