### ISSUE TITLE
Search option within our Options Framework?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#226]
Hi Mate, 

I just saw, avada 4.0 coming soon features! That's are awesome!

I think one feature will help our users lot, which is search field in our Options panel. Like following : 
<a href="http://theme-fusion.com/wp-content/uploads/2016/02/fusion_theme_options_search.jpg" target="_blank"><img src="http://theme-fusion.com/wp-content/uploads/2016/02/fusion_theme_options_search.jpg" alt="search field" /></a>

Just thought about, nice to have that option for our users! :)

**Comment by Codevz** [comment]
Hi @Ansif 

Add this custom jquery code to cs-framework.js or your own custom-js file: 

```Javascript
  jQuery('<input id="searchbox" type="text" placeholder="Search" />').insertAfter('.cs-header h1');
  jQuery('#searchbox').css('margin-left', '30px');
  jQuery.expr[':'].Contains = function(a, i, m) {
    return jQuery(a).text().toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
  };
  
  jQuery('#searchbox').on('keyup', function() {
    var w = jQuery(this).val();
    if (w) {
      jQuery('.cs-body').addClass('cs-show-all');
      jQuery('.cs-title h4').closest('.cs-element').hide();
      jQuery('.cs-title h4:Contains('+w+')').closest('.cs-element').show();
    } else {
      jQuery('.cs-body').removeClass('cs-show-all');
      jQuery('.cs-title h4').closest('.cs-element').show();
    }
  });
```

**Comment by Codestar** [comment]
@Codevz Awesome!

Also i noted this, It will come as feature in the future :+1:

**Comment by Codevz** [comment]
@Codestar Great, Thanks man :smiley: Best Wishes :)

**Comment by Ansif** [comment]
Thanks a lot mate! :) @Codevz and @Codestar! You both guys are code geeks! :100: :)

**Comment by Codestar** [comment]
Cheers :smiley: :+1:

**Comment by WPsmart** [comment]
Thanks Very much For this option :+1:

**Comment by JoeSz** [comment]
"I had a following problem with the search solution: after a search, the dependencies stopped working."
Please see #464 for a possible solution.
