### ISSUE TITLE
Theme Check Error

### ISSUE THREAD

**Issue by shopnilsazal** [Codestar/codestar-framework#227]
REQUIRED: /cs-framework/classes/framework.class.php. Themes should use add_theme_page() for adding admin pages.
`Line 319: if( $args['menu_type'] == 'add_submenu_page' ) {`

**Comment by Codestar** [comment]
Still waiting any idea :+1:

**Comment by Codestar** [comment]
Hi,

I found an idea for this issue. this problem fixed in version 1.0.1 new usage is:

```php
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>',
);
```

```php
// whats changes
$settings           = array(
  'menu_type' => 'add_menu_page', // before
  'menu_type' => 'menu', // after
);
```

@Codevz @NoahjChampion @devariya

**Comment by NoahjChampion** [comment]
@Codestar I'm sure it is good but I don't understand. 

Can you write.. 

Top Menu Example...

Submenu Example (by slug)

**Comment by Codevz** [comment]
@NoahjChampion as i checked: 

```PHP
// Top level Menu
$settings = array(
   'menu_title'   =>  'Theme Options',
   'menu_type'  => 'menu',
   'menu_slug'  => 'theme_options',
);

// child of another menu in wordpress
$settings = array(
   'menu_title'   =>  'Theme Options',
   'menu_type'  => 'theme', // You can change this to your parent
   'menu_slug'  => 'theme_options',
);

// child of another by parent name
$settings = array(
   'menu_title'   =>  'Theme Options',
   'menu_type'     => 'submenu', // <-------
   'menu_parent'  => 'your_parent_slug', // <-------
   'menu_slug'      => 'theme_options',
);
```

**Comment by NoahjChampion** [comment]
@Codevz Thanks. 

I got it. I thought @Codestar maybe removed `menu_parent`, so I wasn't sure how that worked. But I see it is still there, so I understand now. Thanks. 

@Codevz please check out This New Field Type > #272 and leave any comments/feedback you have/can add if you see something missing.

**Comment by Codestar** [comment]
@Codevz you are man! thanks for explain. also i added your tips on documentation http://codestarframework.com/documentation/#framework-configure :100:

**Comment by Codevz** [comment]
@NoahjChampion You're welcome :smiley: @Codestar You are Hero :+1:

**Comment by Codestar** [comment]
Cheers :+1:
