### ISSUE TITLE
how to create custom field, for selecting all kinds of  media files, including docs and pdfs?

### ISSUE THREAD

**Issue by dahituc** [Codestar/codestar-framework#228]
I need to create a custom field for selecting files, can be images, docs, pdf or pptx, etc.
 Using the code of upload and image, I can create the required field, but how to write the jquery for that?

**Comment by Codevz** [comment]
Hi, 

If you need upload type settings check here: https://github.com/Codestar/codestar-framework/issues/100

Regards

**Comment by Codestar** [comment]
Follow @Codevz
