### ISSUE TITLE
Demo importer created with support CS Framework

### ISSUE THREAD

**Issue by AminulBD** [Codestar/codestar-framework#229]
I created a demo importer / quick installer with support codestar framework support.

Repo Link: https://github.com/AminulBD/dt-demo-importer

I think this is useful, you guys please fork and send pull request :)

Thanks!

**Comment by Codestar** [comment]
Hi,

Wow, it is great. i am so happy :wink: It will be helpful for codestar framework users.  :+1: :100: 

Regards, Codestar

**Comment by Ansif** [comment]
Wow! :) You made it!!

This is awesome! :+1: :100:

**Comment by channelriyas** [comment]
Thanks dude, really nice, this is what I am searching, you made with CS !
Good luck with Widget import ;)

**Comment by AminulBD** [comment]
@channelriyas Yes, I'm working on it. Thank you guys :)
