### ISSUE TITLE
Lack of description on Hooks and Actions in documentation

### ISSUE THREAD

**Issue by Pb164** [Codestar/codestar-framework#23]
Hello!

How to initialize actions by framework options? 

For example I need to register an sidebar by checking a "checkbox" in themes options page made with codestar framework. So i have an action code, how to start that code? If i put action code in functions.php file, the code runs as soon as i save the file. I want to run that code only after theme options are changed.

**Comment by Codestar** [comment]
Hi,

You can check spesific option change or not:

```php
if( ! function_exists( 'check_for_option_changed' ) ) {
  function check_for_option_changed( $request, $instance ) {

    // Set option key, which option will control ?
    $opt_key = 'any-option-id';

    // The saved options from framework instance
    $options = $instance->options;

    // Checking the option-key change or not.
    if ( isset( $options[$opt_key] ) && isset( $request[$opt_key] ) && ( $options[$opt_key] !== $request[$opt_key] ) ) {
      // Do stuff
    }

  }
  add_action( 'csf_PREFIX_FRAMEWORK_ID_save_before', 'check_for_option_changed', 10, 2 );
}
```

And multiple options check:

```php
if( ! function_exists( 'check_for_option_changed' ) ) {
  function check_for_option_changed( $request, $instance ) {

    // Set option keys, which options will control ?
    $opt_keys = array( 'opt-id-1', 'opt-id-2' );

    // The saved options from framework instance
    $options = $instance->options;

    $changed = false;

    // Checking the option keys change or not.
    foreach( $opt_keys as $key ) {

      if ( isset( $options[$key] ) && isset( $request[$key] ) && ( $options[$key] !== $request[$key] ) ) {

        $changed = true;

      }

    }

    if( $changed ) {
      // Do stuff
    }

  }
  add_action( 'csf_PREFIX_FRAMEWORK_ID_save_before', 'check_for_option_changed', 10, 2 );
}
```

Have a nice day.

Regards, Codestar

**Comment by Pb164** [comment]
Thanks alot! Same to you, have a nice day! ;)

**Comment by Codestar** [comment]
You're welcome ;)

**Comment by Pb164** [comment]
Hey! I got some question again.. 

Is --- $opt_key = 'any-option-id'; ---- this means the option of the framework or the option of single field?

If i have an array of checkbox values, what should i check to? 

So i have an option in framework options:
array(
	'id'         => 'sidebar_control',
	'type'       => 'checkbox',
	'title'      => 'Checkboxes',
	'options'    => array(
		'option-1' => 'sidebar1',
		'option-2' => 'sidebar2',
		'option-3' => 'sidebar3',
		'option-4' => 'sidebar4'
	),
		'default'    => array( 'option-1', 'option-3' )
),

How to check a single checkbox? IE i need to run register sidebar code when checked related checkbox.

**Comment by Pb164** [comment]
Please be patient, im trying to learn how works your framework. And trying to figure out is it possible to use it in my projects, this will give you some purchases ;)

**Comment by Codestar** [comment]
Hi,

Oh no problem, Generally I am helping for custom questions. Yes it is option id. You shoud to set:

`$opt_key = 'sidebar_control'`

Try and see the result.

Regards, Codestar

**Comment by Pb164** [comment]
Hello again, thanks for advice... but

not working... Well I dont understand the full way of actions combined together.

Here what i do:

1. in 'functions.php' there is a code (i planned more than 2 sidebars, but for example there are 2):

```
add_action( 'widgets_init', 'my_sidebars' );
function my_sidebars() {
	register_sidebar(
		array(
			'id'            => 'content_top',
			'name'          => __( 'Top panel' ),
			'description'   => __( 'Text label' ),
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widget-title">',
			'after_title'   => '</h3>',
		)
	);

	register_sidebar(
		array(
			'id'            => 'content_bot',
			'name'          => __( 'Bot panel' ),
			'description'   => __( 'Text label' ),
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget'  => '</div>',
			'before_title'  => '<h3 class="widget-title">',
			'after_title'   => '</h3>',
		)
	);
}
```
2. Later in 'functions.php' there is a code (there are checkboxes for 4 sidebars):

```
array(
'id' => 'sidebar_control',
'type' => 'checkbox',
'title' => 'Checkboxes',
'options' => array(
'option-1' => 'sidebar1',
'option-2' => 'sidebar2',
'option-3' => 'sidebar3',
'option-4' => 'sidebar4'
),
'default' => array( 'option-1', 'option-3' )
)
```
So You can see that all my sidebars are should appear on a checked option of ONE options field. There are more than one condition, so cant be working "on change", because there can be many ways of changes. How does code get what kind of changes were done? For example there are default options are ON. And there are should be run code for those 2 sidebars. If i do check another checkbox there should work another code to register additional sidebar.

**Comment by Codestar** [comment]
Hi,

I think there is a misunderstanding, You said `I want to run that code only after theme options are changed.` I was think you will create a CACHE system and want to control spesific option change or not.

But you do not need to check spesific option control for manage widget sidebars area. My opinion is:

```php
// Config
array(
  'id'      => 'sidebar_control',
  'type'    => 'checkbox',
  'title'   => 'Checkboxes',
  'options' => array(
    'content_top' => __( 'Top panel' ),
    'content_bot' => __( 'Bot Panel' ),
    'content_cen' => __( 'Center Panel' ),
  ),
  'default' => array( 'content_top' )
)
```
```php
// Widget Register
add_action( 'widgets_init', 'my_sidebars' );
function my_sidebars() {

  $options = get_option( 'FRAMEWORK_PREFIX' );

  if( ! empty( $options['sidebar_control'] ) ) {
    foreach( $options['sidebar_control'] as $id => $name ) {
      register_sidebar(
        array(
          'id'            => $id,
          'name'          => $name,
          'description'   => __( 'Add widgets here to appear in sidebar.' ),
          'before_widget' => '<div id="%1$s" class="widget %2$s">',
          'after_widget'  => '</div>',
          'before_title'  => '<h3 class="widget-title">',
          'after_title'   => '</h3>',
        )
      );
    }
  }

}
```

I didn't test, but I think it will work. Said as me, You do not need any hooks and action for this, why you started to topic about hooks and action, That is why we confused :) ?

Regards, codestar

**Comment by Pb164** [comment]
Hello! Thanks! Works as it should! I think i will purchase framework some time later ;)

So.. is it possible to use a Repeater field to scale amount of Checkboxes for sidebar?
By default there will be 4 sidebars.. and if admin needs he presses repeater button and it will add another checkbox which could be checked for additional sidebar?

**Comment by Pb164** [comment]
Im just learning PHP and other stuff.. so dont be angry :D

**Comment by Codestar** [comment]
Hi,

No angry, I'm giving support always :) Also If you remember, this project was open-source/free 1 years ago. No problem, when you have money you can purchase pro version.

Ok, Let's come back question. Why you do not using repeater/group field for create sidebars ? Usually developers are using that way. For eg:

```php
// Config
array(
  'id'     => 'sidebars',
  'type'   => 'group',
  'title'  => 'Create Sidebar',
  'button_title'  => 'Add new sidebar',
  'fields' => array(
    array(
      'id'    => 'name',
      'type'  => 'text',
      'title' => 'Sidebar Title',
    ),
  ),
  'default' => array(
    array(
      'name' => 'Top Sidebar'
    ),
    array(
      'name' => 'Bottom Sidebar'
    ),
  )
),
```

```php
// Widget Register
add_action( 'widgets_init', 'my_sidebars' );
function my_sidebars() {

  $options = get_option( 'FRAMEWORK_PREFIX' );

  if( ! empty( $options['sidebars'] ) ) {
    foreach( $options['sidebars'] as $sidebar ) {
      register_sidebar(
        array(
          'id'            => sanitize_title( $sidebar['name'] ),
          'name'          => $sidebar['name'],
          'description'   => __( 'Add widgets here to appear in sidebar.' ),
          'before_widget' => '<div id="%1$s" class="widget %2$s">',
          'after_widget'  => '</div>',
          'before_title'  => '<h3 class="widget-title">',
          'after_title'   => '</h3>',
        )
      );
    }
  }

}
```

But If still you want to scale amount of Checkboxes. Its possible:

```php
// Config
array(
  'id'      => 'sidebar_control',
  'type'    => 'checkbox',
  'title'   => 'Checkboxes',
  'options' => 'get_the_sidebars', // custom function for merge sidebars
  'default' => array( 'content_top' )
)

array(
  'id'     => 'custom_sidebars',
  'type'   => 'group',
  'title'  => 'Custom Sidebars',
  'button_title'  => 'Add new sidebar',
  'fields' => array(
    array(
      'id'    => 'name',
      'type'  => 'text',
      'title' => 'Sidebar Title',
    ),
  ),
),
```

```php
// Helper function for merge pre-defined sidebars and custom sidebars
function get_the_sidebars() {

  // Predefined Sidebars
  $sidebars = array(
    'content_top' => __( 'Top panel' ),
    'content_bot' => __( 'Bot Panel' ),
  );

  $options = get_option( 'FRAMEWORK_PREFIX' );

  // Merge Custom Sidebars
  if( ! empty( $options['custom_sidebars'] ) ) {
    foreach( $options['custom_sidebars'] as $name ) {
      $sidebars[ sanitize_title( $name ) ] = $name;
    }
  }

  return $sidebars;

}
```

Btw, I advise to turn off save ajax feature. because page need to refresh for re-count custom sidebars.

```php
CSF::createOptions( $prefix, array(
  'menu_title' => 'CSF Demo',
  'menu_slug'  => 'csf-demo',
  'save_ajax'  => false, // turn off save ajax
) );
```

Regards, Codestar

**Comment by Pb164** [comment]
Thanks for your help! =) Ill be back some time later!

**Comment by Pb164** [comment]
Hey mate!

I got a question about frontend check of options:

```
array(
'id' => 'sidebar_control',
'type' => 'checkbox',
'title' => 'Checkboxes',
'options' => array(
'option-1' => 'sidebar1',
'option-2' => 'sidebar2',
'option-3' => 'sidebar3',
'option-4' => 'sidebar4'
),
'default' => array( 'option-1', 'option-3' )
)
```
How to check in frontend that enabled any of sidebars?
That needed to hide blocks of custom sidebars templates. I have tried like this:
```
<?php if ( isset( $options['sidebar_control']['content_right']) ) : ?>
	<div id="content-right" class="sidebar order-6 col-md-3">
		<?php dynamic_sidebar( 'content_right' ); ?>
	</div><!-- #content-right -->
<?php endif ?>	
```

**Comment by Pb164** [comment]
Hello there! One more question... 

I need another $name of sidebars, different than $id of the option.

`foreach( $options['sidebar_control'] as $id => $name )`

Here ^^name of the sidebar is getting the ID of the option, and that is not good, better to place a NAME of the option there, is it possible? I need that to get good looking names of the sidebars instead of "content_top" or "content_bot" etc. 
How to get values of those options, instead of IDs?
```
array(
	'id'         => 'sidebar_control',
	'type'       => 'checkbox',
	'title'      => __( 'Включить панели' ),
	'options'    => array(
		'content_top' => __( 'Панель над контентом' ),
		'content_bot' => __( 'Панель под контентом' ),
		'content_left' => __( 'Панель слева' ),
		'content_right' => __( 'Панель справа' )
	),
	'default'    => array( 'content_right', 'content_top' )
),
```
Other questions i have solved, so deleted some comments.

**Comment by Pb164** [comment]
Oh :) the 1st question is done.. i have used the code that you provide with repeating.

so i need only frontend checking. 
Thanks again for helping

**Comment by Codestar** [comment]
Hi,

Sorry for delay, i was sick a little.. (cold-flu)

Hmm, it is not possible. because the array system only supports `key => value` no more.

Regards, Codestar

**Comment by Pb164** [comment]
Here is the book 'Learning PHP, MySQL & JavaScript'

Year: 2018 
Author: Robin Nixon
Edition: 5th 
Language: english 
Pages: 700 
ISBN 10: 1491979070 
ISBN 13: 9781491979075 
File: EPUB, 12.43 MB

https://mega.nz/#!S75G0CRY!MJbjnxY-NJfxfdK-BvnwyqUOZ3aj_Pc5ZxPvyEM7EQU

there is something you should read, maybe it will give you some more ideas, Chapter 6. PHP Arrays:

"The second half assigns associative identifiers and accompanying longer product descriptions to the array $p2 using the format key => value. The use of => is similar to the regular = assignment operator, except that you are assigning a value to an index and not to a variable."

So if you will use '=' instead of '=>', then you can use a single string of array as variable (even array variable) so can get data from it similar to arrays.

Regards, and dont get sick :D

**Comment by Codestar** [comment]
Hi,

Uh, Actually everything is possible in programming language :smile:  For eg. this is possible:

```php
array(
  'id'      => 'sidebar_control',
  'type'    => 'checkbox',
  'title'   => __( 'Включить панели' ),
  'options' => array(
    'content_top' => array(
      'id'        => 'id_of_sidebar',
      'title'     => 'Title of Sidebar'
    ),
    'content_bot' => array(
      'id'        => 'id_of_sidebar',
      'title'     => 'Title of Sidebar'
    ),
  ),
),
```
But, The **checkbox** field **doesn't** support this nested array type. That is why I wrote "it is not possible". 

Regards, No problem :)

**Comment by Pb164** [comment]
Hey! So if i will use grop of 'switcher' fields instead of checkboxes? I have added it, but cant understand how to spread data to widget area generator snippet.

```
//
// Управление панелями
array(
	'id'        	=> 'sidebars_control',
	'type'      	=> 'fieldset',
	'title'     	=> __( 'Enable sidebars', 'my_options' ),
	'fields'    	=> array(
		array(
			'id'    => 'content_tops',
			'type'  => 'switcher',
			'text_on'  => __( 'Yes', 'my_options' ),
			'text_off' => __( 'No', 'my_options' ),
			'title' => 'Top sidebar' // or __( 'Top sidebar', 'my_options' ),
		),
		array(
			'id'    => 'content_bots',
			'type'  => 'switcher',
			'text_on'  => __( 'Yes', 'my_options' ),
			'text_off' => __( 'No', 'my_options' ),
			'title' => 'Bottom sidebar' // or __( 'Bottom sidebar', 'my_options' ),
		),
		array(
			'id'    => 'content_lefts',
			'type'  => 'switcher',
			'text_on'  => __( 'Yes', 'my_options' ),
			'text_off' => __( 'No', 'my_options' ),
			'title' => 'Right sidebar' //__( 'Right sidebar', 'my_options' ),
		),
		array(
			'id'    => 'content_rights',
			'type'  => 'switcher',
			'text_on'  => __( 'Yes', 'my_options' ),
			'text_off' => __( 'No', 'my_options' ),
			'title' => 'Left sidebar' //__( 'Left sidebar', 'my_options' ),
		),
	),
	'default'		=> array(
		'content_lefts'	=> false,
		'content_rights' => false,
		'content_tops'	=> false,
		'content_bots'	=> false,
	),
),
```
So how do i get those data to ID or TITLE of sidebar? Its my lack of PHP knowledge, i have tried many ways but...
