### ISSUE TITLE
Req: Add preview for upload option

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#232]
Hi, 

Could you please for next update add preview image for upload option type, like upload_image and gallery.
ex: https://drive.google.com/file/d/0B7q-ingsr5hKWnVZY3VkZXpJYVU/view?usp=drivesdk

I added it to cs-framework.js but i'm sure its not right way. 
i needed for image and audio and this code works.

```javascript
var ext = attachment.attributes.url.split('.').pop();
if ( ext === 'mp3' ) {
   $this.find('.cs-fieldset').prepend('<div style="width: 200px;margin-bottom:20px"><audio controls><source src="'+ attachment.attributes.url + '" type="audio/mpeg"></audio></div>');
} else {
   $this.find('.cs-fieldset').prepend('<div style="width: 200px;margin-bottom:20px"><img src="'+ attachment.attributes.url + '" /></div>');
}
```

Thanks :)

**Comment by Codestar** [comment]
Hi,

Also this feature :) yes it is nice... some users was ask this feature. i will add it :wink: Right now, i am developing a new theme, when i finish it, i will add a lot of new features :+1: 

Regards, Codestar

**Comment by Codevz** [comment]
Thank man ;) I wish your new theme sells a lot :smiley:

**Comment by Codestar** [comment]
Thank you :smile:
