### ISSUE TITLE
Change switcher label

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#233]
Is there any way to change switcher on/off label?

**Comment by Ansif** [comment]
Hi,

You can change the On and Off text at : [switcher.php](https://github.com/Codestar/codestar-framework/blob/master/fields/switcher/switcher.php#L20) file.

In that line you can see : 
<pre>
&lt;em data-on=&quot;'. __( 'on', 'cs-framework' ) .'&quot; data-off=&quot;'. __( 'off', 'cs-framework' ) .'&quot;&gt;&lt;/em&gt;
</pre>

Change your text there. And replace that file in your own folder of your theme. Check out override file method here : http://codestarframework.com/documentation/#override-configure

:+1:

**Comment by Codestar** [comment]
Yep, follow @Ansif

**Comment by kingRayhan** [comment]
Is there any way to change a specific field's switcher label ?

**Comment by Ansif** [comment]
Yes, you can do that by following changes in switcher.php file.

Check here : https://gist.github.com/Ansif/e101d08fa38cfa0e0ad5

**Comment by kingRayhan** [comment]
hey @Ansif 
I think this will change whole switcher labels

**Comment by Ansif** [comment]
No, it'll not!! I checked!

Don't think just see what's inside of it! :)

**Comment by kingRayhan** [comment]
Suppose I want just to change this filed's switcher label

```php
array(
  'id'    => 'sample_field',
  'type'  => 'switcher',
  'title' => __('On/Off Texts', 'text_domain'),
  'on_text' => __('Tru', 'text_domain'),
  'off_text' => __('Fal', 'text_domain'),
),
```

Can you help me for changing the label of containing id `sample_field` ?

**Comment by kingRayhan** [comment]
Wow it worked :heart_eyes:

Thanks @Ansif 
That was my need

**Comment by kingRayhan** [comment]
@Codestar 
I think it will be great if you modify [switcher.php](https://github.com/Codestar/codestar-framework/blob/master/fields/switcher/switcher.php) file according to @Ansif idea

**Comment by Ansif** [comment]
@kingRayhan, No - This is your own custom changes.

If we followed this way for all other fields in codestar, that makes lots and lots of attributes. That's not a user friendly i think.

So, keeping framework minimal and more functional is must. I think currently code star is followed that way :100: 

:+1:

**Comment by kingRayhan** [comment]
OK :smile: 
Can you give me a code snippet for adding jquery ui time picker ?

**Comment by Ansif** [comment]
You can integrate jQuery UI Time Picker plugin using following script : https://fgelinas.com/code/timepicker/

Also, you've to write some php code for that! :smile: 

:+1:

**Comment by Codestar** [comment]
Hi guys,

Yes as said @Ansif it is a  custom changes. There is a lot of attributes for fields.

@kingRayhan time picker will come ASAP :+1:
