### ISSUE TITLE
Improve group option

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#234]
Hi, 

Please add this to next update for live update accordion title:

``` javascript
field_groups.on('input', '#acc_title', function(e) {
      var $this = $(this),
          val   = $(this).val(),
          title = $(this).closest('.cs-group').find('.cs-group-title');

      title.html('<span class="ui-accordion-header-icon ui-icon dashicons dashicons-arrow-right"></span> '+val);
});
```

Of course group option title should be does specific id attribute.

Regards

**Comment by Codevz** [comment]
Another idea, please add remove button for group like this: https://drive.google.com/file/d/0B7q-ingsr5hKMVltd3pwSkFYNjg/view?usp=drivesdk

**Comment by Codestar** [comment]
Hi,

Wow bro, that is great ideas really, when i have free-time, i will add it surely. i liked it :+1: :100: it is looking useful :wink: 

Regards, Codestar

**Comment by Codevz** [comment]
Thanks a lot man :dancer:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by Codevz** [comment]
Hi @Codestar 

I have another idea for group option, I have multiple options under group fields and some of them haven't title and another option should be set as title, So it will great if we can set other options as accordion title, I edited group field with adding this code to Line 55: 

```PHP
$title = ( ! $title && !empty( $this->value[ $key ]['ANOTHER_ID'] ) ) ? $this->value[ $key ]['ANOTHER_ID'] : $title;
```

Also if another option ID is post id you can use this: 

```PHP
$title = ( ! $title && !empty( $this->value[ $key ]['ANOTHER_ID'] ) ) ? get_the_title( $this->value[ $key ]['ANOTHER_ID'] ) : $title;
```

Regards

**Comment by Codestar** [comment]
Hi,

Yes it sounds good, but can you explain it more ? where will come ANOTHER_ID from config array? can you write some config example about this ? :+1:  :wink:

**Comment by Codevz** [comment]
@Codestar ANOTHER_ID is another option id within group, For example if we does two options within group, first is title second is song name, then when title value is empty and options saved, accordion title will be song name instead of title field value. 

Now group option does 

`'accordion_title' => 'title',`

It will be good if accordion_title be array, then we can add another option id

`'accordion_title' => array( 'title', 'song' ), `

I hope this show you whats my mean: https://drive.google.com/file/d/0B7q-ingsr5hKRXhGRU53R2RjbGM/view

**Comment by Codestar** [comment]
@Codevz Thanks, now i understand it. Yes it is good idea. 

```php
'accordion_title' => array( 'title', 'song' ), // two field, if "title" empty, it will check "song"
```

Great, i will try to add it asap. Also i need it. sometimes first option can be empty. we need to check second one. it is like a fallback for title :+1:

**Comment by Codevz** [comment]
@Codestar Thanks man :heart:

**Comment by Codestar** [comment]
Cheers :+1:

**Comment by Codevz** [comment]
Hey @Codestar 

How are you ? ;)

Here is clone button for each group: 
```javascript
      $( '.cs-group', _this ).each(function(){
        $( this ).prepend( '<a href="#" title="Clone this" class="clone-group" style="position: absolute;right: 20px;top: 15px;z-index: 2;"><i class="fa fa-clone"></i></a>' );
      });
      $( document ).on({
        click: function(e) {

          var clone_this = $( this ).closest('.cs-group').clone();
          e.preventDefault();

          clone_this.find('input, select, textarea').each( function () {
            this.name = this.name.replace(/\[(\d+)\]/,function(string, id) {
              return '[' + (parseInt(id,10)+1) + ']';
            });
          });

          var cloned = clone_this.clone();
          field_groups.append( cloned );

          if ( accordion_group.length ) {
            field_groups.accordion('refresh');
            field_groups.accordion({ active: cloned.index() });
          }

          field_groups.find('input, select, textarea').each( function () {
            this.name = this.name.replace('[_nonce]', '');
          });

          // run all field plugins
          cloned.CSFRAMEWORK_DEPENDENCY( 'sub' );
          cloned.CSFRAMEWORK_RELOAD_PLUGINS();

          i++;
        }
      }, '.clone-group' );
```
Let me know what you think about it ;)

Please do not forget to move remove button to head of each group for next update,  i think this is really important, because for example if user have 20 group and need to remove all, should open each group and remove and ... repeat

Thanks

**Comment by Codevz** [comment]
Following previous comment, for remove icon: 

```javascript
      $( '.cs-group', _this ).each(function(){
        $( this ).prepend( '<a href="#" title="Clone this" class="clone-group" style="position: absolute;right: 40px;top: 15px;z-index: 2;"><i class="fa fa-clone"></i></a>' );
        $( this ).prepend( '<a href="#" title="Remove this" class="cs-remove-group" style="position: absolute;right: 20px;top: 15px;z-index: 2;"><i class="fa fa-remove"></i></a>' );
      });
```

**Comment by Codevz** [comment]
@Codestar :walking:

**Comment by Codestar** [comment]
Ops, I just back from festival and I was forget this request. thanks for message :smile: I will re-open and add this feature asap. :+1: 

Also i tested it, and working perfectly. :wink:

**Comment by kenthd** [comment]
@Codevz hey, how are you? 

Your code working perfect. But now I 'm found some errors. Hope you can review and fix it.
If I wrote the group in the group, it will happen when i click " Add New ", it not work good.

Here is my code:

```
array(
    'name'   => 'what_news_section',
    'title'  => esc_html__( "What's new", 'codestart' ),
    'fields' => array(
        array(
            'id'              => 'what_new',
            'type'            => 'group',
            'title'           => '',
            'button_title'    => esc_html__( 'Add New', 'codestart' ),
            'accordion_title' => 'what_new',
            'fields'          => array(
                array(
                    'id'            => 'new_content',
                    'type'          => 'textarea',
                    'title'         => esc_html__( 'Content', 'codestart' ),
                    'attributes'    => array(
                        'placeholder' => 'Do stuff',
                        'rows'        => 20,
                    ),
                ),
                array(
                    'id'              => 'what_new1',
                    'type'            => 'group',
                    'title'           => '',
                    'button_title'    => esc_html__( 'Add New', 'codestart' ),
                    'accordion_title' => 'what_new',
                    'fields'          => array(
                        array(
                            'id'            => 'new_content1',
                            'type'          => 'textarea',
                            'title'         => esc_html__( 'Content', 'codestart' ),
                            'attributes'    => array(
                                'placeholder' => 'Do stuff',
                                'rows'        => 20,
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
),
```

Thanks and best regards

**Comment by Codevz** [comment]
@kenthd Thanks :smiley: about 6 month ago i asked this question from codestar and he said its not possbile to add group inside group https://github.com/Codestar/codestar-framework/issues/201

**Comment by ujbeszel** [comment]
```javascript
      field_groups.on('input', '.cs-fieldset input', function(e) {
        var $this = $(this),
            val   = $(this).val(),
            group_title = $(this).closest('.cs-group').find('.cs-group-title'),
            title = $(this).closest('.cs-group').find('.cs-title h4').html();
        group_title.html('<span class="ui-accordion-header-icon ui-icon dashicons dashicons-arrow-right"></span> '+title+': '+val);
      });
```
A little improvement for the live title

**Comment by Codestar** [comment]
@ujbeszel thanks for improve :+1:

**Comment by Codestar** [comment]
Added this feature in v2 soon.

![support_20160817113249](https://cloud.githubusercontent.com/assets/1313301/17729817/a180dd90-646e-11e6-9e6a-9b300b4ba473.gif)

**Comment by JoeSz** [comment]
My last post has an error. If I add multiple text field, then the title change will apply on any input change.
So here is the updated code, this will monitoring only the first input fied.

```javascript
      field_groups.find('.cs-fieldset').first().on('input', 'input', function(e) {
        var $this = $(this),
            val   = $(this).val(),
            group_title = $(this).closest('.cs-group').find('.cs-group-title'),
            title = $(this).closest('.cs-group').find('.cs-title h4').html();
        group_title.html('<span class="ui-accordion-header-icon ui-icon dashicons dashicons-arrow-right"></span> '+title+': '+val);
      });
```

**Comment by Codestar** [comment]
Thanks for the code @JoeSz :+1:
