### ISSUE TITLE
Save fieldset children separately

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#235]
Hi, 

Is there anyway ? or could you please for next update add new parameter to fieldset option for removing array save then fieldset child options will save like other options.

Actually i'm looking something like grouping some options view: https://drive.google.com/file/d/0B7q-ingsr5hKbTdGeldiS0pkSE0/view

Thanks

**Comment by Codestar** [comment]
Hi,

hmmm, it is not possible, because there is can be conflict with other options? you know all option fields needed unique id. actually it is possible but required a lot of modifications. :smiley:

**Comment by Codestar** [comment]
Actually, issue is this [fieldset.php#L25](https://github.com/Codestar/codestar-framework/blob/master/fields/fieldset/fieldset.php#L25) field value getting by field id... i can not imagine, how we can get value easyly.

**Comment by Codevz** [comment]
Dear @Codestar Thanks for your attention and time.
I think i found it: 

`
echo cs_add_element( $field, cs_get_option( $field_id ), $this->unique );
`

What do you think ? :smiley:

**Comment by Codevz** [comment]
For net update it would be great if we have new parameter for set which fieldset save array or separately, eg.

```PHP
if ( isset( $this->field['as_array'] ) ) {
    echo cs_add_element( $field, cs_get_option( $field_id ), $this->unique );
} else {
    echo cs_add_element( $field, $field_value, $unique_id );
}
```

**Comment by Codestar** [comment]
Yeah, great idea. why not ? and i added it now. 450b6030328802b821194eaedb8730f09a13b98a

btw, i modifyed it so:

```php
// "un_array" because, before this modification all users using un array version.
// we can not change it directly. because when update framework, there will be issue.
// i think you understand what i mean :)
if ( ! empty( $this->field['un_array'] ) ) {
  echo cs_add_element( $field, cs_get_option( $field_id ), $this->unique );
} else {
  echo cs_add_element( $field, $field_value, $unique_id );
}
```

**Comment by Codevz** [comment]
You're right, this much better, we do not lose other fieldsets array.
Thanks a lot :+1: :100:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by NoahjChampion** [comment]
@Codestar @Codevz 

Does this mean that my fields can have the same id's as long as they belong to a unique fieldset id?

Example... 

```
<?php

// Fieldset
array(
	'type' => 'fieldset',
	'id' => 'Unique_Fieldset_ID_1',
	'fields' => array(
		// Horizontal Color Picker (Heading 1)
		array(
			'type' => 'color_picker',
			'title' => 'Heading 1',
			'id' => 'Heading_1',
		),
		// Horizontal Color Picker (Heading 2)
		array(
			'type' => 'color_picker',
			'title' => 'Heading 2',
			'id' => 'Heading_2',
		),
	),
),
// Fieldset
array(
	'type' => 'fieldset',
	'id' => 'Unique_Fieldset_ID_2',
	'fields' => array(
		// Horizontal Color Picker (Heading 1)
		array(
			'type' => 'color_picker',
			'title' => 'Heading 1',
			'id' => 'Heading_1', // ID can be the same because it belongs to a unique fieldset id?
		),
		// Horizontal Color Picker (Heading 2)
		array(
			'type' => 'color_picker',
			'title' => 'Heading 2',
			'id' => 'Heading_2',  // ID can be the same because it belongs to a unique fieldset id?
		),
	),
),

?>

```

**Comment by Codestar** [comment]
We added a option for unique id operation... let me explain it on a example. for eg. in your example config usage.

```php
// default usage
$options = cs_get_option( 'Unique_Fieldset_ID_1' );
$head_1 = $options['Unique_Fieldset_ID_1']['Heading_1'];
$head_2 = $options['Unique_Fieldset_ID_1']['Heading_2'];
```

And let's see new feature `un_array`

```php
array(
  'type'     => 'fieldset',
  'id'       => 'Unique_Fieldset_ID_1',
  'un_array' => true, // new feature is this
  'fields'   => array(
    array(
    'type'   => 'color_picker',
    'title'  => 'Heading 1',
    'id'     => 'Heading_1',
    ),
    array(
    'type'   => 'color_picker',
    'title'  => 'Heading 2',
    'id'     => 'Heading_2',
    ),
  ),
),

// and usage here.
$head_1 = cs_get_option( 'Heading_1' );
$head_2 = cs_get_option( 'Heading_2' );
```

but do not forget to conflict with another ids. i mean you can not use same ID for another fields.

**Comment by NoahjChampion** [comment]
Ok. 

So in default usage as you explained, can I do...

```
$options_1 = cs_get_option( 'Unique_Fieldset_ID_1' );
$head_1 = $options['Unique_Fieldset_ID_1']['Heading_1'];
$head_2 = $options['Unique_Fieldset_ID_1']['Heading_2'];

$options_2 = cs_get_option( 'Unique_Fieldset_ID_2' );
$head_3 = $options['Unique_Fieldset_ID_2']['Heading_1'];
$head_4 = $options['Unique_Fieldset_ID_2']['Heading_2'];
```

In this case does` ['Heading_1']` and `['Heading_2']` **_ALWAYS_** have to be unique? 

I was hoping that access by a unique fieldset ID would allow common id's if they belong to a unique fieldset id. But maybe that is not possible? It would make it easier because the options values could be the same, if they belong to a unique fieldset id. Then I could copy/paste more and only have to change the fieldset id.

**Comment by Codevz** [comment]
@NoahjChampion When you've set 

`'un_array' => true`

So, children of fieldset will save separetely and usage will be like this: 

```
echo cs_get_option( 'Heading_1' );
echo cs_get_option( 'Heading_2' );
```

**Comment by NoahjChampion** [comment]
@Codevz Thanks. I'm still a little confused (haha), but let me try the un_array and look at the database, then I think I will better understand what you mean, if you mean what I think you mean.

**Comment by NoahjChampion** [comment]
@Codevz 

Okay. Correct me if I am wrong. I think got it after testing `un_array` true and false. 

`un_array` means you can call fieldset children with out the fieldset id, correct? 

For example... 

If `'un_array' => 'true'` 

we don't need `$head_1 = $options['Unique_Fieldset_ID_1']['Heading_1'];`

We can use instead `cs_get_option( 'Heading_1' );`

as if it were not part of a fieldset?

**Comment by Codevz** [comment]
@NoahjChampion Yes exactly :+1:

**Comment by NoahjChampion** [comment]
@Codevz Thanks! Appreciate it.
