### ISSUE TITLE
Remove Add media button from Wysiwyg editor

### ISSUE THREAD

**Issue by kingRayhan** [Codestar/codestar-framework#237]
![](http://i.imgur.com/Qb6S5Pr.png)
Is there any way to remove `Add Media` button from a specific field id's Wysiwyg editor?

**Comment by Codestar** [comment]
Yes it is possible, see example:

```php
array(
  'id'       => 'wysiwyg_2',
  'type'     => 'wysiwyg',
  'title'    => 'Wysiwyg with Custom Settings',
  'settings' => array(
    // 'textarea_rows' => 5,
    // 'tinymce'       => false,
    'media_buttons' => false,
  )
),
```

and you can see all settings options from https://codex.wordpress.org/Function_Reference/wp_editor#Arguments

**Comment by kingRayhan** [comment]
wow Thanks :smile_cat:

**Comment by Codestar** [comment]
Cheers! :+1:
