### ISSUE TITLE
How to list custom post types in drop down list

### ISSUE THREAD

**Issue by dmsumon** [Codestar/codestar-framework#238]
To list all the "pages"  we write code like 

        array(
          'id'             => 'unique_select_14',
          'type'           => 'select',
          'title'          => 'Select with Chosen with Pages',
          'options'        => 'pages',
          'class'          => 'chosen',
          'default_option' => 'Select a page'
        ),

I have a custom post type name "accordion"

If I write the above code like ... 'options'        => 'accordion',

It is not listing my "accordion" post types

Please help me asap

**Comment by Codevz** [comment]
Try this: 

```PHP
array(
  'id'      => 'unique_1',
  'type'    => 'select',
  'title'   => __('Accordion(s)', 'cd'),
  'options' => 'posts',
  'class'   => 'chosen',
  'query_args'  => array(
    'post_type' => 'accordion',  // Your post_type name
    'orderby'   => 'title',
    'order'     => 'ASC',
    'posts_per_page' => -1,
  ),
  'attributes' => array(
    'data-placeholder' => __('Accordion(s)', 'cd'),
    'style' => 'width: 320px'
  )
)
```

**Comment by SantiagoInteractive** [comment]
Hi @dmsumon,

You can follow the documentation:
http://codestarframework.com/documentation/#select

In there you will see examples for select with: pages, posts, categories, tags, custom post type posts, custom post type categories, custom post type tags.

Cheers!

**Comment by dmsumon** [comment]
@SantiagoInteractive and @Codevz  ... Yaaaay! Code Star rocks ... **Thanks a lot man .**..

**Comment by Codestar** [comment]
Cheers :+1:

**Comment by stivoox** [comment]
and what if we want post type list?

**Comment by varunsridharan** [comment]
@stivoox  already replied for your requirement (https://github.com/Codestar/codestar-framework/issues/537)


Just replace the code below

```php
'options'  => 'posts',
```

To

```php
'options' => 'post_type',
```


https://github.com/Codestar/codestar-framework/blob/ef60dab50b9c39f081e0cff185d65f4676a6e3fc/classes/options.class.php#L307-L323
