### ISSUE TITLE
How to print the current post id in a readonly text field

### ISSUE THREAD

**Issue by dmsumon** [Codestar/codestar-framework#239]
Hello, @Codestar

I have a text field code like below 

  ```
array(
    'id'    => 'section_1_text',
    'type'  => 'text',
    'title' => 'Text Field',
    'default' => 'do stuff',
    'attributes' => array(
        readonly => 'readonly',
    ),
),
```

But I wonder is there any way to print the current post ID in the Text Field default value ? 

Please help me ASAP. Thanks in advance.

**Comment by Codestar** [comment]
Hi,

Interesting request, why you need this ? you can get current post ID without a field. ? It is contrary to nature :smiley:

**Comment by dmsumon** [comment]
Actually I wanted to dynamically create shotcode like this ... [SHORTCODE
id="53"]

The shortcode will publish a custom post type.

Here 53 is just an example post ID .... I just want to show the users which
shorcode to use ... Is there any way?

On Mon, Mar 14, 2016 at 4:31 PM, Codestar <notifications@github.com> wrote:

> Hi,
>
> Interesting request, why you need this ? you can get current post ID
> without a field. ? It is contrary to nature [image: :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codestar/codestar-framework/issues/239#issuecomment-196245707>
> .
>



-- 
Din Muhammad Sumon

**Comment by dmsumon** [comment]
Sir, suppose I've created a custom post type name "accordion" . Then I created a shortcode like this 

`[MYSHORTCODE id="53"]`

Here 53 will be the post id ... 

When adding a new custom post  "Accordion" . CodeStar will show the user which shortcode will list all the "Accordion" posts .

**Comment by Codestar** [comment]
Actually you can use a notice text field for this for eg:

```php
// a variable before config array
$current_post_id = ( isset( $_GET['post'] ) ) ? $_GET['post'] : 'waiting for publish';

// config array
array(
  'type'    => 'notice',
  'class'   => 'info',
  'content' => 'Useful Shortcode: <strong>[shortcode id="'. $current_post_id.'"]</strong>',
),
```

But you know, ID generation after publish post/page. i mean when you click to "New" id will not show. when you click to publish it will show. it will be normal.

**Comment by dmsumon** [comment]
WOW ! Didn't knew that. Thanks again man

**Comment by Codestar** [comment]
You're welcome, btw another idea:

```php
// a variable before config array
$my_shortcode = ( isset( $_GET['post'] ) ) ? '[shortcode id="'. $_GET['post'] .'"]' : 'waiting for publish';

// config array
array(
  'type'    => 'content',
  'title'   => 'Use this shortcode',
  'content' => '<input type="text" value="'. htmlentities( $my_shortcode ).'" style="width: 100%;" readonly>',
),
```

If you want to a readyonly input field for easy copy-paste, you can use this idea :+1:
