### ISSUE TITLE
Text and Textarea's are not support embed codes?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#24]
Hi,

I'm working on post formats now. I want to include video and audio embed code in input textarea. I've already done that, but when i paste iframe HTML code then click "Update", after update that textarea content gone.

Can you please advice?

Pasting embed code :
![screen shot 2015-02-17 at 2 56 27 pm](https://cloud.githubusercontent.com/assets/5621180/6225859/adc49c12-b6b5-11e4-8f8f-8fa39dffa349.png)
After Update :
![screen shot 2015-02-17 at 2 57 17 pm](https://cloud.githubusercontent.com/assets/5621180/6225863/bf77198a-b6b5-11e4-8801-4ec43fc23ef3.png)

Thanks,
Ansif

**Comment by Codestar** [comment]
Hi,

There is **sanitize** for all fields. Because i followed WordPress Core. but you can enable/disable sanitize for all fields. for eg:

```
array(
  'id'       => 'text_1',
  'type'     => 'text',
  'title'    => 'Text',
  'sanitize' => false,
),

array(
  'id'       => 'textarea_1',
  'type'     => 'textarea',
  'title'    => 'Textarea',
  'sanitize' => false,
),
```

**Comment by Ansif** [comment]
Ah thanks!

I don't know how i missed from your documentation! 

Great Work Done! :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by rejbioli** [comment]
thanks
