### ISSUE TITLE
Hello! Need help

### ISSUE THREAD

**Issue by Pb164** [Codestar/codestar-framework#24]
Hello there! One more question...

```
array(
	'id'         => 'sidebar_control',
	'type'       => 'checkbox',
	'title'      => __( 'Sidebars' ),
	'options'    => array(
		'content_top' => __( 'Top sidebar' ),
		'content_bot' => __( 'Bottom sidebar' ),
		'content_left' => __( 'Left sidebar' ),
		'content_right' => __( 'Right sidebar' )
	),
	'default'    => array( 'content_right', 'content_top' )
),
```
How to get - 'Top sidebar' instead of 'content_top' as TITLE of the sidebar in widgets area?

Thanks!

**Comment by Pb164** [comment]
Hmmm... is it possible to set type of the data besides 'string'? At this moment options inside arrays are 'string' data type. Thats why i cant manipulate them.

**Comment by Codestar** [comment]
Hm, no it is not possible.

**Comment by Pb164** [comment]
Hello! It is not possible at all? Or it is not possible at that moment? In some book PHP etc there were information about how to make an variable from single array cell. If you use 'a=b' instead of 'a=>b' it will be a variable with possibility to change data-type of it. Maybe i will try it.

Regards!

**Comment by Codestar** [comment]
#23
