### ISSUE TITLE
Do fieldset class keys pass custom classes?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#244]
Hi. 

Solid, Easy Framework. 

This is a feature request if it is not available yet. I was passing... 

`'class' => 'info my-custom-class-here',`

I also tried...

`'wrap_class' => 'my-custom-class-here',`

but I don't see that custom class passed through. I tried it on several different array structures. I was hoping this would give me more styling options and that I could remove the styles I already applied to the default notice statuses. Which would also be update savvy as custom styles would still be applied to the custom classes rather than the default framework classes.

**Comment by NoahjChampion** [comment]
Don't know what the issue was but it is fixed. The custom class are passing through.

**Comment by NoahjChampion** [comment]
I found the issue here. Correct me if I am wrong, but the class key doesn't work outside of the notice key, correct? 

If so, I would like to request that custom classes to pass through all arrays. I was trying to get a custom class specifically on the heading and subheading keys. 

Thoughts?

**Comment by Codestar** [comment]
Hi,

Thanks for your opinion, hmm about class attribute.

```php
array(
  'id'      => 'text_1',
  'type'    => 'text',
  'title'   => 'Text',
  'class'   => 'input-class-name', // this is meaning input classname
  'wrap_class'   => 'wrapper-of-input-class-name', // this is meaning wrapper classname
),
```

That is two different feature. btw about "notice" field there is no any input and you do not need to use ```wrap_class``` you can use directly ```class```

So, when i have free-time, i am developing this framework. If you have any idea, submit [pull requests](https://github.com/Codestar/codestar-framework/pulls) :+1:

**Comment by NoahjChampion** [comment]
Ok and welcome. 

I see that <strong>wrap_class</strong> needs to be passed along with <strong>class</strong> or no wrapper class is outputted. At least that what it seems to be from testing this right now. 

Previously I was adding a wrapper class to a top level option and class inputs to lower level items that show down the page. Not sure if, the <strong>wrap_class</strong> would be good to pass independantl of the <strong>class</strong>, but I'm fine with this either way. I got it to work. 

<strong>Pull Requests:</strong>

I've knew to pull requests and have to look more into how that process goes. 

I did try one last night, did you get that? Did it go ok? 

It was just a Documentation (READ.me) change 
@ https://github.com/NoahjChampion/codestar-framework/commit/e0e9f93237d9140e183206622986206d92fc1dde

<strong>Color Schemes / Framework Skins:</strong>

_I won't be able to contribute much code pull requests, but I've already decided to work on some Framework skins (color schemes). When I get a moment I will do that._

**Comment by Codestar** [comment]
Oh yes, i got the pull request, i will add it :+1:
