### ISSUE TITLE
Feature Request: "Duplicate" and "Close" Button for Group Fields

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#246]
When you have quite a bit of options in a group field and you come to the end of that group, there is only a "Remove" button. Then to collapse that group field you have to scroll back up and click on it. It would be more savvy I think to have a "Close" and "Duplicate" button by the "Remove" button. 

I initially envision it like this... the buttons in this order on the bottom right of the group field...

**Duplicate** 
-- Duplicates the current group field (and its options for the user to not repeat creating the same options/settings in that group again). _Maybe the green color of the ON switcher._
**Close** 
-- Closes the group field (so if the user is done, they can close that option right then and there). _Maybe the Wordpress .secondary (grey) button color._
**Remove** 
-- Removes the group field _(already there of course)_

Thoughts?

**Comment by Codestar** [comment]
Yes it is nice idea, i noted this :+1: i will add it asap :wink:
