### ISSUE TITLE
Feature Request: Code Editors (like ACE) for Custom Css and Custom Js inputs

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#247]
Feature Request: Code Editors (like ACE) for Custom Css and Custom Js inputs.

**Comment by Codestar** [comment]
See #189

**Comment by NoahjChampion** [comment]
@Codestar Thanks. I'll make sure to look through the closed requests before submitting next time.

**Comment by Codestar** [comment]
Cheers :+1:

**Comment by JoeSz** [comment]
Hello everyone!

So I had a little time and implemented ACE editor. Maybe not the perfect way, but untill somebody come up with a better one, I thought, I share it.

See: https://github.com/Codestar/codestar-framework/issues/189
