### ISSUE TITLE
Feature Request: Sub Level Dependencies (?)

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#249]
Hi. 

Are dependencies within dependencies available?
- If I have a dependency within a dependency that is dependent on a field outside of those dependencies, is that possible? 

I wanted to show a single switcher "**Show Related Dev/Usage Information:**", that when clicked would show all related dev/usage information, so the idea of Documentation/Help could be more intuitive, because visible in the same place where someone would need it. 

This might be a little more difficult to explain, especially if not possible, so I made a simple screenshot with arrows. 

Image @ http://take.ms/MQ2Y1
<img src="http://take.ms/MQ2Y1">

**Comment by Codestar** [comment]
Hi,

I added all available dependencies on default config file. if you need more, you can develop it :wink:
