### ISSUE TITLE
Dependency not working with "Radio" option

### ISSUE THREAD

**Issue by Tekanewa** [Codestar/codestar-framework#250]
When I attempt to make a colorpicker dependent upon the value in a radio element, the dependency does not work (colorpicker doesn't show at all). Once I change the "radio" element to a "select" element (simply by changing the "type" attribute and NO other changes), the dependency is working correctly.

**Comment by Codevz** [comment]
I wish this help you https://github.com/Codestar/codestar-framework/issues/107

```
  'attributes' => array(
    'data-depend-id' => 'layout', // Change this to your dependency id
  ),
```

**Comment by Tekanewa** [comment]
Thank you! That fixed it. 

And I love the feature to use multiple dependencies on one element!
