### ISSUE TITLE
Feature Request: 'show_all_options' => 'false'

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#252]
I noticed in "Show All Options" view that all options show (as would be expected), but I would like to have some filed not show in all options view. 

I'm just working on a template of the options layout so far and I added a section within each tab that has a video tutorial/developer related information. 

Because the videos will be big (whole screen width) in show all options view I would like disable those sections from showing in all options view. 

So what do you think about an attribute like 

`'show_all_options' => 'false'`

I think this would be good in general because in a all view layout some things don't need to be visible for convenience. 

Thoughts?

**Comment by Codestar** [comment]
Only add this custom css :smile: 

```css
.cs-expand-all{
  display: none;
}
```

**Comment by NoahjChampion** [comment]
Thanks! 

I actually meant to look for a css option before posting this, but doing so many things, I forgot to check :( :)

Thanks! Tested and this works perfectly!

**Comment by Codestar** [comment]
Yes, we can use custom css option for small things :wink: 

Cheers :+1:

**Comment by NoahjChampion** [comment]
Yep, sounds good. :+1: 

For anyone else needing this, a more "automated" approach to this would be to pass a custom class to the section you want hidden and just make one rule to hide that class when show all is active. 

Give the `wrap_class` or `class` like below... 

```
'wrap_class' => 'hide-show-all',
```

Then in your css just have...

```
.cs-expand-all .hide-show-all {
  display: none;
}
```

This way you don't need to write a `display: none;` statement for each section you want to hide in show all view.

**Comment by Codestar** [comment]
Yes, nice idea :+1: :100:
