### ISSUE TITLE
How to output group and post meta value .  

### ISSUE THREAD

**Issue by Nur-jaman** [Codestar/codestar-framework#253]
First of all BIG thanks for introducing such kind of cool and awesome framework . i am new to CodeStar and also now i hate myself why i didn't found this earlier :( . so right now i facing two difficulty 

1) How can i output multiple group value like - 

```php
array(
  'id'              => 'unique_option_901',
  'type'            => 'group',
  'title'           => 'Group Field',
  'button_title'    => 'Add New',
  'accordion_title' => 'Add New Field',
  'fields'          => array(
    array(
      'id'    => 'unique_option_901_text_1',
      'type'  => 'text',
      'title' => 'Text Field 100',
    ),
    array(
      'id'    => 'unique_option_901_upload_1',
      'type'  => 'upload',
      'title' => 'Upload Field',
    ),
    array(
      'id'    => 'unique_option_901_switcher_1',
      'type'  => 'switcher',
      'title' => 'Switcher Field',
    ),
  ),
),
```

2) Basically i wanna control page layout based on whatever i select in Custom Page Side Options . how can a fetch the selected value and also Custom Fields value  ?

Many thanks again .
Nur

**Comment by Codevz** [comment]
You can see output of your group option like this:

```PHP
var_dump( get_post_meta( $post->ID, 'unique_option_901', true ) );
```

Check here https://github.com/Codestar/codestar-framework/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+group+post

**Comment by Nur-jaman** [comment]
Hey, nothing changed :( please take out . i copied your EXACT same code  `  <?php 
                   $meta_groups = get_post_meta( $post->ID, 'unique_option_901', true );
                    var_dump($meta_groups);    
                    if ( !empty($meta_groups) ) {
                    foreach ( $meta_groups as $meta_group ) {
                        echo $meta_group['unique_option_901_text_1'];
                        }
                    }
                ?>`

when i using ` var_dump($meta_data['meta_groups']); `  . it's show me this: [http://s15.postimg.org/qnri3s9qz/screenshot_92.png](url)


Here is my metabox.config.php file code  

`<?php if ( ! defined( 'ABSPATH' ) ) { die; } 

$options      = array();

$options[]    = array(
  'id'        => '_custom_page_options',
  'title'     => 'Custom Page Options',
  'post_type' => 'post',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => array(

    // begin: a section
    array(
      'name'  => 'section_1',
      'title' => 'Section 1',
      'icon'  => 'fa fa-cog',
      // begin: fields
      'fields' => array(
            array(
              'id'              => 'unique_option_901',
              'type'            => 'group',
              'title'           => 'Group Field',
              'button_title'    => 'Add New',
              'accordion_title' => 'Add New Field',
              'fields'          => array(
                array(
                  'id'    => 'unique_option_901_text_1',
                  'type'  => 'text',
                  'title' => 'Text Field 100',
                ),
              ),
            ),

      ), // end: fields
    ), // end: a section
  ),
);

CSFramework_Metabox::instance( $options );
`
 
Here is the full code how i am trying to output my group field value :  
    
<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>

<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>> 
  <div class="container">
      <div class="row">
          <div class="col-sm-12">
                <?php the_post_thumbnail();?>
                <?php the_content();?>
      
              <h2>Posted:
                <?php 
                   $meta_groups = get_post_meta( $post->ID, 'unique_option_901', true );
                    var_dump($meta_groups);    
                    if ( !empty($meta_groups) ) {
                    foreach ( $meta_groups as $meta_group ) {
                        echo $meta_group['unique_option_901_text_1'];
                        }
                    }
                ?>
         </h2>
          </div> 
      </div> 
  </div> 
</article> 

<?php endwhile; else : ?>

Please help me :( . @Codestar @Codevz 
Thanks 
Nur

**Comment by Codestar** [comment]
Hey @Nur-jaman 

There is issue for `get_post_meta` key name. i am seeing your first message key name is: `'id' => 'unique_option_901',` and @Codevz followed this key name and answer is `var_dump( get_post_meta( $post->ID, 'unique_option_901', true ) );` this is right. but your second message key name is different.

Your latest message key name is `'id' => '_custom_page_options',``` and let's use this key. see new code:

```php
<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>> 
  <div class="container">
    <div class="row">
      <div class="col-sm-12">

        <?php the_post_thumbnail();?>

        <?php the_content();?>

        <h2>Posted:
        <?php 
          
          $meta_data = get_post_meta( $post->ID, '_custom_page_options', true );
          
          // var_dump( $meta_groups );    
          
          // getting group field
          $meta_groups = ( ! empty( $meta_data['unique_option_901'] ) ) ? $meta_data['unique_option_901'] : '';

          if ( ! empty( $meta_groups ) ) {
            foreach ( $meta_groups as $meta_group ) {
              echo $meta_group['unique_option_901_text_1'];
            }
          }

        ?>
        </h2>

      </div><!-- END col-sm-12-->
    </div><!-- END row -->
  </div><!-- END container-->
</article><!-- END article-->
```

**Comment by Nur-jaman** [comment]
OMG ! . it's working fine . Many Many Many thanks @Codestar @Codevz  . just thinking how some people can help someone like this  :+1: 
You guys are really AWESOME .
BIG Thanks again . 
Nur

**Comment by Codestar** [comment]
You're welcome @Nur-jaman when you need any help, we are here :+1:
