### ISSUE TITLE
Feature Request: Extended Usage of the Icon Dialog

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#254]
(it would be useful) or is it too custom/unique of a request?

```
array(
  'type' => 'dialog_*',
  'content' => 'Content to show in the dialog popup here...',
),
```

I was thinking a link so something like... 

**Learn More** or **See Demo**

Could be clicked to show content in the dialog when it pops up like... 

```
array(
  'type' => 'dialog_link',
  'title' => 'Learn More', // or 'title' => 'See Demo', 
  'content' => 'Content to show in the dialog popup here...',
),
```

Then we could have the following... 

```
'type' => 'dialog_link',
'type' => 'dialog_button',
'type' => 'dialog_image',
```

Then we could pass something like...

```
'content' => 'Youtube video iframe that would show in the dialog like.. https://www.youtube.com/embed/9AEMKudv5p0',
```

For example this plugin @ https://wordpress.org/plugins/wpbizplugins-custom-admin-help-boxes/screenshots/ will take whatever content you give it and when the help button is clicked, the content will show in the Wordpress TB dialog window.

Thoughts?

**Comment by Codestar** [comment]
Hi,

Yes, it is nice idea, i liked it. also i will need it in my themes :+1: noted this.

**Comment by NoahjChampion** [comment]
Ok, thanks. 

Yeah, I thought this was a good and could really be used to help users in a savvy way. Passing content to the dialog would allow instant help anywhere in CF from single click. 

Appreciate it.

**Comment by Codestar** [comment]
Yes right... when i finish it, i will return this topic :+1:
