### ISSUE TITLE
Feature Request: Restore/Reset Metabox Option like in Settings Page

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#257]
Hi. 

I think this feature should be added and would be unique to CF. I haven't seen any other frameworks offer a restore or reset options for the post metabox. 

What do you think about adding this? 

Or is there a hack I can use to give this option in the metabox to get the post id, delete it's post meta, then update that options as false so it doesn't run every time? Though, it would seem more intuitive and consistent if a restore/reset option could be passed to the metabox, just like in the CF settings pages. 

Thoughts?

**Comment by Codestar** [comment]
Hi,

hmm, interesting. I had not thought it.. hmm yes why not. i will try to add it :+1:

**Comment by NoahjChampion** [comment]
:+1:

**Comment by NoahjChampion** [comment]
@Codestar 

To add, what do you think about Saving ajax button on post metabox? 

It would speed up productivity when a user needs to edit only the metabox theme options. This way they can make changes, save via ajax if they want and view their changes without having to wait for the post to save and reload.

**Comment by Codestar** [comment]
Uh, hmm i do not think saving ajax for metaboxes. because there is "update" button. extra buttons will confusing for users. also i did not see this for any options framework :smile:

**Comment by NoahjChampion** [comment]
No problem, just thought I would put the idea out. 7, 8 or 9 out of 10 is good :100:
