### ISSUE TITLE
How to check for Multiple Image Select Dependencies?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#258]
In #49 

How can we check for multiple image select dependencies? 

Something simple like below doesn't work... 

```
'dependency' => array(
  array('Id_Here_Value_Here', 'Id_Here_Value_Here'), 
'==', 'true'),
```

I tried other articles I found for CF but none are working for me for the image select. 

I see multiple dependencies checking the multiple ids, but not multiple values. Is this possible? 

I've tried about 3-5 different array options like array, array_merge, array_keys, array_push, and different $variable methods, but still nothing works for me. I can always get the first dependency value to work, but not the other values.

**Comment by Codestar** [comment]
hmm try this 

```php
'dependency' => array( 'Id_Here_Value_Here|Id_Here_Value_Here', '==', 'true'),
```

More things

```php
'dependency' => array( 'Id_Here_Value_Here|Id_Here_Value_Here', '==|=!', 'true|true'),
```

```php
'dependency' => array( 'Id_Here_Value_Here|Id_Here_Value_Here', '==|==', 'black|white'),
```

But there is important, you are using RADIO image select or CHECKBOX image select? write here your example config array ( only image select field and dependency fields array ).

**Comment by NoahjChampion** [comment]
@Codestar 

I am using radio image select. 

I made a gist of fields array @ https://gist.github.com/NoahjChampion/bd5c2211261498f4d8e0

I tried the above methods you just gave but none worked either. The first option is what I tried first because that was in #49 , The second option you gave works, but only passes the first dependency, not the others. The last method didn't work at all. Then I kind of mixed them together trying things, but I still only get the first dependency to work, not multiple.

**Comment by Codestar** [comment]
Hmm this is not radio options, this is checkboxes. add radio attribute like this:

```php
array(
  'id'      => 'website_layout',
  'type'    => 'image_select',
  'options' => array(
    'website_layout_fullwidth' => 'image-1.png',
    'website_layout_boxed'     => 'image-2.png',
  ),
  'default' => 'website_layout_fullwidth',
  'radio' => true,
),
```

Still same ? your example config working on my localhost ? when i select `website_layout_fullwidth` i am seeing chosen selector.

**Comment by Codestar** [comment]
I added your config on my config and the result:

![support_20160324131327](https://cloud.githubusercontent.com/assets/1313301/14015529/5b8ad760-f1c2-11e5-9ca9-5f41edd0ccfe.gif)

It is normally?

**Comment by NoahjChampion** [comment]
Hi. 

Sorry, yes that example config works. I need multiple dependencies so I should have added another value to show multiple dependency issue. 

I updated that gist, to show multiple dependency issue, but I pasted the gist below too. I tried to simplify it so it should be easy to understand. 

```
// ------------------------------------------------------------------------------------------------------------------------------------------------------
// Website Layout
// ------------------------------------------------------------------------------------------------------------------------------------------------------
// Single Image Select (Radio)
array(
	'id' => 'website_layout',
	'type' => 'image_select',
	'options' => array(
		'website_layout_1' => 'image-1.png',
		'website_layout_2' => 'image-2.png',
		'website_layout_3' => 'image-3.png',
	),
	'default' => 'website_layout_1',
),
// ------------------------------------------------------------------------------------------------------------------------------------------------------
// Website Size
// ------------------------------------------------------------------------------------------------------------------------------------------------------
// Single Chosen Select
array(
	/* 
	* I need dependency for website_layout_1 and website_layout_3
	*/
	'dependency' => array('website_layout_1', '==', 'true') , // This first value works but...
	//'dependency' => array('website_layout_3', '==', 'true'), // I need dependency for this value too but how to?
	'id' => 'website_size_dropdown',
	'type' => 'select',
	'class' => 'chosen',
	'options' => array(
		'size_1' => 'size-1',
		'size_2' => 'size-2',
		'size_3' => 'size-3',
	),
	'default' => 'size_1',
),

```

**Comment by Codestar** [comment]
Hmm, try this and tell me the result :

```php
array(
  'id'      => 'website_layout',
  'type'    => 'image_select',
  'options' => array(
    'website_layout_1' => 'image-1.png',
    'website_layout_2' => 'image-2.png',
    'website_layout_3' => 'image-3.png',
  ),
  'attributes' => array(
    'data-depend-id' => 'website_layout',
  ),
  'default' => 'website_layout_1',
  'radio'   => true
),
array(
  'dependency' => array('website_layout', 'any', 'website_layout_1,website_layout_3'),
  'id' => 'website_size_dropdown',
  'type' => 'select',
  'class' => 'chosen',
  'options' => array(
      'size_1' => 'size-1',
      'size_2' => 'size-2',
      'size_3' => 'size-3',
  ),
  'default' => 'size_1',
),
```

**Comment by NoahjChampion** [comment]
You are the "Chosen One" :+1:  :+1:  :+1: 

BTW `'any'` in that dependency **is required**. 
NOTE: maybe in future documentation note it is required. I thought this was an example till now. Haha.

**Comment by Codestar** [comment]
Yes, actually i will create a detailed documentation for usage framework. but you know free-time is problem :smile:
