### ISSUE TITLE
Feature Request: Horizontal Tabs?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#259]
In #256 

What did you think about Horizontal Tab support? 
- Even if using the default Wordpress tabs.

**Comment by Codestar** [comment]
Hmm, it is possible with css. but what you think about sub tabs? we will add a dropdown menu ?

**Comment by NoahjChampion** [comment]
Sub tabs sounds good. For me, in my framework.config I think sub tabs will be too much. I think it will get too crowded on the menus. But, I haven't seen or tried them to know if it really would. 

So I was thinking sub tabs so a page could still have all the content just better grouped into horizontal tabs that make it easy to understand and find options. 

For example (in the screenshot below) Wordpress uses their horizontal welcome page tabs. In CF, this could all be under 1 About Tab, instead of 3 sub tabs. 

I was trying to organize and save some scrolling space for the user. Since some options because dependency, when shown it starts to take up space and that use may need to scroll to other sections. Which is not horrible, but I was just thinking of a Wordpress already solution for this, so it would be as much work I think. ?? (I try to think my requests through first before asking so that it involves the least work/better idea) but if sub tabs is easier, then maybe you want to try that?

<img src="https://monosnap.com/file/xacAaNN4aSwIESYtdb6iP237uC9afa.png">

**Comment by Codestar** [comment]
Yes, i understand. looking good. let's add this for feature list :wink:
