### ISSUE TITLE
Issue: button_title, frame_title, insert_title do not work on Background type?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#260]
Should button_title, frame_title, insert_title work for Background type? 

I've tried most of the options here to pass a custom upload button title, frame title and insert button title, but nothing works. 

See **Gist:** of what I tried @ https://gist.github.com/NoahjChampion/6c62b372098a172da1a3

I see in **/fields/background//background.php** 

```
$upload_type    = ( isset( $upload_type  ) ) ? $upload_type  : 'image';
$button_title   = ( isset( $button_title ) ) ? $button_title : __( 'Upload Image', 'cs-framework' );
$frame_title    = ( isset( $frame_title  ) ) ? $frame_title  : __( 'Select Your Background Image', 'cs-framework' );
$insert_title   = ( isset( $insert_title ) ) ? $insert_title : __( 'Use This Image', 'cs-framework' );
```

I changed the text what I need, but should button_title, frame_title, insert_title work for Background type?

**Comment by Codestar** [comment]
Oh yes, there is a bug.. Ok i fixed it now. Only update `fields/background/background.php` and added one line here [background.php#L30](https://github.com/Codestar/codestar-framework/blob/master/fields/background/background.php#L30)

Usage:

```php
array(
  'id'       => 'unique_background_1',
  'type'     => 'background',
  'title'    => 'Background',
  'settings' => array(
    'upload_type'  => 'image',
    'button_title' => 'Upload Background Image',
    'frame_title'  => 'Select Your Background Image',
    'insert_title' => 'Use This Image',
  ),
),
```

Thanks for report :+1:

**Comment by NoahjChampion** [comment]
Works perfect! 

Your welcome :+1: 

@Codestar how can I send you an email? Address?

**Comment by Codestar** [comment]
Nice... You can use routewp[at]gmail.com :+1:
