### ISSUE TITLE
Feature Request: New Field Type "Css Builder" (Margin & Padding Designer)

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#261]
**Feature Request:** New Field Type "Css Builder" (Margin & Padding Designer)

<img src="https://monosnap.com/file/4QZLtz8XDb5srXd5jfIiqq12zwHvj9.png">

I was just thinking of this and remembered a similar Advanced Custom Fields addon made by an outside author on Github @ [ACF-CSS-Margin-Padding-Settings](https://github.com/tmconnect/ACF-CSS-Margin-Padding-Settings)

It looks great, covering all the css margin and padding options, like [Visual Composer](http://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431) does in their [Design Options](https://youtu.be/34Xd9L_oLcs?t=8s) panel. 

What do you think about adding this as a new field? Useful? :) :) :+1: 

`'type' => 'css_builder',`

If I knew how to add it to CF I would grab the git and do it for us, but I'm really just better ideas and visuals.

**Comment by Codestar** [comment]
Actually, yes i am thinking a similar field. ok let's noted this.
