### ISSUE TITLE
Feature Request: New Field Type 'type' => 'metabox'

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#262]
Can you add support for a metabox field type to be used in the framework.config.php? 

It should work like the post edit screen metabox so that content can be toggled open or close, but metabox is always visible. 

I see group field data can collapse in the group field, but is only visible when Add Group field is used. 

I would like collapsible content container but with no Add button/repeatable button. Just like normal Wordpress metabox in the post edit screens so content can be collapsed. 

Let me know if that makes sense or should I be more clear, with an image.

**Comment by Codestar** [comment]
Hmm, can add this feature for `Fieldset` field ? only a new param for eg `toggle => true` or usage with default position `toggle => 'open' or 'close'`

**Comment by NoahjChampion** [comment]
Ok, glad I was clear enough. It sounded confusing a little when I wrote it. But you got it. 

Yes, that sounds perfect... `'type'  => 'fieldset'` `'toggle' => 'open' or 'close'`

Thoughts?

**Comment by Codestar** [comment]
Ok, i will try to add it asap :+1:

**Comment by NoahjChampion** [comment]
Ok, thanks. 

I've already started moving all my options to fieldsets, so then I can just add the toggle => true. 

But I also found a good trick :+1: from fieldset you just led me to. 

Before, I was writing dependency code for every option like... 

```
// Number Chosen Unit Select (Content Unit Type)
array(
    // Writing dependency value every time
	'dependency' => array(
		'SHOW-CustomThemeCore-Content_Layout',
		'==',
		'true'
	) ,
	'type' => 'select',
	'id' => 'content_layout_unit_type',
	'class' => 'chosen',
	'default' => 'pixel-based',
	'options' => array(
		'em-based' => '(em)',
		'pixel-based' => '(px)',
		'percentage-based' => '(%)',
	) ,
) ,

// Number Chosen Unit Select (Content Unit Type)
array(
    // Writing dependency value every time
	'dependency' => array(
		'SHOW-CustomThemeCore-Content_Layout',
		'==',
		'true'
	) ,
	'type' => 'select',
	'id' => 'content_layout_unit_type',
	'class' => 'chosen',
	'default' => 'pixel-based',
	'options' => array(
		'em-based' => '(em)',
		'pixel-based' => '(px)',
		'percentage-based' => '(%)',
	) ,
) ,
```

But now I can write the dependency one time for everything in the fieldset type like... 

```
array(
	'type' => 'fieldset',
	'id' => 'CustomThemeCore-Header_Layout',
	'dependency' => array(
		'SHOW-CustomThemeCore-Header_Layout',
		'==',
		'true'
	) , // Now everything in this fieldset is dependent on this one dependency
	'fields' => array(
		// Number Chosen Unit Select (Content Unit Type)
		array(
			'type' => 'select',
			'id' => 'content_layout_unit_type',
			'class' => 'chosen',
			'default' => 'pixel-based',
			'options' => array(
				'em-based' => '(em)',
				'pixel-based' => '(px)',
				'percentage-based' => '(%)',
			) ,
		) ,
		// Number Chosen Unit Select (Content Unit Type)
		array(
			'type' => 'select',
			'id' => 'content_layout_unit_type',
			'class' => 'chosen',
			'default' => 'pixel-based',
			'options' => array(
				'em-based' => '(em)',
				'pixel-based' => '(px)',
				'percentage-based' => '(%)',
			) ,
		) ,
	) ,
) ,
```

I'll make a note of that so I can post a tip, so when users search for the dependency issues, they can find that tip hopefully. Cool?

**Comment by Codestar** [comment]
Oh yes, cool. Good trick. :+1: I liked it :100:
