### ISSUE TITLE
You should put name of commit like "Fixed ABC..." instead of *update*

### ISSUE THREAD

**Issue by anhskohbo** [Codestar/codestar-framework#263]

**Comment by Codestar** [comment]
Sorry, Yes you are right totally. I am planing to create changelog, versions and commit name for next updates, but as you know "time" is problem. this framework not a teamwork. i am alone :smile: when i have free-time i will do everything :+1:

**Comment by anhskohbo** [comment]
Yes, but thanks for the great framework :+1:

**Comment by Codestar** [comment]
Thank you :wink:

**Comment by Codestar** [comment]
Hi,

Hey, how its looking now. what you think tell me :smile: 

https://github.com/Codestar/codestar-framework
https://github.com/Codestar/codestar-framework#the-latest-updates
https://github.com/Codestar/codestar-framework/blob/master/CHANGELOG.md
https://github.com/Codestar/codestar-framework/releases/tag/1.0.1
