### ISSUE TITLE
Post meta data adding issue while front end posting! 

### ISSUE THREAD

**Issue by channelriyas** [Codestar/codestar-framework#264]
I am in a weird situation,

I was working on front-end posting everything works well but I cannot handle add_post_meta()  to add values, I sure the issue on data serializing. I tried with serialize() and json_encode() but nothing working exactly compatible with our framework

here are my code:
                                                                                                                                                                                                
```php
$sample_section_data = array('sample_field' => 'hello');                                                                                                                 
$sample_section_serialized = serialize($sample_section_data); 
//result a:1:{s:12:"sample_field";s:5:"hello";}                                     
//this result is fine and compatible with CSframwork metabox but this result only returning while just   print or echo stage                     
//but  while we saving to database the result is like this  
//result s:38:"a:1:{s:12:"sample_field";s:5:"hello";}";                                     
//its not compatible with our framework :(  

$sample_sec_jencoded = json_encode($sample_section_serialized );  
//result "a:1:{s:12:"sample_field";s:5:"hello";}"                        
//this result is much better than above but not compatible with csFramework, the only issue is that a starting and ending quotation  
```  
                                                                                                                                                                                                
`add_post_meta($post_id, 'sample_section', $sample_sec_jencoded, true);  `      

You have any previous experience like this ? or you have any suggestion

Please help me on this!
Thanks!

**Comment by Codestar** [comment]
I am trying to understand issue, but there is no framework code? this is normal code? where you are trying this code?

Btw, you can not json encode serialized data.

```php
$sample_sec_jencoded = json_encode( $sample_section_serialized ); // this is wrong
$sample_sec_jencoded = json_encode( $sample_section_data ); // this is true

// also you do not need serialize or encode in add_post_meta.. this function making it serialized.
// for eg
add_post_meta($post_id, 'sample_section', $sample_section_data, true); // this is enough for save array
```

**Comment by channelriyas** [comment]
Oh really thanks bro! its worked well!

sorry for wasting your time, add_post_meta() doing this serializing, its just a wp basic ;) I thought you are using some other serializing to get like this result _a:1:{s:12:"sample_field";s:5:"hello";}_  

Thanks bro, really appreciated !

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by mustafakucuk** [comment]
Thanks, worked!
