### ISSUE TITLE
Question: Simple way to force Switcher off every load/after save?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#265]
I'm using a switcher for "Reveal or Collapse Content". But, whenever this option is visited I wanted the switcher to be off by default every time. I never want it to be save as on. Is there a way I can do this? I want it to work more like a Toggle. 

Is there a way or any value I can pass that will make an option not save to the database or be ignored? 

For example I have... 

```
<?php

// REVEAL_THIS_SECTION (Switcher)
array(
	'type'          => 'switcher',
	'id'            => 'REVEAL_THIS_SECTION-Paragraph_Font_Styles',
	'title'         => 'Reveal or Collapse This Section:',
	'on_text'       => __('REVEAL', 'custom-theme-settings') ,
	'off_text'      => __('COLLAPSE', 'custom-theme-settings') ,
	'wrap_class'    => 'reveal-collapse-section-switcher',
)

?>
```

I want the above to always be saved as off so when the settings page is active all sections are collapsed. 

Is there a way to achieve something like this in CF? The only way I know is to do an update_option maybe on every save, but that would be too much

**Comment by Codestar** [comment]
You can use `cs_validate_save` filter. for eg:

```php
if( ! function_exists( '_cs_validate_save' ) ) {
  function _cs_validate_save( $request ) {

    $request['FOR_EG_ELEMENT_ID'] = false;
    $request['REVEAL_THIS_SECTION-Paragraph_Font_Styles'] = false;

    return $request;

  }
  add_filter( 'cs_validate_save', '_cs_validate_save' );
}
```

**Comment by NoahjChampion** [comment]
Thanks! Works. :+1:

**Comment by NoahjChampion** [comment]
Glad I asked.

**Comment by Codestar** [comment]
You're welcome :+1:
