### ISSUE TITLE
Question: Simple way to print/echo/var_dump fieldset children?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#266]
Is there a simple way to `var_dump` all fieldset children without have to write our each fieldset child?

**Comment by NoahjChampion** [comment]
When I try it for the fieldset alone like... 

`echo cs_get_option( 'Fieldset_ID' );`

I only get...

`Array`

**Comment by Codestar** [comment]
You need to use foreach for fieldset childs if un_array false. no any way without foreach...

**Comment by NoahjChampion** [comment]
Ok, thanks. I was just wondering/inquiring. Appreciate it.

**Comment by Codestar** [comment]
You're welcome, if you found a idea about this, share with us :+1:

**Comment by NoahjChampion** [comment]
@Codestar what is the way you use written out, so if I find something simpler I will still post it.

**Comment by Codestar** [comment]
You can write here :+1:
