### ISSUE TITLE
Request: Attributes "col" and "rows" for image_select

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#267]
Hi. 

Can you add support for image_select to have a max 'col' and max 'rows'? 

`'type'  => 'image_select',`

Support for...

```
'attributes' => array(
  'cols' => 3,
  'rows' => $variable,
),
```

I have 6 images to select from. It would better if the settings panel always shows 3 images on top and 3 images on the bottom. Instead the browser resizing may show 5 on top and 2 on the bottom or 6 images on top and 1 image on the bottom, etc.

**Comment by Codestar** [comment]
Hi,

Yes nice idea. i will try to add it... noted :+1:

**Comment by NoahjChampion** [comment]
Appreciate CodeSTAR.
