### ISSUE TITLE
Question/Suggestion: Save (action) buttons in cs-footer

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#268]
I placed the action buttons from the header in the footer and they work fine except for the "Settings Saved." doesn't appear. 

Example: 
<img src="https://monosnap.com/file/k3Wo2IG41Mb38A8elu2pbwOYVv2wI5.png">

Do you know why? 

The cs-header has... 

```
echo ($this->settings['ajax_save'] === true) ? '<span id="cs-save-ajax">' . __('Settings saved.', 'cs-framework') . '</span>' : '';
submit_button(__('Save All Settings', 'cs-framework') , 'primary cs-save', 'save', false, array('data-save' => __('Saving Data...', 'cs-framework')));
submit_button(__('Restore Last Settings', 'cs-framework') , 'secondary cs-restore cs-reset-confirm', $this->unique . '[reset]', false);
submit_button(__('Reset All Settings', 'cs-framework') , 'secondary cs-restore cs-reset-confirm', $this->unique . '[resetall]', false);
```

And the cs-footer has the same...

```
echo ($this->settings['ajax_save'] === true) ? '<span id="cs-save-ajax">' . __('Settings saved.', 'cs-framework') . '</span>' : '';
submit_button(__('Save All Settings', 'cs-framework') , 'primary cs-save', 'save', false, array('data-save' => __('Saving...', 'cs-framework')));
submit_button(__('Restore Last Settings', 'cs-framework') , 'secondary cs-restore cs-reset-confirm', $this->unique . '[reset]', false);
submit_button(__('Reset All Settings', 'cs-framework') , 'secondary cs-restore cs-reset-confirm', $this->unique . '[resetall]', false);
```

But when I press save in the footer the saving ajax message doesn't show. It saves, but doesn't show. 

And just a suggestion (not a big deal) but maybe you can add action buttons in the footer too, so user doesn't have to scroll up on longer pages to save their settings.

**Comment by Codestar** [comment]
Hi,

Yes it is true, because i am following element ID in jQuery. You can disable ajax_save option for this request. btw, why i did not add this buttons on footer, because i am planing to a sticky scroll system for save/restore/reset buttons.

**Comment by NoahjChampion** [comment]
Oh, ok. Sounds good! I did not think of that. Good idea.

**Comment by Codestar** [comment]
BTW, i added a new option for you in development version of framework. it will come future... see details..

[framework.config.php#L12](https://github.com/Codestar/codestar-framework/blob/dev/cs-framework/config/framework.config.php#L12) - [framework.class.php#L371-L373](https://github.com/Codestar/codestar-framework/blob/dev/cs-framework/classes/framework.class.php#L371-L373)

Output:
![support_18-33-35](https://cloud.githubusercontent.com/assets/1313301/14253345/cd1c709e-fa93-11e5-8ab0-b4c1d03ab694.png)

**Comment by NoahjChampion** [comment]
Awesome! 

Question, as I haven't actually been sure. 

What is the difference between Restore and Reset All Options? 

And is there a different once a user has saved already?

**Comment by Codestar** [comment]
"Restore" means only reset current section fields.
"Reset All Options" means reset all of section fields.

Actually there is some english issues.. i will improve it. for eg i can translate "Restore" to "Reset This Section" or "Restore only this section" i am not sure.. if you have any idea, share with me.

**Comment by NoahjChampion** [comment]
Ok, that is what I thought or hoped it did, but wasn't sure. 

I think it would be simple to just have... This would be the safest and easiest to understand because they both use the same language and same amount of words.

**Reset This Section** 
**Reset All Sections**

And for me, I made "Save" to "Save All Settings" because I don't want a user to think it might save only a section. I want them to know that Save, saves ALL settings, not a section, like Reset does.

**Comment by Codestar** [comment]
Yea great, nice translate. i will use it :+1:

**Comment by NoahjChampion** [comment]
Ok, good deal. :)
