### ISSUE TITLE
Sorter field with active & inactive sections

### ISSUE THREAD

**Issue by mandava** [Codestar/codestar-framework#27]
Hey,

I have created "Layout Sorter" field for codestar framework. 

![sorter](https://cloud.githubusercontent.com/assets/125006/6256385/a872c560-b785-11e4-9cef-b7760cde1e11.PNG)

Here is the code I put down to create those "Active" & "Inactive" sections and saving the settings accordingly. https://gist.github.com/mandava/131fbdf1aaa683beb47c

Included options config & CSS in the gist. You can improvise the code & include "sorter" or "layout" field in codestar framework. 

Cheers!

**Comment by Codestar** [comment]
Hi,

Woow great, i will add this option, i noted this for next update :100:

**Comment by mandava** [comment]
Great! I wrote it quickly and included JS in the field file itself. Hope you will make necessary changes before adding it.

**Comment by Codestar** [comment]
Yep, wait until this weekend ;)

**Comment by Codestar** [comment]
Hi,

I worked on sorter field today. take a look. 

![support_19-25-33](https://cloud.githubusercontent.com/assets/1313301/6271983/3027faec-b86d-11e4-8102-3cb6021acece.png)

It is on dev branch: https://github.com/Codestar/codestar-framework/archive/dev.zip

Config Usage:
```
array(
  'id'             => 'sorter_1',
  'type'           => 'sorter',
  'title'          => 'Sorter',
  'default'        => array(
    'enabled'      => array(
      'bmw'        => 'BMW',
      'mercedes'   => 'Mercedes',
      'volkswagen' => 'Volkswagen',
    ),
    'disabled'     => array(
      'ferrari'    => 'Ferrari',
      'mustang'    => 'Mustang',
    ),
  ),
),

array(
  'id'             => 'sorter_2',
  'type'           => 'sorter',
  'title'          => 'Sorter',
  'default'        => array(
    'enabled'      => array(
      'blue'       => 'Blue',
      'green'      => 'Green',
      'red'        => 'Red',
      'yellow'     => 'Yellow',
      'orange'     => 'Orange',
      'ocean'      => 'Ocean',
    ),
    'disabled'     => array(
      'black'      => 'Black',
      'white'      => 'White',
    ),
  ),
  'enabled_title'  => 'Active Colors',
  'disabled_title' => 'Deactive Colors',
),
),
```

Can you unit test it ? and report me if you found any bug ;)

**Comment by mandava** [comment]
Everything is fine, expect the names of the fields. How about displaying capitalized names by stripping the underscores? 

![names](https://cloud.githubusercontent.com/assets/125006/6273494/ca226112-b83d-11e4-933e-495afbb51312.PNG)

$enname = esc_html( ucwords( str_replace( '_', ' ', $en_name ) ) );

**Comment by Codestar** [comment]
Uh i did not understand underscores request. can you explain it more ? why we need to use this

```
$enname = esc_html( ucwords( str_replace( '_', ' ', $en_name ) ) );
```

It is simple
```
array(
  'id'             => 'sorter_1',
  'type'           => 'sorter',
  'title'          => 'Sorter',
  'default'        => array(
    'enabled'      => array(
      'a_module_name'        => 'A Module Name',
      'another_module'        => 'Title is this, Can be write anything',
    ),
    'disabled'     => array(),
  ),
),
```

**Comment by mandava** [comment]
Try saving the options and you can see what I mean. The $en_name displays the ID, so I filtered it out to display without underscores. Got it?

**Comment by Codestar** [comment]
Interesting, when i save options, i am seeing normal titles there. but i am seeing on your screenshot id replacing as title. it is intresting. i am on ipad now, i will check it tomorrow again. btw can you make a "Restore" options before save. because i used default attribute as field value. Try it on a new field id.

**Comment by mandava** [comment]
Alright, I tested it again and its perfect! You can push the update now. Cheers!

**Comment by Codestar** [comment]
Great! pushed :+1: Cheers!
