### ISSUE TITLE
Loading interuption in Firefox

### ISSUE THREAD

**Issue by Slobork** [Codestar/codestar-framework#270]
Hi,

I really like the framework and that's the reason I decided to move to CS from another options framework. I'm in the middle of this process and I like how the things have been organized with CS. Appreciate your efforts very much and before anything else would like to say thank you!

I do have 340 option fields, though some of them I still didn't convert to CS. It seems to take excessive amount of time to load an options page in the WP's admin. Firefox even interrupts the page's loading and throws a message box:

**************
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://127.0.0.1/mywp/wp-admin/…olor-picker,plupload&ver=4.3.3:4
**************

It loads the page after I click on one of the buttons ("stop script" or "continue") that Firefox is throwing. Everything works fine after that. Since the ajax_save is active, after the initial load, saving the options goes smoothly.

If I delete a bunch of the fields, it will load without that interruption. Obviously, number of fields plays a role here. 

About 1/4 of my fields are actually from a couple of theme's plugins, but currently I do not see an option to load them on a separate page. I'm loading them conditionally, if they are active, with a filter "cs_framework_options".

Do you consider this amount of option fields to be so large? Or can this be something specific to my configuration? Any chance for loading improvement?

Thanks!

**Comment by Codestar** [comment]
Hi,

Thanks for your nice words, i get happy :smiley:  

I have not any idea about this, because i can not see the error code. Add your config files on https://gist.github.com/ i can test it.. because as you know, i can not solve it without look :wink: 

Regards, Codestar

**Comment by Slobork** [comment]
Hi CS,

this is the gist: https://gist.github.com/Slobork/e6a72a39667f3182719602dcb540d781

I've tried to make this easier. I've set the demo fields you provide with your basic dev theme as a foundation. You'll notice that to that foundation I've added 3 sections (General Styling, Header and Blog). It shouldn't be important, anyway just to mention that first 2 sections have subsections as well. 

If I omit any of these 3 sections, Firefox won't throw the error. If all code is present, Firefox will interrupt the loading.

Let me know if you can reproduce this or if I can be of any more help. Thanks!

**Comment by Codestar** [comment]
Hi,

Now i am testing it on firefox, i can see all options. no issue. for eg.

![screenshopt](https://cloud.githubusercontent.com/assets/1313301/14280342/dc6dd090-fb3a-11e5-830c-be70ea0c71cd.png)

But yes, it is loading within 3-4s. btw what can i advise you.. for eg. disable chosen selector for small selector. see screenshot there is 1,2,3,4 select options. you do not need chosen there. because you know chosen using javascript.

If still you having problem, send a screenshot?

**Comment by Slobork** [comment]
Well, that's not so bad news. Since you're not able to reproduce, it probably means that I have a conflict with either Firefox's addon or WP's plugin, or the culprit is even the localhost environment. 

I'll test this more over the weekend and will report back what I find.

Cheers!

P.S. as requested, here's the screenshot, but it's just the reflection what I've quoted in the opening post:

![cs-mf](https://cloud.githubusercontent.com/assets/6130788/14285017/3c382fca-fb4a-11e5-8765-8a57901ff24b.png)

**Comment by Codestar** [comment]
Interesting, i can not get this error in firefox. i am not sure how i can fix it :smiley: hmm ok, i will wait your report :+1:

**Comment by Slobork** [comment]
After removing the 'chosen' class from the fields, the issue isn't appearing anymore.
It seems that if 'chosen' is set many times, there's a problem... i.e. in my case.

**Comment by Codestar** [comment]
Yes, i was think same. because chosen suck system really. also i will try to find a solution about this :+1:
