### ISSUE TITLE
Question/Feature Request: add_submenu_page option

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#271]
Add Submenu Page option `add_submenu_page` Mentioned @ #70 

Reference @ https://developer.wordpress.org/reference/functions/add_submenu_page/

Was this added? 

I see the conversation only ended in supporting `add_options_page` `add_appearance_page` and others, but not adding a submenu page by `$parent_slug`. 

I would like to add a CS options page under another plugin's menu, but that only works if I add the menu, then hide it with css, then add my own function with the same CS options page slug so the menu item shows under the plugin's menu. 

Example... 

```
// Add this menu then hide it with css, then add the same menu slug in our submenu function below
$settings = array(
	'menu_title' 		=> 'CS Options Page',
	'menu_type' 		=> 'add_menu_page', // Creates Top Level Menu Item
	'menu_slug' 		=> 'cs-framework-options-page', // Slug must match submenu slug below
	'menu_position' 	=> '999', // Determines menu position of our menu
	'ajax_save' 		=> true, // Enable or disable saving by ajax
);
```
```
add_action('admin_menu', 'Add_CodeStar_FRAMEWORK_Menu_As_Submenu', 1);
function Add_CodeStar_FRAMEWORK_Menu_As_Submenu() {
	add_submenu_page( 'third-party-plugin-slug-here.php', 'CS Options', 'CS Options', 'manage_options', 'admin.php?page=cs-framework-options-page', '');
}
```

I also thought about this because I'm thinking about offering an addon to the theme options, so when a user purchase's an addon, they will activate that addon as a plugin and the menu will appear under the theme's settings menu. 

This idea is probably new, but probably a good way to make extra money from selling your theme, or any author's theme who can create an extended functionality plugin. 

Is there a native way to `add_submenu_page` yet with CF?

**Comment by Codestar** [comment]
Actually, i did not understand request. you can add framework menu anywhere? for eg. 

```php
// see Admin Panel > Tools
$settings = array(
    'menu_parent'   => 'tools.php',
    'menu_title'    => 'CS Options Page',
    'menu_type'     => 'add_submenu_page',
    'menu_slug'     => 'cs-framework-options-page',
    'menu_position' => '999',
    'ajax_save'     => true,
);
```

**Comment by NoahjChampion** [comment]
Okay, I see the issue. 

I did not have/find `'menu_parent'`. I only had `menu_type`.

`'menu_parent'` will allow me to add submenu page by slug. 

It's fixed now. 

Thanks!

**Comment by Codestar** [comment]
Yes there is a `menu_parent` yes but, it is my fault :smile: because i need to create a more detailed documentation. but you know free-time is issue. haha there is a lot of secret features :smile:

**Comment by NoahjChampion** [comment]
NO problem. I will help out on documentation and video tutorials. I just need to get everything grouped together and understand the options so I can explain in a nice video/documentation. 

I think I understand almost everything so far, at least the field options and set ups.

**Comment by Codestar** [comment]
Super! :+1:  It will be great really! :wink: I get happy. Yes, as you said. you can do it, when you understand everyhing about framework controls. :100:

**Comment by Codestar** [comment]
Hey btw, i changed `menu_type` param. now usage is:

```php
$settings = array(
...
    'menu_type'     => 'submenu', // removed here "add_" and "_page"
...
);
```

Because we are getting theme check plugin error.. see https://github.com/Codestar/codestar-framework/issues/227
