### ISSUE TITLE
Feature Request: 'type' => 'file_upload'

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#272]
**Feature Request:** New Field Type

`'type' => 'file_upload'`

This would look like below (Wordpress file import file upload field)...
<img src="https://monosnap.com/file/NcYymPBUu1RUqEU8S4vHdRTl3JWWxQ.png">

Then author's can take some action on the uploaded file or run other options like import options. 

I thought this one through quite a bit and made a Gist of options and examples. \
Hopefully it is a good idea.

Let me know what you think :) ??
@Codestar 

@ https://gist.github.com/NoahjChampion/a3e5284ede579592d8329ab13b8eb902

**Comment by Codestar** [comment]
Yes why not, i can add it. and nice gist explain. i will understand it totally :+1: Forked gist. and notes request :+1:

**Comment by Codestar** [comment]
Btw, what you think about new feature "Taxonomy Framework", take a look details: https://github.com/Codestar/codestar-framework/pull/212 make a beta test. i will release it.

**Comment by NoahjChampion** [comment]
@Codestar I updated the gist link to your fork, so comments, feedback, etc. can be placed there since you will be adding it. 

Here is my gist if it is ever needed for some reason @ (original gist) https://gist.github.com/NoahjChampion/a3e5284ede579592d8329ab13b8eb902

**Comment by Codestar** [comment]
Got it :+1:

**Comment by NoahjChampion** [comment]
@Codestar I checked out taxonomy... Nice and works! 

But, no metabox option? 

Can we still add option via metabox so we can have tab support? 

I tried settings from metabox.config and changed it to 'taxonomy' => 'category-test', but metabox UI and tabs (sections) don't work. ?

I think metabox and tab section should be optional on taxonomies, since they are so useful and used in most other places.

**Comment by Codestar** [comment]
Yes yes, i will add tab support in the future for taxonomy :wink: Now i started with simple taxonomy framework. it will be develop surely.

**Comment by NoahjChampion** [comment]
Ok, good deal. Everything seems to work from my quick test. When you update it or I get to taxonomies I will test more and let you know if any issues happen.

**Comment by Codestar** [comment]
Nice :+1:
