### ISSUE TITLE
Issue: Theme Load Method doesn't work

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#273]
I tried loading CF for theme usage and it doesn't work. There are some wrong references somewhere. 
I think it is because of plugin path codes? 

Example: 

If... 

`require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';`

`cs-framework-path.php` will not load because [Line #42](https://github.com/Codestar/codestar-framework/blob/master/cs-framework.php#L42) has...

`require_once plugin_dir_path( __FILE__ ) .'/cs-framework-path.php';`

**plugin_dir_path( __FILE__ )** won't load Framework Path (`cs-framework-path.php`) when used as theme. 

If I change...

`require_once plugin_dir_path( __FILE__ ) .'/cs-framework-path.php';`

to...

`require_once '/cs-framework-path.php';`

CF still does not load when used as theme. 

Have you found this issue?
-- I would pull request, but I'm not sure where the other issues are.

**Comment by Codevz** [comment]
Try it with `get_template_directory`

`require_once get_template_directory() . '/cs-framework-path.php';`

**Comment by NoahjChampion** [comment]
Thanks @Codevz 

The issue is not getting `cs-framework-path.php` to load. I tweaked things to load that file, but even when `cs-framework.php` and `cs-framework-path.php` are loaded, the Framework admin panel still doesn't load when used as a theme.

This is what I meant by maybe some internal (other) codes that reference plugin paths, maybe? Since the one line of code has a plugin reference I was tossing the idea that this might be the issue in other places perhaps. 

I'm still building my settings panel, so I went back to CF as a plugin, and if nothing is fixed or checked by the time I finish enough, then I can look more into the theme usage issue. But even when `cs-framework-path.php` loads CF still doesn't work. 

But I defintely wanted to mention it. 

I should not that I am using a child theme at the moment, but everything should load because I use query monitor and other dev tools and I can tell that both the CF files are loading. I just don't get the admin panel to load. As soon as I move it back to a plugin everything works as expected.

**Comment by Codestar** [comment]
Actually, i did not understand the issue. I am using the framework inside theme and no any issue.

```php
// only you need to put this on theme/functions.php
require_once get_template_directory() . '/cs-framework/cs-framework.php';
```

```php
require_once plugin_dir_path( __FILE__ ) .'/cs-framework-path.php';

// This is loading correctly. because let's see this plugin_dir_path source from wp core:
// CORE: wp-includes/plugin.php
function plugin_dir_path( $file ) {
  return trailingslashit( dirname( $file ) );
}
```
as we see, this function only getting dirname of file. no plugin directory. i think there is another issue. also see developer version https://github.com/Codestar/codestar-framework/tree/dev there is framework using inside theme. btw do not forget to disable CF plugin before try it inside theme.

I have not any idea really. because i am seeing first time this issue :smiley:

**Comment by NoahjChampion** [comment]
Hi. 

Yes, you are right about plugin_dir_path. I meant to take that part down, because I checked the Wordpress codex and saw that. I was too tired at night to edit my comment on the phone. 

I thought the issue might be CF as plugin and as theme, but I just tried CF again as theme usage (with no CF plugin) but CF still doesn't load for theme usage. 

It might be an issue with child theme or my theme framework I am migrating from. I will close this and try with default Wordpress theme a little bit later on.

**Comment by Codestar** [comment]
Yes, try it on a clean wordpress. if still same. report me :+1:

**Comment by NoahjChampion** [comment]
Hi. 

@Codestar 

**I tested this more:** 
I tested on my parent theme and child theme. The issue is using my child theme's framework. When using my child theme's framework CF won't show when using as a theme. It only shows when using as a plugin. 

**What happens?:**
I use 
```php
require_once get_stylesheet_directory() . '/frameworks/settings/load-framework.php';
// or
require_once dirname(__FILE__) . '/frameworks/settings/load-framework.php';
// or
require_once get_template_directory() . '/frameworks/settings/load-framework.php';
```

I am using [Dev Monitor](https://github.com/NoahjChampion/entuitions-dev-monitor) and I see `cs-framework.php` loads and `cs-framework-path.php` loads, but all all other CF files do not load. 

I see from this sreenshot...

![manage themes custom theme wordpress-screen-capture-18-05-16](https://cloud.githubusercontent.com/assets/6123260/15356052/594719dc-1cc4-11e6-99ca-af128a871021.png)

There are no debug errors :/ It just stops loading the other files.

Would you take a look?
-- I can provide theme or logins.

**Comment by Codestar** [comment]
@NoahjChampion 

Uh, interesting. hmm yes i need to see theme. you can send theme from routewp[at]gmail[dot].com

**Comment by NoahjChampion** [comment]
@Codestar  

I found a fix for this! 👍 

I am moving from [Runway Framework](http://runwaywp.com). When using Runway child theme, cs-framework won't load standard way because of custom `do_action`s I think. But if I place cs-framework in Runway's child theme framework folder, cs-framework loads correctly. 

See screenshot...

![functions php - cloud9-screen-capture-18-05-16](https://cloud.githubusercontent.com/assets/6123260/15361073/1211c25a-1cde-11e6-8ac5-b4a48424c853.png)

**Comment by Codestar** [comment]
wow nice :+1: i am happy :heart_eyes:

**Comment by NoahjChampion** [comment]
Me too :)
