### ISSUE TITLE
Idea/Feature Request: Media Upload Screen Fields

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#274]
See https://wordpress.org/plugins/media-extra-fields/

It would be nice to have by post type, so a portfolio post type can have custom image fields. 

Thoughts? 

Example: 
![media extra fields wordpress plugins-05-04-2016-km2gy](https://cloud.githubusercontent.com/assets/6123260/14302254/e8bc7004-fb6c-11e5-8149-8ae3def735c9.png)

Just an idea, but maybe too much or not needed as much?

**Comment by Codestar** [comment]
Yes why not, also i need this feature in my themes. for eg. i used this in my last theme.

![support_14-22-18](https://cloud.githubusercontent.com/assets/1313301/14314936/0fb54d48-fc03-11e5-8ea3-1d1e902a4f42.png)

Ok, i will try to add it future :+1:

**Comment by NoahjChampion** [comment]
Nice! Exactly! 

So it will be in v1.1 since you need it in your theme, or in a later version?

**Comment by Codestar** [comment]
I am not sure, yet :smiley: but i will try to add this :+1:
