### ISSUE TITLE
Is there a way to load php file from field or options array on into CF?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#276]
Hi. 

Is there any way we can load a custom php file in a CF page or section so we can do custom work from that file? 

I have a breadcrumbs plugin and I would like to load it's options panel into CF, so I don't need another admin menu and everything is in CF.

**Comment by Codestar** [comment]
Hi,

You can add a new custom field. like this http://codestarframework.com/documentation/#how-to-add-new-field and you can add include code there. for eg.

```php
// new field
class CSFramework_Option_include extends CSFramework_Options {

  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }

  public function output(){

    include 'x.php';
    // or
    include $field['file'];

  }

}

// config
array(
  'id'    => 'include_1',
  'type'  => 'include',
  'title' => 'Include a PHP',
  'file' => 'x.php',
  // or
  'file' => get_template_directory_uri() .'/x.php',
),
```

But i think you can not move a plugin options to framework panel. you need to extra effort for integration.

**Comment by NoahjChampion** [comment]
Ok. Yeah, this doesn't work for php files. 

A function will break the CF panel. 

But as a good note... you can include a HTML file which is good. I wanted to do that so I can add a nice welcome splash page in CF section and contact form. 

Thanks for the instructions on extending fields. 

To test I just used... 

```
class CSFramework_Option_help_page extends CSFramework_Options {
	
	public function __construct( $field, $value = '', $unique = '' ) {
		parent::__construct( $field, $value, $unique );
	}
	
	public function output(){
		echo '<iframe src="https://docs.example.com/" name="help_docs" scrolling="auto" frameborder="no" align="center" height = "1200px" width = "100%"></iframe>';
		// OR simple local .html file include
		include 'index.html';
	}
}
```

**Comment by Codestar** [comment]
Yes, it is flexible. :+1:
