### ISSUE TITLE
Compatibility Request: WordPress Dynamic CSS

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#279]
Hi. (you might like this plugin for your theme's dynamic css?)

I found this awesome tool, but I can't get it to work with `cs_get_option`

Can you check it out and see what the issue might be, if its a simple fix? 
- The cs_get_option is not returning the value output for the dynamic css. 

This tool is like [Sass](http://sass-lang.com/guide#topic-2), but easier (and lighter) I think. 

The plugin is [WordPress Dynamic CSS](https://wordpress.org/plugins/wp-dynamic-css/)

Here is how it works in simple form (like Sass but Wordpress only)...

I have... 

```
// This loads the plugin
require_once (CUSTOM_THEME_BACKEND_PATH . CustomTheme_Constants::ASSETS . '/css-generator/bootstrap.php');
```

Then I have function...

```
wp_dynamic_css_set_callback( 'my_dynamic_style', 'my_dynamic_css_callback
function my_dynamic_css_callback($var_name) {
  return cs_get_option($var_name);
}
```

Then I enqueue my dynamic css styles like... 

```
wp_dynamic_css_enqueue( 'my_dynamic_style', 'path/to/my-style.css' );
```

Then my dynamic css file has...

```
body {
	background-color: $Website_Background_Background_Color_Value !important;
}

// And this equals CF option 'id' => 'Website_Background_Background_Color_Value',
```

But my css output comes out like...

```
body {
	background-color:  !important;
}
```

**Comment by SantiagoInteractive** [comment]
Have you tried not defining your options in capitalize?

**Comment by NoahjChampion** [comment]
@SantiagoInteractive 

No, but I will try that shortly and see. Thanks for the pointer.

**Comment by NoahjChampion** [comment]
@SantiagoInteractive 

<img src=http://i.giphy.com/VUYTIed7MnjoY.gif">
