### ISSUE TITLE
csf_{$prefix}_save_after Action Issue

### ISSUE THREAD

**Issue by thekendog** [Codestar/codestar-framework#28]
I've got two fields, a username and password field, that is used to connect to an external API.  I'm using the csf_{$prefix}_save_after action to connect to this API upon save and see if it works.  Here's my setup...

- I enter credentials and save.  I have a function hooking into the csf_{$prefix}_save_after action.  If the credentials work and connection to the API works, I update an option (using update_option) to true.  Otherwise, it's false. 

-  Just before the CSF::createSection, I am reading this option and setting style and content variables based on it.  If true, it's a success class.  If false, it's danger.  The submessage field uses these variables.

-  I'm not using ajax for the form.  I enter valid credentials and hit save.  When the page reloads I expect the submessage to be a success, but it still shows as danger.  Only when I refresh the page does the field turn to success.  It's like the option is not being read in time or something.

Hopefully this makes sense....

**Comment by Codestar** [comment]
Hi,

Yes This is make sense. But I need to see coding for check detailed. btw, Thanks for purchasing. Let's go support forum and start a new topic for this subject. You can share the code for I check it.

Regards, Codestar

**Comment by blikr** [comment]
I would like to ask how csf_{$prefix}_save_after is used? Is there any sample code available

**Comment by blikr** [comment]
I want to update the cache after saving the theme settings, but currently add_ Action csf_ {$prefix}_ Save_ Error reported after
