### ISSUE TITLE
Disable browser scrolling while jQuery UI modal dialog is open

### ISSUE THREAD

**Issue by santiagointeractive** [Codestar/codestar-framework#28]
When you scroll to a shortcode modal dialog window, if you reach bottom then entire body scroll too, so you get your dialog window moved and it's very annoying.

To fix this kind of issue I recommend adding some css on body <code>overflow: hidden</code> while open and <code>inherit</code> on close.

I have done this like that:

<pre><code>
open: function() {
    $("body").css({ overflow: 'hidden' });
// -- here you leave the rest of function content --
},
close: function() {
    $("body").css({ overflow: 'inherit' });
// -- here you leave the rest of function content --
}
</code></pre>

Into <code>/assets/cs-framework.js</code> at about 757 line, where dialog window is triggered.
Would be great to have this already in the framework to not change this on every update.

Thank you!

**Comment by Codestar** [comment]
Nice bro, merged the request :+1:
