### ISSUE TITLE
Compatibility Request or How To Tweak?: Clearing Comet Cache on CF Save

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#280]
In my previous Framework I saw easily how to implement Comet Cache's clear cache api so that when saving theme settings the cache would be cleared, but with CF saving ajax, I'm not sure how to. I tried a few things, but nothing worked. 

How can I use the code below to make sure the cache is cleared when CF settings are saved?

```
add_action( 'save_post', 'my_custom_clear_cache', 10, 1 );
function my_custom_clear_cache( ) {
    comet_cache::clear();
}
```

And if you tell me what needs to be done, I can make sure to test other caching plugins later to make sure the caches clear for them too when saving and update you about it... W3, etc.

**Comment by Codestar** [comment]
Take a look here [framework.class.php#L246](https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php#L246) you can use this actoun for CF settings are saved.

```php
function my_custom_clear_cache( ) {
    comet_cache::clear();
}
add_action( 'cs_validate_save', 'my_custom_clear_cache' );
```

**Comment by NoahjChampion** [comment]
Thanks. I looked at the before posting and I will give this a try again. I believe I tried it, but the settings weren't saving afterwards, but I may have only used add_filter and not add_action. 

I'll bookmark this and try again later and update. I'll close this for now though. Appreciate it.
