### ISSUE TITLE
Check if framework already included

### ISSUE THREAD

**Issue by belicslavko** [Codestar/codestar-framework#285]
Hi,
Thank you for the best lite framework. I am using your framework in a plugin and I have a problem. How to check if a framework is already included in other theme/plugin.
I try from my plugin with` class_exists('CSFramework')` or `function_exists('cs_framework_init')` or `defined( 'CS_ACTIVE_FRAMEWORK' )` without sucess?

Thanks!

**Comment by Codestar** [comment]
Hi,

Thanks for your opinion about framework, and yes. i am working on this feature. All users need this feature. Multiple usage config will available in the future... :wink:
