### ISSUE TITLE
Add filter 'cs_framework_settings' error

### ISSUE THREAD

**Issue by belicslavko** [Codestar/codestar-framework#286]
Hi, I have a problem with adding extra framework settings filter.
```php
function extra_cs_framework_settings( $settings ) {

    $settings           = array(
        'menu_title'      => 'My Plugin',
        'menu_type'       => 'menu',
        'menu_slug'       => 'myplugin',
        'ajax_save'       => false,
        'show_reset_all'  => false,
        'framework_title' => 'MyPlugin',
    );

    return $settings;
}

add_filter( 'cs_framework_settings', 'extra_cs_framework_settings' );
```

`Warning: call_user_func() expects parameter 1 to be a valid callback, function 'menu' not found or invalid function name in /wp-content/themes/mytheme/codestar-framework/classes/framework.class.php on line 323`

But when using code from an earlier version of codeframework the error does not appear.
Example:
```php
$settings = array(
    'menu_title' => 'My Plugin',
    'menu_type' => 'add_theme_page',
    'menu_slug' => 'myplugin',
    'ajax_save' => false,
);
```
It seems to be a problem with 'menu_type'?

**Comment by Codestar** [comment]
Hi,

I made an update about menu_type. are you sure for using framework version 1.0.1 ?

```php
// v1.0.0 usage
'menu_type' => 'add_theme_page',
```


```php
// v1.0.1 usage
'menu_type' => 'theme',
```

If you using `'menu_type' => 'theme',` this. do not forget to update [framework.class.php](https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php)

Btw, i advise, update all framework files :wink: You can see latest version here https://github.com/Codestar/codestar-framework/releases

**Comment by belicslavko** [comment]
Hi Codestar, thank for an answer, I figure out that I am using a plugin with framework version 1.0.1 and theme with framework version 1.0.0. First of all, I check if a framework exists in other plugin/theme then include file.  

But now I need to check version for a framework because settings are different. Do you have any hook for framework version check?

**Comment by Codestar** [comment]
You can use ```CS_VERSION``` define variable. for eg:

```php
echo CS_VERSION;
```

Btw, it works after update ? i did not understand, tell me result :wink:

**Comment by Codestar** [comment]
I improved plugin versions now, you can re-download it :smile: thanks for report.

**Comment by belicslavko** [comment]
Yes it now works, thanks

**Comment by Codestar** [comment]
Nice. you're welcome :wink:
