### ISSUE TITLE
Uploaded image preview?

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#287]
I would like to thank you for this awesome project.
I wonder if you could implement a upload preview for uploaded images.
Vafpress has something like that but I want to use this package.
Thank you.

**Comment by Codestar** [comment]
Thanks for nice words about framework. hmm, did you try image field? for eg.

```php
array(
  'id'        => 'image_1',
  'type'      => 'image',
  'title'     => 'Image',
),
```

**Comment by cansanet** [comment]
Nice, it shows image but When saved image disappears.

**Comment by Codestar** [comment]
`Nice, it shows image but When saved image disappears.` ups? i tested image field on my localhost, image showing normally after click to save. interesting.

Btw, your example is `upload` field. hmm there is not preview option because this upload not only for image, there is you can upload video, image, font, zip etc. but i am thinking to add preview feature. take a look this request #232 

Hmm, ok, i will add this feature in next framework update 1.0.2 :wink:

**Comment by cansanet** [comment]
Maybe some function can check if upload is image and if it is image than shows preview of image, but if it is video or pdf maybe can show a video icon or pdf icon? only suggestion

**Comment by cansanet** [comment]
After I upload my theme on themeforest I would like to make some donation to this awesome project. Is there an option somewhere

**Comment by Codestar** [comment]
Yes yes surely, i am thinking same :+1: when i have free time, i will add this feature :+1: Noted it.

**Comment by smEunus** [comment]
Can i set default image for image section?

**Comment by mehedi-sharif** [comment]
I want to use upload option instead of image . But I am not able to show image in my theme. can you please me to echo the image. 
`<?php
	            $gallery = cs_get_option( 'slider_img' );

	            if( ! empty( $gallery ) ) {

		            $ids = explode( ',', $gallery );

		            foreach ( $ids as $id ) {
			            $attachment = wp_get_attachment_image_src( $id, 'full' );
			            var_dump( $attachment );
			            ?>
                        <h1>
                            test
				            <?php echo $id['slider_img'];  ?>

                        </h1>
			            <?php
		            }

	            }

	            ?>`
It just show some number. What I am missing. 
Thanks

**Comment by partharoy** [comment]
@mehedi-sharif your echo is not right . Please echo as <?php echo '<img  src="'. $attachment[0] .'" alt="" />' ; ?>

**Comment by stivoox** [comment]
@Codestar : any update about this ??
