### ISSUE TITLE
Easiest way to view VAR_DUMP, PRINT, or ECHO option values :)

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#288]
Reference conversation: #266 

Link: [Wordpress.org Page](https://wordpress.org/plugins/inspector/)

Link: [Video Screencast](https://www.youtube.com/watch?v=2T3N_ankM-s)

##### Inspecting Option Screenshots:

![option inspector custom theme - baby wordpress-14-04-2016-hxhrq](https://cloud.githubusercontent.com/assets/6123260/14529299/d27ac4f6-0221-11e6-9799-a40f2e452338.png)
![option inspector custom theme - baby wordpress-14-04-2016-mniip](https://cloud.githubusercontent.com/assets/6123260/14529360/2e65552e-0222-11e6-9268-c3d634cf7534.png)
![edit page custom theme - baby wordpress-14-04-2016-ujtdw](https://cloud.githubusercontent.com/assets/6123260/14529461/a4506058-0222-11e6-8d34-e91f26189301.png)
![edit page custom theme - baby wordpress-14-04-2016-qzcek](https://cloud.githubusercontent.com/assets/6123260/14529520/f555e428-0222-11e6-9366-819375cf5230.png)

##### "Help" Tab, Screen Information Screenshot:

![edit page custom theme - baby wordpress-14-04-2016-pt6ny](https://cloud.githubusercontent.com/assets/6123260/14530880/ebe24548-0228-11e6-92fd-2471eae45738.png)

**Comment by NoahjChampion** [comment]
@Codestar

**Comment by Codestar** [comment]
Yesss. nice plugin :wink: helpful :100:
