### ISSUE TITLE
Multiple framework instances

### ISSUE THREAD

**Issue by filipeleira** [Codestar/codestar-framework#289]
Hi!

When this feature will come?

But first, thank you for this amazing thing! I'm developing with your framework from 8 months!

Currently i'm working on a huge project, which includes a premium WP theme and plugin. I want to use your framework on both, but, they should work alone...

Would be nice to have more control over options page (flexibility to create subpages, etc..), I think it's a good solution for plugins/themes.

I'm very excited to show you all my custom fields, features and modifications to your framework, I hope to finish my project soon!

Thank you!

**Comment by Ansif** [comment]
Great! :+1:
@filipeleira what type of custom fields you already added with CS framework?

**Comment by NoahjChampion** [comment]
This is always a plus 1 :) 

@filipeleira if you are looking to add CF as submenu pages check out #271 

@Codestar I sent you an email about this. 
- I have a marketing strategy to help CF get more authors and contributions, but we need for multiple instances of CF and library only loaded once so authors will be more willing to join. See email "`Github, Codestar Framework: Noahj`" for details.

**Comment by filipeleira** [comment]
@NoahjChampion thank you!

@Ansif I have an custom google font previewer (with size, height, line-height and alignment controls), inline select, inline sorter, url... I modified some default fields too, like heading (added a description field), image select (retina support), icon (added + families and live icon search), slider (added unity) + all elements redesign.

![inline_sorter](https://cloud.githubusercontent.com/assets/15265636/14578582/2508268c-0362-11e6-9a59-965a2b47ecce.jpg)
![font-preview](https://cloud.githubusercontent.com/assets/15265636/14578583/25098dce-0362-11e6-92af-6f7bd03cb44e.jpg)

**Comment by NoahjChampion** [comment]
@filipeleira welcome and this looks nice, sounds good! 

When do you hope to release your theme?

**Comment by Codestar** [comment]
@filipeleira 

Wow, your re-design looking awesome really. i liked it. i want to see it after release your theme. i wonder it :100:  Great modifications.

Btw, about `Multiple Framework Instance`. also i need this really. i am thinking and searching some ideas for multiple instance. but i will add this feature surely soon.

You know, time is problem. i am working on a new theme, when i release it, i will add more features on framework :wink:

**Comment by filipeleira** [comment]
@Codestar yeah, you're right, time is the problem. I work in a agency at day and freelancer at night, so time is precious. :smile:

This is the very time that i'm developing for themeforest, and your framework saves me a lot.. If you need some help with visuals, please ask me, would be a pleasure to help you designing your framework and be a part of this project. :+1: 

@NoahjChampion Thank you! I'm planning to launch my theme on June/July.

**Comment by screets** [comment]
@Codestar Hello guys.. Any update on this?

**Comment by omarkasem** [comment]
Any update on this?

**Comment by screets** [comment]
-- Please reply above this line --


Hey Codestar/codestar-Framework, 

 We got your help request! One of our agents will respond to you, asap
(usually in 1 BUSINESS DAY). Note that we don't work on weekends. 

 However, if we release a major update recently, we are following the
issues. 

 For support questions, please also email us SCREETS API KEY which is
required for support questions. If you already included in your
message, you don't need to do anything else.

**Comment by varunsridharan** [comment]
@omarkasem @screets 

Would you like to have a look at http://github.com/wpsf/wpsf ?

**Comment by Codestar** [comment]
Coming soon :)
