### ISSUE TITLE
taxonomy custom meta field  save problem

### ISSUE THREAD

**Issue by apurbajnu** [Codestar/codestar-framework#290]
I have added a image field in my custom taxonomy. But When I am going to save , no response after saving data.  All the value is still in the input box. After refresh I can see my saved data. What should I do here?

**Comment by Codestar** [comment]
Actually, it is working correctly. there is no issue for saving. only problem is clear form fields after click "add" button. hmm text, textarea fields clearing automatically, but custom fields do not clearing automatically. i will improve it surely ;) only i am thinking an idea for clear my all fields.

```php
;(function ( $ ) {
  'use strict';

  $(document).ready( function() {

    $('#addtag').each( function(){

      var $this   = $(this),
          $submit = $this.find('#submit'),
          $form   = $this.parents('form');

      $submit.on( 'click', function() {

        // this validateForm function from core (common.js). if you get error, remove this line.
        if ( ! validateForm( $form ) ) { return false; }

        // clear image field after click  "add"
        $this.find('.cs-image-preview').addClass('hidden');
        $this.find('.cs-field-image input').val('');

      });

    });

  });

})( jQuery );
```

It works?

**Comment by Codestar** [comment]
Today, I worked on this issue and commit in dev repo. this issue fixing in v1.0.2

But you can update your cs-framework.js file until v1.0.2 release. you can download new file from [cs-framework.js](https://github.com/Codestar/codestar-framework/blob/dev/cs-framework/assets/js/cs-framework.js) 

and commit details https://github.com/Codestar/codestar-framework/commit/80d8c44004d41f4cb3043c1aa7cc32d66d6e456b

Make a beta-test and tell me its works?

**Comment by apurbajnu** [comment]
I have used image field here. After adding your given script. It only make blank image field. But rest of field value is still there. Also I can't see recently added category without refresh.

**Comment by Codestar** [comment]
hmm, interesting. i am trying it on my localhost, it is working correctly, hmm can you give me your taxonomy.config.php via https://gist.github.com/

I want to try your config on my local.

**Comment by apurbajnu** [comment]
https://gist.github.com/apurbajnu/57da89d49dbd7612b401d0b30ebf9eda

**Comment by Codestar** [comment]
See the result in my localhost:

![support_20160420173101](https://cloud.githubusercontent.com/assets/1313301/14678301/ccb2d5b2-071d-11e6-8510-4fc7ab143e7d.gif)

**Comment by apurbajnu** [comment]
after updating to WordPress 4.5 is't working fine with your given Script. Thank you very much.

**Comment by Codestar** [comment]
Interesting, it is working normally in my local. Let's test developer version... download https://github.com/Codestar/codestar-framework/archive/dev.zip and extract it on your local themes folder.

After active Codestar Framework theme, go to CPT -> Categories and test it.
