### ISSUE TITLE
Chosen Jquery tweak for 'type' => 'background' dropdown menus

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#291]
Can you provide a javascript or php tweak that can make `'type' => 'background'` dropdown menus use the Chosen Jquery look?

See screenshot explanation below to help...

![custom theme custom theme - baby wordpress-20-04-2016-vzgwy](https://cloud.githubusercontent.com/assets/6123260/14674569/b9515eb2-06d2-11e6-8cb5-2e7ef2eb833b.png)

I'm using all chosen select and would like `'type' => 'background'` dropdown menus to use the chosen look too.

**Comment by Codestar** [comment]
I do not advise chosen for simple selectors. that's what i mean #270 because chosen is affecting load time badly. Only recommended chosen for long options selects.

**Comment by Codestar** [comment]
Btw, i checked Chosen plugin version after your message, and i updated it from 1.4.2 to 1.5.1

Thank you for reminding me :tada: :smile:

**Comment by NoahjChampion** [comment]
Hey welcome. 

Ok, so I can update and see if that improves the loading speed maybe?

**Comment by Codestar** [comment]
I updated it on dev repo https://github.com/Codestar/codestar-framework/commit/f028c1952dbcc3d947a63bbbf3d62e111789bdce but i am not sure for any improves for loading speed. actually this is not an issue for chosen. it is normal. there is working a lot of things for generate selector.

**Comment by NoahjChampion** [comment]
Ok. 

I think the issue is with Typography. 

I tested loading speeds. 

I removed all `'class' => 'chosen'` and the loading speed is the same. But Typography uses chosen. 

Can you give me a way to use Typography without chosen so I can test loading speed for that? 

I think it would be best to move Typography to separate page so other items load faster.

**Comment by NoahjChampion** [comment]
Maybe? 

After testing add... 
`cs_locate_template('config/framework.typography.config.php');` 
so...
`cs_locate_template('config/framework.config.php');` 
loads faster because typography slows down loading by itself.

**Comment by Codestar** [comment]
Yes nice, Actually you can use your own modifyed version of typography field. it is easy :wink: but i will think an idea for background chosen selectors like `'class' => 'chosen'` in config :+1:

**Comment by NoahjChampion** [comment]
Ok. 

This was an idea, but when I try `cs_locate_template('config/framework.typography.config.php');` it doesn't load. Should it? I thought Multiple Instances (@#289) doesn't work?

**Comment by Codestar** [comment]
You can not load twice. because multiple instance not supporting, yet. it will come soon. if you need to load extra fields. you can use filter method like this:

```php
// framework options filter example
function extra_cs_framework_options( $options ) {

  $options      = array(); // remove old options

  $options[]    = array(
    'name'      => 'section_unique_id',
    'title'     => 'First Section',
    'icon'      => 'fa fa-heart',
    'fields'    => array(
      array(
        'id'    => 'option_id',
        'type'  => 'text',
        'title' => 'First Option',
      ),
      array(
        'id'    => 'another_option_id',
        'type'  => 'textarea',
        'title' => 'Secondary Option',
      ),
    )
  );

  return $options;

}
add_filter( 'cs_framework_options', 'extra_cs_framework_options' );
```

**Comment by NoahjChampion** [comment]
Ok. 

But there is a problem for not loading the library twice. 

I spoke with a developer and he said there is this issue for example... 

Plugin A = CF v1.0
Plugin B = CF v2.0

Plugin A = CF v1.0 loads first
Now Plugin B = CF v2.0 library won't load. 
Now Plugin B = CF v2.0 can't use CF v2.0 features because Plugin A loaded first and has CF v1.0. 

Thoughts? 

He said the only way is to use a [Namespaces](http://php.net/manual/en/language.namespaces.rationale.php) for each plugin or to load the framework separately as a plugin so all instances use the same plugin framework files. 

Thoughts?

**Comment by NoahjChampion** [comment]
I've never used Namespaces, but I've seen them and I think they are easy.

**Comment by Codestar** [comment]
Yes yes, i will find a solution for this problem soon :wink:
