### ISSUE TITLE
Doesn't process p tag in Wysiwyg type

### ISSUE THREAD

**Issue by Nur-jaman** [Codestar/codestar-framework#292]
I am trying to dynamic a static page by codestar Wysiwyg editor. in this page there are 6 block of text with different 6 `<p>` tag so that it's nice formatting but when i paste text in codestar  Wysiwyg editor and save, in font-end all text merge together and when i inspect element i saw it's remove p tag. how can i add p tag in Wysiwyg ? is there any option to add `<br>` ?
Please @Codestar @SantiagoInteractive @demartini @anhskohbo help me.
Many thanks 
Nur

**Comment by NoahjChampion** [comment]
@Nur-jaman check out #15 

It has what you are looking for?

`'sanitize' => false` Documentation @ http://codestarframework.com/documentation/#textarea

**Comment by Codestar** [comment]
@Nur-jaman follow the @NoahjChampion solution :+1:

**Comment by Nur-jaman** [comment]
@NoahjChampion @Codestar many thanks for quick reply.
it's still doesn't work :(. here is my code, is this correct or where i need to add ` 'sanitize' => false,` `array(
    'id'    => 'service_bottom_setion',
    'type'  => 'wysiwyg',
    'title' => 'Service bottom setion text',
    'sanitize' => false,
    'settings' => array(
                    'textarea_rows' => 15,
                    'tinymce'       => true,
                    'media_buttons' => true,
                  ),
    
   ),`

Pls take me out :(

**Comment by Nur-jaman** [comment]
OMG! now i am facing another problem now my value save but don't update :(. it's doesn't show in front-end. example i developed social link input and my client when insert link and update it's stick with default value https://www.facebook.com/. @Codestar @NoahjChampion please please please help me i am in a big trouble i love this framework i never ever wanna switch to another one. :(

Advance thanks

**Comment by NoahjChampion** [comment]
@Nur-jaman 
@Codestar can let you know if you are doing something wrong with the `'sanitize' => false,`. I've ever used it. I just took the time to go through all the Github issues so I would know how to work with issues others already reported. 

I'm not sure if @Codestar is available on the weekends. But I will try to help. 

Maybe the issue is sanitizing the `wsysiwyg` type? If you look @ [Issue #24 and This Comment](https://github.com/Codestar/codestar-framework/issues/24#issuecomment-74655945) it looks like your code is correct. Until @Codestar can respond try using `'type' => 'textarea'` instead and `'sanitize' => false`. 
-- As a sidenote to help. You should probably paste your config file in a Gist @ https://gist.github.com/ and paste that gist link here to look at and test. 

For your other issue, if what you developed in WAMP worked and still works, then you probably have a plugin or Wordpress version conflict in your client's site. You should troubleshoot all plugins first on your client's site, if it worked in WAMP before. Then report back.

**Comment by Nur-jaman** [comment]
@NoahjChampion many thanks man for your help. really appreciate. let me try and back to you. 
is this ok if i share my theme and database with you so that you can check ?
Many thanks again 
Nur

**Comment by Codestar** [comment]
@NoahjChampion I am available always, but i was in festival :smile: I am here now..

@Nur-jaman Actually there is not sanitize for `wsysiwyg` I think there is an another conflict. I am trying to add html tags on my localhost, i can add it. no problem ?

![support_12-16-24](https://cloud.githubusercontent.com/assets/1313301/14813094/c756a73a-0ba8-11e6-8684-39d96e90847f.png)

![support_12-16-33](https://cloud.githubusercontent.com/assets/1313301/14813097/ca57757c-0ba8-11e6-8d08-6104aea7e9ec.png)

I can see it normally?

**Comment by Nur-jaman** [comment]
@Codestar @NoahjChampion pls help me of my second issue "   
now i am facing another problem now my value save but don't update :(. it's doesn't show in front-end. example i developed social link input and my client when insert link and hit save it's stick with default value like https://www.facebook.com/. but it was working fine when i developed my theme in local wamp server . @Codestar @NoahjChampion please please please help me i am in a big trouble i love this framework i never ever wanna switch to another one. :(

Advance thanks


"

**Comment by Codestar** [comment]
Ok, i will help you more, give me your wordpress admin information via routewp[at]gmail.com i will check it for you. btw, which option not working write in mail :wink:

**Comment by Nur-jaman** [comment]
@Codestar you guy so awesome. love to you. mail sent. if you go to codestart theme option. which one i name as admin then you can see some text field with some default value those value are not updating in front-end when i hit save :(

**Comment by Codestar** [comment]
@Nur-jaman fixed, but i am not sure where is the problem or whats happened there before fix. Only i added this on functions.php for reset options. and removed again.

`delete_option( '_cs_options' );` 

after this reset operation, it is working normally. btw, when i check debug for `get_option( '_cs_options' );` i saw default config data ? how it is possible, interesting really :smile: 

Ok, check it now, if you see it again, report me :+1:

**Comment by Nur-jaman** [comment]
Wow it's working great. many many many many thanks to @Codestar  and @NoahjChampion. same to me it first time work fine but when i put it in live it didn't work. btw really appreciate your help guys .
Many thanks  again

**Comment by Codestar** [comment]
You're welcome @Nur-jaman 

Cheers :+1:
