### ISSUE TITLE
Get error after updating to latest version?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#297]
Hi,

I get following error after updating to latest version : 
Fatal error: Call to undefined function cs_get_var() in ../cs-framework/classes/taxonomy.class.php on line 55

I made some custom changes in custom path **functions** folder. When i rename that folder then that issue is no longer available. I've checked each and every files which is fine and little changes only. As you can see in following files, you'll get my custom changes from **Custom Changes** commend line. Just for easy to find my changes.

That changes files are : 
[actions.php](https://gist.githubusercontent.com/Ansif/12b0dc191a39ed5db05d01b00e94e2e2/raw/61da49e6900642cc4c011d48150b123f896c6fe4/actions.php)
[enqueue.php](https://gist.githubusercontent.com/Ansif/e64276bc57b200223261e75ac92ccb34/raw/cd79fd43dcc76a318aeef66b4e13285a4f46bede/enqueue.php)
[helpers.php](https://gist.githubusercontent.com/Ansif/9e928f2bc9fa5e563182bc43ed0c2a45/raw/6b1ea54f77dbf3a6662bd5c01cee26ffcd63ef66/helpers.php)

Thanks! :+1:

**Comment by Codestar** [comment]
Hi,

Uh, i added `cs_get_var` on [helpers.php#L176-L190](https://github.com/Codestar/codestar-framework/blob/4aa7c64aa8f4847dcb6aac7bc2165d43d5e931f9/functions/helpers.php#L176-L190)

You need to add this function on your edited helpers.php :+1: you understand it?

**Comment by Ansif** [comment]
Ok, thanks! It's fixed! :+1:

**Comment by Ansif** [comment]
One more thing, can we able to add `menu_type` as our custom created menu page?

add_menu_page and add_submenu_page?

**Comment by Codestar** [comment]
Yes surely, also i am using it on my one theme. for eg:

```php
$settings           = array(
  'menu_parent'     => 'your-custom-created-menu-slug', // [see] this is your custom menu_slug
  'menu_title'      => 'Theme Options',
  'menu_type'       => 'submenu', // [see] set as submenu
  'menu_slug'       => 'my-options',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>',
);
```

Got it?

**Comment by Ansif** [comment]
Awesome! It worked! :100:

**Comment by Codestar** [comment]
Great :+1:
