### ISSUE TITLE
How to add extra theme option

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#298]
**First off, hanks much for developing CS. 100% in love with CS!**

Is it possible to add extra theme option without changing original framework files?

**Comment by NoahjChampion** [comment]
Hi @pn1gh2 

Yes. Try… 

```
function Your_Unique_Function_Name_Here($options) {
	$options[] = array(
		'title'		=> 'Top_Tab_Name', // Top level title name here
		'name'		=> 'slug-name-here', // Unique slug name here
		'icon'		=> 'fa fa-cogs', // Icon name here
		'sections'	=> array(
			// @SUBMENU => Text
			array(
				'title'	=> 'Sub_Tab_Name', // Sub level title name here
				'name'	=> 'sub-tab-slug-name-here', // Unique slug name here
				'icon'	=> 'fa fa-font', // Icon name here
				'fields'=> array(
					// Start your new fields
				
				),
			),
		),
	);
	return $options;
}
add_filter('cs_framework_options', 'Your_Unique_Function_Name_Here', 1);
```

**Comment by pn1gh2** [comment]
Hi Noah

Thanks for the snippet and pointing out setting filter. I do appreciate that!

But I'd like to create new (second) theme option outside from original framework option. Would that be possible in CS?

**Comment by NoahjChampion** [comment]
Hi @pn1gh2 

Unfortunately, no, not yet. It is planned for soon release once Codestar sees how he wants to implement it. If you have any ideas you can share.

Here is Codestar’s exact words about “Multiple Framework Instances” in [Issue #289](https://github.com/Codestar/codestar-framework/issues/289#issuecomment-210792176)

> ...`Multiple Framework Instance`. also i need this really. i am thinking and searching some ideas for multiple instance. but i will add this feature surely soon.
> 
> You know, time is problem. i am working on a new theme, when i release it, i will add more features on framework.


But, for now… you can duplicate the library and change the classes and function prefixes if needed.

**Comment by pn1gh2** [comment]
Thanks again Noah. 

Hope Codestar will add "Multiple Framework Instances" soon.

**Comment by NoahjChampion** [comment]
@pn1gh2 No problem, you’re welcome. 

I mentioned @Codestar so he will at least see your request since you closed the ticket :)

**Comment by pn1gh2** [comment]
I'm using OptionTree framework. 

Thinking to move everything to CodeStar. IMHO, working on CS - theme options look much organized. Surprisingly, same exact theme options on CodeStar and OptionTree, CS uses less queries.

@Codestar - **you should think about crowdfunding for CodeStar Framework.**

**Comment by Ansif** [comment]
@pn1gh2 Crowd Funding is nice idea! 👍 

But it needs more popular(codestar framework) than now, like Redux framework everyone know in WordPress community. Because of the power usage in that framework.

Redux also released their Crowd Funding method, and they already successful in 111% of their needed fund! 😃 

You see here : https://ideas.reduxframework.com/campaigns/complete-customizer-integration/

Thanks! 👍

**Comment by Codestar** [comment]
Thanks for nice words guys. i am motivated for development framework. I am planing a lot of new features but as you know, time is problem. Redux is team, I am alone. imagine :smile: 

Thanks for ideas, i noted this ideas for future :wink: 

Btw, Multiple instances will come asap. i am working on it.

Cheers :wine_glass:
