### ISSUE TITLE
Action before saving options

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#299]
Hi, 

I'm wondering there is any action before saving options, I'm asking this because i'm adding product activation text field in theme options and buyers should activate theme with their purchase code before saving options. If they do not activate it, then theme options shouldn't save.

I hope you can help me or show me better solution.

Thanks

**Comment by Codestar** [comment]
Hi,

If i understand right, you can use this method.

```php
// Product activation text field in theme config
array(
  'id'    => 'purchase_code',
  'type'  => 'text',
  'title' => 'Enter your purchase code',
),
```

```php
// Action for check purchase code is verify
function _my_validate_purchase( $request ) {

  $code = $request['purchase_code'];

  // 
  // do not save options if not verify purchase
  // 
  if( empty( $code ) {

    return;

  } else {

    // But it will check API always, it is bad.
    if( ! verify_purchase_api( $code ) ) {

      return;

    }

  }

  return $request;

}
add_filter( 'cs_validate_save', '_my_validate_purchase' );
```

Actaully, i do not advise this methods. I advise create a custom admin page for activation product. and if user has activated product, include framework, if not, do not include framework. :wink: 

Or i did not understand request well? Expain it more =)

**Comment by Codevz** [comment]
Hey man really thanks :+1: this is what i was looking for. I know this is not a good solution but i'm working for finding best way.

**Comment by Codestar** [comment]
You're welcome bro, if this is what you was looking for, ok i developed this code a little for avoid check api always.

```php
// Action for check purchase code is verify
function _my_validate_purchase( $request ) {

  $code = $request['purchase_code'];

  // do not save options if not verify purchase
  if( empty( $code ) {

    return;

  } else {

    // Get verify
    $verify = ( ! empty( $request['verify'] ) ? true : false;

    // If user purchase code changed, check api verify again.
    if( $code !== cs_get_option( 'purchase_code' ) ) {
      $verify = false;
    }

    // Avoiding for check API Always
    if( ! $verify ) {

      // check api verify
      $verifyed = verify_purchase_api( $code ); // true or false

      if( $verifyed ) {

        // is verifyed, set verify variable for avoid always check api
        $request['verify'] = $verifyed;

      } else {

        return;

      }

    }

  }

  return $request;

}
add_filter( 'cs_validate_save', '_my_validate_purchase' );
```

I did not test, but maybe you can get some ideas from this code :+1:

**Comment by Codestar** [comment]
updated code :up:

**Comment by Codevz** [comment]
@Codestar your code really helped me :100: We can check if activation field is empty / wrong, so theme options keep previous options: 

```PHP
	function validate_save( $request ) {

		$key = isset( $request['activation'] ) ? $request['activation'] : false;
		$old = wp_parse_args( array( 'activation' => $key ), get_option( '_cs_options' ) );

		if ( empty( $key ) ) {
			return $old;
		} elseif ( verify_purchase( $key ) ) {
			return $request;
		} else {
			return $old;
		}
	}
```

**Comment by Codestar** [comment]
@Codevz yes it is great. i will use this tips :+1:
