### ISSUE TITLE
How to display metabox field data!

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#3]
Can you please help me !!

**Comment by Codestar** [comment]
Hi,

Hmm you are talking about how to get metabox options from front page? hmm if so lets see:

```
...
// this is your metabox config (for eg) see the ID _custom_meta_options
$metaboxes[]      = array(
  'id'            => '_custom_meta_options',
  'title'         => 'Custom Options',
  'post_type'     => 'page', // or post or CPT
  'context'       => 'normal',
  'priority'      => 'default',
  'sections'      => array(
...
```

```
...
// this is how to get metabox options from ID _custom_meta_options on theme
$meta_data = get_post_meta( get_the_ID(), '_custom_meta_options', true );
var_dump( $meta_data ); // output returns array
...
```

**Comment by devariya** [comment]
yes i saw that, but  section_1_text field data not displayed
<pre>
      // begin: fields
      'fields' => array(

        // begin: a field
        array(
          'id'    => 'section_1_text',
          'type'  => 'text',
          'title' => 'Text Field',
        ),
        // end: a field
</pre>

**Comment by Codestar** [comment]
```
$meta_data = get_post_meta( get_the_ID(), '_custom_meta_options', true );
echo $meta_data['section_1_text'];
```

hmm is it not working ? if so let me check it yesterday, i am on ipad now :)

**Comment by devariya** [comment]
yes ,same code i wrote too ,and it's not working ,maybe it's a bug ,

**Comment by devariya** [comment]
Warning: Illegal string offset 'section_1_text'

**Comment by Codestar** [comment]
hmm oke noted, i will check it tomorrow ;)

**Comment by santiagointeractive** [comment]
You should use <code>_custom_page_options</code> as this is the id declared into metabox.config file. So your code should look like this:

<code>$meta_data = get_post_meta( get_the_ID(), '_custom_page_options', true );
echo $meta_data['section_1_text'];</code>

**Comment by devariya** [comment]
@santiagointeractive  yes you are right :)

**Comment by Codestar** [comment]
@santiagointeractive thanks for your english :) you are right ;)

**Comment by wpbean** [comment]
Anyone use Codestar framework group field. I have added it as custom meta on a custom post type. 
It's sounds good but problem is when I trying to get the value form meta boxes. 
It's return a multidimensional array, can't do any thing with this array. 
As you can see I have added only one Button but the array returning me one extra array with empty values. 
Also it's gives me Illegal string offset & Illegal string offset error when i tried to var_dump it's index like so
<pre>var_dump($meta_data['_nonce']);</pre>
http://puu.sh/ftK7T/6527c98771.png

Thanks

**Comment by reja-sumon** [comment]
how we can show meta-box from codestar framework for another page

**Comment by reja-sumon** [comment]
if you kindly help me for this issue i'm very proud of you.......
