### ISSUE TITLE
wysiwyg field in add more group

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#30]
...doesn't work, you just get a blank textarea. :)  This is the holy grail of repeaters, if you can get it working that'd be fantastic.

**Comment by Codestar** [comment]
Hi,

Hmm, yep it is normal, i am creating wysiwyg editor via php function wp_editor. i need to a tinymce ja trigger when click add a group fields. hmm ok i will think an idea for this subject ;)

**Comment by santiagointeractive** [comment]
Hello,
Any news for this feature? Or do you have any suggestion how to get this working and do some hacks to get this working somehow?

Thank you!

**Comment by Codestar** [comment]
Hi,

Actually this is possible, but required a lot of js codes. There is not a js trigger like this <code>$('element').wpEditor();</code> for eg, color picker is easy you know <code>$('element').wpColorPicker();</code> i am waiting an update for wp editor in the future. i searched it on forums, but no any simple solution. for eg i can try to adapt this https://github.com/anteprimorac/js-wp-editor

If you found any solution or ideas share with me ;)

Regards

**Comment by santiagointeractive** [comment]
Thank you for your response. I understand better now the issue.
What do you think about this solution: https://github.com/hezachary/wordpress-wysiwyg-widget

**Comment by Codestar** [comment]
Yep, thanks for share, i will think about this issue again what can i do ;)

**Comment by santiagointeractive** [comment]
Great! Thank you very much! :+1:

**Comment by SteveS123** [comment]
http://fieldmanager.org has a pretty nice repeatable WYSIWYG implementation.

**Comment by SteveS123** [comment]
Hi Codestar, I noticed you closed this issue.  Do WYSIWYG fields now work in groups?

**Comment by Codestar** [comment]
Not yet, only i "noted" this issue on github. i will work on this feature when i have free time :wink:

**Comment by hasinhayder** [comment]
Hi, 

I have fixed the wysiwyg issue in group repeater. Now it's working perfectly in group without any problem at all. I hope you will merge this pull request.

You can checkout my fork and see how it's working at https://github.com/hasinhayder/codestar-framework

![screen shot 2015-05-18 at 2 48 10 pm](https://cloud.githubusercontent.com/assets/490779/7677373/4959854a-fd6d-11e4-9166-02fb7b5fb72a.png)

**Comment by Codestar** [comment]
Thanks for contribute @hasinhayder coming this fixed in v1.1 :+1:

**Comment by dangolprajwol** [comment]
@hasinhayder  can you mark the tell which files should be changed in order to make it work in group fields ? :D i'm ver badly in need of this functionality :+1: ...
