### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#300]
Hi, I would like to clarify an issue about license of this awesome work. I am developing a new theme to release on themeforest. So is it possible to use this framework on this theme. I see that some software doesnt permit unless author has developer license. Is it possible to write more clear description on readme.md file if you allow this kind of usage.

**Comment by Codevz** [comment]
**License**

Codestar Framework is free to use both personal and commercial. If you used commercial, please credit. Read more about GNU http://www.gnu.org/licenses/gpl-2.0.txt

**Comment by Codestar** [comment]
as said @Codevz it is clear. you can use it anywhere as **FREE**. Only give proper credit to me on item description it is enough for me :wink:
