### ISSUE TITLE
I have tried to make repeatable text fields in visual composer by creating a custom param. 

### ISSUE THREAD

**Issue by Ishtiaque-Shaad** [Codestar/codestar-framework#301]

**Comment by Codevz** [comment]
Hi, 

cs-framework is not fully compatible with visual composer, but if you want repeatable field, Check visual composer core elements, one called "Round Chart" its repeatable. 

Cheers

**Comment by Codestar** [comment]
Follow the @Codevz

**Comment by Ansif** [comment]
Hi,

Visual composer has in build option. You can use it like a normal fields.

`'type' => 'param_group',`
https://wpbakery.atlassian.net/wiki/display/VC/Use+Param+Group+in+Elements

👍
