### ISSUE TITLE
Not able to add extra icon sets using .json file in our custom folder?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#305]
Hi Bro,

I can't able to add my custom icon sets using .json file in my override path folder of icon. 

This issue is because of : 
[actions.php#L15](https://github.com/Codestar/codestar-framework/blob/master/functions/actions.php#L15) => **CS_DIR**
`$jsons = glob( CS_DIR . '/fields/icon/*.json' );`

It's working fine in `get_template_directory()` to our custom path. But not working in your CS_DIR.

How to fix it without over write **actions.php** file?

Thanks! :)

**Comment by Codestar** [comment]
Hi bro,

Yes it is not able to add extra icons from override path folder. hmm actually it is normal because `override` meaning override a exists file. there is some actions  `cs_add_icons_before` `cs_add_icons_after` you can use thems.

But i can add this for you and other users.

```php
// actions.php#L15
$jsons = apply_filters( 'cs_add_icons_json', glob( CS_DIR . '/fields/icon/*.json' ) );
```

```php
// Custom filter
function _cs_add_icons_json( $json = array() ) {

  $json[] = get_template_directory() .'/cs-framework-override/fields/icon/my-icons.json';
  // or
  $json[] = get_template_directory() .'/anywhere/flat-icons.json';

  return $json;

}
add_filter( 'cs_add_icons_json', '_cs_add_icons_json' );
```

What you think about new filter, is it a solution for you ? :wink:

**Comment by Ansif** [comment]
Hi Bro,

That's working fine as expected! 💯 

Can you please add this in core actions.php file too? So, just for a single line we don't have to over ride that file. 😉 

Thanks! 👍

**Comment by Codestar** [comment]
Hi bro,

Yes yes sure, also i added it on actions.php in last commit https://github.com/Codestar/codestar-framework/commit/a8fd8b829077a53b5e01a9bc23d3391e73531a62 you can use it now.

You're welcome :+1: 
Cheers.

**Comment by Ansif** [comment]
Thanks, Bro! 💯

**Comment by Codestar** [comment]
:tropical_drink:

**Comment by anhskohbo** [comment]
Hi @Codestar, I custom icon font path as you recommend, but it's not working.


```php
/**
 * Add more icon to cs-fw.
 *
 * @param  array $json Given json paths.
 * @return array
 */
function _cs_add_icons_json( $json = array() ) {
	array_unshift( $json , get_template_directory() .'/fonts/thepearl-icons.json' );
	return $json;
}
add_filter( 'cs_add_icons_json', '_cs_add_icons_json' );
```

As I see in actions.php (line 21), seem it's always loading icon in `fields/icon/*`
```
$object = cs_get_icon_fonts( 'fields/icon/'. basename( $path ) );
```

**Comment by Codestar** [comment]
Hi, @anhskohbo 

Hmm interesting, can you try this ?

```php
/**
 * Add more icon to cs-fw.
 *
 * @param  array $json Given json paths.
 * @return array
 */
function _cs_add_icons_json( $json = array() ) {
	$json[] = get_template_directory() .'/fonts/thepearl-icons.json';
	return $json;
}
add_filter( 'cs_add_icons_json', '_cs_add_icons_json' );
```

It works?

**Comment by anhskohbo** [comment]
Unfortunately, it did not work :( 

![screenshot from 2016-06-15 17-23-55](https://cloud.githubusercontent.com/assets/1529454/16076547/f59f8214-331d-11e6-99ea-dffa426423d2.png)

(I use `array_unshift` just want it on the head)

**Comment by Codestar** [comment]
I re-checked it, and yes there is needed a improve for icon load. you can use this code temporary until improve.

```php
/**
 * Add more icon to cs-fw.
 *
 * @param  array $json Given json paths.
 * @return array
 */
function _cs_add_icons_before() {

  $file = get_template_directory() .'/fonts/thepearl-icons.json';

  ob_start();
  load_template( $file, true );
  $json = ob_get_clean();
  $myicons = json_decode( $json );

  foreach ( $myicons->icons as $icon ) {
    echo '<h4 class="cs-icon-title">'. $myicons->name .'</h4>';
    foreach ( $myicons->icons as $icon ) {
      echo '<a class="cs-icon-tooltip" data-cs-icon="'. $icon .'" data-title="'. $icon .'"><span class="cs-icon cs-selector"><i class="'. $icon .'"></i></span></a>';
    }
    echo '<h4 class="cs-icon-title">Font Awesome</h4>';
  }

}
add_action( 'cs_add_icons_before', '_cs_add_icons_before' );
```

**Comment by anhskohbo** [comment]
Thanks!

**Comment by Codestar** [comment]
You're welcome :+1:
