### ISSUE TITLE
How can we able to check if framework function exist?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#308]
Hi Bro,

I'm using codestar framework in my theme. And i want to get some fields output in my custom plugin. That plugin includes custom post types and theme shortcode functions.

For example, portfolio custom post type created in my custom plugin. I want users can able to change that portfolio name. So, Theme Options have that field options to change.

And that plugin code is like : 
`$portfolio_cpt = (function_exists('cs_get_option')) ? cs_get_option('theme_portfolio_name') : '';`

But when i switch to different theme, my plugin will get error of : 
`Call to undefined function cs_get_option ...`

How to check if our framework function is exist?

**Comment by NoahjChampion** [comment]
There should be a lot of ways you can do this, but here is one I use. I'm not sure what @Codestar would recommend. 

```
// Check the value of the constant (if is true)
if (CS_ACTIVE_FRAMEWORK === true ) {
  $portfolio_cpt = (function_exists('cs_get_option')) ? cs_get_option('theme_portfolio_name') : '';
}
```

**Comment by Ansif** [comment]
@NoahjChampion Thanks!

But if you turn on wp_debug mode then you'll receive following error from that method : 
 Notice: Use of undefined constant CS_ACTIVE_FRAMEWORK - assumed 'CS_ACTIVE_FRAMEWORK' in /../../some-file.php

👍

**Comment by NoahjChampion** [comment]
Oh, sorry... 

That should just mean that `CS_ACTIVE_FRAMEWORK` should be wrapped in Apostrophes like `'CS_ACTIVE_FRAMEWORK'`. 

So try.. 

```
// Check the value of the constant (if is true)
if ('CS_ACTIVE_FRAMEWORK' === true ) {
  $portfolio_cpt = (function_exists('cs_get_option')) ? cs_get_option('theme_portfolio_name') : '';
}
```

I use it when checking to see if `WP_DEBUG` is true.. which is... 

```
if (WP_DEBUG === true)) {
  // Code...
}
```

So it should work for checking the values of other constants. 

Let me know.

**Comment by Ansif** [comment]
No, that method not worked well. It's not getting cs_get_option within that if condition.

`if ('CS_ACTIVE_FRAMEWORK' === true ) {
		$portfolio_cpt = cs_get_option('theme_portfolio_name');
	} else {
		$portfolio_cpt = 'portfolio';
	}`

Thanks.

**Comment by NoahjChampion** [comment]
@Ansif 

I got a moment to test this out. 

This is what I do and I tested it. 

```
// If CS_ACTIVE_FRAMEWORK [is defined] and the cs_get_option [function exists]...
if ( defined( 'CS_ACTIVE_FRAMEWORK' ) && function_exists( 'cs_get_option' ) ) {
	echo "TEST"; // Your code...
}
```

This way, your code will only run if `CS_ACTIVE_FRAMEWORK` **and** `cs_get_option` are **both** true. 
This means if another theme or plugin uses a `cs_get_option` function your plugin won't run. 
It's a double checking to make sure both are values are true before running. 

Let me know.

**Comment by NoahjChampion** [comment]
(see previous update) I had a mistake in the code earlier, but if you need to in the future you can check how to check a value of a constant (like `CS_ACTIVE_FRAMEWORK`) 
@ [How can I check if the value of the constant equals something?](http://stackoverflow.com/questions/9239733/how-can-i-check-if-the-value-of-the-constant-equals-something)

I wouldn't check for `CS_ACTIVE_FRAMEWORK` to be true unless needed. I think it defeats the purpose because if CF is installed the whole purpose is for the framework to be active.

**Comment by Ansif** [comment]
Ok. 👍 

Let's ask @Codestar and @codevz!

**Comment by Codevz** [comment]
@Ansif Same as you, i've included cs-framework in my theme and using this code in plugin: 

`$var = function_exists( 'cs_get_option' ) ? true : false;`

I checked it works fine when theme is activated or not.

**Comment by Codestar** [comment]
Hey Guys,

I think you can use this ways 

```php
// Codevz's example
function is_cs_framework_active() {
  return ( function_exists( 'cs_get_option' ) ) ? true : false;
}

if( is_cs_framework_active() ) {
// do stuff
}
```

```php
// Another example
function is_cs_framework_active() {
  return ( defined( 'CS_VERSION' ) ) ? true : false;
}

if( is_cs_framework_active() ) {
// do stuff
}
```

**Comment by NoahjChampion** [comment]
@Codestar 

Good way :) That way you don't have to call the check in different areas, just call the function. 

I can update other codes to that way as well since it is becomes easier to manage. 

Thanks your highness. 

Any updates planned? Did you get my email?

**Comment by NoahjChampion** [comment]
@Codestar don't you think it is still good to do a double check? Thoughts? Or too much?

Some other plugin may use `CS_VERSION` or `cs_get_option` and if we check only for one then our code may run when CF is not active. It is probably rare, but I think it is forward thinking. At least I would do a double check to make sure.

**Comment by Codestar** [comment]
@NoahjChampion uh no i did not get any email ? :smile:

**Comment by NoahjChampion** [comment]
@Codestar 

It was about helping out CF or paying for some features. Search email for "Github, Codestar Framework: Noahj" April 15th I mailed it. 
Spam maybe? My email is from entuitions.com.

**Comment by Codestar** [comment]
@NoahjChampion 

Hmm, no i do not know, it is not offical. maybe him is a freelancer :smiley:

**Comment by NoahjChampion** [comment]
@Codestar 
I can resend email to Info [at] Codestar [dot] com?

**Comment by Codestar** [comment]
@NoahjChampion you can use routewp[at]gmail.com :wink:

**Comment by Ansif** [comment]
Awesome! @Codestar! That's All, what i need! 😉 

Thanks, @Codevz! 👍

**Comment by Codestar** [comment]
Cheers :tropical_drink:
