### ISSUE TITLE
Please update you google-fonts.json file . Some google fonts are missing 

### ISSUE THREAD

**Issue by apurbajnu** [Codestar/codestar-framework#309]
Please update  google-fonts.json file . Some google fonts are missing . I searched for Poppins font. But I was unable to find this font. current version of  google-fonts.json file is not updated. I have replaced this file with current google web font json.   Finally I have found Poppins font .

**Comment by Codestar** [comment]
Hi,

Yes sure, also you can see here my update https://github.com/Codestar/codestar-framework/commit/75908b2de85dad3e57759acfbcb36cb880e15ebf

6 days ago google-fonts.json updated you need to re-download repo :wink: 

Btw, this updates will come in release v1.0.2 but said as me you can download master repo.
