### ISSUE TITLE
image field type (Codestar Field) in customizer doesn't trigger 'Save & Publish' button

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#31]
When you add an image via the image field in the customizer the "Saved" button doesn't change to "Save & Publish".

**Comment by Codestar** [comment]
Hi,

Can you write your config for only image field ? i will check it ;)

**Comment by SteveS123** [comment]
Sure-

```array(
      'name'      => 'codestar_image',
      'control'   => array(
        'type'    => 'cs_field',
        'options' => array(
          'type'  => 'image',
          'title' => 'Select Image',
        ),
      ),
    ),

**Comment by santiagointeractive** [comment]
I can confirm this problem.

The issue seems to be input type="hidden" that stores the attachment value. If you change the type into text it works.  Also I see that icon field also doesn't work in customizer. No dialog window is showing for choosing icon.

**Comment by santiagointeractive** [comment]
Fixed your issue. See changes here: https://github.com/santiagointeractive/codestar-framework/commit/bd00b7361d965f1e2d2cb3dc67aa224f4acf4bb4

I have created a pull request for this fix to be included into the master framework.

**Comment by Codestar** [comment]
@santiagointeractive fixed this issue, you can re-download the framework ;)

**Comment by SteveS123** [comment]
Thank you both!

**Comment by Codestar** [comment]
You're welcome :+1:
