### ISSUE TITLE
Option doesn't appear on the site

### ISSUE THREAD

**Issue by Radzio1615** [Codestar/codestar-framework#31]
Hi! I'm trying to display the option on the site, but something doesn't work.

in function.php I add:

```
if( class_exists( 'CSF' ) ) {

	$prefix = 'my_framework';

	CSF::createOptions( $prefix, array(
		'menu_title' => 'MyFramework',
		'menu_slug'  => 'my-framework',
		'menu_icon'  => 'dashicons-star-filled',
		'framework_title' => 'MyFramework'
	) );

	// Create a section
	CSF::createSection( $prefix, array(
		'id'    	  => 'my-settings',
		'title'       => 'Settings',
	) );

	CSF::createSection( $prefix, array(
		'parent'      => 'my-settings',
		'title'       => 'Footer',
		'fields'      => array(

		array(
		  'id'     => 'my-settings-footer',
		  'type'   => 'tabbed',
		  'tabs'   => array(

			array(
			  'title'     => 'Layout',
			  'fields'    => array(

				array(
					'id'        => 'my-settings-footer-layout',
					'type'      => 'image_select',
					'options'   => array(
						'layout01' => 'http://img1.gif',
						'layout02' => 'http://img2.gif',
						'layout03' => 'http://img3.gif',
						'layout04' => 'http://img4.gif',
					),
					'default'   => 'layout01',
				),

			)),
		))

		)
	) );
}
```

In footer.php I add:

```
<?php $options = get_option( 'my_framework' );
echo $options['my-settings-footer-layout'];
?>
```

I want to display default value 'layout01' or selected value on the dashboard. Nothing is displayed now. Can you help?

**Comment by Radzio1615** [comment]
I notice that when I move field "my-settings-footer-layout" HERE value will appear. How to make it work in sub section tabs?

```
	CSF::createSection( $prefix, array(
		'parent'      => 'my-settings',
		'title'       => 'Footer',
		'fields'      => array(
Here
```

**Comment by Radzio1615** [comment]
Can anyone help?

**Comment by Codestar** [comment]
Hi,

I haven't any idea really. I am hearing this problem first time.

Regards

**Comment by mukundthanki** [comment]
Hi

Here is Tabbed field example code from "samples/options.sample.php"

https://github.com/Codestar/codestar-framework/blob/362243f3b41c9e724b827628d888de64e4a26462/samples/options.samples.php#L1369-L1481

Please check how default values set in there. 'default' key and values array are after all 'tabs'.

Please change your code according to that and see if it works.

Thanks

**Comment by Radzio1615** [comment]
@mukundthanki thanks, I copied all this sample code to my locally hosted site.

How to output eg.: Color 2 default/saved value? I have to do it wrong. This code doesn't work:
```
<?php $options = get_option( 'my_framework' );
echo 'Color 2: '. $options['opt-color-2'];
?>
```

**Comment by mukundthanki** [comment]
Here is how can we get value for inner field for tabbed elements.

`$options = get_option('my_framework');
echo 'Color 2: ' . $options['opt-tabbed-2']['opt-color-2'];`

**Comment by Radzio1615** [comment]
@mukundthanki that's what I looking for! Unfortunately, official documentation doesn't contain this information. Thank you very much, you're my hero :D

**Comment by mukundthanki** [comment]
That's cool. I don't think official documentation require to mention how to retrieve particular field data. it has enough general information. and well bro always try to dump options like `print_r($options)` and look for your expected value for any field. its that simple.

if fields are configured as nested, their values stored in nested manner.

Thanks

**Comment by Codestar** [comment]
@mukundthanki thanks for reply bro.
