### ISSUE TITLE
Not able to get metabox value?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#311]
Hi,

My metabox file : [metabox-config.php](https://gist.githubusercontent.com/Ansif/ca72f5357a1a07f853ea77889aaa9df5/raw/2067d068235354f52b5fb0bf25cbf0c99e40fa86/metabox-config.php)

Not able to get those field values, here is regular code : 
`echo get_post_meta( $post->ID, 'section_1_text', true );`

Thanks! 👍

**Comment by Codestar** [comment]
Hi,

Take a look it again, http://codestarframework.com/documentation/#metabox-configure

Fo eg, You should use `_custom_page_options` as this is the id for your key declared into metabox config file. So your code must look like this:

```php
$meta_data = get_post_meta( $post->ID, '_custom_page_options', true );
echo $meta_data['section_1_text'];

// Others
// echo ( ! empty( $meta_data['section_1_text'] ) ) ? $meta_data['section_1_text'] : '';
// var_dump( $meta_data );
```

**Comment by Ansif** [comment]
Oh ok. I missed that sorry! 😉 

Thanks! 👍

**Comment by Codestar** [comment]
Haha, NP, You're welcome. :wink: :+1:
