### ISSUE TITLE
cs_get_post_meta function...

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#312]
Reference #311 

I thought of this yesterday and just want to see what you think about it. Thoughts? 

It would make getting the post meta options easier for users, and the same experience as `cs_get_option`

So instead of... 

```php
$meta_data = get_post_meta( $post->ID, '_custom_page_options', true );
echo $meta_data['Field_ID_Here'];
```

It could be something like...

```php
$meta_data = cs_get_post_meta( 'Field_ID_Here' );
echo $meta_data;
```

**Comment by Codestar** [comment]
Hi,

Yes why not, but there is sometimes issue for $post->ID  for eg. in home with blog loop $post->ID = latest blog post. or a custom post type. i do not know how i can explain it but this post id is dangereus :smile:

Also this is not static `_custom_page_options` this is dynamic.

```php
// imagine
echo cs_get_post_meta( 'Field_ID_Here', '_custom_page_options' );

// also someguys will ask about true/false
echo cs_get_post_meta( 'Field_ID_Here', '_custom_page_options', true );

// haha, almost same with orginal function.
```

```php
// If you want it, create by yourself. for eg.
function prefix_get_post_meta_value( $option, $key = '_custom_page_options', $single = true ) {

  global $post->ID; // or get_the_ID();

  $meta = get_post_meta( $post->ID, $key, $single );
  return ( ! empty( $meta[$option] ) ) ? $meta[$option] : NULL ;

}
```

**Comment by NoahjChampion** [comment]
Ok. Thanks for the info! 

Is home page and blog loop the only danger?

**Comment by Codestar** [comment]
@NoahjChampion Actually it is not only for blog loop. for eg. imagine if there is using a custom `WP_QUERY` and do not adding `wp_reset_query()` or `wp_reset_postdata()` post id will change.

I am not sure 100% where you will have problem, use it and report us if you have any issue :+1:

**Comment by NoahjChampion** [comment]
Ok, I will give it some basic tests and report back to see if it is worth it to go any further. 

Thanks. 

@Codestar Did you get my email yet?

<img src="http://i.giphy.com/IFpVKDqOo84F2.gif">

**Comment by Codestar** [comment]
@NoahjChampion yes i got email. yeah it is interesting :) it is not my texts :smile:
