### ISSUE TITLE
Color picker appears twice in widgets

### ISSUE THREAD

**Issue by rahulnever2far** [Codestar/codestar-framework#316]
I'm using Codestar Framework to add fields in widgets. I have added 2 color fields. When that widget is added to a widgetized area, color picker appears twice for each field as in the screenshot attached.
![color-feild-before](https://cloud.githubusercontent.com/assets/3503359/15273603/da62b814-1abc-11e6-96df-66241e3a8759.jpg)
 
After saving the widget and reloading the page, it appears once like it should.
![color-feild-after](https://cloud.githubusercontent.com/assets/3503359/15273602/da5f5d72-1abc-11e6-81ce-f1193c6282f4.jpg)

I'm using the following code for my fields:
```PHP
// Color 1
$color_1_value = esc_attr( $instance[ 'color_1' ] );
$color_1_field = array(
  'id'      => $this->get_field_name( 'color_1' ),
  'name'    => $this->get_field_name( 'color_1' ),
  'type'    => 'color_picker',
  'title'   => esc_html__( 'Color 1', 'codestar' ),
  'default' => '#ff0078',
);
echo cs_add_element( $color_1_field, $color_1_value );

// Color 2
$color_2_value = esc_attr( $instance[ 'color_2' ] );
$color_2_field = array(
  'id'      => $this->get_field_name( 'color_2' ),
  'name'    => $this->get_field_name( 'color_2' ),
  'type'    => 'color_picker',
  'title'   => esc_html__( 'Color 2', 'codestar' ),
  'default' => '#ff5400',
);
echo cs_add_element( $color_2_field, $color_2_value );
```

**Comment by Codestar** [comment]
I checked it and yes you are right. hmmm can you try to change this line [cs-framework.js#L1432](https://github.com/Codestar/codestar-framework/blob/master/assets/js/cs-framework.js#L1432)

```javascript
// from
$cs_body.CSFRAMEWORK_RELOAD_PLUGINS();

// to
$('.cs-framework').CSFRAMEWORK_RELOAD_PLUGINS();
```

And check framework, metabox, shortcodes etc option fields. i did try this code, it is works. tell me your test i will update the code :+1:

**Comment by rahulnever2far** [comment]
This change fixed the issue :+1: 

Thank you for a prompt reply :)

**Comment by Codestar** [comment]
You're welcome, also added this fixes on repo :+1:

**Comment by Codevz** [comment]
@Codestar Your code destroyed color picker in customizer, add this:

`$('.cs-framework, .customize-control-cs_field').CSFRAMEWORK_RELOAD_PLUGINS();`

**Comment by Codestar** [comment]
@Codevz Ops, i forget to check it on customizer. i fixed it now https://github.com/Codestar/codestar-framework/commit/39f5f722b3833f264ec420f83e30cebe384d9686

Thanks for report :+1:
