### ISSUE TITLE
GPL License Issue

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#319]
hi @Codestar 
I am preparing a theme which uses your awesome framework in order to sell on theme markets.
I want to use it as a plugin while overriding config files. Is it possible to change folder and file names without toching licence files and crediting to your homepage. 

For example, my theme name is cansanet, I will name modified plugin as cansanet-core.

I wil change this =>

|---- cs-framework
      |---- cs-framework.php
      |---- cs-framework-path.php

to this=>

|---- cansanet-core
      |---- cansanet-core.php
      |---- cansanet-core-path.php

i will put plugin inside my theme to be installed by TGM Plugin and I will manage updates automatically.

Is license in this scenario.

**Comment by Codestar** [comment]
Hi @cansanet 

Yes sure, you can do it. No problem for me. Said as me before. give proper credit to me on item description. it is enough for me :wink: 

Wishes nice sales :100:
