### ISSUE TITLE
codestar-framework doesn't work after upgrade.

### ISSUE THREAD

**Issue by shankhadevpadam** [Codestar/codestar-framework#321]
call_user_func() expects parameter 1 to be a valid callback, function 'add_add_menu_page_page' not found or invalid function name in cs-framework/classes/framework.class.php on line 323

**Comment by Codevz** [comment]
Try to change cs-framework config: http://codestarframework.com/documentation/#framework-configure

**Comment by Codestar** [comment]
Hi,

Said as @Codevz take a look new configure. I made an update about `menu_type`

```php
// v1.0.0 old usage
'menu_type' => 'add_menu_page',
```

```php
// v1.0.1 new usage
'menu_type' => 'menu',
```

Only you need to update your settings config. for eg:

```php
// v1.0.1 new usage
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // new usage
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false, // new param
  'framework_title' => 'Codestar Framework <small>by Codestar</small>', // new param
);
```

**Comment by WPsmart** [comment]
Hi Codestar (After long time,)

Its Worked for me Thanks very much :+1:

**Comment by Codestar** [comment]
You're welcome :+1:
