### ISSUE TITLE
Add field clone and sort capabilities

### ISSUE THREAD

**Issue by ahmedmrj** [Codestar/codestar-framework#323]
How can i add clone and sort capabilites to default field type like text field or select field.

**Comment by cansanet** [comment]
I would also ask this question.

**Comment by Codestar** [comment]
`Group Field` not enough for this request ?

**Comment by ahmedmrj** [comment]
Yes, we can do it with  `Group` option, but for simplicity i want to apply clone and sort capabilities directly to simple built-in options.
Is it possible to extends options attributes like this?

```
array(
  'id'      => 'text_uniq_id',
  'type'    => 'text',
  'title'   => 'Text Field',
  'clone'    => true,
  'max_clone_number'    =>  'a number',
  'sortable' =>  true,
),


```

**Comment by Codestar** [comment]
Oh yes, i understand. we only need a simple text clone. hmm ok. i noted this idea :+1:
