### ISSUE TITLE
Config override vs extend

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#326]
Hi @Codestar,
I am preparing a specific plugin for the theme and future themes. I include csframework inside this plugin. Shortcodes and custom post types and some widgets are maintained by this plugin. And other things are still maintained by plugin thanks to cs framewok but I am using config override files for theme specific features.

Question: Is there a way of combining these config files ? First initialize plugins framework.config.php then render the one from theme override folder. 

Why I want this? I want to deliver some options that will reside on my all themes and some options that will be theme specific. When I update plugin, all of the themes get specific features.

Thanks.

**Comment by NoahjChampion** [comment]
@cansanet Do you mean like an add_filter so your settings extended your theme settings but do not override? If so yes, there is a filter for that.

**Comment by NoahjChampion** [comment]
See #298 - It might answer another question you have too, but is this what you mean? Or does this help?

**Comment by cansanet** [comment]
Thanks @NoahjChampion I will check it

**Comment by Codestar** [comment]
@cansanet actually we can not use framework multiple instance, yet. i will working on this features. What you can use now, said as @NoahjChampion add_filter method. details: http://codestarframework.com/documentation/#filter-reference

Shortly, you can not framework files inside plugin also theme.. only you need to include framework files inside theme.. for plugin settings. you will use add_filter method. I hope i explained it :smile:
