### ISSUE TITLE
Color Picker Not Working

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#328]
Hi Codestar

I recently Updated My Theme Framework, (Codestar Framework 1.0 to 1.1) now My color pickers not working on Widgets. 

screen shot - 

![image](https://cloud.githubusercontent.com/assets/5784887/15636892/b1163502-262a-11e6-9661-936fe373ee6c.png)

Here Is code I used - 

```
$pic_color_value = esc_attr( $instance['packagecolor'] );
$color_picker_field = array(
'id'    => $this->get_field_name('packagecolor'),
'name'  => $this->get_field_name('packagecolor'),
'type'    => 'color_picker',
'title'   => 'Package Color',
'default' => '#F5F5F5',
);

 echo cs_add_element( $color_picker_field, $pic_color_value );`
```
Can you please check this?

Thanks

**Comment by NoahjChampion** [comment]
Hi @WPsmart Did you check the recent closed issues? 

There has been some talk over the widgets and specifically the color pickers. Maybe the solution is in there for you? 

See https://goo.gl/Ul5d6D

And https://goo.gl/kiCxVX

Any help? Otherwise I do not know and someone else will have to chime in.

**Comment by WPsmart** [comment]
Hi

I try to https://github.com/Codestar/codestar-framework/issues/322 this method, but not working for me, but old framework files worked well, 

I added - `$('.cs-framework, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();`

But not working :(

**Comment by NoahjChampion** [comment]
@WPsmart ok. Just checking. Sorry to hear that. I haven't used widgets framework yet to help, but thought I would mention the recent issues. 

I guess @Codestar or @Codevz will have to help.

**Comment by WPsmart** [comment]
Its ok, Thanks Very much for your replays, and really help for your links to get idea about this issue :)

**Comment by Codestar** [comment]
@WPsmart hmm, it is interesting, i am using this

```php
$('.cs-framework, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();
```

and the result:

![support_20160526141915](https://cloud.githubusercontent.com/assets/1313301/15573037/069c7288-234d-11e6-870b-f65e321caaa4.gif)

Is your framework online, i can check it. you can send information via routewp[at]gmail[dot].com

**Comment by WPsmart** [comment]
Hi Codestar

I Found the Bug, Im Using Aqua Page builder With Codestar Framework, there page builder blocks codes same to WordPress Widgets

I change Your code 
    `$('.cs-framework, #page-builder').CSFRAMEWORK_RELOAD_PLUGINS();`

Now  its working, I have another Question, My Page builder Upload Feild Not working, (After New Update) When I click Upload Button, no any popup message

Any idea why?

Thanks

**Comment by WPsmart** [comment]
Fixed... All is Working Well now  after This Coe

`$('.cs-framework, #page-builder').CSFRAMEWORK_RELOAD_PLUGINS();`

Please Mark this issue as Fixed 

Thanks VeryMuch

**Comment by Codestar** [comment]
Oh yeah, great. You're welcome :+1:

**Comment by Codevz** [comment]
@Codestar Why you do not call it with body ?

`$('body').CSFRAMEWORK_RELOAD_PLUGINS();`

I'm using codestar upload option type in visual composer and also front-end and just with above code it works.

**Comment by WPsmart** [comment]
Hi @Codestar

Are you know about Aqua page builder? (any experience about Aqua page builder ?)

**Comment by Codestar** [comment]
@Codevz 
Hey bro, i am not sure how i can explain it with my english but i will try. There is some conflict with reload plugins. for eg. `color_picker in group field`

Group field have some hidden elements for clone (for repeatable) and if i use `$('body')` this hidden elements will run and when you click clone, you will see twice `color_picker` 

Also this example same for Widgets... Widgets have hidden elements and when you drag/drop this elements showing.

You got it? 

@WPsmart I will check your aqua page builder dependencies.. take a look your issue :+1: i wrote a message to you.

**Comment by Codevz** [comment]
@Codestar Thanks for quick reply, I underestand, Maybe you could add visual composer id to reload plugins in next update

`$('.cs-framework, ..., ..., #wpb_visual_composer').CSFRAMEWORK_RELOAD_PLUGINS();`

**Comment by Codestar** [comment]
@Codevz yes why not i can add this surely. But we need to add this reload plugins when open visual composer edit panel. i will search where is the vc edit panel opened trigger. Noted this.

**Comment by Codestar** [comment]
@Codevz Btw, i found the trigger. you can use this code as tempolry. if you need...

```php
$( '#vc_ui-panel-edit-element' ).on( 'vcPanel.shown', function() {
  $(this).CSFRAMEWORK_DEPENDENCY();
  $(this).CSFRAMEWORK_RELOAD_PLUGINS();
});
```

**Comment by Codevz** [comment]
@Codestar Thanks for code, it works but there is one issue, When i click on upload button and then want to close it, should i close it 3 times. 

It seems by first clicking on upload button, media uploader opens 3 times.

**Comment by Codestar** [comment]
@Codevz hmm yes it is can be. i did not tested it.. hmm let's try this..

```php
$('#vc_ui-panel-edit-element').on( 'vcPanel.shown', function() {

  var $elems = $(this).find('.wpb_edit_form_elements');

  $elems.CSFRAMEWORK_DEPENDENCY();
  $elems.CSFRAMEWORK_RELOAD_PLUGINS();

});
```

**Comment by Codestar** [comment]
@Codevz yes. it is can be. i did not tested the code... hmm let's try this :wink: 

```js
$('#vc_ui-panel-edit-element').on( 'vcPanel.shown', function() {

  var $elems = $(this).find('.wpb_edit_form_elements');

  $elems.CSFRAMEWORK_DEPENDENCY();
  $elems.CSFRAMEWORK_RELOAD_PLUGINS();

});
```

**Comment by Codestar** [comment]
Niceee :+1: i will add it..
