### ISSUE TITLE
An Idea about Group Option

### ISSUE THREAD

**Issue by cansanet** [Codestar/codestar-framework#329]
On group options section, when clicked on any group there is a remove button.
How could it be on over accordion toggle?
Below image is explaining well what I wanted to say.

![untitled-2](https://cloud.githubusercontent.com/assets/16270198/15651961/975c32ea-268b-11e6-982e-afc594926781.jpg)

I think this option will give user a faster use experience.

Another idea: Maybe remove buttons can come only when hover on accordion toggle.

**Comment by Codestar** [comment]
#234 Yes, We talked about it. I will add this feature soon.

![codevz-idea](https://cloud.githubusercontent.com/assets/1313301/15652224/5dbb5b36-268d-11e6-981c-324395097c4c.png)

**Comment by NoahjChampion** [comment]
@Codestar this is good. I thought the same but with buttons, like @cansanet but this is better idea. 👍

**Comment by Codestar** [comment]
Yes yes i will improve it. red button will better. :wink:

**Comment by NoahjChampion** [comment]
@Codestar ok. But no, I was saying I like copy  and x icon better. Either way is good. Long as it works, everyone is happy. No big design issue.

**Comment by Codestar** [comment]
You are right @NoahjChampion, and yes sure, clone and remove shortcuts will come there. :+1:
