### ISSUE TITLE
Possibility to embed framework in plugin or theme

### ISSUE THREAD

**Issue by Octopixell** [Codestar/codestar-framework#33]
Hi @Codestar 

First and foremost, thank you for creating such an amazing framework! I'm not sure where to aks a quick question other than here on Github. Sorry if this is incorrect.

Is it possible to use the framework embedded into a plugin? That way my users wont have to have both plugins installed but just my plugin. That way my plugin would serve the framework and it'd just be standalone. 

Kind of need to know this before I go any further and perhaps get the premium version.

Thanks!

**Comment by Octopixell** [comment]
Correction, I see you can embed in a theme: http://codestarframework.com/documentation/#/installation?id=using-inside-theme

Does this work the same for plugins?

**Comment by Octopixell** [comment]
Ok so it seems I've confirmed this would also work with a plugin. Is there any specific reason against using this method? Or is it fine to do so?

**Comment by Codestar** [comment]
Hi,

Yes you can embed the framework into a plugin or theme multiple. There will not be a conflict with other codestar frameworks.

Regards, Codestar
