### ISSUE TITLE
No dialog window is showing for choosing icon on Customizer

### ISSUE THREAD

**Issue by santiagointeractive** [Codestar/codestar-framework#33]
Probably a iframe z-index issue but I haven't figure it out.

I tried adding z-index property on $dialog.dialog - not working. Also position of: window.parent, and window.top - not working.

**Comment by Codestar** [comment]
hmm, i am seeing normally? icon window over shortcode generator window ?

![support_14-59-18](https://cloud.githubusercontent.com/assets/1313301/6286528/25eb8c2a-b911-11e4-85ad-17aa3c089d24.png)

**Comment by santiagointeractive** [comment]
Try it over customizer.

**Comment by Codestar** [comment]
Opps, i understand it now :) hmm yes it is true. let me check it.

**Comment by Codestar** [comment]
Fixed, i was added icon window codes only "admin_footer". and i added also "customize_controls_print_footer_scripts" it is working now. btw, i fixed some z-index issues. and added stop-scrolling for shortcode and icon windows. You can try it now ;)

**Comment by santiagointeractive** [comment]
Tested and worked like a charm. :)
Thank you very much! :+1:

**Comment by Codestar** [comment]
You're welcome :+1:
