### ISSUE TITLE
How to get value from metabox feilds ?

### ISSUE THREAD

**Issue by wpexpert24** [Codestar/codestar-framework#331]
I am new in codestar framework. I do not know the exact way to output metabox values. I tried with 

$my_field = get_post_meta( THE_POST_ID, 'my_field', true );

But no luck. Can you please explain in details ?

Thanks in advance

**Comment by sinsky** [comment]
$my_field = get_post_meta(get_the_ID, 'my_field', true );

**Comment by NoahjChampion** [comment]
I don't want anyone to get confused. I think it would make it easier to understand to say `my_options_id`, because `my_field` should be your metabox options id, not your field options id. 

Example saying... 

```php
$this_metabox = get_post_meta( $post->id, 'your_metabox_options_id', true );
// This is your metabox options ID, not your field option ID. 
// See more below...
```
Example usage is... 

```php
$this_metabox = get_post_meta( $post->ID, '_custom_page_options', true ); 
// See screenshot below @ 'id' => '_custom_page_options'

echo $this_metabox['your_field_option_id_1']; // This is your field id
echo $this_metabox['your_field_option_id_2']; // This is another field id

// Others
// echo ( ! empty( $this_metabox['your_field_option_id_1'] ) ) ? $this_metabox['your_field_option_id_1'] : '';
// var_dump( $this_metabox );
```
See screenshot below. 

![image](https://cloud.githubusercontent.com/assets/6123260/15806228/4cfbe8e0-2b0d-11e6-996a-34e0869a493b.png)

**Comment by Codestar** [comment]
Follow the @NoahjChampion answer. :heart:

**Comment by wpexpert24** [comment]
I tried Above Method in Theme template, it's working fine, But when i tried it into short-code it doesn't work.

Below Code example which i tried
===========================

// Register Shortcode
function rd_hover_effects_shortcode($atts){
	extract( shortcode_atts( array(
		'category' => '',		
		'unique_option_102' => '',			
	), $atts) );
	    $q = new WP_Query(
        array('posts_per_page' => -1, 'post_type' => 'royalprotfolio', 'hover_cat' => $category)
        );
$meta = get_post_meta( $post->ID, '_custom_page_options', true ); 
var_dump( $meta_data );

while($q->have_posts()) : $q->the_post();
	$output ='<h3>'.$meta['title'].'</h3>';
	endwhile;
	wp_reset_query();
	return $output;
}
add_shortcode('hover', 'rd_hover_effects_shortcode');

Hope will get a perfect solution

**Comment by NoahjChampion** [comment]
@wpexpert24 

Just an FYI, because your code came through formatted very bad. It's hard to look at :)

I had to look this up myself too at one point. 
Link: [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
Link: [More advanced formatting](https://help.github.com/articles/working-with-advanced-formatting/)

For php use **backtick backtick backtick php** and this will create a formatted php code block. 

For css use **backtick backtick backtick css** and this will create a formatted php code block.

Then end the code block with **backtick backtick backtick**

I tried to clean up/format the code you posted, but maybe you can edit the same. 

```php
// RegisterShortcodefunction rd_hover_effects_shortcode($atts) {
extract(shortcode_atts(array(
	'category' => '',
	'unique_option_102' => '',
), $atts));
$q = new WP_Query(array(
	'posts_per_page' => - 1,
	'post_type' => 'royalprotfolio',
	'hover_cat' => $category
));
$meta = get_post_meta($post->ID, '_custom_page_options', true);
var_dump($meta_data);
  while ($q->have_posts()):
	$q->the_post();
	$output = '' . $meta['title'] . '';
  endwhile;
  wp_reset_query();
  return $output;
}
add_shortcode('hover', 'rd_hover_effects_shortcode');
```
Then @Codestar can answer because I don't know. Just wanted to help on the code when I looked.

**Comment by wpexpert24** [comment]
Hi, Thanks , 
Below Code you may check. Metabox value doesn't come 

`//require_once plugin_dir_path( __FILE__ ) .'/cs-framework-path.php';
// ------------------------------------------------------------------------------------------------

require_once '/cs-framework/cs-framework.php';

// Registering Custom Post
function royal_custom_post() {
	register_post_type( 'royalprotfolio',
		array(
			'labels' => array(
				'name' => __( 'Royal Protfolio' ),
				'singular_name' => __( 'Hover Effect' ),
				'add_new_item' => __( 'Add new hover item title ' )
				),
			'public' => true,
			'supports' => array('title'),
			'has_archive' => true,
			'rewrite' => array('slug' => 'hover-effects'),
			'menu_icon' => '',
			'menu_position' => 20,
			)
		);
	
}
add_action( 'init', 'royal_custom_post' );

// Registering Custom post's category
function royal_custom_post_taxonomy() {
	register_taxonomy(
		'hover_cat',  
		'royalprotfolio',
		array(
			'hierarchical'          => true,
			'label'                 => 'Protfolio Category',
			'query_var'             => true,
			'show_admin_column'             => true,
			'rewrite'                       => array(
				'slug'                  => 'rd-category',
				'with_front'    => true
				)
			)
		);
}
add_action( 'init', 'royal_custom_post_taxonomy'); 


require 'icon.php';


//require_once 'metabox.php';

//Loading Shortcode
// Register Shortcode
function rd_hover_effects_shortcode($atts){
	extract( shortcode_atts( array(
		'category' => '',		
		'unique_option_102' => '',			
	), $atts) );
	    $q = new WP_Query(
        array('posts_per_page' => -1, 'post_type' => 'royalprotfolio', 'hover_cat' => $category)
        );
$meta = get_post_meta( $post->ID, '_custom_page_options', true ); 
var_dump( $meta_data );

while($q->have_posts()) : $q->the_post();
	$output ='<h3>'.$meta['title'].'</h3>';
	endwhile;
	wp_reset_query();
	return $output;
}
add_shortcode('hover', 'rd_hover_effects_shortcode');`

**Comment by wpexpert24** [comment]
Hi please help anyone i need this.
Screenshot Below with Code you may check. Meta-box value doesn't come in shortcode
http://prntscr.com/bcwdci
Hope Codestar help us.
Regard
RD Development

**Comment by Codestar** [comment]
Please read answers, there is all answers ?

**Comment by wpexpert24** [comment]
Issue has been solved

**Comment by Codestar** [comment]
Cheers :wine_glass:

**Comment by mdjwel** [comment]
@wpexpert24 how you solved the issue?
I'm facing the same problem. Can you share the solution please...

Regards
Md Jwel

**Comment by Tauhid-pro** [comment]
# How to get value from metabox

// ===============================================================
// -----------------------------------------------------------------------------------------------
// METABOX OPTIONS
// -----------------------------------------------------------------------------------------------
// ==============================

function TechnoTrends_Metabox_options($options) {
$options      = array();
    
$options[] = array(
    'id' => 'tauhidpro_portfolio_options',
    'title' => 'Portfolio details',
    'post_type' => 'post',
    'context' => 'normal',
    'priority' => 'high',
    'sections' => array(
        array(
            'name' => 'section_4',
            'fields' => array(
                
                array(
                    'id' => 'external_link',
                    'type' => 'text',
                    'title' => 'External link',
                ),
                
            )
        )
    )
);
        
    
    
return $options;    
}
add_filter('cs_metabox_options', 'TechnoTrends_Metabox_options');


//=============================
//=== Shortcode
//=============================
function tz_shortcode($atts) {
global $post; 
extract(shortcode_atts(array(
  
), $atts));
// base args
        $args = array(
            'post_type'      => 'post',
            'posts_per_page' => -1,
            'paged'          => ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1
        );
        $posts           = new WP_Query( $args );

 if ( $posts->have_posts() ) {
        while ( $posts->have_posts() ) :
            $posts->the_post();
            global $post;            
            $meta_data = get_post_meta( get_the_ID(), 'tauhidpro_portfolio_options', true );
            $link   = $meta_data['external_link'];
            $output = '<div class="main">';
            	$output .= '<h1>'.$link.'</h1>';
            $output .= '</div>';
	    return $output; 
        endwhile;

    }
}
add_shortcode('external-link', 'tz_shortcode');
