### ISSUE TITLE
can i use the framework give the taxonomy description a editor ?

### ISSUE THREAD

**Issue by sinsky** [Codestar/codestar-framework#332]
can i use the framework give the taxonomy description a editor (Wysiwyg)? 

and how to query the all of "Switcher" is true taxonomy .

like 

$args = array(
                'taxonomy' => 'category',
                'hide_empty' => 0,
                'meta_key' => 'isprofession',
                'meta_value' => true
            );

            $c = get_categories($args);
            foreach($c as $cat){
                echo $cat->name;
            }

this is wrong i know .

**Comment by NoahjChampion** [comment]
@sinsky 

Did you try yet? 

See https://github.com/Codestar/codestar-framework/blob/master/config/taxonomy.config.php

I think most fields are available, but not the Codestar UI yet. But I haven't tested much. Test and see. I think it should work.

**Comment by sinsky** [comment]
id description is the wordpress cat default .

taxonomy meta query i use two foreach . 

I think there will be a better way to do it?

**Comment by NoahjChampion** [comment]
I'm not sure.. I haven't tested much at all. 

@Codestar

**Comment by Codestar** [comment]
@sinsky yes all framework option fields available for Taxonomy ( If you write correct config ).

Yes @NoahjChampion all fields is works in Taxonomy :wink: :+1: Also i did not test, but i am sure :100: haha

**Comment by sinsky** [comment]
i mean the  the cat description is  textarea ,can we change it to Wysiwyg ~ @Codestar

**Comment by Codestar** [comment]
Oh no, it is not possible. because it is wp core field. You need to custom work for it. Framework can not touch it :+1:

**Comment by NoahjChampion** [comment]
@sinsky 

There are plugins you can do this, I haven't tested though. 

See 
- https://wordpress.org/plugins/wp-tax-wysiwyg/
- https://wordpress.org/plugins/taxonomy-tinymce/

There is one more that I bookmarked to use, but I have to find it. I like it better. It has more control.

**Comment by sinsky** [comment]
@NoahjChampion  thanks  ,but i don't like plugins so much. i will look at the plugin code ,thanks

**Comment by NoahjChampion** [comment]
@sinsky yes, code should be easy to pull from and keep light.
