### ISSUE TITLE
how to use get function with array value

### ISSUE THREAD

**Issue by hmbashar** [Codestar/codestar-framework#34]
Hi, I need your help. I've used "Get an option value (advanced)" 
```

// A Custom function for get an option
if ( ! function_exists( 'prefix_get_option' ) ) {
  function prefix_get_option( $option = '', $default = null ) {
    $options = get_option( 'my_framework' ); // Attention: Set your unique id of the framework
    return ( isset( $options[$option] ) ) ? $options[$option] : $default;
  }
}

echo prefix_get_option( 'opt-text' );
echo prefix_get_option( 'opt-text', 'default value' );
```
Now I've once media file. that's id is 'hg-logo'

Now I'm using prefix_get_option( 'hg-logo' ); but now need to use 'url' array for this fields. how can i use 'url' with my prefix funtion?

**Comment by Codestar** [comment]
Hi,

You can use like this.

```php
$logo = prefix_get_option( 'hg-logo' );
echo $logo['url'];
```

Hmm, there is no any quick way for get url directly... May be you can write a detailed get option function.

Regards, Codestar

**Comment by hmbashar** [comment]
> e

Yeah. Alrady I've use this way.
```
$logo = prefix_get_option( 'hg-logo' );
echo $logo['url'];
```
