### ISSUE TITLE
Number option min attribute not working

### ISSUE THREAD

**Issue by MarthSantos** [Codestar/codestar-framework#342]
**_min_** attribute does not work when I add the attributes key to Number option.
Here's the code I used:
```php
array(
 'id'         => 'banner_height',
 'type'       => 'number',
 'title'      => 'Banner Height',
 'default'    => '0',
 'attirbutes' => array(
  'min' => 0,
 ),
),
```
It looks like the **_min_** attribute is not being added when the number field is being generated.
![screen shot 2016-06-24 at 10 38 59 am](https://cloud.githubusercontent.com/assets/626518/16326305/0cab8bde-39f8-11e6-9823-71963fb2097a.png)

**Comment by Codestar** [comment]
`attirbutes` is wrong. `attributes` is correctly :smiley: spelling error...

**Comment by MarthSantos** [comment]
@Codestar you're right. LOL. I didn't noticed it yesterday. I was just copy and pasting code that time. LOL

**Comment by Codestar** [comment]
Cheers :wine_glass:
