### ISSUE TITLE
@Codestar - Check email...

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#343]
@Codestar 

Just thought I would post this here because recently my IP got blacklisted by some places. I got rid of every blacklist but one. I sent you an email about custom work hire, but my email may have went to spam because we don't email each other too often. 

Please check :) Let me know. 

Thanks.

**Comment by Codestar** [comment]
@NoahjChampion 

Ok, i am seeing your message in my inbox, it is ok. no spam. :wink:
