### ISSUE TITLE
Feature  condition field 

### ISSUE THREAD

**Issue by xpeeder** [Codestar/codestar-framework#35]
First of all this is a great framework.
It will be great if your framework have condition field like this http://cl.ly/image/3j3L3Z100t2K (this is from option tree)
when we select ON another field open  and if OFF this field hidden.

Thank you

**Comment by santiagointeractive** [comment]
This seems to be Dependency function you need there.
Codestar Framework already do this kind of thing.

Example:

<pre><code>array(
  'id'         => 'unique_option_1',
  'type'       => 'switcher',
  'title'      => 'Switcher Field',
  'default'    => true,
),
array(
  'id'         => 'unique_option_2',
  'type'       => 'text',
  'title'      => 'Text Field',
  'dependency' => array( 'unique_option_1', '==', 'true' ),
),
</code></pre>

More usage examples on the documentation:
http://codestarframework.com/documentation/#how-to-use-dependency

**Comment by xpeeder** [comment]
Great i will try this :)

Thank you

**Comment by xpeeder** [comment]
It will be great if you include this in your demo option to :)

most of the user thing this feature not available in your framework. 

Thank you

**Comment by Codestar** [comment]
Actually it is included in demo already, only you need to check Switcher tab and see last 'Switcher Field with Dependency Method' detail is [framework.config.php#L953,#L965](https://github.com/Codestar/codestar-framework/blob/master/config/framework.config.php#L953,#L965)
