### ISSUE TITLE
New Fields: CS Canvas 'type' => 'canvas_*'

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#352]
Hi. 
_(These are still in BETA - Feedback if any please.)_

I've made some custom fields that if you approve and/or help tweak we can add to the CF core. Let's hope so because you had this similar idea, but I went ahead and added it. But I need a little help on making the values unique for each field use.

I have called these **CS Canvas** fields for css design outputs.

I made 2 because (Canvas 2 - the normal one user have experienced) is not as advanced and (Canvas 1) I think is easier for developers to extended with custom parts, like box shadow, etc..

Here they are. 
- View the css gist [here](https://gist.github.com/NoahjChampion/9fc182ee610bc11c861caf3f529eb135).
## 1. CS Canvas Block

![theme settings custom theme wordpress-07-02-16-12-47-47](https://cloud.githubusercontent.com/assets/6123260/16541515/350350c4-4053-11e6-9cad-704e3a52d5b3.png)
![theme settings custom theme wordpress-07-02-16-13-04-13](https://cloud.githubusercontent.com/assets/6123260/16541630/806da6ac-4055-11e6-9f51-7ce640da160d.png)
![theme settings custom theme wordpress-07-02-16-13-05-01](https://cloud.githubusercontent.com/assets/6123260/16541636/adb844dc-4055-11e6-8bea-4f7ddb02cc3b.png)

**USAGE:**

``` php
// Field - Canvas Block
array(
  'id'    => 'canvas_block_id',
  'type'  => 'canvas_block',
  'title' => 'Canvas Block',
),

$background_color = canvas_block_id[background_color]
$text_color = canvas_block_id[text_color]

$margin_top = canvas_block_id[margin_top]
$margin_bottom = canvas_block_id[margin_bottom]
$margin_left = canvas_block_id[margin_left]
$margin_right = canvas_block_id[margin_right]

$padding_top = canvas_block_id[padding_top]
$padding_bottom = canvas_block_id[padding_bottom]
$padding_left = canvas_block_id[padding_left]
$padding_right = canvas_block_id[padding_right]

$border_top = canvas_block_id[border_top]
$border_bottom = canvas_block_id[border_bottom]
$border_left = canvas_block_id[border_left]
$border_right = canvas_block_id[border_right]

$border_type = canvas_block_id[border_type]
$border_color = canvas_block_id[border_color]

$border_radius_top = canvas_block_id[border_radius_top]
$border_radius_bottom = canvas_block_id[border_radius_bottom]
$border_radius_left = canvas_block_id[border_radius_left]
$border_radius_right = canvas_block_id[border_radius_right]
```
## 2. CS Canvas Box

![cs canvas box](https://cloud.githubusercontent.com/assets/6123260/16527117/fc2fa05c-3f82-11e6-8820-b7ef507cd1f6.png)

**USAGE:**

``` php
// Field - Canvas Box
array(
  'id'    => 'canvas_box_id',
  'type'  => 'canvas_box',
  'title' => 'Canvas Box',
),
```

@Codestar I know I emailed you about this. We can maybe continue here, but I wanted to post this so other users can see and give any feedback they have! :)

Thoughts?
- @Codevz @SantiagoInteractive @anhskohbo @mhmoudsami @Ansif @AminulBD @demartini

**Comment by anhskohbo** [comment]
I like "CS Canvas Box", like visual composer, simple and modem :)

**Comment by NoahjChampion** [comment]
@anhskohbo Thanks. 

I like `canvas_box` too. I did pull the design idea from VC. 

I like it, but it doesn't offer complete control. Most authors may not want complete control and users may not want complete control either, but I wanted to make something for complete control which is easier to extend because I myself needed complete control and simple controls. 

But I updated the `canvas_block` screenshot. What do you think now? 
Does it look better? More friendly?
- Added `border_type`, `border_color` and `border_radius`
- Removed Canvas Design label (not needed in actual implementation)
- Made the design cleaner

**Comment by AminulBD** [comment]
This is amazing! The canvas box is very user-friendly :+1:

**Comment by Tekanewa** [comment]
Noahj,

this is truly great and a really needed parameter type!

What would be even greater, is if one could remove some inputs; for example, if I only want to provide an input for borders, there should be a setting option to show/hide all others:

    // Field - Canvas Box
    array(
        'id'    => 'canvas_box_id',
        'type'  => 'canvas_box',
        'title' => 'Canvas Box',
        'background' => false,
        'fontcolor' => false,
        'margin' => false,
        'padding' => false,
        'border' => true,
    ),

**Comment by NoahjChampion** [comment]
@Tekanewa 

Good idea! When I first made this I was very unfamiliar with how to create a custom field, but after I made my last field (about a week ago) and became familiar, this is easy to do. Will do!

What do you think about this for the Border Radius? King Composer has made an update and in their BETA at least, this new Border Radius style is available. Screenshot below. 

![image](https://cloud.githubusercontent.com/assets/6123260/17279744/7225930a-574a-11e6-985d-cb45ff971dfa.png)

Then we can make this true or false too.

**Comment by Codestar** [comment]
@NoahjChampion Yeah, looking amazing. good field. let's add on useful-tools.

**Comment by MichaelSmi** [comment]
@NoahjChampion is there any chance to get your Canvas Fields custom code? Or when do you plan to integrate it in to the core? I hope I don't miss anything here... I'm currently working on a custom theming section. Your Canvas Field would be the perfect way to fit users needs in this place!

**Comment by NoahjChampion** [comment]
@MichaelSmi ok. I will try to send it this week. I need to look through some old files to find it or recreate it. I didn't end up using it, but it should be in my dropbox.

**Comment by MichaelSmi** [comment]
@NoahjChampion that would be very awesome!!! :heart_eyes: Can I give you a favor? Maybe support this project with a donation?

**Comment by MichaelSmi** [comment]
@NoahjChampion Hope you had a nice holiday. Is there any chance to get your code from the canvas CF? It would really help me!

**Comment by NoahjChampion** [comment]
@MichaelSmi 

I just bookmarked your reply yesterday or the day before so I could get back to it. Sorry, I didn't get the 22 days ago response because I haven't reinstalled my Github notifier mac app and haven't been keeping up with them. 

But sure, you can support with a donation that would be great. I do have to remake this field, which I can, just communicate by email @ Noahj {at} FearlessMode {dot} com. (anyone else can do the same)
