### ISSUE TITLE
Jquery Reload  Issue

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#353]
Hi

After new update faced upload button and color picker issue, so i open support ticket and its fixed - https://github.com/Codestar/codestar-framework/issues/328

but again i faced same issue :( im using aqua page builder, when i drop some block to page builder area, dependency, upload button and color picker not working, if i click save button, then i can fix it, 

please check this - 
![animation](https://cloud.githubusercontent.com/assets/5784887/16543945/9a81ab2e-410e-11e6-9865-41dbd024cf5a.gif)

Any suggestions for this ?

ps - Last time I fixed using this code, `$('.cs-framework, #page-builder').CSFRAMEWORK_RELOAD_PLUGINS();` but its not working now

**Comment by WPsmart** [comment]
Any suggestion ?

**Comment by NoahjChampion** [comment]
@WPsmart - I don't know of a fix as last time. But I know Codestar is out on holiday and won't be back for a week or more. I'm not sure that he will be available till he gets back sometime. I only know because I emailed him about custom work.

**Comment by WPsmart** [comment]
Oh, Thanks For update :+1:

**Comment by Codestar** [comment]
@WPsmart send me a email about this. i need to see it on live-site. routewp[at]gmail[dot].com

**Comment by WPsmart** [comment]
@Codestar Oh Thanks Codestar, Wait i will send it today :)

**Comment by Codestar** [comment]
@WPsmart Ok :wink:

**Comment by WPsmart** [comment]
Are you received it Codestar? I send it now

**Comment by Codestar** [comment]
@WPsmart 

Ok found the code. add this code on your cs-framework.js end of code (but inside jquery wrapper).

```php
$('#blocks-archive > li.block').each(function() {
  $(this).on('dragstop', function( event, ui  ){
    $(ui.helper).CSFRAMEWORK_DEPENDENCY();
    $(ui.helper).CSFRAMEWORK_RELOAD_PLUGINS();
  });
});
```

**Comment by WPsmart** [comment]
@Codestar

Yahoo Its Working Well Sir, Thanks very very much. All of theme issues Fixed No any issues, Dependency and upload working well, 

one issue here (im really sorry disturbing you sir. because i have no anyone for asked abut this)
color pickers show as duplicated 

![image](https://cloud.githubusercontent.com/assets/5784887/16771329/baa7cb70-486d-11e6-9763-97027e978db9.png)

**Comment by Codestar** [comment]
@WPsmart oh no problem :wink: 

Uh yes i checked. but i am seeing you changed line 1430 as ( or using older js version i am not sure but update this line )

```php
// from
$('body').CSFRAMEWORK_RELOAD_PLUGINS();
// to
$('.cs-framework, #widgets-right').CSFRAMEWORK_RELOAD_PLUGINS();
```

**Comment by WPsmart** [comment]
All errors Fixed, Thanks Very much Sir, Thanks Again

**Comment by Codestar** [comment]
You're welcome :+1:
