### ISSUE TITLE
CF not working as plugin for latest Wordpress

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#354]
@sohan5005 

Please be more specific as to what is not working. What is not working?

I just installed the master on a fresh install and everything seems to be working fine.

![](http://g.recordit.co/3yT7rdLl0i.gif)

**Comment by sohan5005** [comment]
I'm trying to include it in a plugin. It's not working. I've tried on fresh wp installation too.

**Comment by NoahjChampion** [comment]
> trying to include it in a plugin

Does this mean you are activating Codestar from the plugins page?
Or des this mean you are running your own include from a theme or somewhere else to run Codestar from the plugins page?

And did you try the master Codestar Framework to double check the one you have isn't having an issue?

I tried the latest master and latest Wordpress to check. 

Let me know, thanks.

**Comment by sohan5005** [comment]
Nope. I've created a custom plugin. Codestar framework is included in that plugin. When I activate the plugin, nothing appears. No Framework options, no shortcodes and no metaboxes. But when I include the plugin in theme, it works perfectly.

**Comment by sohan5005** [comment]
![image](https://cloud.githubusercontent.com/assets/5048770/16546432/efba7f32-416b-11e6-86c8-17086dff824e.png)

Just installed a new wordpress and downloaded the framework from github, extracted on plugins directory and activated it. Nothing appears.

**Comment by sohan5005** [comment]
Just found the problem. It's in function `cs_locate_template`. See the picture:

![image](https://cloud.githubusercontent.com/assets/5048770/16546519/25bf6d7e-416f-11e6-8c4e-72a045fb2d55.png)

The constant `CS_BASENAME` holds the full absolute path to cs-framework directory in plugins folder. But in the function, we see `$plugin_normal_override = $dir_plugin . $dir_template;` which refers to `WP_PLUGIN_DIR . CS_BASENAME . '/'. $template_name;`.

So the result is like this for me: `c:\www\wp\wp-content\plugins\c:\www\wp\wp-content\plugins\cs-framework-master\template.php` which is the error. I don't know why it's happening.

To fix this in real time, I've just edited a line from:
`$plugin_normal_override = $dir_plugin . $dir_template;`
to:
`$plugin_normal_override = $dir_template;`

Now it works for me. Please take a look at this issue in the next update.

**Comment by NoahjChampion** [comment]
@sohan5005 Thanks. Glad you got it working! 

I will test it out when I get a moment then. 

But share with me the code you are using to call the framework to load from your plugin so I can do the same exactly.

**Comment by anamwp** [comment]
I applied your process @sohan5005 . But CSS Not working properly. 
Wait for the next response

**Comment by sohan5005** [comment]
Yes, I got same kind of error later. Js & css files were not loading. I think this issue varies on different server configuration. @Codestar please take a look at this in different server configuration and make a unified way that works on all server.

The first error I got on EasyPHP server. After I upload my files to a live server, I got some other error. Then I did something like this [here](https://github.com/Codestar/codestar-framework/blob/master/cs-framework-path.php#L114):
`$located = apply_filters( 'cs_locate_template', file_exists( $located ) ? $located : $dir_template, $template_name );`

Now works on both of my server. But I know this is not a perfect way.

**Comment by sohan5005** [comment]
@NoahjChampion install EasyPHP server and use the master as plugin, you'll get the error.

**Comment by Codestar** [comment]
Hi guys,

If still you are having this issue, you can send me your wordpress admin informations via email routewp[at]gmail[dot]com

Now i tested it on WordPress Version 4.5.3 as plugin. it is working normally. but maybe there is php server issue. i can check and found any solution for users :wink:

**Comment by Codestar** [comment]
#375
