### ISSUE TITLE
How to use Multilang and show_only_lang 

### ISSUE THREAD

**Issue by sinsky** [Codestar/codestar-framework#355]
How to use Multilang and show_only_lang 
Can you give me an example?

**Comment by NoahjChampion** [comment]
@sinsky email me! Just thought of something you wanted. 

noahj at entuitions period com

**Comment by sinsky** [comment]
@NoahjChampion Your email address is ?

**Comment by NoahjChampion** [comment]
@sinsky read above, does it come out alright? I gave it above. 

noahj at entuitions period com

**Comment by Codestar** [comment]
I think it is ok ? :smile:

**Comment by NoahjChampion** [comment]
@Codestar, no not from me. I didn't know how to use it to help @sinsky.
I thought maybe a wp-config code might help, but no.

**Comment by Codestar** [comment]
@NoahjChampion I did not understand. what you need exactly? =) you do not know how to use `show_only_lang` ?

**Comment by NoahjChampion** [comment]
@Codestar Yes. Sinky's needs to know how to use Multilang and `show_only_lang`.

**Comment by Codestar** [comment]
Ok, i noted this. i will add a "how to usage" in framework documentation for this option soon :wink:
