### ISSUE TITLE
Gallery Image Adding Problme After few month 

### ISSUE THREAD

**Issue by proscriptsell** [Codestar/codestar-framework#356]
HI
Thanks for the great frame work. I really love this :)
I developed a site use this frame work ... but right now facing problem to adding more image gallery .
When will i go to more picture then lost old all gallery image .. 

Hope i will get feedback As soon as possbile ..

Sorry for bad english ..

Thanks

**Comment by NoahjChampion** [comment]
Hi @proscriptsell 

Glad you "love" this framework :)

General Questions. 

Are you updated to the latest version of Codestar? 
Which Wordpress version are you using?
Do you get any console errors when you find the image gallery issue?
When did you find the issue started occurring?

**Comment by proscriptsell** [comment]
Hi 
I am using 
wordpress  Version 4.5.3  and using latest verions of Codestar : Version: 1.0.1

For More detalis you check : http://alienative.ws/bsous-cms/wp-admin/edit.php?post_type=gallery
User: codestar
Password: admin123

Thanks

**Comment by Codestar** [comment]
Hi @proscriptsell 

I did try to login your wordpress but i can not see your wordpress system. you removed site? btw you can send your wordpress admin informations via routewp[at]gmail[dot]com
