### ISSUE TITLE
Add Shortcode Button in default text widget content area!

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#358]
Hi,

As it title says, can we able to add support of "Add Shortcode" button in a default text widget?

So, users can able to add shortcodes directly via text widget itself instead of going to take a reference in a pages.

Thanks! :)

**Comment by NoahjChampion** [comment]
@Ansif 

Maybe you can see how these plugins use the TInyMCE into their widget to get ideas for just the shortcode insert part? 

Plugins:

- https://wordpress.org/plugins/black-studio-tinymce-widget/screenshots/
- https://wordpress.org/plugins/wp-editor-widget/screenshots/

I think (but maybe not) adding the shortcode insert to the default text widget sounds like custom work since it is not done by many plugins or any plugin that I have seen. I usually steer away from the default text widget, but I think Wordpress should make the TinyMCE for the default text widget part of the core.

**Comment by Ansif** [comment]
@NoahjChampion Ok that's fine.

I'm also think WordPress will make that editor possible with text widget. Untill we can create our own widget using codestar fields. 👍 

That's the best solution now i think! :)

**Comment by NoahjChampion** [comment]
💯 

It should be fairly easy to create your own widget and add the TinyMCE or Add CF Shortcode option though. I've never done it, but I'm guessing it would be some simple filters to your widget or the Default Text Widget. Feel free to update for anyone else :)

**Comment by Ansif** [comment]
@NoahjChampion Sure! 👍 

Widget Preview : 
![custom-text-widget](https://cloud.githubusercontent.com/assets/5621180/16685539/6deabd0c-4529-11e6-863a-22217d6361aa.jpg)

Here it's code for custom text widget : 
<pre>
<?php
/*
 * Custom Text Widget
 */

class cs_text_widget extends WP_Widget {

  /**
   * Specifies the widget name, description, class name and instatiates it
   */
  public function __construct() {
    parent::__construct(
      'cs-text-widget',
      __( 'Custom Text Widget', 'text_domain' ),
      array(
        'classname'   => 'cs-text-widget',
        'description' => __( 'A custom text widget for our theme.', 'text_domain' )
      )
    );
  }

  /**
   * Generates the back-end layout for the widget
   */
  public function form( $instance ) {
    // Default Values
    $instance   = wp_parse_args( $instance, array(
      'title'    => '',
      'content' => ''
    ));

    // Title
    $title_value = esc_attr( $instance['title'] );
    $title_field = array(
      'id'    => $this->get_field_name('title'),
      'name'  => $this->get_field_name('title'),
      'type'  => 'text',
      'title' => __( 'Title :', 'text_domain' ),
    );
    echo cs_add_element( $title_field, $title_value );

    // Content
    $content_value = esc_attr( $instance['content'] );
    $content_field = array(
      'id'    => $this->get_field_name('content'),
      'name'  => $this->get_field_name('content'),
      'type'  => 'textarea',
      'shortcode'  => true,
      'attributes'    => array(
        'rows'        => 16,
        'cols'        => 20,
      ),
      'title' => __( 'Content :', 'text_domain' ),
    );
    echo cs_add_element( $content_field, $content_value );

  }

  /**
   * Processes the widget's values
   */
  public function update( $new_instance, $old_instance ) {
    $instance = $old_instance;

    // Update values
    $instance['title']      = strip_tags( stripslashes( $new_instance['title'] ) );
    $instance['content']    = strip_tags( stripslashes( $new_instance['content'] ) );

    return $instance;
  }

  /**
   * Output the contents of the widget
   */
  public function widget( $args, $instance ) {
    // Extract the arguments
    extract( $args );

    $title      = apply_filters( 'widget_title', $instance['title'] );
    $content    = $instance['content'];

    // Display the markup before the widget (as defined in functions.php)
    echo $before_widget;

    if ( $title ) {
      echo $before_title . $title . $after_title;
    }

    echo $content;

    // Display the markup after the widget (as defined in functions.php)
    echo $after_widget;
  }
}

// Register the widget using an annonymous function
add_action( 'widgets_init', create_function( '', 'register_widget( "cs_text_widget" );' ) );
</pre>

Thanks! 👍

**Comment by Codestar** [comment]
Nice code for users :+1:
