### ISSUE TITLE
Multiselect showing notice in widget

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#359]
Hello!
Multiselect showing a notice in widget after click on save.

Here is the message: Notice: Array to string conversion in C:\xampp\htdocs\318couture\wp-includes\formatting.php on line 1025

**Comment by WPsmart** [comment]
Hi

is "formatting.php" Codestar Framework File?

**Comment by NoahjChampion** [comment]
@WPsmart no it's not but Codestar could trigger this error. 

@sabuz You will have to provide your config to see if the issue can be duplicated. 

Do you get the same issue when using the default Wordpress theme, Twenty16?

I can test it out for you, but I haven't used any widgets yet, so I don't know until I can test it at least to try to help.

**Comment by sabuz** [comment]
Yes, same issue on twenty sixteen.

$cat_value = esc_attr($instance['cat']);
			$cat_field = array(
				'id' => $this->get_field_name('cat'),
				'name' => $this->get_field_name('cat'),
				'type' => 'select',
				'title' => 'Category',
				'options' => 'categories',
				'query_args' => array(
					'type' => 'product',
					'taxonomy' => 'product_cat',
					'order' => 'DESC',
				),
				'attributes' => array(
					'multiple' => 'multiple',
				),
			);
			echo cs_add_element($cat_field, $cat_value);

**Comment by sabuz** [comment]
There is same error for checkbox also. This is maybe the data is stored as string. But multi select and checkbox data are array.

**Comment by Codestar** [comment]
@sabuz 

You need to remove `esc_attr` for array strings. because this function using only clean texts. whats solution ? only update this line. btw this is same for multiple checkboxes.

```php
// from
$cat_value = esc_attr($instance['cat']);
// to
$cat_value = $instance['cat'];
```

**Comment by sabuz** [comment]
Yes, working now!
Thank you @Codestar

**Comment by Codestar** [comment]
You're welcome :+1:
