### ISSUE TITLE
CSS Output doesn't work

### ISSUE THREAD

**Issue by Radzio1615** [Codestar/codestar-framework#36]
I'm trying to use 'output' attribute to add background-image to my class. Code below doesn't work.
```
array(
'id'      => 'logo-img',
'type'    => 'background',
'title'   => 'Select Image',
'background_size' => false,
'background_attachment' => false,
'background_repeat' => false,
'background_position' => false,
'background_color' => false,
'output' => '.logo',
'dependency' => array( 'logo', '==', 'image' ),
),
```

**Comment by Codestar** [comment]
Hi,

I have just tested and worked normally. Btw, **output** feature only works as main option. I mention **output** doesn't support inside a group field or tabbed field ( means all of nested fields ).. Where you are using it exactly ?

Regards

**Comment by Radzio1615** [comment]
Thanks for answer
Yep I use it in tabbed field. Are you going to add support for this field? Is there a different way to output it?

**Comment by Codestar** [comment]
Hi,

You should to write custom **output** code for nested fields. Only supports top level field **output**. Because **output** controlling is complex for nested fields.

Regards
