### ISSUE TITLE
Using Codestar to populate pre-existing options

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#36]
Is it possible to use Codestar to generate fields that populate pre-existing WP options like blogname, blogdescription, etc...?

**Comment by Codestar** [comment]
Hi,

It is not possible, because you do not need to a framework for to change pre-existing WP options. You can use WordPress Core for this request ;)

**Comment by SteveS123** [comment]
Yeah I hear ya, I was hoping to amalgamate WP core options found on other pages into my Codestar option page.
