### ISSUE TITLE
CS Switcher as Visual Composer Field!

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#361]
Hi,

Here i've worked code star switcher field in visual composer field type.

![screen shot 2016-07-11 at 4 20 43 pm](https://cloud.githubusercontent.com/assets/5621180/16728355/762be1b0-4783-11e6-89da-d9d97d7c3236.png)

Code : 
<pre>
/* Switcher */
if(!class_exists('VcSwitcherField'))
{
	class VcSwitcherField {

		public function __construct() {
			add_action( 'vc_load_default_params', array(
				&$this,
				'vc_load_vc_switcher_param',
			) );

			add_action( 'vc_backend_editor_render', array(
				&$this,
				'vc_enqueue_editor_scripts_befe',
			) );
		}

		public function vc_enqueue_editor_scripts_befe() {
			wp_enqueue_script( 'core-scripts', YOUR_PATH_URL . '/core-scripts.js' );
		}

		/**
		 * Add custom param to system
		 */
		public function vc_load_vc_switcher_param() {
			vc_add_shortcode_param( 'switcher', array(
				&$this,
				'vc_switcher_form_field',
			) );
		}

		/**
		 * Checkbox shortcode attribute type.
		 *
		 * @param $settings
		 * @param string $value
		 *
		 * @return string - html string.
		 */
		public function vc_switcher_form_field( $settings, $value ) {
			$output = '';
			$on_text = isset($settings['on_text']) ? $settings['on_text'] : 'On';
			$off_text = isset($settings['off_text']) ? $settings['off_text'] : 'Off';
			$current_value = is_string( $value ) ? ( strlen( $value ) > 0 ? explode( ',', $value ) : array() ) : (array) $value;
			$values = isset( $settings['value'] ) && is_array( $settings['value'] ) ? $settings['value'] : array( __( '' ) => 'true' );
			if ( ! empty( $values ) ) {
				foreach ( $values as $label => $v ) {
					$checked = count( $current_value ) > 0 && in_array( $v, $current_value ) ? ' checked' : '';
					$output .= '&lt;div class=&quot;cs-field-switcher&quot;&gt;&lt;div class=&quot;cs-fieldset&quot;&gt;&lt;label class=&quot;vc_checkbox-label&quot;&gt;&lt;input id=&quot;' . $settings['param_name'] . '-' . $v . '&quot; value=&quot;' . $v . '&quot; class=&quot;wpb_vc_param_value ' . $settings['param_name'] . ' ' . $settings['type'] . '&quot; type=&quot;checkbox&quot; name=&quot;' . $settings['param_name'] . '&quot;' . $checked . '&gt; ' . $label . '&lt;em data-on=&quot;'. $on_text .'&quot; data-off=&quot;'. $off_text .'&quot;&gt;&lt;/em&gt;&lt;span&gt;&lt;/span&gt;&lt;/label&gt;&lt;/div&gt;&lt;/div&gt;';

				}
			}

			return $output;
		}
	}
}

if( class_exists( 'VcSwitcherField' ) )
{
	$switcher = new VcSwitcherField();
}
</pre>

Above code you'll see, **core-scripts.js** that file code is here : 
Also, replace **YOUR_PATH_URL** to your path.
<pre>
// Switch field for Visual Composer
(function ( $ ) {

  /* Class used in edit form and editor models to save/render shortcode */
  vc.atts.switcher = {
    /**
     * Used to save multiple values in single string for saving/parsing/opening
     * @param param
     * @returns {string}
     */
    parse: function ( param ) {
      var arr, newValue;

      arr = [];
      newValue = '';
      $( 'input[name=' + param.param_name + ']', this.content() ).each( function () {
        var self;

        self = $( this );
        if ( this.checked ) {
          arr.push( self.attr( 'value' ) );
        }
      } );
      if ( 0 < arr.length ) {
        newValue = arr.join( ',' );
      }
      return newValue;
    },
    /**
     * Used in shortcode saving
     * Default: '' empty (unchecked)
     * Can be overwritten by 'std'
     * @param param
     * @returns {string}
     */
    defaults: function ( param ) {
      return ''; // needed for saving - without this default value for param will be first value in array
    }
  };
})( window.jQuery );
</pre>

And, finally usage is : 
<pre>
array(
          "type" => "switcher",
          "heading" => __( "Open New window?", 'text_domain' ),
          "param_name" => "open_link",
          "std" => true,
          'value' => '',
),
</pre>

Hope you get understand above codes! 👍

**Comment by Codestar** [comment]
Thanks for code :+1:
