### ISSUE TITLE
Multiple check box issue?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#362]
Hi,

I've exact same issue like #83.

But, that solutions also not working for me.

My theme option code is here, hide meta data's field : 
<pre>
array(
  'id'      => 'theme_metas_hide',
  'type'    => 'checkbox',
  'title'   => __('Meta\'s to hide', 'text_domain'),
  'info'    => __('Check items you want to hide from blog/post meta field.', 'text_domain'),
  'class'      => 'horizontal',
  'options'    => array(
    'category'   => __('Category', 'text_domain'),
    'date'    => __('Date', 'text_domain'),
    'author'     => __('Author', 'text_domain'),
    'comments'      => __('Comments', 'text_domain'),
  ),
),</pre>

How to get each of those separate conditions? I've tried like mentioned in #83 : 
<pre>
$metas_hide = cs_get_option('theme_metas_hide');
if ( isset($metas_hide) && !$metas_hide[1] ) { // If not check, echo following codes.
  // code here
}</pre>

Thanks! 👍

**Comment by Codevz** [comment]
Hi, 

Try like this: 

```PHP
if ( in_array( 'author', $metas_hide ) ) {
 // So do this ...
} else {
 // ...
}
```

**Comment by Ansif** [comment]
Hi,

Thanks for your response! 

I've tried that too. But that gives me an error like : 
<pre>
Warning: in_array() expects parameter 2 to be array, null given in
</pre>

👍

**Comment by Codevz** [comment]
Edited please try again.

**Comment by Ansif** [comment]
Great, You're Awesome!! 💯
