### ISSUE TITLE
How to use shortcodes

### ISSUE THREAD

**Issue by saqibali334** [Codestar/codestar-framework#363]
When I click on shortcode button to generate and fill all the fields and after submit it will display a shortcode in content section.When i see this on frontend it show same shortcode as in content.

e.g:
[cs_toggle title="First Title"]First Description[/cs_toggle]
this shortcode is generated in content section in wp backend.
and it shows same shortcode on frontend.there is no layout now design only shortcode is echoed.
this is the screenshot where it is echoed.
![harry s 2 - just another wordpress site 2016-07-14 11-26-41](https://cloud.githubusercontent.com/assets/20452935/16830049/e8d80d40-49b5-11e6-9b86-ef211ef0c89c.png)

please help.

**Comment by Codevz** [comment]
Hi, 

You need to add output function for each shortcode eg:

```PHP
function prefix_cs_toggle( $atts, $content = '' ) {
	$atts = shortcode_atts( array(
		'title' => ''
	), $atts );

	return $atts['title'] . '<br />' $content;
}
add_shortcode( 'cs_toggle', 'prefix_cs_toggle' );
```

**Comment by saqibali334** [comment]
o yes got it.It works
Thanks

**Comment by Codestar** [comment]
Great :+1:

**Comment by saqibali334** [comment]
hi again,
How to enable shortcode in metaboxes because framework metabox doesnot support shortcode.
When I insert shortcode in metabox. It will display same shortcode on frontend,not the output.

**Comment by Codevz** [comment]
For metabox output with shortcode you need to it like this:

```PHP
$meta = get_post_meta( $post->ID, 'your_meta_id', true );
$content = empty( $meta['your_field_id'] ) ? '' : $meta['your_field_id'];

do_shortcode( $content );
```

Read more about [do_shortcode()](https://developer.wordpress.org/reference/functions/do_shortcode/) function

**Comment by saqibali334** [comment]
Hi,
I have added group field and in the shortcode. When I clicked on add shortcode button in page content a popup box open and I select the shortcode but the group fields doesn't add.
this is my code:
array(
            'name'      => 'image_slider',
            'title'     => 'Image Slider Shortcode',
            'fields'    => array(
	                  array(
					 	'id'              => 'unique_group_slider',
						'type'            => 'group',
						'title'           => 'Slider Fields',
						'button_title'    => 'Add Image',
						'fields'          => array(

                        array(
							'id'        => 'slide_image',
							'type'      => 'image',
							'title'     => 'Use Image of size 286x186.',
							'add_title' => 'Slide Image',
						    ),

                        array(
                            'id'      => 'image_link',
                            'type'    => 'text',
                            'title'   => 'Image Link',
                            'desc'     => 'Must use http:// with the link.',
                            'attributes'    => array(
                                'placeholder' => 'http://'
                            )
                        ),
                    )
                ),		
            ),
        ),

**Comment by saqibali334** [comment]
This is screenshot and button that did't work.
![edit page landing pages wordpress 2016-07-19 15-25-26](https://cloud.githubusercontent.com/assets/20452935/16946864/3834bdc6-4dc5-11e6-979e-5afc355de976.png)

**Comment by NoahjChampion** [comment]
Hi @saqibali334 

When developing you should always keep a working framework install to compare fields. I believe all "working" fields in the demo are good and should have no issues. 

In the [demo shortcode.config.php](https://goo.gl/fXBASP) there is no `'type' => 'group'`. I don't think the group field works in the shortcode.config since it is not there, but `group` field changes to `clone` and `clone_duplicate` and you can achieve the same result.

The coding changes like this when using shortcodes...
`'type' => 'group'` 
**becomes** `'view' => 'clone'` **or** `'view' => 'clone_duplicate'` your choice.

See [demo shortcode.config.php](https://goo.gl/fXBASP) for example.
(NOTE: The docuementation site needs updated on this :) 👍 

---

When using `clone` or `clone_duplicate`

`'id' => 'your_field_id'` 
**becomes** `'clone_id' => 'your_field_id'`

`'title' => 'Add Slider Image'` 
**becomes** `'clone_title' => 'Add Slider Image'`

`'fields' => array()` 
**becomes** `'clone_fields' => array()`

**So I think you will have to change it like this which works for me...**

```php
$options[]     = array(
  'title'      => 'Slider Shortcodes',
  'shortcodes' => array(

    // begin: shortcode
    array(
      'name'          => 'image_slider',
      'title'         => 'Image Slider',
      'view'          => 'clone_duplicate',
      'clone_title'   => 'Add Slider Image',
      'clone_fields'  => 
      array(
        array(
          'id'        => 'slide_image',
          'type'      => 'image',
          'title'     => 'Use Image of size 286x186.',
          'add_title' => 'Select Slider Image',
        ),
        array(
          'id'          => 'image_link',
          'type'        => 'text',
          'title'       => 'Slider Image Link',
          'desc'        => 'Must use http:// with the link.',
          'attributes'  => 
          array(
            'placeholder' => 'http://'
          ),
        ),
      ),
    ),
    // end: shortcode

  ),
);
```

### See screenshot examples with your config...

![image](https://cloud.githubusercontent.com/assets/6123260/16949763/94157eb8-4d8a-11e6-86f4-69e6b2fba7dc.png)
![image](https://cloud.githubusercontent.com/assets/6123260/16950299/8de59322-4d8d-11e6-8cd8-b16af980aa1f.png)

**Comment by saqibali334** [comment]
ok thanks alot.

**Comment by saqibali334** [comment]
hi,
how to add shortcode function in function.php file to show valuse of this shortcode on page.

$options[]     = array(
  'title'      => 'Slider Shortcodes',
  'shortcodes' => array(

    // begin: shortcode
    array(
      'name'          => 'image_slider',
      'title'         => 'Image Slider',
      'view'          => 'clone_duplicate',
      'clone_title'   => 'Add Slider Image',
      'clone_fields'  => 
      array(
        array(
          'id'        => 'slide_image',
          'type'      => 'image',
          'title'     => 'Use Image of size 286x186.',
          'add_title' => 'Select Slider Image',
        ),
        array(
          'id'          => 'image_link',
          'type'        => 'text',
          'title'       => 'Slider Image Link',
          'desc'        => 'Must use http:// with the link.',
          'attributes'  => 
          array(
            'placeholder' => 'http://'
          ),
        ),
      ),
    ),
    // end: shortcode

  ),
);

**Comment by saqibali334** [comment]
Hi,
I add shortcode in the page content.Then I add a paragraph and media image in content.
then again add a shortcode.
but shortcode value show one after another on frontend. I want to show first shortcode value then paragraph and then again shortcode.
Please help me to resolve the issue.

**Comment by saqibali334** [comment]
Hey I got the solution for this:
use shortcode like this one

function test() {
    ob_start();
    echo '-TEST-';
    $output = ob_get_contents(); // end output buffering
    ob_end_clean(); // grab the buffer contents and empty the buffer
    return $output;
}
add_shortcode( 'testshortcode', 'test' );
Thanks

**Comment by malek1316** [comment]
Codestar is awesome for me. How can display clone_fields value in forntend ?? Please help me anybody

**Comment by nurulamin9** [comment]
How can i display clone field in frontend using shortcode ?

**Comment by haqueamirul** [comment]
how to display Duplicate Group Shortcode in codestar framework
