### ISSUE TITLE
menuWarning: Illegal string offset

### ISSUE THREAD

**Issue by SquareNetMedia** [Codestar/codestar-framework#367]
if you set a default option and the user does not type anything in the box, you get an error Warning: Illegal string offset when that meta box is called.

How comes it doesn't pick up your default setting?
array(
          'id'    => 'banner_duration',
          'type'  => 'text',
          'title' => 'Duration',
          'default' => '4000',
          'desc'       => __( 'Duration is the amount of time in between slides'),
        ),

**Comment by Codestar** [comment]
Show a screenshot, i did not understand where is the issue. i can use default param without error.
