### ISSUE TITLE
Shortcode for Group field 

### ISSUE THREAD

**Issue by theparmis** [Codestar/codestar-framework#369]
Hi,
I just involved for days to create export php for my shortcode : 
<pre>
[social]
[social_sub social_icon="fa fa-facebook" social_link="#"]
[social_sub social_icon="fa fa-google" social_link="#"]
[social_sub social_icon="fa fa-twitter" social_link="#"]
[/social]
</pre> 

I searched many times and i use many many method like another array in <code> extract(shortcode_atts(array())); 
</code> to get and show social_sub , But it seems there is a problem. 

I just tried some ways like <code>foreach</code> command for every social_sub in <code>shortcode_atts</code> but it doesn't too work.

Anybody can help me ?

**Comment by Ansif** [comment]
Hi,

You may not set $content = true in your shortcode function. Check following code : 
`<?php
/* Social */
function social_shortcode_function($atts, $content = true) {
   extract(shortcode_atts(array(
      "custom_class" => ''
   ), $atts));

   $result = '<ul class="my-social '. $custom_class .'">'. do_shortcode($content) .'</ul>';
   return $result;

}
add_shortcode("social", "social_shortcode_function");

/* Social Sub */
function social_sub_function($atts, $content = NULL) {
   extract(shortcode_atts(array(
      "social_link" => '',
      "social_icon" => '',
   ), $atts));

   $social_link = ( isset( $social_link ) ) ? 'href="'. $social_link . '"' : '';

   $result = '<li><a '. $social_link .'><i class="'. $social_icon .'"></i></a></li>';
   return $result;

}
add_shortcode("social_sub", "social_sub_function");`

👍

**Comment by Codestar** [comment]
Follow the @Ansif 

Also you can use this for your request.

```php
// USAGE
[sociasl]
[social_sub social_icon="fa fa-facebook" social_link="#"]
[social_sub social_icon="fa fa-google" social_link="#"]
[social_sub social_icon="fa fa-twitter" social_link="#"]
[/socials]
```
```php
/**
 *
 * Socials
 *
 * @since 1.0.0
 * @version 4.1.0
 *
 */
if( ! function_exists( 'cs_socials' ) ) {
  function cs_socials( $atts, $content = '', $key = '' ) {

    global $cs_socials;
    $cs_socials = array();

    extract( shortcode_atts( array(
      'id'    => '',
      'class' => '',
    ), $atts ) );

    do_shortcode( $content );

    // is not empty clients
    if( empty( $cs_socials ) ) { return; }

    $output   = '';
    $output  .= '<ul>';

    foreach( $cs_socials as $social ) {

      $icon = $social['atts']['social_icon'];
      $link = $social['atts']['social_link'];

      $output .= '<li>'. $icon . $link . '</li>';

    }

    $output  .= '</ul>';

    return $output;

  }
  add_shortcode( 'cs_socials', 'cs_socials' );
}


/**
 *
 * Social
 *
 * @version 1.0.0
 * @since 1.1.0
 *
 */
if( ! function_exists( 'cs_social' ) ) {
  function cs_social( $atts, $content = '', $key = '' ) {
    global $cs_socials;
    $cs_socials[]  = array( 'atts' => $atts, 'content' => $content );
    return;
  }
  add_shortcode('cs_social', 'cs_social');
}
```

**Comment by haqueamirul** [comment]
how to display Duplicate Group Shortcode in codestar framework
