### ISSUE TITLE
CSS assets called via HTTP in HTTPS admin

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#37]
The plugin is calling the assets via HTTP when my WP admin is HTTPS.

<link rel='stylesheet' id='cs-framework-css'  href='http://...
<link rel='stylesheet' id='font-awesome-css'  href='http://...

**Comment by Codestar** [comment]
Hi,

Hmm, I am using wordpress core WP_PLUGIN_URL and get_template_directory_uri() this constants adding http or https, not me ? i mean this is not my code.

Another libraries including as https ?

BTW, Framework have a action for modify url and directory. Take a look below, you can use it so:

```
/**
 *
 * Codestar Framework Libraries URL fix for from http to https
 *
 */
function custom_get_path_locate( $paths ){
  $paths['uri'] = str_replace( 'http', 'https', $paths['uri'] );
  return $paths;
}
add_action( 'cs_get_path_locate', 'custom_get_path_locate', 100 );

/**
 *
 * Codestar Framework
 * A Lightweight and easy-to-use WordPress Options Framework
 *
 */
require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';
```
