### ISSUE TITLE
How i add Nested Group???

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#370]
Hi,
I want to add nested group. I have a group field and i want to add another group include this group.
Ex: i am making a pricing table, i have added a group for each pricing table now i need another group for each pricing table feature list. 
So please help me to add nested group
Regard
RD Development

**Comment by Codevz** [comment]
Hi, 

Its not possible with codestar framework. Is better if you add multiple text field inside your group option, then for front-end check which text field does value then show it. eg.

```PHP
array(
  'id'              => 'pricing_table',
  'type'            => 'group',
  'title'           => 'Pricing table',
  'button_title'    => 'Add New',
  'accordion_title' => 'Add New',
  'fields'          => array(
    array(
      'id'          => 'title',
      'type'        => 'text',
      'title'       => 'Title',
    ),
    array(
      'id'          => 'subtitle',
      'type'        => 'text',
      'title'       => 'Sub title',
    ),
    array(
      'id'          => 'price',
      'type'        => 'text',
      'title'       => 'Price',
    ),
    array(
      'id'          => 'feature_1',
      'type'        => 'text',
      'title'       => 'Feature 1',
    ),
    array(
      'id'          => 'feature_2',
      'type'        => 'text',
      'title'       => 'Feature 2',
    ),
    array(
      'id'          => 'feature_3',
      'type'        => 'text',
      'title'       => 'Feature 3',
    ),
    array(
      'id'          => 'feature_4',
      'type'        => 'text',
      'title'       => 'Feature 4',
    ),
    array(
      'id'          => 'feature_5',
      'type'        => 'text',
      'title'       => 'Feature 5',
    ),
    array(
      'id'          => 'feature_6',
      'type'        => 'text',
      'title'       => 'Feature 6',
    ),
    array(
      'id'          => 'button_title',
      'type'        => 'text',
      'title'       => 'Button title',
    ),
    array(
      'id'          => 'button_link',
      'type'        => 'text',
      'title'       => 'Button link',
    ),
  )
),
```

then for front you need something like this for checking each table price.

```PHP
$meta = get_post_meta( $post->ID, 'page_meta', true );
$pricing_table = isset( $meta['pricing_table'] ) ? $meta['pricing_table'] : array();

foreach( $pricing_table as $table ) {

  // ...

  $count = 6;
  for ( $i = 0; $i < $count; $i++ ) { 
    if ( $table[ 'feature_' . $i ] ) {
      echo $table[ 'feature_' . $i ];
    }
  }

  // ...

}
```

I hope this way helps you. 

Cheers

**Comment by wpexpert24** [comment]
Hi,
This is a way. But I want nested option in codestar. why in codestar there is no nested group option.
This is really nice framework and it should add nested option to looking more professional. 
If i need to spend money i agree to get nested group option.

**Comment by saddamwp** [comment]
I want to add the nested group. 
this time is possible.

**Comment by saidl14s** [comment]
I also want to add the nested group.

**Comment by Codestar** [comment]
Nested group is not possible yet.

**Comment by ProMehedi** [comment]
Codestart has another feature That's called fieldset. You can use that, this is the pretty much same as the nested group.
[Check Out there documentation](http://codestarframework.com/documentation/#fieldset)

**Comment by Muhendis85** [comment]
is it possible now? nested group

**Comment by asufian97** [comment]
waiting for answer :)

**Comment by asufian97** [comment]
is there anyone try this https://github.com/Codestar/codestar-framework/issues/547
Let me know please if it's work.

**Comment by Codestar** [comment]
It is not possible still..
