### ISSUE TITLE
Dependency for shortcodes?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#372]
Hi,

I want dependency option in shortcodes too. I write dependency code, exactly like metabox and themeoptions to shortcode fields. But in shortcode it's not working.

Thanks! 👍

**Comment by Ansif** [comment]
Sorry, i was used shortcode out side of clone fields.

Within that clone fields dependency is working fine as expected!

Is we can able to control fields dependency, outside of clone fields?

**Comment by Codestar** [comment]
Hi, No, it is not possible. :smile:

**Comment by Ansif** [comment]
Ok fine. 😄
