### ISSUE TITLE
Is there any action hook to trigger when the CS Options (menu_page) are saved?

### ISSUE THREAD

**Issue by mayeenulislam** [Codestar/codestar-framework#376]
I'm taking `posts_per_page` value of a `WP_Query()` dynamically using a CS Options page (menu_page). I'm using Transients for caching. I need to clear the cache when the Options page (made using `cs_framework_options` filter) is saved.

What's the action hook I can hook to trigger the action?

**Comment by NoahjChampion** [comment]
@mayeenulislam 

See #158

**Comment by Codestar** [comment]
Also you can use `cs_validate_save_after` this action for trigger when options saved.
