### ISSUE TITLE
Framework menu element don't show on child theme

### ISSUE THREAD

**Issue by aqazi** [Codestar/codestar-framework#379]
I'm using baki free theme and it's based on cs framework. When creating a child theme, the framework's menu element disappear.
I checked the override method, but in my case I don't want to override anything.
The theme uses CF V1.0.0 and I use WP 4.5.3
I tried to load the CF in function.php of my child theme by adding:
`require_once get_template_directory() . '/framework/cs-framework.php';`
but no luck!
Is there anything I need to do in my child theme in order to show the theme's option panel?

**Comment by Codestar** [comment]
I tested it now again, it is working normally in my localhost. I think there is a setup problem. you can send the files via routewp[at]gmail[dot]com

**Comment by aqazi** [comment]
I sent the files.
I tracked the loading of php files like I read on another issue and I did find that only `cs-framework.php` and `cs-framework-path.php` were loaded.
I tried to make the changes you recommended for the function `cs_get_path_locate()` to extract correctly the framework path but still don't work
```
function cs_get_path_locate() {
    $dirname        = wp_normalize_path( dirname( __FILE__ ) );
    $plugin_dir     = wp_normalize_path( WP_PLUGIN_DIR );
    $located_plugin = ( preg_match( '#'. $plugin_dir .'#', $dirname ) ) ? true : false;
    $directory      = ( $located_plugin ) ? $plugin_dir : get_template_directory_uri();
    $directory_uri  = ( $located_plugin ) ? WP_PLUGIN_URL : get_template_directory();
    $basename       = str_replace( wp_normalize_path( $directory ), '', $dirname );
    $dir            = $directory . $basename;
    $uri            = $directory_uri . $basename;
    return apply_filters( 'cs_get_path_locate', array(
      'basename' => wp_normalize_path( $basename ),
      'dir'      => wp_normalize_path( $dir ),
      'uri'      => $uri
    ) );
  }
```

**Comment by kingRayhan** [comment]
Same problem to me

**Comment by imamassamaqandy** [comment]
Hi, I have same problem with Child Theme.

I can load the Framework Options, Metabox, etc from Plugin (upload plugin), but when I add as a theme extensions inside my child theme, it wont showing.

There's no error, but just not showing only.
I tested to change my parent theme and also with fresh WordPress install, still same.

Thank you

**Comment by Galibri** [comment]
@imamassamaqandy  Did you find any solution? Same problem for me. No error, just not showing the options panel.

**Comment by mrkenng** [comment]
@imamassamaqandy  and @Galibri You will need to change a few things in order to load on child theme. Firstly, the loading of cs-framework.php on your child theme functions.php should be `require_once get_stylesheet_directory() . '/cs-framework/cs-framework.php';
`
get_stylesheet_directory() <-- Child theme.

then open up cs-framework-path.php and find line 28 and 29 and replace it with 

`$directory      = ( $located_plugin ) ? $plugin_dir : get_stylesheet_directory();
    $directory_uri  = ( $located_plugin ) ? WP_PLUGIN_URL : get_stylesheet_directory_uri();`

This should work. 👍

**Comment by emrulmax2** [comment]
Its still a issue. I couldn't work it on child theme. I already created a child theme and I included all the codestart framework in the parent theme function.php . but it still not working at all. It only shows when I active parent theme.

**Comment by Galibri** [comment]
@mrkenng Thanks for your solution. I will try it if this works and will update here.

**Comment by zihad0292** [comment]
@mrkenng Thanks, it works.

**Comment by aqazi** [comment]
Thanks guys
