### ISSUE TITLE
View uploaded image in the upload field.

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#38]
Hi, 
Is it possible to view the uploaded image on upload field ? If yes can anyone tell me how can I do this? 

 I didn't see any option for that on documentation. 

Thanks

**Comment by Codestar** [comment]
Hi,

Upload filed view uploaded image as default ? I did not understand, if you have images in Media Library firstly showing exists images. Shortly, i am seeing this when i click upload field button:

![support_14-11-54](https://cloud.githubusercontent.com/assets/1313301/6391695/ad3afd96-bdc1-11e4-8a3c-1e230c39171a.png)

**Comment by wpbean** [comment]
Sorry I didn't mean that. If you see the the following image, you can see there is a logo we can see what I upload in the logo upload field . 

<img src="http://puu.sh/gdTed/a64d9772a2.png">

I need something like this.

**Comment by Codestar** [comment]
Hi,

Oh yes, i understand it now. hmmm i will try to add it. hmm btw did you try new field image upload ? take a look this:

```
array(
  'id'        => 'site_logo',
  'type'      => 'image',
  'title'     => 'Image with Custom Title',
  'add_title' => 'Add Logo',
),
```

btw i added this option 1 week ago. field [documentation here](http://codestarframework.com/documentation/#image)

**Comment by wpbean** [comment]
WoW. That's why I love this framework. Thanks once again.

**Comment by Codestar** [comment]
You're welcome :+1:
