### ISSUE TITLE
New Field Request 

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#39]
Hi Codestar ,

It would be great if you add those filed in future .

*Date field
*Date Time unix field
*Date unix field

**Comment by Codestar** [comment]
Hi,

Yes, noted this option fields, I will add them in the future ;)

**Comment by devariya** [comment]
Great news

**Comment by Codestar** [comment]
@devariya can you leave an email via routewp[at]gmail[dot]com
