### ISSUE TITLE
Shortcode upload field error, when we try to upload a image from it?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#390]
Hi,

I've latest version of codestar framework. For upload, image and gallery fields have some issue about WordPress media uploader popup.

As, you can see in below screenshot. Media upload popup loads behind the shortcode popup, so we not able to choose image for it. To choose a image we've to close shortcode popup first to choose our image.

![screen shot 2016-08-15 at 10 02 03 pm](https://cloud.githubusercontent.com/assets/5621180/17671621/9fbd0e6e-6335-11e6-892f-96d9bc81e519.png)

Thanks!

**Comment by NoahjChampion** [comment]
Hey @Ansif, this should be an easy fix. I don't have the default install to check with Shortcode and media uploader, but inspect the css and change the z-index value. 

You should be able to make the shortcode popup, `display: none;` then you see and edit the media upload screen. Then find the z-index of the media upload screen and set it's value higher than the shortcode popup. Then if that works, make a pull request. This should be easy, I just can't check it out right now, but you could probably fix it quicker than you may get a response.

See @ https://css-tricks.com/almanac/properties/z/z-index/

**Comment by Ansif** [comment]
Yes, you're right! 👍 

Shrotcode popup use high value of z-index for it. So, native WordPress media uploader not front of that.

So, following css will fix that issue : 
<pre>.media-modal {z-index: 1000103 !important;}</pre>

Thanks! 👍

**Comment by Codestar** [comment]
@Ansif 

Hey bro, i tested it on my localhost in a clean wordpress, it is looking normally. i wonder, is this issue same for clean wordpress, or there is a conflict with a plugin or anything ?

**Comment by Ansif** [comment]
@Codestar. Ok, bro. I think it's conflict from other plugins.

Thanks! :)

**Comment by Codestar** [comment]
You're welcome :+1:
