### ISSUE TITLE
Feature Request : Typography field font variant needs multiple select capabilities?

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#392]
Hi,

Can you please make font variant field as multiple select option. As you know, we need same font with different type of variant at once. So, this is really needed feature to all! :)

![screen shot 2016-08-16 at 10 39 30 am](https://cloud.githubusercontent.com/assets/5621180/17688569/07f37960-639e-11e6-98ac-7cf5cb0e06a7.png)

Thanks! 👍

**Comment by Ansif** [comment]
I think we've to create new select option for it? For each type of selectors?

**Comment by Codestar** [comment]
Yes, you need to create a new select option =)

**Comment by Ansif** [comment]
Ok fine, :)
