### ISSUE TITLE
Small thing, how to output category of custom post type?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#395]
Hi. 

Maybe I've just had not sleep, but I don't see how to output the category of a custom post type. 

I want the select output to be `my-post-type > my-category-name` only. 

How can I do that? Is this possible?

**Comment by Ansif** [comment]
Hi,

You can get custom post type categories from following php code : 
<pre>
$category_list = wp_get_post_terms($post->ID, 'portfolio_category');
foreach ($category_list as $term) {
  echo $term->name;
}
</pre>

👍

**Comment by NoahjChampion** [comment]
@Ansif Hi, thanks! 

I don't think that will work. 

What I want is the select output to list the posts that are assigned a certain category. 

Here is an example what I thought might work, but doesn't. 

```php
'options' => 'posts',
  'query_args' => array(
    'post_type' => 'post-type-name',
    'taxonomy' => 'category-name',
  ),
```

So the select output will only list post names that have `category-name` saved to that post. 

Now that I think of it, maybe that is not good for performance, because it will have to get the post meta for each post listed to see if that category is assigned or not and return the results?

**Comment by NoahjChampion** [comment]
Like the frontend blog post list of a site where you can filter the results of the posts by category. I just want to list the posts that are using a specific category. 

Is that clearer? I can maybe take a look at frontend plugins that are doing this (filtering by category and returning those results).

**Comment by NoahjChampion** [comment]
@Ansif 

Something like this but for the backend, ahha. 


Reference:
@ http://diythemes.com/thesis/rtfm/add-category-posts-on-a-page/

```php
add_action('thesis_hook_after_content','my_page_of_posts');
function my_page_of_posts() {
  if (is_page('833')) {
  $custom_loop = new WP_Query('posts_per_page=5&cat=9');
  echo '<div class="my-archives"><ul class="archive-list">';
  if ( $custom_loop->have_posts() ) : while ( $custom_loop->have_posts() ) : $custom_loop->the_post();
    echo '<li><a class="archive-link" href="' . get_permalink() . '">' . get_the_title() . '</a> <span class="my-comment-count">( ';
    comments_number('0', '1', '%');
    echo ' )</span></li>';
  endwhile;
    wp_reset_query();
  endif;
  echo '</ul></div>';
  }
}
```

**Comment by NoahjChampion** [comment]
@Ansif 

Ok, I found a function for this but it is for the frontend, haha. This should clear up what I mean,if I wasn't able to make myself clear ;) 

[in_category](https://developer.wordpress.org/reference/functions/in_category/)

I want to get **in_category** of my **post-type** and output into the select options. 

@Codestar any idea? Is this supported?

**Comment by Ansif** [comment]
Oh you want that in field type of codestar framework. I thought you just want to output the value in front end.

For that, please refer documentation :
http://codestarframework.com/documentation/#select-with-custom-post-type-categories
<pre>
array(
  'id'             => 'unique_option_512',
  'type'           => 'select',
  'title'          => 'Select Field for CPT Posts',
  'options'        => 'categories',
  'query_args'     => array(
    'type'         => 'movies',
    'taxonomy'     => 'movies_taxonomy',
    'orderby'      => 'post_date',
    'order'        => 'DESC',
  ),
  'default_option' => 'Select a category',
),
</pre>

👍

**Comment by NoahjChampion** [comment]
Hmm... ok. I will try this again. I saw this and tried it, but maybe I just got confused, lol. Which is what I was saying in the beginning, because I thought this was already possible.

**Comment by NoahjChampion** [comment]
@Ansif 

Ok, I tried this again about 15 different times and when I add a taxonomy the output returns nothing. What should my taxo be?

```php
array(
  'options'        => 'categories',
  'query_args'     => array(
    'type'         => 'movies',
    'taxonomy'     => 'movies_taxonomy', // What should this be? My Category, my category ID? I've tried but none are outputting. 
  ),
),
```

**Comment by NoahjChampion** [comment]
Hi. Yeah, I checked and maybe this is not supported because the demo doesn't have this demo. 

There is only demos for listing the the categories, not posts in a certain category. 

I'll see what I can for a function though and come back to this.
