### ISSUE TITLE
New Feature: CS Dynamic Metabox Title, a little help maybe?

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#396]
@Codestar 
@Codevz 

What do you think about this?

Giving the option to output the post title in the metabox title for clarity purposes?

This works fine, except when I click Add New "Post" the post type title for Post is not generated. It works when adding a new page, products, etc. and when editing pages, products or posts, just only not when adding a new "Post" from the post type post. 

### Code...

```php
// ----------------------------------------------------------------------------------------------------
// My Get Current Post Type Function
// ----------------------------------------------------------------------------------------------------
function cs_get_post_type() {
	global $post, $typenow, $current_screen;
	// We have a post so we can just get the post type from that
	if ($post && $post->post_type) {
		return $post->post_type;
	}
	// Check the global $typenow
	else if ($typenow) {
		return $typenow;
	}
	// Check the global $current_screen Object
	else if ($current_screen && $current_screen->post_type) {
		return $current_screen->post_type;
	}
	// Check the Post Type QueryString
	else if (isset($_REQUEST['post_type'])) {
		return sanitize_key($_REQUEST['post_type']);
	}
	// Try to get via get_post(); Attempt A
	else if (empty($typenow) && !empty($_GET['post'])) {
		$post = get_post($_GET['post']);
		$typenow = $post->post_type;
		return $typenow;
	}
	// Try to get via get_post(); Attempt B
	else if (empty($typenow) && !empty($_POST['post_ID'])) {
		$post = get_post($_POST['post_ID']);
		$typenow = $post->post_type;
		return $typenow;
	}
	// Try to get via get_current_screen()
	else if (function_exists('get_current_screen')) {
		$current = get_current_screen();
		if (isset($current) && ($current != false) && ($current->post_type)) {
			return $current->post_type;
		}
		else {
			return null;
		}
	}
	// We do not know the post type so return nothing and expect a bug/conflict report =)
	return null;
}
// ----------------------------------------------------------------------------------------------------
// My Dynamic Meta Box Title Output
// ----------------------------------------------------------------------------------------------------
function cs_dynamic_metabox_title() {
    global $pagenow;
    // Run this only on post type related pages or we will get "Notice: Trying to get property of non-object in..." for variable $title
    if ($pagenow == 'post-new.php' || $pagenow == 'post.php') {
        $post_type_name = get_post_type_object(cs_get_post_type());
        $title = $post_type_name->labels->singular_name;
        return "$title Settings";
    }
}
```

### Config...

```php
$options[] = array(
	'id' => '_custom_settings',
	'title' => cs_dynamic_metabox_title(), // Run the dynamic metabox title function for this metabox only
	'post_type' => $supported_post_types,
	'context' => 'normal',
	'priority' => 'default',
	'sections' => array()
);
```

Example ### output...

![image](https://cloud.githubusercontent.com/assets/6123260/17782221/834116c4-6540-11e6-8a3b-10450da424b8.png)

I was thinking maybe we can offer the text before and after `cs_dynamic_metabox_title()` as an input for the developer. Thoughts on that?

And do you know how to check so the dynamic metabox title generates when adding specifcally new "Posts" on post-new.php?

**Comment by Codevz** [comment]
Good idea ;) but personally i set "**Page settings**" for all of the post types.

**Comment by NoahjChampion** [comment]
@Codevz Hey, yeah no problem. 

I just wanted a little more clarity since I am offering tutorials throughout my theme within the framework I wanted a little more clarity to the customer. So when I speak in the tuts about "Pages" or "Posts" etc. I want that to be clear to them when tweaking things to their liking. I'm trying to have the framework options reflect my tutorials and vice versa :) - Thanks! Appreciate the feedback! I'm just happy I could figure it out. It took me some hours and it turned out to be much simpler than I found online, haha.

**Comment by Codevz** [comment]
@NoahjChampion I underestand, Everyday i facing begginers clients that they don't know difference between Page, Post or Post type, I totally agree with your idea, but you know is better to keeping our themes & plugins light weight for better performance backend and frontend. 

Anyway if your project is not heavy, then add any functions your want :D Its your project :smiley:
