### ISSUE TITLE
Remove Shortcode And Taxonomy Options From Framework

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#398]
Is it possible to remove shortcode and taxonomy options from framework? 

I just want to have CS for theme and metabox options.

Thanks much for great framework!

**Comment by NoahjChampion** [comment]
@pn1gh2 

You can turn each framework portion/config off. 

See [cs-framework.php](https://github.com/Codestar/codestar-framework/blob/master/cs-framework.php#L51-L52) Lines 51-52. Just define them as false in your theme. 

But if you want, You can comment out the `cs_locate_template` for these files and then delete those files related to shortcodes and taxos, if you want. I believe I did this before to make the package lighter and no problems came up. Above is the recommended way.

**Comment by pn1gh2** [comment]
@NoahjChampion Thanks Noah. Appreciate your point-out.

Are there any hooks from CS to disable shortcode and taxonomy - without touching core? I found cs_taxonomy_options and cs_shortcode_options filters at documentation. But I still couldn't figure out.

**Comment by pn1gh2** [comment]
I add two line in functions.php from child theme.

`define( 'CS_ACTIVE_TAXONOMY',   false );`
`define( 'CS_ACTIVE_SHORTCODE',  false );`

And it works. Hopefully it is the right way to disable certain option.

**Comment by NoahjChampion** [comment]
Hi, great. Yes, this is the current way. Thanks! Cheers!
