### ISSUE TITLE
How to use Font Family in Shortcode

### ISSUE THREAD

**Issue by saqibali334** [Codestar/codestar-framework#402]
Hi @Codestar

Font Family Used in shortcode doesn't show on page.
Like I am using shortcode:
`<?php function prefix_v4_testimonial($atts , $content = '' ){
    ob_start();
    global $post; 
    $atts = shortcode_atts(
       array(
       'testimonial_font_family' => ''   
       ),);?>`

but it show empty on page
    font-family: ; 
Can Anyone Help Please:

**Comment by Codestar** [comment]
Typograpy option field is not available for shortcode generator.. it will be available in v2 ;)
