### ISSUE TITLE
category, tag, query_args .. issue, sort of kind of... ??

### ISSUE THREAD

**Issue by NoahjChampion** [Codestar/codestar-framework#407]
Hi.

When using...

```php
'options' => 'categories'
'options' => 'tags'
```

These only return an item if a post has been assigned to them. Is there a way to return them if they exist and no post has been assigned to them? Basically, return them regardless if a post is assigned or not to the category or tag?

**Comment by Codestar** [comment]
Hi,

Maybe you can try this.

```php
'options'       => 'categories',
'query_args'    => array(
  'hide_empty'  => false, // or true
),
```

**Comment by NoahjChampion** [comment]
💯
