### ISSUE TITLE
How to return the taxonomy name instead of id in 'accordion_title' ??

### ISSUE THREAD

**Issue by EnterpriseBranding** [Codestar/codestar-framework#408]
When using...

``` php
'accordion_title' => 'field_id'
```

and `field_id` is the return of the `'options' => 'categories or tags'` the `accordion_title` will return the category/tag id number and not the category/tag name. 

I know cats and tags are identified by id's mostly (I think), but is it possible and if so any example how to return the name of the category or tag so I can get the `accordion_title` to populate the category/tag name instead of the id number? The id number doesn't help for `accordion_title` at all :)

**Comment by Codestar** [comment]
Yes why not, it is possible. Actually i need to improve `accordion_title` again in v2 :) because there is a lot of quesitons about this. we need to a flexible `accordion_title' :+1

**Comment by Codestar** [comment]
Fixed in v2.
