### ISSUE TITLE
feature request : submenu page

### ISSUE THREAD

**Issue by mrqaidi** [Codestar/codestar-framework#409]
Hello

thanks for this awesome framework  i will use it  in my new theme . i am asking you to add an do_action in  admin_menu function in class CSFramework  to add my own submenu to my theme option section 

right now i  did this   and everything working fine

`  // adding option page
  public function admin_menu() {

```
$defaults_menu_args = array(
  'menu_parent'     => '',
  'menu_title'      => '',
  'menu_type'       => '',
  'menu_slug'       => '',
  'menu_icon'       => '',
  'menu_capability' => 'manage_options',
  'menu_position'   => null,
);

$args = wp_parse_args( $this->settings, $defaults_menu_args );

if( $args['menu_type'] == 'submenu' ) {
  call_user_func( 'add_'. $args['menu_type'] .'_page', $args['menu_parent'], $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ) );
} else {
  call_user_func( 'add_'. $args['menu_type'] .'_page', $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ), $args['menu_icon'], $args['menu_position'] );
}
do_action('aq_admin_menu');
```

  }`

**Comment by NoahjChampion** [comment]
@mrqaidi Hi!

Thanks for finding a solution, for now, that is working for you. But in v2 this is already supported natively because v2 it will allow for multiple instances of Admin pages.

**Comment by mrqaidi** [comment]
awesome  when v2 will be release ?

**Comment by NoahjChampion** [comment]
I'm not sure. Codestar will release his theme first. 

He mentioned in comments releasing his theme before the end of the year, so soon I hope :)

We are all waiting :) 💯  - He said it will have the date picker field too. :)

**Comment by mrqaidi** [comment]
@NoahjChampion  thanks for you info :)

**Comment by NoahjChampion** [comment]
No problem. It will maybe help someone else looking because most of those comments are in other issues as I have noticed them. #Salute

**Comment by mrqaidi** [comment]
yeah i changed title to be found  easier

**Comment by Codestar** [comment]
@mrqaidi 

I am planing to release v2 in end of this year. We are testing it, yet :+1:

**Comment by raajen** [comment]
@Codestar @NoahjChampion  
Can I get the v2 to help in testing? 
please email me @ raajen73@gmail.com

**Comment by raajen** [comment]
Year ended its already more than half of new year's new month, when will we get to hear about you?
