### ISSUE TITLE
WPML Error

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#41]
My theme testing On WPML team

and they say framework have one error

```
Array
(
    [type] => 1
    [message] => Call to undefined function get_current_screen()
    [file] => /cs-framework/classes/metabox.class.php
    [line] => 154
)
```

This is it, can you help me to fix this?

**Comment by Codestar** [comment]
Hi,

Can you re-download the framework, I think you are using old files, i had made an update for this issue. shortly update your files. ;)
