### ISSUE TITLE
"Text Field" in Metabox Issue

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#410]
"text field" (not textarea field) in metabox cannot accept string with single and double quotes. Would it be possible to fix that issue?

Thanks much!

**Comment by Codevz** [comment]
Hi, 

Thanks for reporting this issue, edit fields / text / text.php and change this:

`$this->element_value()`

to this: 

`htmlspecialchars( $this->element_value(), ENT_QUOTES )`

Hope this fix the problem.

**Comment by pn1gh2** [comment]
@Codevz Thank you very much! It works.
