### ISSUE TITLE
Default Values in Shortcode

### ISSUE THREAD

**Issue by Tekanewa** [Codestar/codestar-framework#416]
I apologize for posting three "issues" in one day, but the more I'm getting "into" CodeStar, the more feedback I have. :)

It would be great if the shortcode framework could be set to NOT generate a shortcode attribute for all attributes where the value corresponds to the set default value (if a default value has been set). That way, the generated shortcode can be kept much shorter, as the default values are usually be set in the shortcode function itself as well and therefore don't need to be added to the shortcode attributes again.

Any thoughts?

**Comment by Codestar** [comment]
#415
