### ISSUE TITLE
Using "fieldset" in metabox

### ISSUE THREAD

**Issue by pn1gh2** [Codestar/codestar-framework#421]
Hi @Codestar 

I'm trying to use "fieldset" in metabox. For example -

```
$options = array();

$options[] = array(
    'id'        => 'my_metabox',
    'title'     => 'Metabox',
    'post_type' => 'page',
    'context'   => 'normal',
    'priority'  => 'high',
    'sections'  => array(
        array(
            'id'       => 'my_button',
            'type'     => 'fieldset',
            'title'    => 'Button',
            'un_array' => true,
            'fields'   => array(
                array(
                    'id'    => 'my_button_icon',
                    'type'  => 'icon',
                    'title' => 'Button Icon',
                ),
                array(
                    'id'    => 'my_button_label',
                    'type'  => 'text',
                    'title' => 'Button Label',
                ),
                array(
                    'id'    => 'my_button_url',
                    'type'  => 'text',
                    'title' => 'Button URL',
                ),
            ),
        ),
    ),
);

CSFramework_Metabox::instance($options);
```

The issue is - when I use **'un_array' => true,** for "fieldset" in metabox, the option fileds within "fieldset" cannot hold data values.

Am I the only one who is facing that issue? 

Thanks always for amazing and lightweight framework. And happy thanksgiving to you!

**Comment by Codestar** [comment]
Hi,
```php
'un_array' => true,
```

this un_array method only working in option panel area not in metabox. i am planing to support this option for metaboxes future updates ;)

**Comment by choijun** [comment]
Hi @pn1gh2 
I have a idea for that problem, and you can try it
- Step 1: Open the file cs-framework/classes/metabox.class.php and insert the code below before the line 135 ( see screenshot http://prntscr.com/djztkf )
<pre>
if( 'fieldset' == $field['type'] && !empty($field['fields']) && !empty($field['un_array']))
{
    $fieldset_value = array();
    foreach($field['fields'] as $child_field )
    {
    	if(!empty($child_field['id']))
    	{
    	    $child_value_default = ( isset( $child_field['default'] ) ) ? $child_field['default'] : '';
            $fieldset_value[$child_field['id']] = ( is_array( $meta_value ) && isset( $meta_value[$child_field['id']] ) ) ? $meta_value[$child_field['id']] : $child_value_default;
        }
    }
    $field['child_value'] = $fieldset_value;
}
</pre>

- Step 2: Open the file cs-framework/fields/fieldset/fieldset.php and find the code
<pre>echo cs_add_element( $field, cs_get_option( $field_id ), $this->unique );</pre>
and replace it by
<pre>
if(isset($this->field['child_value']))
{
    $child_value = (isset($this->field['child_value'][$field_id])) ? $this->field['child_value'][$field_id] : '';
    echo cs_add_element( $field, $child_value, $this->unique );
}
else
{
    echo cs_add_element( $field, cs_get_option( $field_id ), $this->unique );
}
</pre>

I hope that will be helpful for you.
