### ISSUE TITLE
Default value of image_select type didn't work in Customizer

### ISSUE THREAD

**Issue by sonnnaht** [Codestar/codestar-framework#422]
Hi, This framework is verry great. Thanks you for sharing.
I has got issues in Customizer the image_select can't select default value.

`array(
	'name'          => 'layout',
	'default'   	=> 'value-2',
	'control'       => array(
		'type'      	=> 'cs_field',
		'options'     	=> array(
			'type'      	=> 'image_select',
			'radio'     	=> true,
			'title'     	=> esc_html__( 'Blog List Layout', 'basetheme' ),
			'options'   	=> array(
				'value-1' 		=> 'http://codestarframework.com/assets/images/placeholder/65x65-2ecc71.gif',
				'value-2' 		=> 'http://codestarframework.com/assets/images/placeholder/65x65-e74c3c.gif',
				'value-3' 		=> 'http://codestarframework.com/assets/images/placeholder/65x65-3498db.gif',
			)
		),
	),
),`

Sorry, I can't format code to beautiful more.

**Comment by Codestar** [comment]
Hi,

You're welcome, i am happy for you to use it. you need to use default value here.

```php
    array(
      'name'          => 'layout',
      'default'        => 'value-2', // default here
      'control'       => array(
        'type'        => 'cs_field',
        'options'     => array(
          'type'      => 'image_select',
          'title'     => 'Codestar Image Select Field',
          'options'   => array(
            'value-1' => 'http://codestarframework.com/assets/images/placeholder/65x65-2ecc71.gif',
            'value-2' => 'http://codestarframework.com/assets/images/placeholder/65x65-e74c3c.gif',
            'value-3' => 'http://codestarframework.com/assets/images/placeholder/65x65-3498db.gif',
          ),
          'radio'     => true,
        ),
      ),
    ),
```

**Comment by sonnnaht** [comment]
Hi,
Thank you for reply!
I has using your code, but It didn't work for me.
Are you have any other note for me.
Please look at image below.
![code](https://cloud.githubusercontent.com/assets/14999196/20765742/41e66ce2-b766-11e6-95f5-ec2bddac9e06.png)
![customize](https://cloud.githubusercontent.com/assets/14999196/20765744/45c68e1e-b766-11e6-9186-e7f17b245884.png)

**Comment by Codestar** [comment]
Hi,

Hmm interesting, maybe you click to "save" before add default value? can you try to change option name from "blog_list" to "blog_list_test"

Regards

**Comment by sonnnaht** [comment]
Hi,
I has change name => "layout" to another name, It working well,
But if name => "blog_post_layout", It don't work.
all name are unique.
Can you tell me why? thank you.

**Comment by Codestar** [comment]
I have not any idea really..

Btw, you can remove all saved options with this code... write this on functions.php and delete after refresh page..

```php
delete_option('_cs_customize_options');
```

This will reset options ;)

**Comment by sonnnaht** [comment]
okay, Thanks a lot. :+1:

**Comment by Codestar** [comment]
You're welcome :+1:
