### ISSUE TITLE
wp admin issue on hosted server in windows

### ISSUE THREAD

**Issue by anamwp** [Codestar/codestar-framework#423]
Can you please help me..When I use Codestar as a plugin on windows server and active the plugin then below error show.

Fatal error: Call to undefined function wp_get_current_user() in C:\Program Files (x86)\Ampps\www\greenland.demo.dev\wp-includes\capabilities.php on line 448

I download the latest version of CS framework  form github and I use latest version of WordPress. I really appreciate early response.

**Comment by anamwp** [comment]
Please see the attached file. Hope it should help you for debugging your code. 
![die worked](https://cloud.githubusercontent.com/assets/16535589/20785350/eb02b3ea-b7c9-11e6-9d60-f4dc047dbd29.jpg)
![die not worked](https://cloud.githubusercontent.com/assets/16535589/20785351/eb0dc118-b7c9-11e6-835c-224da285c1f8.jpg)

**Comment by Codestar** [comment]
Hi,

Hmm, it is very interesting, let me check it detailed. i did reply your email ;)

Regards

**Comment by lelik4w** [comment]
@Codestar pls, share the solution :)
tnx in advance!

**Comment by Codestar** [comment]
@lelik4w leave an email via routewp[at]gmail[dot]com
