### ISSUE TITLE
Fieldset option doesn't working on site

### ISSUE THREAD

**Issue by shadaf99** [Codestar/codestar-framework#424]
I m using Fieldset opton on framework, all are working fine, but the input/switch or any values ,  i m saving , doesnt showing in my front-end , i mean , on my site... any solutions?

![capture](https://cloud.githubusercontent.com/assets/24210361/20784244/4a09510c-b7c3-11e6-8cf3-b35778c01ab5.PNG)

**Comment by Codestar** [comment]
Can you show your config array ? let's see it.

**Comment by shadaf99** [comment]
here is the code i am using

 // -----------------------------
    // begin: sorter options       -
    // -----------------------------
   $options[]      = array(
  'name'        => 'news_ticker',
  'title'       => 'News Ticker',
  'icon'        => 'fa fa-paper-plane',

  // begin: fields
  'fields'      => array(

       
       array(
          'id'        => 'fieldset_news_ticker',
          'type'      => 'fieldset',
          'fields'    => array(
  array(
              'type'    => 'subheading',
              'content' => 'News Ticker',
            ),

           
        array(
          'id'      => 'news_ticker',
          'type'    => 'switcher',
          'title'   => 'News Ticker',
          'default' => true,
        ),

       // begin: a field
    array(
      'id'      => 'ticker_title',
      'type'    => 'text',
      'title'   => 'Title',
    ),
    // end: a field
	
	// begin: a field
    array(
      'id'      => 'ticker_items_count',
      'type'    => 'text',
      'title'   => 'Number of items',
    ),
    // end: a field
	
	
  array(
          'id'             => 'ticker_category',
          'type'           => 'select',
          'title'          => 'Categories',
          'options'        => 'categories',
          'default_option' => 'Select a category'
        ),
		
		
		
          ),
        ),
	


 ), // end: fields
);

**Comment by shadaf99** [comment]
i m using this code in **framework.config.php**

// -----------------------------
    // begin: sorter options       -
    // -----------------------------
   $options[]      = array(
  'name'        => 'news_ticker',
  'title'       => 'News Ticker',
  'icon'        => 'fa fa-paper-plane',

  // begin: fields
  'fields'      => array(

       
       array(
          'id'        => 'fieldset_7',
          'type'      => 'fieldset',
          'fields'    => array(
  array(
              'type'    => 'subheading',
              'content' => 'News Ticker',
            ),

           
        array(
          'id'      => 'fieldset_7_news_ticker',
          'type'    => 'switcher',
          'title'   => 'News Ticker',
          'default' => true,
        ),

       // begin: a field
    array(
      'id'      => 'fieldset_7_ticker_title',
      'type'    => 'text',
      'title'   => 'Title',
    ),
    // end: a field
	
	// begin: a field
    array(
      'id'      => 'fieldset_7_ticker_items_count',
      'type'    => 'text',
      'title'   => 'Number of items',
    ),
    // end: a field
	
	
  array(
          'id'             => 'fieldset_7_ticker_category',
          'type'           => 'select',
          'title'          => 'Categories',
          'options'        => 'categories',
          'default_option' => 'Select a category'
        ),
		
		
		
          ),
        ),
	


 ), // end: fields
);





and this php code where i want to show the value
<?php echo cs_get_option( 'fieldset_7_ticker_title' ); ?>






so hopefully that u guys will help me

**Comment by benimub** [comment]
Hi,
I am also having same problem does it have solution or not?

**Comment by girisagar051** [comment]
Yes i have also problem in switcher option in fieldset. when you disable the switcher,the switcher index disappears from the fieldset array. Do you have any idea about this?

**Comment by Codestar** [comment]
You need to use this coding for output:

```php
$fieldset_7 = cs_get_option( 'fieldset_7' );
echo $fieldset_7['fieldset_7_news_ticker'];
echo $fieldset_7['fieldset_7_ticker_title'];
echo $fieldset_7['fieldset_7_ticker_items_count'];
echo $fieldset_7['fieldset_7_ticker_category'];
```

**Comment by girisagar051** [comment]
yes i did in such a way but it works only when switcher is on.If the switcher is disabled,the index(fieldset_7_news_ticker) removed from the array and undefined index error occurs there.

**Comment by benimub** [comment]
@girisagar051 use condition 

$fieldset_7 = cs_get_option( 'fieldset_7' );
if($fieldset_7) {
echo $fieldset_7['fieldset_7_news_ticker'];
echo $fieldset_7['fieldset_7_ticker_title'];
echo $fieldset_7['fieldset_7_ticker_items_count'];
echo $fieldset_7['fieldset_7_ticker_category'];
}

This may help you.
