### ISSUE TITLE
Base 64 issues in Theme Check. It's not recommended in Marketplace or WordPress free theme repo!

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#426]
Hi @Codestar,

Hope you're doing good. And we're really waiting for your theme and codestar framework updates this month. 👍

I'm not able to fix this issue, we've used this in backup theme option codes. Can you please recommend any other ways instead of it?
![base_64](https://cloud.githubusercontent.com/assets/5621180/20786005/7048b42e-b7c9-11e6-8eef-cbcec28a0acf.png)

Thanks! :)

**Comment by Codestar** [comment]
Hi @Ansif 

Oh yes, it is frustrating. most common functions not acceptable by Marketplace or WordPress free. but we need to use this functions.

For eg. file_get_content, include_once, base64 etc. 

I think this functions is available for internet world :) I have not any idea really about this. i am trying to submit my theme with this functions. try your luck :)

@NoahjChampion @Codevz 

Also i think this two authors think same, there is no solution about this. there is two choose. "use" or "use your another idea" what can i do ? i am not sure :)

Regards

**Comment by Ansif** [comment]
Yes, i even don't have any idea instead **base64**. 👎 

It's really based on the theme reviewer! 😉 

Some of theme reviewers accept it & some don't. First, i've to prepare the list of standards and send the mails to all reviewers. That'll fix this issue, i hope. 😆 

For now, i'm going separate that particular function within my plugin.

Thanks! :)

**Comment by Ansif** [comment]
What i planned to use this function as : 

Call following helpers.php file functions to my plugin.
`/**
 *
 * Encode string for backup options
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
if ( ! function_exists( 'cs_encode_string' ) ) {
  function cs_encode_string( $string ) {
    return rtrim( strtr( call_user_func( 'base'. '64' .'_encode', addslashes( gzcompress( serialize( $string ), 9 ) ) ), '+/', '-_' ), '=' );
  }
}

/**
 *
 * Decode string for backup options
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
if ( ! function_exists( 'cs_decode_string' ) ) {
  function cs_decode_string( $string ) {
    return unserialize( gzuncompress( stripslashes( call_user_func( 'base'. '64' .'_decode', rtrim( strtr( $string, '-_', '+/' ), '=' ) ) ) ) );
  }
}`

And where ever we used **cs_encode_string** and **cs_decode_string** functions. I'm going to use : 
`if( ! function_exists( 'cs_decode_string' ) ) {`
method.

What you think? If it's fine, can you please add function_exists method in your files? So, i'll not loss this thing in next update!

Thanks! :)
