### ISSUE TITLE
Database fields copied/duplicated instead of updated for the CS metaboxes

### ISSUE THREAD

**Issue by Slobork** [Codestar/codestar-framework#427]
Hi, 

I have noticed some undesirable behavior in the database with the custom fields which are created/updated with the CS framework. Namely, after the post has been updated the meta key and its values are replicated in the database, with the new ID. Precisely, instead of updating the meta values of the same meta key, the new database field is added for the same meta key. See the screenshot.

![cs-f2](https://cloud.githubusercontent.com/assets/6130788/20868661/46a8db9a-ba61-11e6-8379-2fc2de13aabf.jpg)

Hopefully it's clear what I mean.

On the front side of the site it isn't noticeable since it will read from the last update.

You can see in the screenshot, with the theme which isn't using the CS framework to create and update the meta boxes, there is only one row for the meta key, which is updated when the values are changed through the UI. When the theme with the CS framework is used, the replicating problem occurs.

I've tested this on the localhost with my theme in development and with the CS Options Framework theme. Used WordPress 4.6 and 4.5. In all instances the issue occurs. In essence, it creates the unnecessary new database row, which in some instances may form the huge bloat if the post/page is updated many times.

**Important note:** The issue occurs only when the changes are made over the WordPress editor, i.e. for the content. When the changes are made in the meta box and the post/page updated, the meta value will be properly updated in the database, i.e. no problem of duplicating the field.

From recently I am using the wp-cli as well. Interesting, if I update the post's content with the wp-cli the issue won't appear. So, the problem is occurring only when the update is made over the regular WP interface.

It would be good if someone with more experience with the framework could take the further investigation. At least hopefully someone can promptly try to reproduce this so I can know that the issue isn't on my end.

Thanks!

**Comment by Codevz** [comment]
Hi, 

Try this, edit `metabox.class.php` and find this code:

```PHP
if( get_post_meta( $post_id, $request_key ) ) {

  update_post_meta( $post_id, $request_key, $request );

} else {

  add_post_meta( $post_id, $request_key, $request );

}
```

change it to this:

`update_post_meta( $post_id, $request_key, $request );`

**Comment by Slobork** [comment]
Yeap, that's it. We just need the confirmation from the @Codestar for the framework update with the next release.

**Comment by NoahjChampion** [comment]
He will update it :) 💯

**Comment by Codestar** [comment]
Updated @NoahjChampion @Codevz @NoahjChampion :+1:
