### ISSUE TITLE
How to work meta fields with "meta_query"?

### ISSUE THREAD

**Issue by channelriyas** [Codestar/codestar-framework#429]
Hi,

I have a meta field like this config:
```
$options[]    = array(
  'id'        => 'abc_section',
  'title'     => 'ABC',
  'post_type' => 'abc_cpt',
  'sections'  => array(
    array(

      'name'   => 'section_1',
      'fields' => array(
 
        array(
          'id'    => 'abc_field',
          'type'  => 'text',
          'title' => 'Abc Data:',
        ),
        
      ),
    ),

  ),
);
```

I know how to show custom meta, like this:
```
$var1 = get_post_meta( $post->ID, 'abc_section', true );
echo $var1['abc_field'];
```

But I curious to know how to run a wp_query with this meta_key, in this case, meta_key located under "abc_section" so how will be wp_query ?

some thing like this: 
```
$args = array(
	'post_type' => 'abc_cpt',
	'meta_query' =>array(
		array(
			'key'     => 'abc_section',
			'value'   => 'test value'
		),
	),
);
```
but 'abc_field' ?

Please help me on this!

Thanks!

**Comment by raajen** [comment]
I don't think you can directly do that with the framework by default unless you play with the 'cs_save_post' filter and save those values with the individual meta key in your case: 'abc_field'. The framework is quite extensible with the help of actions and filters provided. If you need help, please leave a comment here.

**Comment by raajen** [comment]
Here is a sample code with your configuration stated above:

`add_filter('cs_save_post', 'raw_save_metadata', 10, 3);
function raw_save_metadata($request, $request_key, $post)
{
	//only proceed for our custom post and if request key matches
	//so that other metaboxes won't be affected
	if($post->post_type === 'abc_cpt' && $request_key === 'abc_section'){
		$post_id = $post->ID;
		$key = 'abc_field';		
		$existing = get_post_meta($post_id, $key, true);
		$value = $request[$key];


		if($existing != $value){
			// we've modified content
			update_post_meta($post_id, $key, $value);
		} else if(empty($existing) && !empty($value)){
			// we've fresh value
			add_post_meta($post_id, $key, $value, true);
		} else if(empty($existing) && empty($value)) {
			// we don't have any values, so delete the key
			delete_post_meta($post_id, $key);
		}
	}

	// mandatory, for regular functioning
	return $request;
}`

**Comment by raajen** [comment]
Maybe this code can help you:

`add_filter('cs_save_post', 'raw_save_metadata', 10, 3);
function raw_save_metadata($request, $request_key, $post)
{
	//only proceed for our custom post and if request key matches
	//so that other metaboxes won't be affected
	if($post->post_type === 'abc_cpt' && $request_key === 'abc_section'){
		$post_id = $post->ID;
		$key = 'abc_field';		
		$existing = get_post_meta($post_id, $key, true);
		$value = $request[$key];


		if($existing != $value){
			// we've modified content
			update_post_meta($post_id, $key, $value);
		} else if(empty($existing) && !empty($value)){
			// we've fresh value
			add_post_meta($post_id, $key, $value, true);
		} else if(empty($existing) && empty($value)) {
			// we don't have any values, so delete the key
			delete_post_meta($post_id, $key);
		}
	}

	// mandatory, for regular functioning
	return $request;
}`

**Comment by raajen** [comment]
@channelriyas did it helped you? if so please close the issue :)

**Comment by channelriyas** [comment]
Raajen, thanks for the answer, sorry fo the late response!
So you saying we cannot write query directly, and look like native WP "add_meta_box" will be fine for like this wp_query situation.

**Comment by raajen** [comment]
If you try the solution given above it will work for you. You'll have to filter throught the cs_save_post for your needed meta keys.

~Thanks

**Comment by saqibali334** [comment]
Hi Rajeen,,
Thanks for your solution. This works perfect.
Thanks

**Comment by raajen** [comment]
@saqibali334,
You're welcome. 

~Cheers,
