### ISSUE TITLE
Gallery Caption

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#43]
How to display gallery image caption !!

**Comment by Codestar** [comment]
You can get image caption with this method:

```
$gallery = cs_get_option( 'gallery_1' );

if( ! empty( $gallery ) ) {

  $ids = explode( ',', $gallery );

  foreach ( $ids as $id ) {

    $attachment_src = wp_get_attachment_image_src( $id, 'full' );
    var_dump( $attachment_src ); // attachment informations

    $attachment_data = get_post( $id );
    // var_dump( $attachment_data ); // all data
    var_dump( $attachment_data->post_excerpt ); // getting caption from post_excerpt

  }

}
```

**Comment by devariya** [comment]
Cool

**Comment by devariya** [comment]
is it possible to get image upload date too !!!

**Comment by devariya** [comment]
Got it , but it's display date and time too ,How can i display only date !!

$attachment_data->post_date

**Comment by Codestar** [comment]
You can use so ```mysql2date( 'd-m-Y' , $attachment_data->post_date )``` and this function is safe because it is wordpress core function http://codex.wordpress.org/Function_Reference/mysql2date

**Comment by devariya** [comment]
Thank you very much :+1:

**Comment by Codestar** [comment]
You're welcome :+1:
