### ISSUE TITLE
How i can set value for certain input text when i coding ?

### ISSUE THREAD

**Issue by crying2812** [Codestar/codestar-framework#431]
Sorry for my bad english, my problem is i want to set a value for input text in admin section. 
Here my example: 
`$meta_data['unique_group_1'][1]['text-box-1'] = 'This is demo text for input';`

is there any way to do this ?

**Comment by raajen** [comment]
Do you want to set a default value for metabox? if so why not passing with a 'default' key paired with any value? or if you can explain a bit more of your situation.

**Comment by crying2812** [comment]
@raajen  tks for reply, for example, i have: 
$meta_data['unique_group_1']['text-box-1']
I want to change the value of this in database, how can i do that ?

**Comment by raajen** [comment]
Try with this one, I don't know the actual scenario, but try it running only once, running everytime may be 
`
// need to fire it in wp action cause init is too early
add_action( 'wp', 'xyz_alter_meta_value' );
function xyz_alter_meta_value() {
    global $post;
    
    $postID = $post->ID;

    // only do for certain post ids
    if( $postID !== 123 ) {
        return;
    }

    // only do for certain post type
    // it can be attached to above if block too
    if( $post->post_type !== 'post_type_slug' ){
        return;
    }


    $meta = get_post_meta( $postID, 'your_meta_key_here', true );
    $meta['text-box-1'] = 'your custom value';

    // first check where you want your custom value, if its set or not
    
    // echo '<pre>';
    // print_r($meta);
    // echo '</pre>';

    // then after everything is done update with your meta key and pass the $meta
    update_post_meta( $postID, 'your_meta_key_here', $meta );
}
`
