### ISSUE TITLE
Reset Button for Specific Fields and Section

### ISSUE THREAD

**Issue by saqibali334** [Codestar/codestar-framework#438]
Hi,
How to create reset button for specific sections of fields.
Is there any possibility or function for that.
Can someone explain
Thanks

**Comment by OmarAtta** [comment]
If you mean reset all options in all sections you need to set `"show_reset_all => true"` in framework.config.php (line 12) to show "Reset all options" button.
The "restore" button next to "save" button used to reset options in current section only.

**Comment by Codestar** [comment]
Hmm, i think it is not possible yet. :)
