### ISSUE TITLE
Theme Check WARNING.

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#44]
Hi, I was checking my theme and got some serious WARNING form CS framework. It's because of 
<pre> base64_encode </pre> & <pre> file_get_contents </pre> in several files. 

Here the screenshot of the theme check result

<img src="http://puu.sh/gtN6y/0f20cfa930.png" alt="cs-framework">  

Can you please help me to solve these issues. 

Thanks

**Comment by Codestar** [comment]
Yes, i know this warning, but this warnings passing with Theme-Check with ThemeForest-Check. I am an ThemeForest/Author and no problem this for TF Authors.

Btw about warnings, i was used ```wp_remote_get``` for ```file_get_content``` but it is not working for in all servers. i am not sure for this modification. and base64_encode passing on ThemeForest-Check.

Still you need to fix it, find alternative method for file_get_content and base64_encode and report me :+1:

**Comment by Codestar** [comment]
Shortly, Test it on Theme Check + ThemeForest-Check ( https://wordpress.org/plugins/themeforest-check/ )

**Comment by Codestar** [comment]
```file_get_content``` changed with ```WP_Filesystem``` and fixed :+1:
