### ISSUE TITLE
Code-star framework on wordpress not saving changes.

### ISSUE THREAD

**Issue by MayorBiney** [Codestar/codestar-framework#44]
I bought a new theme that came with your framework and any change made to the theme refuses to save.
![Screen Shot 2019-10-10 at 11 31 46 AM](https://user-images.githubusercontent.com/15333647/66565426-f9f56c80-eb51-11e9-83a5-5e241dff75d6.png)

**Comment by ashawkat** [comment]
You should contact with the theme author instead here as it might be a theme issue or may be a hosting issue.

**Comment by MayorBiney** [comment]
> You should contact with the theme author instead here as it might be a theme issue or may be a hosting issue.

I actually have and they are delaying so am trying all options.

**Comment by Codestar** [comment]
> > You should contact with the theme author instead here as it might be a theme issue or may be a hosting issue.
> 
> I actually have and they are delaying so am trying all options.

Hi @MayorBiney,

Hmm ok, I can check it for you, If you send me the wordpress admin informations via
**routewp[at]gmail[dot]com**

Regards, Codestar
