### ISSUE TITLE
Allow theme options to show when the wordpress role is a different one than admin

### ISSUE THREAD

**Issue by user247** [Codestar/codestar-framework#442]
Currently in my setup theme options shows only when the wordpress admin role user signs in into the dashboard. The codestar theme options does not show up when a user with another role such as author or editor sings in into the wordpress dashboard. I want to be able to allow user other than admin to configure settings through codestar theme options. I want to know if this is possible and how to achieve this. Thanks in advance.

**Comment by raajen** [comment]
@user247 ,

Offcourse you can if it's not already sorted out. You need to pass  'menu_capability' argument on the settings array with the value of any role suitable. 

Hope it helps

**Comment by user247** [comment]
@raajen Thanks for your reply. Can you also tell me what should i put in the 'menu_capability' if I want to allow three users 'admin', 'author' and 'editor' to use the Codestar Theme Options?

**Comment by raajen** [comment]
I think 'edit_published_posts' will work as per your expectation.
