### ISSUE TITLE
How Resize Uploaded Image

### ISSUE THREAD

**Issue by imrostom** [Codestar/codestar-framework#443]
I Want To Resize Automatically My Uploaded Image Codestar Upload Fields Like add image size.
![capture](https://cloud.githubusercontent.com/assets/14936617/23443766/274c5a7c-fe5b-11e6-87a9-016f8ad149d1.PNG)

**Comment by kingRayhan** [comment]
@OmarAtta Yeah , that's the best solution I think so .... 😄
