### ISSUE TITLE
Can't set default background image for background field on customize

### ISSUE THREAD

**Issue by sonnnaht** [Codestar/codestar-framework#446]
Hi,
On customize page, I had add a background field code, and set default value to it.
But image file show value "[object Object]" for any value set by default. Other attributes is well.
My code below:

```
             array(
			'name'          => 'header_background',
			'default'       => array(
			    'image'      => get_template_directory_uri() .'/images/bg.png',
			    'repeat'     	=> 'no-repeat',
			    'position'   	=> 'center center',
			    'attachment' 	=> 'scroll',
			    'size'       	=> 'cover',
			    'color'      	=> '',
			),
			'control'       => array(
				'type'      	=> 'cs_field',
				'options'     	=> array(
					'type'      	=> 'background',
					'title'     	=> esc_html__( 'Header Background', 'nemo' ),
					'dependency'   	=> array( 'header_style', '==', '3' ),
				),
			),
		),
``` 

![untitled](https://cloud.githubusercontent.com/assets/14999196/24258936/d25c12b8-1021-11e7-95a0-5ebc2d98f01f.png)

**Comment by Codevz** [comment]
Hi, 

Current version of CS framework do not support background field in customize page, You should wait until CS framework v2

Regards

**Comment by sonnnaht** [comment]
Hi,
Thank you for answer!
Regards.
