### ISSUE TITLE
How to update cs_get_option programmatically?

### ISSUE THREAD

**Issue by channelriyas** [Codestar/codestar-framework#451]
Hi,

How I could update value of an element in cs_get_option ? I can see this serialized data, how to update a specific element without affecting to other?

Thanks!

**Comment by Codevz** [comment]
If you want to update a option, you can use this: 

`cs_set_option( 'option_name', 'new_value'  )`

**Comment by channelriyas** [comment]
Thanks Codevz, its worked well, I was used complicated way something like array update, anyway thanks its working well!!!!

Any documentation for like this task? these are not available in [here](http://codestarframework.com/documentation).

**Comment by samjco** [comment]
Yes pleasssse more documentation on updating, adding, deleting programatically  option/meta fields!
