### ISSUE TITLE
Metabox without main id?!

### ISSUE THREAD

**Issue by ozknozsrt** [Codestar/codestar-framework#452]
![image](https://cloud.githubusercontent.com/assets/11375802/24751979/723e374a-1ad4-11e7-9d20-96f562189b3a.png)

My have old theme. But now my theme editing..

So, I just want to get with meta field id. How ? 

Thanks

**Comment by AminulBD** [comment]
Codestar store metadata in serialize format, So you will always require setting meta box ID to store meta data. Also you can check this #207
