### ISSUE TITLE
How create password type field?

### ISSUE THREAD

**Issue by channelriyas** [Codestar/codestar-framework#453]
I have to collect some secret keys so I think password type field is better than the just plain text field, any help?

**Comment by wiljonbolten** [comment]
You kan add/edit attributes, here is an example to transform a normal textfield into a password field.

`array(
    'id'         => 'secret_key',
    'type'       => 'text',
    'title'      => 'Secret key',
    'attributes' => array(
        'type' => 'password'
        ),
    ),`

**Comment by channelriyas** [comment]
It's worked, attributes overriding method is really great!!!

**Comment by wiljonbolten** [comment]
Yeah indeed, a small notice is that not every HTML5 input type works in every browser. For example `'type' => 'date'` is working great in Chrome but not in every other browser, but the fallback for the field is always text.

Another great thing is adding `'required' => 'required'` to make the field required.

**Comment by channelriyas** [comment]
I see that's really cool, and you know how to change switcher status-label? as default, every switch status-label is ON/OFF but I would like to change it's to YES/NO  can I do this also by attributes?
