### ISSUE TITLE
Title of elements in a group field

### ISSUE THREAD

**Issue by newRahulVerma** [Codestar/codestar-framework#454]
I have `group` field for slideshow in my Theme Options. The first field in that `group` is a `select` field with 'posts' as its options. When a new slide is added and saved, the title of that slide becomes "Slide: 254" (254 is the post id of the select post). Is it possible to display post title instead if post id in each slide title?

![group](https://cloud.githubusercontent.com/assets/3503359/24800250/fe0f149a-1bbc-11e7-8775-3c905ad2def6.png)

**Comment by Codevz** [comment]
In current version its not possible to get titles from ID's, but you can edit group field file and write some new codes to check if value is_int so  get title by get_the_title() function.

**Comment by kingRayhan** [comment]
@SantiagoInteractive 
Give your code here

**Comment by rahulnever2far** [comment]
@SantiagoInteractive If your code helps in getting around this issue, please share it.

**Comment by SantiagoInteractive** [comment]
What code @kingRayhan @rahulnever2far  ???
What are you talking about?
