### ISSUE TITLE
When will be next release? , I need Video Field type

### ISSUE THREAD

**Issue by nriddhi** [Codestar/codestar-framework#456]
This framework is has not video field type, when it will be available?

**Comment by Codevz** [comment]
Whats your mean by video type ?

**Comment by nriddhi** [comment]
video field type like oembed

**Comment by Codevz** [comment]
You can create one by yourself. Actually video field type is same as text field, just you need append video iframe when text field updating. jQuery can do it. 

Something like this

```JAVASCRIPT
$('.youtube_video_field').on('keyup', 'input', function() {

	var parent		= $( this ).parent(),
		video_id 	= $( this ).val(),
		iframe 		= iframe = '<iframe src="https://www.youtube-nocookie.com/embed/' + video_id + '" allowfullscreen></iframe>';

	if ( video_id.length < 3 ) {
		parent.find( 'iframe' ).detach();
		return;
	}

	if ( ! $( 'iframe', parent ).length ) {
		parent.append( iframe );
	}

});
```

PS. @Codestar working on his new theme and haven't free time for updating or adding new features currently, but when he finish his theme, he will release CS Framework v2 with new useful features.

**Comment by nriddhi** [comment]
where have to put this code?

**Comment by kingRayhan** [comment]
Make a file with name something like `cs-modify.js`.

**Put** these codes in cs-modify.js file.


```javascript
$('.youtube_video_field').on('keyup', 'input', function() {

	var parent		= $( this ).parent(),
		video_id 	= $( this ).val(),
		iframe 		= iframe = '<iframe src="https://www.youtube-nocookie.com/embed/' + video_id + '" allowfullscreen></iframe>';

	if ( video_id.length < 3 ) {
		parent.find( 'iframe' ).detach();
		return;
	}

	if ( ! $( 'iframe', parent ).length ) {
		parent.append( iframe );
	}

});
```
> Change `youtube_video_field` with your text field id

**Now** , Enqueue this js file in admin back-end
```javascript
// 2. Copy-Oaste this code on your themename/functions.php
if( ! function_exists( 'cs_modify_enqueue_script' ) ) {
  function cs_modify_enqueue_script() {
    wp_enqueue_script( 'cs-modify',  get_template_directory_uri() .'/js/cs-modify.js',  array( 'jquery' ), '1.0.0', true );
  }
  add_action( 'admin_enqueue_scripts', 'cs_modify_enqueue_script' );
}
```

**Comment by nriddhi** [comment]
can it be found from metabox putting youtube_video_field type?

**Comment by kingRayhan** [comment]
I didn't tried but I believe it will work in metabox as well :)

**Comment by kingRayhan** [comment]
# This issue should be closed
