### ISSUE TITLE
Group within Group

### ISSUE THREAD

**Issue by newRahulVerma** [Codestar/codestar-framework#458]
Is there any way to include `group` field inside a `group` field?

**Comment by kingRayhan** [comment]
you can't do this in this version.

**Comment by groupunknown** [comment]
@Codestar there is some expectation for the release of the version that contains the nested group

**Comment by groupunknown** [comment]
one of the best framework available for free, only loses to the metabox.io, but how and for free is in front, a pity that the project seems to be abandoned :(
