### ISSUE TITLE
Group not Add in customize

### ISSUE THREAD

**Issue by malek1316** [Codestar/codestar-framework#459]
I am a pure fans of CS Framework. This is great and easy Options Framework. Please add group fields and sorter in customiser

Thanks a lot of Codestar Framework

**Comment by Codevz** [comment]
Wait for version 2

**Comment by malek1316** [comment]
When it will be release dear???

**Comment by kingRayhan** [comment]
@malek1316  
@Codestar is working with his Theme. He promised us, after finishing that project , he will release the next version.

**Be patient**

**Comment by Yeadh** [comment]
Hope something more special waiting for us in version 2.
Can't wait to see that.

**Comment by Codestar** [comment]
@Yeadh leave an email via routewp[at]gmail[dot]com

**Comment by ariona** [comment]
Any update for this? The group is rendered, but whenever the value is changed the publish button whon activate.
