### ISSUE TITLE
Framework not shows on the wordpress admin menu

### ISSUE THREAD

**Issue by techhaat** [Codestar/codestar-framework#460]
hi 
I download Codestar and create a folder into my theme folder name "cs-framework"
then add this code into my functions.php.
require_once get_template_directory_uri() .'/cs-framework/cs-framework.php';

there is no error but Framework not shows on the wordpress admin menu.

can you please tell me what wrong Im doing ?

**Comment by AminulBD** [comment]
If the file not found, then it must show error. Did you enable debug?

**Comment by khiconit** [comment]
Same problem
