### ISSUE TITLE
please add Nested Group Option

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#461]
I want to add nested group. I have a group field and i want to add another group include this group.
Ex: i am making a pricing table, i have added a group for each pricing table now i need another group for each pricing table feature list.
I want Nested Option In Codestar, I request to codestar please add Nested Group Option.
Thanks

**Comment by AminulBD** [comment]
@wpexpert24 I like to suggest you create your field for codestar. Codestar is open source, and the codebase standard is very easy to understand.

If you can't then you should use ACF or something like this already have nested groups support.

Duplicate issue: #370

**Comment by pixxet** [comment]
hi you can check this issue 
[](https://github.com/Codestar/codestar-framework/issues/294)

if you want ready to go framework with example i just created a repo based on a functioning Codestar-framework directory in my theme

https://github.com/pixxet/codestar-framework
