### ISSUE TITLE
Future of the framework

### ISSUE THREAD

**Issue by Slobork** [Codestar/codestar-framework#462]
Is the project abandoned?

I've switched from another famework because of the enhuisiasam of the Codestar framework's author at that time. 6-9 months ago I've read a lot here about the upcoming framework version 2.0. That's lost and no version 2.0 since then. 

@Codestar please update us about the future of the project?

**Comment by Codestar** [comment]
Hi @Slobork 

No, this is project not abandoned. Problem is the time. I am not a team. and I am giving support for themeforest themes and working on new themes for money for life :)

I have not free-time for this project right now. But when i have free time, i am developing the framework.

Also, I did not get donate for this project, how i can motivated for develop it :smile:  :smile:  :smile: :laughing: 

Regards

**Comment by Slobork** [comment]
Yeap, I understand. But maybe it's the time to move from "one-man show" to the team project?

My knowledge of JS isn't on so high level and I'm afraid I couldn't contribute to the project in so helpfull way. But maybe including some people, who were willing to contribute in the past (like @Codevz etc.), to the project, would help to move things forward.

**Comment by Codestar** [comment]
That is why i uploaded the project on github :smile: Who want to contribute it is free :) This is a open-source framework. :+1:
