### ISSUE TITLE
Framework Conflict When Activated 2 plugin which made Codestar Framewok

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#463]
Hi,
We have Made Two Plugin With Codestar Framework, When i Activating 2 plugin same time then another one meta-box isn't showing. But When i Deactivating Another One just 1 plugin Activate it's working perfectly.

But I need more Plugin Activate in a same time. Why then another plugin meta-box not showing?
how can i remove the conflict?
Thanks

**Comment by Codevz** [comment]
Try to use filter for adding meta boxes https://github.com/Codestar/codestar-framework/issues/103

**Comment by samjco** [comment]
You can also add a check function within you plugin.
Check for cs-framework.php if it is loaded.

Checking for cs-framework should be a standard in the documentary I believe.

**Comment by samjco** [comment]
You can add this around your "include" statement:

```
// IF the Codestar Framework is NOT running
if( ! function_exists( 'cs_framework_init' ) || ! class_exists( 'CSFramework' ) ):
//not running so include it
else:
//is running. do not include it
endif;

```

Oh course you will need to call your custom metas on your plugin page.

**Comment by Codestar** [comment]
@codecans leave an email via route[at]gmail[dot]com

**Comment by codecans** [comment]
Hi codestar This Email not working - see screenshot: http://prntscr.com/feqe68

**Comment by Codestar** [comment]
Oh my god, it is my fault... mail address is  ***routewp***[at]gmail[dot]com i forget to ***wp*** :)

**Comment by devariya** [comment]
@samjco it's not working .

**Comment by samjco** [comment]
@devariya 
Where are you adding it at? to?
