### ISSUE TITLE
Do I need to add font awesome icons file in my theme

### ISSUE THREAD

**Issue by mehedi-sharif** [Codestar/codestar-framework#465]
Hello Team,
Font awesome is working fine in the option framework . But when I want to display them its just displaying a classname. so do I need to add fontawesome files in my theme to show the icons. ? 
Thanks

**Comment by Codevz** [comment]
Yes, If you included framework in your theme, you can load font awesome like this: 

`wp_enqueue_style( 'theme-font-awesome', get_template_directory_uri() . '/csf/assets/css/font-awesome.min.css' );`

Else if you are using as plugin, you need to add files into your theme and load.

**Comment by mehedi-sharif** [comment]
Thank you so much.
