### ISSUE TITLE
Please explain in detail the functions

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#469]
We already understand this function:

`cs_get_option( $option_name = '', $default = '' ); //Gets the value of option fields`

It would be nice to understand in detail what the other functions do and how it can help us:

```
render_content();
cs_export_options();
cs_add_element( $field = array(), $value = '', $unique = '' );
cs_set_option( $option_name = '', $new_value = '' ); // Sets/Updates a value??
cs_get_all_option();
cs_get_customize_option( $option_name = '', $default = '' );
cs_set_customize_option( $option_name = '', $new_value = '' );
cs_get_all_customize_option();
```

**Comment by Codevz** [comment]
Is better if you wait until version 2 of CS Framework, in v2 all the functions has been changed and some new options type added.

Codestar working alone and when he finishes his new theme, he will notice us about CS Framework v2

**Comment by samjco** [comment]
When do you think that will be?
What about those of us still using v1?

**Comment by samjco** [comment]
BTW, cs_option... should be change to cs_meta.... or cs_field....
Because it is too confusing, I think, with option page. Etc.

**Comment by Codestar** [comment]
v2 will come soon. :+1:

**Comment by samjco** [comment]
When will V2 launch?
