### ISSUE TITLE
Custom taxonomy

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#47]
is it possible to add metabox for Custom taxonomy !!

**Comment by santiagointeractive** [comment]
Yes you can do that.
From <code>post_type</code> option of you array.
As the documentation says: http://codestarframework.com/documentation/#metabox-configure

<pre><code>$metaboxes[]      = array(
  'id'            => '_custom_meta_options',
  'title'         => 'Custom Options',
  'post_type'     => 'product', // or page, post or other custom post type
  'context'       => 'normal',
  'priority'      => 'default',
  'sections'      => array(
</code></pre>

**Comment by devariya** [comment]
i know about custom post type ,but i want to know is it possible to add metabox for Custom taxonomy also .like taxonomy=category taxonomy=post_tag

**Comment by santiagointeractive** [comment]
I see. Didn't tried that and I don't think it will work.
Maybe Codestar could answer you this question.

**Comment by Codestar** [comment]
Actually you can use all framework fields anywhere. but you will need custom code. for eg, i am using framework fields in my custom widgets. this functions for this [helpers.php#L11](https://github.com/Codestar/codestar-framework/blob/master/functions/helpers.php#L11)

<pre>
$value = "your returned value";

$field = array(
  'id' => 'text_1', 
  'type' => 'text', 
  'title' => 'Text'
);

echo cs_add_element( $field, $value );
</pre>

Shortly you need to create your own mini framework for custom things.
