### ISSUE TITLE
How to add Codestar Framework to your Plugin

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#470]
# How to add Codestar Framework to your Plugin
To embed into a plugin, this is what I've done. (below).

## **First, create my custom plugin and include in the codestar framework.**
To make a new plugin and include the codestar framework into it, first make a new folder and file and add to wp-contents/plugins/:  **my-custom-plugin-folder/my-custom-plugin.php** (you can change "my-custom-plugin" to whatever your desired plugin name).

Open up and add the follow code to file: **my-custom-plugin.php** and activate plugin in WordPress.

```php
<?php 
/*
 * Plugin Name: My Custom Plugin
 * Plugin URI: http://www.linkedin.com/in/samcohen/
 * Description: Plugin that does something.
 * Author: Sam Cohen
 * Version: 1.0
 * Author URI: http://www.linkedin.com/in/samcohen/
 */

defined('ABSPATH') or die("Restricted access!");

/**
 * Define constants
 *
 * @since 1.0
 */
defined(MYCUSTOMPLUGIN_DIR') or define('MYCUSTOMPLUGIN_DIR', dirname(plugin_basename(__FILE__))); //Folder Name
defined('MYCUSTOMPLUGIN_BASE') or define('MYCUSTOMPLUGIN_BASE', plugin_basename(__FILE__));
defined('MYCUSTOMPLUGIN_URL') or define('MYCUSTOMPLUGIN_URL', plugin_dir_url(__FILE__));
defined('MYCUSTOMPLUGIN_PATH') or define('MYCUSTOMPLUGIN_PATH', plugin_dir_path(__FILE__));
//defined('MYCUSTOMPLUGIN_TEXT') or define('MYCUSTOMPLUGIN_TEXT', 'my_custom_plugin_text_domain');
defined('MYCUSTOMPLUGIN_VERSION') or define('MYCUSTOMPLUGIN_VERSION', '1.0');

/**
 * Include Codestar Framework
 *
 * @since 1.0
 *
 * Make a new folder "inc" in your plugin folder. if you download the codestar framework zip from GitHub
 *
**/
require_once MYCUSTOMPLUGIN_PATH .'/inc/codestar-framework/cs-framework.php';


/**
 *Show/Hide Codestar Framework Examples
 *
 * @since 1.0
 *
 * Location of actual files is in the inc/codestar-framework/config/ directory
 * Optionally, set each desired, to "false" to not display after plugin activation
 **/
define( 'CS_ACTIVE_FRAMEWORK',  true  ); // default true
define( 'CS_ACTIVE_METABOX',  false); // default true
define( 'CS_ACTIVE_TAXONOMY',  false); // default true
define( 'CS_ACTIVE_SHORTCODE',  false); // default true
define( 'CS_ACTIVE_CUSTOMIZE',  false); // default true
```

## Let's now add Codestar Framework files into your newly create plugin!
Next, make a new folder in **my-custom-plugin-folder/**, named "inc". Open up the inc folder and paste the downloaded, unzipped codestar files and folders. so your plugin folder structure should look like this: **my-custom-plugin-folder/inc/codestar-framework**.

Now Activate your plugin within WordPress plugin directory!
Once activated, you will see all examples of: settings option page, metabox on post/page, taxonomy options, shortcode options, etc.

## EXTRA:  Showing example theme code within the field examples!
If any or all all of the cs framework examples are set to `true` in the above plugin code:
you can edit any of those files located in: **inc/codestar-framework/config/** folder and simply add the attribute `'debug' => true` to each array field option. For an example open up codestar-framework/config/framework.config.php and locate `'id'      => 'textarea_1',` and add in the argument `'debug' => true` after` 'help' =>'This option field is useful. You will love it!',`. Then check out the plugin examples options within wp dashboard.

Example on the textarea_1 array option:

```php
array(
 'id'      => 'textarea_1',
 'type'    => 'textarea',
 'title'   => 'Textarea',
 'help'    => 'This option field is useful. You will love it!',
 'debug' => true,   //<--- add the debug argument to your array
 ),
```

## My Plugin is conflicting with other plugins using CS Framework!
To Keep your plugin from conflicting with another plugin that uses Codestar Framework.
**You might replace THIS:**

```php
/**
 * Include Codestar Framework
 *
 * @since 1.0
 *
 * Make a new folder "inc" in your plugin folder and add codestar files into it.
 *
**/
require_once MYCUSTOMPLUGIN_PATH .'/inc/codestar-framework/cs-framework.php';
```

**with THIS:**

```php
/**
 * Include Codestar Framework
 *
 * @since 1.0
 *
 * Make a new folder "inc" in your plugin folder. if you download the codestar framework zip from GitHub
 *
**/
function cs_framework_init_check() {
	if( ! function_exists( 'cs_framework_init' ) && ! class_exists( 'CSFramework' ) ) {
         
           // Plugin location of cs-framework.php
          require_once MYCUSTOMPLUGIN_PATH .'/inc/codestar-framework/cs-framework.php';

}
add_action( 'plugins_loaded', 'cs_framework_init_check' );
```

**Now you are ready to build your new plugin using Codestar! Enjoy.**

**Comment by Codestar** [comment]
Nice source :+1:

**Comment by dubem-kizito** [comment]
Nice, exactly what I need to start working on my new plugin

**Comment by samjco** [comment]
I've updated and clarified the information a bit!

**Comment by stivoox** [comment]
there is any way to use override configure method with in plugins ?
