### ISSUE TITLE
Codestar Framework Conflict Issue

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#472]
Hi Codestar,
You said send a email to route@gmail.com but this email is not found. see screenshot: http://prntscr.com/feqbtd

So i am writing here again if anyone assist me: 

I am using Codestar Framework in my plugin. it's working fine.
But when i am activate 2 plugin at a time which build with codestar framework , then only one work. Another Plugin Metabox not Working.

I am Sure its Conflict with framework. we made 2 different Plugin so we need to include Codestar framework for each plugin.
Can you please give me solution how i can use Codestar Framework with multiple plugin.

Below Two Plugin Made By Codestar framework.
You can activate 2 plugin then see 1 metabox not working....

1. https://wordpress.org/plugins/amazing-hover-effects/
2. https://wordpress.org/plugins/team-member-showcase/

Hope you will give me proper solution.
Rakibur Rahman Sagar

**Comment by NoahjChampion** [comment]
Hi, @codecans 

This **IS NOT POSSIBLE** in this version of CF. That is why Codestar requested you to email.

Seems he forgot the wp when writing his email 💯  🤕  :D 

Email routewp[at]gmail[dot]com. He'll do something to help you out! You can close this ticket though as this is requested several times already. No one can help you but Codestar, hence the email given ;)

**Comment by Codestar** [comment]
@codecans oh yes that is misspelling.. and @NoahjChampion thanks for fix it.... :smile:

**Comment by codecans** [comment]
Thanks Codestar

**Comment by devariya** [comment]
I am having same problem any solution ??

**Comment by samjco** [comment]
I'm wondering if @Codestar can add in instructions to theme and plugin developers using cs-framework, to include this bit of code in their file:


<?php

The problem might lay in the cs-framework.php:
