### ISSUE TITLE
I want to remove the default meta box

### ISSUE THREAD

**Issue by Yeadh** [Codestar/codestar-framework#473]
I want to remove default meta box from page and post how to remove it?

**Comment by devariya** [comment]
Go to cs-framework/config/metabox.config.php for default meta box settings . you can delete and customize from there or if you are using cs-framework as a plugin you can override settings ,check the doc

> You can override an existing file without change themename/cs-framework folder. just create one themename/cs-framework-override folder on your theme directory. for eg:

```
themename/cs-framework-override/config/framework.config.php
themename/cs-framework-override/functions/constants.php
themename/cs-framework-override/fields/text/text.php
```
