### ISSUE TITLE
Plugin developed with Codestar does not work along with Theme also developed with codestar

### ISSUE THREAD

**Issue by qcloud** [Codestar/codestar-framework#477]
Hi,

We developed a plugin with codestar for settings. But it is causing issues with another theme that is also using codestar framework. The theme options does not show when our plugin is activated. 

Any solution?

Thanks!

**Comment by Codestar** [comment]
Hi,

Actually, I am working on version 2 long time and fixed this issue. you can leave an email via routewp[at]gmail[dot]com for look it.

Regards
