### ISSUE TITLE
Error Array to string conversion if the first field of group is media

### ISSUE THREAD

**Issue by rafaelfndev** [Codestar/codestar-framework#48]
If first field of group is media, occurs the error `Notice: Array to string conversion in ....\codestar-framework\fields\group\group.php on line 93 Array`

Code example:

```php
array(
	'id'     => 'sliders',
	'type'   => 'group',
	'title'  => 'Sections',
	'fields' => array(
		array(
			'id'    => 'title-section',
			'type'  => 'text',
			'title' => 'Section title'
		),
		array(
			'id'     => 'slider-field',
			'type'   => 'group',
			'title'  => 'Sliders',
			'fields' => array(
				array(
					'id'    => 'photo',
					'type'  => 'media',
					'title' => 'Photo',
				),
				array(
					'id'    => 'title',
					'type'  => 'text',
					'title' => 'Title'
				),
				array(
					'id'    => 'description',
					'type'  => 'textarea',
					'title' => 'Description'
				),
			),
		),

	),
),
```

If you change the order for the first field to be text, the error does not occur.

**Comment by rafaelfndev** [comment]
Same for the date field:

```php
array(
	'id'        => 'data',
	'type'      => 'date',
	'title'     => 'Data',
	'from_to'   => true,
	'text_from' => 'De',
	'text_to'   => 'Até',
	'settings' => array(
		'dateFormat'      => 'dd/mm/yy',
		'changeMonth'     => true,
		'changeYear'      => true,
		'showWeek'        => false,
		'showButtonPanel' => true,
		'monthNamesShort' => $meses,
		'dayNamesMin'     => $dias,
	)
),
```

**Comment by Codestar** [comment]
Hi,

This error cames from group item title. It's allows only string output.  "media" and "date" fields has array output. that is why you facing this issue. You can try to move "title" to above "photo" like this:

```php
array(
  'id'    => 'title',
  'type'  => 'text',
  'title' => 'Title'
),

array(
  'id'    => 'photo',
  'type'  => 'media',
  'title' => 'Photo',
),
```

Regards, Codestar

**Comment by rafaelfndev** [comment]
Hi @Codestar Yep, thanks, I see this... but wouldn't it be good to validate, and display without a title? In case I have a group with only one media field and one data field, I wouldn’t need to add an extra field to avoid an error.

**Comment by Codestar** [comment]
Hi,

Hmm, Let's try this. 

1. Open the /codestar-framework/fields/group/group.php
2. Go to line 80 and append this code:

```
$first_value = ( is_array( $first_value ) ) ? reset( $first_value ) : $first_value;
```

If you like it, I can add this fix in the next update.

Regards, Codestar

**Comment by rafaelfndev** [comment]
Nice, this solve the problem!

One suggestion is add option like "accordion_title_number" that results on 1- Title...

Something like "empty_title_box": "My title string", resulting something like "My title string 1", "My title string 2"...

This is just suggestion, but your solution already works, thanks!

**Comment by Codestar** [comment]
Nice... hmm. I noted this and will think about that ;) ( btw, I added this fix for next update )
