### ISSUE TITLE
Is there any way to organize option data?

### ISSUE THREAD

**Issue by AminulBD** [Codestar/codestar-framework#48]
Hi,
Codestar framework stores all data in single array. For Example: http://i.imgur.com/JaWf7QL.png That's why all options are must have a unique id.

But, I need to store some option field data in sub arrays to organize my options and I can easily return my data.

For Example:
$some_group = cs_get_option('main_opt');
echo $some_group['sub_opt'];

Can you tell me how can i do this? 

Thank you for the awesome framework!

**Comment by Codestar** [comment]
Hi,

Hmm, No, There is no any way for this. Actually, i had started framework with your idea 
```
cs_get_option( 'header', 'sub_header_option');
cs_get_option( 'main', 'sub_main_option');
cs_get_option( 'footer', 'sub_footer_option');
// etc.
```
But after i changed my this idea, it is extra work, extra things. i returned back single unique id. Trust me unique id model is better... but i will think this idea again for next updates for you...

Thanks for your opinions :+1:
