### ISSUE TITLE
Image not showing up

### ISSUE THREAD

**Issue by alisiddique** [Codestar/codestar-framework#481]
Hi There,
I added image add option in custom post type page with meta box. But my image not showing. Here is code below.
`	array(
						'id'        => 'work_item_main_img',
						'type'      => 'image',
						'title'     => 'Work Item Main Preview Image',
						//'desc'      => 'Lets write some description for this image field.',
						'help'      => 'Work Item Main Preview Image',
					),`

`<?php
										$image_id = cs_get_option( 'work_item_main_img' );
										$attachment = wp_get_attachment_image_src( $image_id, 'full' );
										var_dump( $attachment );
									?>`

var_dump result showing bool(false). How can get image src url?

**Comment by nicogaldo** [comment]
Hi @alisiddique, how did you solve this?

**Comment by alisiddique** [comment]
@nicogaldo 
Here is my code
https://pastebin.com/9E9VPGeF

**Comment by nicogaldo** [comment]
Yes! I have also done so! Thank you.
