### ISSUE TITLE
Showing Illegal string offset

### ISSUE THREAD

**Issue by alisiddique** [Codestar/codestar-framework#482]
![untitled](https://user-images.githubusercontent.com/4035727/29419231-6326147e-8390-11e7-9ced-a96c3a673f9b.png)
`<?php if($meta_data_side['work_side_link_vw_sw']):?>
								<a class="button bttn-material-flat btn-full " href="<?php echo $meta_data_side['work_side_link_vw_link']; ?>">
									Visit Website
								</a>
							<?php endif ?>`

**Comment by Codevz** [comment]
Check with `isset` or `empty` functions

e.g. 

```PHP
if ( isset( $meta_data_side['work_side_link_vw_sw'] ) ) {
 // Your code
}
```
Or

```PHP
if ( ! empty( $meta_data_side['work_side_link_vw_sw'] ) ) {
 // Your code
}
```

**Comment by alisiddique** [comment]
Thanks.
