### ISSUE TITLE
The plugin does not have a valid header.

### ISSUE THREAD

**Issue by daniel-musteata** [Codestar/codestar-framework#485]
After I try to include cs framework in a simple test plugin
"The plugin does not have a valid header."
appearing when i try to upload and ACTIVATE
ajax request in console with 500 Internal Error
`http://localhost.dev/wp-admin/plugins.php?action=activate&plugin=example-test%2Fcs-plugin-framework%2Fcs-framework.php&_wpnonce=12a25aac1d`
Does anyone know what happend?

**Comment by salimreza1** [comment]
you may follow this thread [#498](https://github.com/Codestar/codestar-framework/issues/498)

**Comment by salimreza1** [comment]
or this thread [#470](https://github.com/Codestar/codestar-framework/issues/470)

**Comment by daniel-musteata** [comment]
Thanks @salimreza1
