### ISSUE TITLE
Server Requirements for cs framework wordpress plugin

### ISSUE THREAD

**Issue by mkarthick84** [Codestar/codestar-framework#486]
Hi Admin.,

I installed the "Codestar Framework" wordpress plugin in my site nordfinanse.pl and activated it. But the plugin option "Framework" menu in the left side menu of dashboard is not showing up. Do not know what is the server requirement for this plugin to work. Can you please list the server requirements for this plugin and the possible issue that is causing the issue. Thanks in advance.

**Comment by technofreaky** [comment]
@mkarthick84 this is not a wordpress plugin. which can be used by wordpress users. 

its a framework which helps plugins / theme developer to add options page for their plugin / theme. 

But still you can install it and check how it works. like a demo.
