### ISSUE TITLE
Metaboxes Deleting other Metaboxes

### ISSUE THREAD

**Issue by jaredbrandon** [Codestar/codestar-framework#487]
I'm having an issue with newly added metaboxes deleting previously added ones. I have not been able to determine a root cause or any consistent things when this happens. Except that it seems to happen most frequently on pages that have numerous metaboxes in use. 

Here's a screencast video demonstrating the issue. https://youtu.be/up83roj-ksw

**Comment by Codestar** [comment]
Hi,

Thanks for detailed explain.  I need to play with it a little for solve issue. Can i try it as live? You can leave an email via routewp[at]gmail[dot]com

Regards, Codestar

**Comment by jaredbrandon** [comment]
Thanks, just sent the email via the WP user page. Let me know If it didn't come through with everything you need. Thanks.

**Comment by Codestar** [comment]
Yes i logged the wordpress admin. hmm now i created a "Metabox Testing" page and adding it normally :S i did not understand where is the issue really.

**Comment by jaredbrandon** [comment]
The issue only ever happens on pages that are edited after content was already published on it. Typically the pages it happens on have multiple metaboxes already added. Try adding something to the Groups page.

**Comment by samjco** [comment]
Could you possibly have duplicate field ids somewhere?

**Comment by Codestar** [comment]
very interesting :S I cannot find the issue really on the code. Is it same in localhost test ?

**Comment by jaredbrandon** [comment]
Yes. I just tested it locally and it still happens. I'm running my live site on WPengine.com and it happens in my staging environment as well.

**Comment by Codestar** [comment]
Hey @jaredbrandon 

I updated your cs-framework.js file a little. can you test it now ? i added a minor "name_replace" function for fix fields index.... test and tell me the result :+1:

**Comment by jaredbrandon** [comment]
so far so good! I added 10 metaboxes with no issues. I'll keep you posted if it happens again.

**Comment by Codestar** [comment]
You're welcome :+1:
