### ISSUE TITLE
Add the ability to use CS Fields in Comments

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#490]
Nice to be able to add fields to the comment section.

**Comment by Codestar** [comment]
Add it by manually haha :smile:

**Comment by samjco** [comment]
Add it manually LOL?
Is there any hooks I can hook into?

**Comment by Codestar** [comment]
WordPress Core Hooks (comment_form_after_fields)

See more: https://www.smashingmagazine.com/2012/05/adding-custom-fields-in-wordpress-comment-form/
