### ISSUE TITLE
http error 500 after installing "Theme Options Framework plugin" on my worpress theme

### ISSUE THREAD

**Issue by alexsan91** [Codestar/codestar-framework#493]
I got a http error 500 after installing "Theme Options Framework plugin" on my worpress theme.

I tried adding these lines on the wp-config.php 

set_time_limit(0);
init_set('memory_limit', '516M');

unfortunaly they didn't work.

Then I changed: **define ('WP_DEBUG', false);** to **define ('WP_DEBUG', true);** (saw it on a forum) and this appear:

Fatal error: Call to undefined function wp_get_current_user() in /home//domains/my-domain/public_html/wp-includes/capabilities.php on line 539

Any idea of what is happening and what to do? Thank you in advance.

**Comment by Codestar** [comment]
Hi,

Hmm, Is it online? Can i check it ? Please leave an email via routewp[at]gmail[dot]com

**Comment by alexsan91** [comment]
Hello, yes is online. Sorry I'm kind of a newbie. What do you need to check it?

**Comment by Codestar** [comment]
I cna check server settings and any conflict via ftp or wp admin. because i have not this issue in my server or localhost.

**Comment by lelik4w** [comment]
I've got the same issue, but it happens only on some servers..
Any Idea what server settings could cause this issue? or if there is a hook to insert into a code.
