### ISSUE TITLE
How to use typography inside customize

### ISSUE THREAD

**Issue by proscriptsell** [Codestar/codestar-framework#496]
How to use typography inside customize ?

**Comment by Codevz** [comment]
Not possible, You need to wait for version 2 of CodeStar Framework.

**Comment by DonElyes** [comment]
Excellent @Codevz , any idea when V2 will be releases?

**Comment by Codevz** [comment]
@DonElyes I don't know, maybe until end of 2017.

**Comment by DonElyes** [comment]
Ok thanks @Codevz 👍

**Comment by proscriptsell** [comment]
@Codevz  & @DonElyes  Thanks !

**Comment by Codestar** [comment]
@proscriptsell send me an email via routewp[at]gmail[dot]com about v2.

**Comment by proscriptsell** [comment]
Hi @Codestar  ! sent email :)

**Comment by xperter** [comment]
When V2 will be released?

**Comment by Codestar** [comment]
Coming soon :)

**Comment by Ataurr** [comment]
Any ETA?

**Comment by Codestar** [comment]
@Ataurr  Half of 2018
