### ISSUE TITLE
Codestar-framwork install after wordpress not work 2017

### ISSUE THREAD

**Issue by Atulshingote** [Codestar/codestar-framework#498]
Codestar Framework. using to theme options but plugin installs after wordpress not open

Wordpress version 4.8.1 (2017)

**Comment by salimreza1** [comment]
You may add the Codestar Framework file in you themes directory and add this code in your function.php
`require_once ('lib/codestar/cs-framework.php');`

Then you will see sample option panel. now goto your theme directory and open then open your Framework file then open "config" folder then you will see 5 file to edit the option panel as you want

**Comment by Atulshingote** [comment]
thanks,

this code i added to theme directory function.php but not work this theme and wordpress admin panal

codestar-framework plugin not work wordpress new version and old ver.

**Comment by Codestar** [comment]
@Atulshingote send me a email about your wordpress via routewp[at]gmail[dot]com

**Comment by salimreza1** [comment]
@Atulshingote I just install codestar-framework and it's 100% working. You did wrong that's it's not working.

**Comment by Atulshingote** [comment]
Thanks again

My WordPress theme use for game community my theme options use for
cs-framework but i active this plugin to WordPress not a open

Please send cs-framework required for use

Ex. Memory limit, php, time limit

Thanks,
For supporting,
999Worlds Network (Atul Shingote)


On Sep 11, 2017 12:55 AM, "salimreza1" <notifications@github.com> wrote:

@Atulshingote <https://github.com/atulshingote> I just install
codestar-framework and it's 100% working. You did wrong that's it's not
working.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Codestar/codestar-framework/issues/498#issuecomment-328365554>,
or mute the thread
