### ISSUE TITLE
Any example to use "SELECT WITH POSTS"

### ISSUE THREAD

**Issue by salimreza1** [Codestar/codestar-framework#499]
I want to know how to show output of "SELECT WITH POSTS". I'm already showing posts from a category but now I want to show a specific post using Codestar Freamwork.

Now I'm using "SELECT WITH CATEGORIES" 
-----------------------------------------------
**in freamwork-config.php**
```php
	array(
		'id'	=> 'index_best_for_you_post_1',
		'type'	=> 'select',
		'title'	=> 'Select Field for Posts',
		'options'	 => 'categories',
		'query_args' => array(
		'orderby'	 => 'post_date',
		'order'	=> 'DESC',
	),
		'default_option' => 'Select a Category'
	),
```
**output**
```php
$featured5items3 = array( 'posts_per_page'   => 1, 'category__in' => cs_get_option('index_best_for_you_post_1') );
$multicat1 = new WP_Query( $featured5items3 );

while ( $multicat1->have_posts() ) : $multicat1->the_post();

the_title();

endwhile;
```

**So please give me an example to use "SELECT WITH POSTS"**

Thanks advance.

**Comment by Codestar** [comment]
I am trying this output, and it is working yes. what you need exactly?

**Comment by salimreza1** [comment]
Hi

Thanks for your reply. I want to use I want to output using `"'options' => 'posts',` not using `'options' => 'categories',` so what will be the code?

**Comment by salimreza1** [comment]
Just solved

**Comment by asufian97** [comment]
> Just solved

how, can you tell me please?
