### ISSUE TITLE
Some suggestion and few question 

### ISSUE THREAD

**Issue by partharoy** [Codestar/codestar-framework#5]
Hi codestar team,

This is a great framework. I really love your framework. Its full of valuable feature that a developer need. 
But I have felt some fields are missing like custom css editor, Js editor. gallery, and list item. 

one question: Can I create a slider via group filed with upload option? Though I have not checked it yet this option. 

Thanks,
Partha

**Comment by Codestar** [comment]
Hi,

Yes this option fields is on the way.  when i have free time i will add new option fields ;)
