### ISSUE TITLE
Editable Shortcodes

### ISSUE THREAD

**Issue by ingeniousweb** [Codestar/codestar-framework#50]
Hi, Thank you for awesome framework, i just started reviewing it. Is there any possibility you could make the shortcodes editable just like shortcake does?
https://github.com/fusioneng/Shortcake

Or if there is a workaround which i can follow to achieve it please advice.

Thanks in advance,
Munir

**Comment by santiagointeractive** [comment]
Hi,
Take a look at my gist here: https://gist.github.com/santiagointeractive/eb533bb8a39ddc51b7a0

This does exactly what you ar asking for. Is not a final version, still needs improvments but you can play around with it if you really need this kind of feature. If you want to help improving this solution, feel free to fork the code.

Enjoy! :smiley:

**Comment by ingeniousweb** [comment]
Hi @santiagointeractive ,

Thank you for your response, sorry to ask but i am still a beginner developer, does this code work on the fly with all added shortcodes? I have added it to my theme's function.php but it doesn't seems to be working?

please advice..

Thanks

**Comment by santiagointeractive** [comment]
Hi,
For the moment you can use it like this:

1. Save the gist file, rename it with something, let's say <code>visual-shortcode.php</code>

2. Edit your <code>visual-shortcode.php</code> file at line 55-58 your shortcodes where to apply this, or comment out all this if you want to apply on all your shortcodes:

<pre><code>$shortcode_tags = array(
'header_section' => 1, // shortcode name
'special_section' => 1 // another shortcode name
);</code></pre>

3. Upload it into your theme folder.

4. Add this line into your <code>functions.php</code> file:
<pre><code>// include visual shortcode extension
require_once dirname( __FILE__ ) .'/visual-shortcode.php';</code></pre>

NOTE: For now this was tested and works with this kind of fields:

text input
checkbox
textarea
select
select with chosen
color picker
switcher

I will improve and extend it in the future depending on usage problems will occur at a point.

Hope this helps you somehow on your project.
Thanks!

**Comment by Codestar** [comment]
Thanks @santiagointeractive :+1:

**Comment by santiagointeractive** [comment]
You're welcome! :smile: 

What a great news @Codestar :100: 
If you have any questions about my code don't hesitate to ask me. :+1:

**Comment by Codestar** [comment]
Yes sure, Thank you :+1:

**Comment by ingeniousweb** [comment]
Thanks @santiagointeractive for the code, however it will be really awesome if this could soon be integrated within the framework as @Codestar mentioned, so i am waiting for this happen :) and i am sure many more will love it.

@Codestar 
Also a newbie questions: Could you guide me how exactly to integrate shortcodes? I mean i have created some shortcodes however how to retrieve values?

Thanks

**Comment by Codestar** [comment]
@ingeniousweb Yes, i can help you, but explain your request more, what you need exactly ? [shortcode.config.php](https://github.com/Codestar/codestar-framework/blob/master/config/shortcode.config.php) there is some shortcode generator config examples.

**Comment by santiagointeractive** [comment]
I this he is asking how to add shortcodes into it's theme.
A starter guide on how you can add shortcodes can be found here: https://codex.wordpress.org/Function_Reference/add_shortcode

**Comment by ingeniousweb** [comment]
Hi,

I mean i need to understand more about the shortcode integration with my theme, is there any free theme available which integrated codestar shortcodes and other features which i can play with to understand some stuff?

Thanks,
Munir

**Comment by Codestar** [comment]
Hi,

Codestar framework have not any shortcode ? there is only dummy shortcodes. for eg. ```[cs_shortcode_1][/cs_shortcode_1]``` this is dummy/fake shortcode. you will create your own shortcodes from config file. but if you talking about my Route WordPress Theme's shortcodes, it is premium not free :) http://themeforest.net/item/route-responsive-multipurpose-wordpress-theme/8815770

**Comment by ingeniousweb** [comment]
Hi,

yeah i know there are no shortcodes and i know how to create shortcodes via the config file, i am just bit confuse on how to properly output the shortcodes on front end, i know how it works with the wordpress shortcodes API, is it same with codestar also? Is there any demo shortcode with output also? or any free theme which has shortcodes in it using the codestar so i can study that?

Hope you understand my question now?

Thanks

**Comment by Codestar** [comment]
Yes, said as @santiagointeractive :+1:

**Comment by ingeniousweb** [comment]
Hi,

Thanks @santiagointeractive  & @Codestar both for your replies.

It means all the shortcode gerneration will be same as we do using the Shortcode API?
I will give it a try and get back if there will be any issue.

Thanks again
