### ISSUE TITLE
Visual option not working

### ISSUE THREAD

**Issue by alisiddique** [Codestar/codestar-framework#500]
![untitled](https://user-images.githubusercontent.com/4035727/30426280-4498b51e-996d-11e7-81b9-51d9ffd4c649.jpg)

Hi There, 
Visual option not working in group field. When i copy paste content it only showing text.

**Comment by wiljonbolten** [comment]
I had this problem when i names the field "content". Perhaps it is resolved when you give it another name.

**Comment by alisiddique** [comment]
Here is my code - https://pastebin.com/uDaisYaP

**Comment by Codestar** [comment]
Hi,

Yes right, it is not working on group field... I will improve it soon ;)

Regards
