### ISSUE TITLE
Changing capability settings with cs_framework_settings

### ISSUE THREAD

**Issue by tameroski** [Codestar/codestar-framework#505]
Hi,

I'm using a child theme for theme using CS Framework. This theme is usong the override method to manage the framework settings.

In my child theme, i'd like to allow a custom role with capability 'edit_theme_options' to see and change Theme Options, so i use the appropriate hook : 

```php
function apho_theme_options_settings($settings){
    $settings['menu_capability'] = 'edit_theme_options';
    return $settings;
}
add_filter( 'cs_framework_settings', 'apho_theme_options_settings' );
```

I can see the Theme Options when logged in as a user with this custom role, but i can't save them, got a permission error.

Any idea ?

Thanks

**Comment by Codestar** [comment]
Hi,

You can try this:

```php
function apho_theme_options_settings($settings){
    $settings['menu_type'] = 'options';
    return $settings;
}
add_filter( 'cs_framework_settings', 'apho_theme_options_settings' );
```

**Comment by Codestar** [comment]
hmm, did you add ***manage_options*** role for your custom role ?

**Comment by tameroski** [comment]
Sorry, the role only had the 'edit_theme_options' capability ... 

Thanks

**Comment by Codestar** [comment]
:+1:
