### ISSUE TITLE
Codestar Framework data is not exporting!!! Help

### ISSUE THREAD

**Issue by ghost** [Codestar/codestar-framework#507]
When i am going to export my theme and going to import in another place. My theme All data is importing but codestar framework data is not imported what can i do?

**Comment by Codestar** [comment]
Do you using WordPress Export/Import feature? wordperss export do not support "options" export. It is only exporting posts and pages. Shortly you can not export framework options with wordpress export feature. That's same for all of frameworks.

You need to write custom php for import data.

**Comment by ochena** [comment]
Thank you Codestar for your reply.. Please help me how could i export framework options and theme post and page at a time in .xml  file.Cause some one click demo installer supports only .xml  .Dat and .json. But codestar exports only .txt file.
