### ISSUE TITLE
Data not showing in Archive page

### ISSUE THREAD

**Issue by alisiddique** [Codestar/codestar-framework#512]
Hi Codestar,
Trying to get data from custom post type(project-items) in archive page. But data showing in single post type page.

1. Single page
![screenshot-2017-10-10 myfolio - ali siddique 1](https://user-images.githubusercontent.com/4035727/31386725-a5955ac6-ade9-11e7-8e41-837ff0811e85.png)

2. Archives page
![screenshot-2017-10-10 project archive - ali siddique](https://user-images.githubusercontent.com/4035727/31386922-5ac314ce-adea-11e7-953f-ae7f334d9365.png)

https://pastebin.com/jach5wGj

**Comment by Codestar** [comment]
Hi,

***get_post_meta*** function needed a ***$post->ID*** and archive/search/404/category pages have not post id if you do not using a loop/while code ?

What is the your full-code? upload it.

**Comment by Codestar** [comment]
Correctly usage:

```php
// single.php
$meta_data = get_post_meta( $post->ID, '_custom_project_options', true );
$meta_data_side = get_post_meta( $post->ID, '_custom_project_side_options', true );
var_dump( $meta_data );
var_dump( $meta_data_side );
```

```php
// archive.php
if ( have_posts() ) :
while ( have_posts() ) : the_post();
$meta_data = get_post_meta( get_the_ID(), '_custom_project_options', true );
$meta_data_side = get_post_meta(  get_the_ID(), '_custom_project_side_options', true );
var_dump( $meta_data );
var_dump( $meta_data_side );
endwhile;
endif;
```

Yes i know, there is issue ```_custom_project_side_options``` but this is post options not global. you need to set up a global options for archive page side options.

**Comment by alisiddique** [comment]
Thanks for quick reply. Here is archive page full code
https://pastebin.com/HzhMth0f
