### ISSUE TITLE
How can I add DT Demo Importer to Codestar framework?

### ISSUE THREAD

**Issue by pinethemes** [Codestar/codestar-framework#514]
Hi, I do not know how to install dt demo importer codestar framework. I tried, but I could not. Can you explain in detail how I can add it?

My Codestar Framework folder:
http://prntscr.com/gyb3jh

My Downloads
http://prntscr.com/gyb406

If you tell us step by step in detail, we would be very happy.

**Comment by NoahjChampion** [comment]
Hi, please search the Issues thread. The issues solved/code sown from those threads should still work. 

Reference @ https://github.com/Codestar/codestar-framework/issues?utf8=%E2%9C%93&q=DT%20Demo%20Importer

**Comment by pinethemes** [comment]
Yes, but I do not know how to install the Codestar Framework DT Demo Importer I could not find it.
Which folder do I need to add to which folder?
Which files do I need to attach to which files?

Very pleased to tell you step by step. I use codestar framework and I need a demo importer.
