### ISSUE TITLE
call_user_func(). How Can I solve Codestar Framework ThemeForest issue?

### ISSUE THREAD

**Issue by Khaled56** [Codestar/codestar-framework#515]
<img width="264" alt="trxvww" src="https://user-images.githubusercontent.com/28137775/32060954-23fc92ee-ba92-11e7-828e-d4d7492e4a03.png">

ThemeForest Give me This Soft Reject for using This Function,

Don't obscure code to do things you know aren't allowed: http://envato.d.pr/TRxvww

File Location: https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php

**Comment by Codevz** [comment]
If you want quick solution, i think this way should works

```PHP
$variable = 'Function Name';
$variable( $args );
```

Example under `if( $args['menu_type'] == 'submenu' ) {` you can use something like this: 

```PHP
$variable = 'add_'. $args['menu_type'] .'_page';
$variable( $args['menu_parent'], $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ) );
```

**Comment by Codestar** [comment]
Try to use this framework as a plugin. because the themeforest will found a lot of issues for rejected it :)

**Comment by Khaled56** [comment]
**Thanks A lot.** @Codestar

**Comment by Codestar** [comment]
Or change this lines [framework.class.php#L320-L324](https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php#L320-L324) as temporary

from:
```php
if( $args['menu_type'] == 'submenu' ) {
  call_user_func( 'add_'. $args['menu_type'] .'_page', $args['menu_parent'], $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ) );
} else {
  call_user_func( 'add_'. $args['menu_type'] .'_page', $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ), $args['menu_icon'], $args['menu_position'] );
}
```

to:
```php
if( $args['menu_type'] == 'submenu' ) {
  add_submenu_page( $args['menu_parent'], $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ) );
} else {
  add_menu_page( $args['menu_title'], $args['menu_title'], $args['menu_capability'], $args['menu_slug'], array( &$this, 'admin_page' ), $args['menu_icon'], $args['menu_position'] );
}
```

You're welcome ;)

**Comment by Khaled56** [comment]
Ok, Thanks,,again. Boss.

**Comment by Codestar** [comment]
You're welcome, send me an email after approval theme via routewp[at]gmail[dot]com I am wondering your theme :)
