### ISSUE TITLE
Are call_user_func() and base64_encode() no longer accepted on Themeforest?

### ISSUE THREAD

**Issue by tanvirul6** [Codestar/codestar-framework#517]
I see you are an elite author at Envato ‍so hope you know that recently many themes are getting soft reject for call_user_func() issue:
I just show you few massage of TF reviewers below:
1. "Don't obscure code to do things you know aren't allowed: http://envato.d.pr/TRxvww "
2. "try to hide code that is in violation of these requirements. Example(s): http://envato.d.pr/nnj1o0/3fEkSw4c
base64_encode() are no longer accepted. curl_init, curl_exec, fwrite, fopen, fread, file_put_contents, file_get_contents is not safe, use WP_Filesystem instead."
3. “Please remove http://envato.d.pr/U0WLQm/4eHu9ZRA ”

and so on...

So now what do you think about this and what should we do please?

**Comment by Codevz** [comment]
Check this issue https://github.com/Codestar/codestar-framework/issues/515

Actually base64 and call_user_func() are no longer accepted by Themeforest and WordPress due to security reasons.

**Comment by Codestar** [comment]
Hi @tanvirul6

I was have some updates about this issues. hmm today i updated it. This issues fixed now. You can check changelog.

**Comment by tanvirul6** [comment]
@Codestar Thanks a lot

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by Codestar** [comment]
Send me an email after approval theme via routewp[at]gmail[dot]com I am wondering your theme :)

**Comment by Galibri** [comment]
Great to know that the issue has been solved! I was also facing the same issue. Thanks!
