### ISSUE TITLE
Is the anyway that I can add options only to specific pages?

### ISSUE THREAD

**Issue by hemnathmouli** [Codestar/codestar-framework#523]
I wanted so the metabox option only for one page, is that possible to do that? Like
`'post_ids' => array( 1,2,3 )`

**Comment by FearVsFear** [comment]
@hemnathmouli 

Yes, you can. Simpler, more control and lighter I think would be to just wrap your options array in a condition so only the metabox options array code loads if the condition is met. This would prevent your array from running unneeded routines on the post ids where it is not needed.

I'm not sitting down right now to write the code and test, but I think you could do something simple like this...

```php
global $post;
$current_post_id = $post->ID;
$your_defined_post_id = 99;
if ($current_post_id == $your_defined_post_id) {
  // Begin your options array
}
```

Or you might wrap your array code in a function tied to an action that only loads on the post id. Or something similar. All array codes should be able to be wrapped in a function of your desired condition. So you don't always need to look at using the array, but instead control the whole array output. I think this offers more control to you.

Does that help? 👍

**Comment by hemnathmouli** [comment]
Hey @FearVsFear I find it helpful. Thanks

**Comment by FearVsFear** [comment]
@hemnathmouli 

Sure. I had a moment to sit down and test this out for you.

You can use the following. 👍 💯  - @Codestar (make a note maybe)

```php
// Create our __Load_Codestar_Metabox_By_Post_ID function tied to the Wordpress add_meta_boxes action

add_action('add_meta_boxes', '__Load_Codestar_Metabox_By_Post_ID');
function __Load_Codestar_Metabox_By_Post_ID() {
	
	// Set our global $post variable
	
	global $post;
	
	// @Note
	//  For testing only. Uncomment to look at the data in our global $post variable
	
	// print_r($post);
	
	// Set our $current_post_id variable
	// @Note
	//  This returns the integer (ie: post id number)
	
	$current_post_id = $post->ID;
	
	// Set our $valid_post_id variable
	//  This will be whatever or however you get and pass your specifed post id to be compared with the $current_post_id variable
	
	$valid_post_id = 1;
	
	// If our $current_post_id is our $valid_post_id
	
	if ($current_post_id == $valid_post_id) {
		
		// Load our options array...
		
	}
	
}
```

Reference the `$post` object data 
@ https://codex.wordpress.org/Function_Reference/$post

Reference the `add_meta_boxes` action 
@ https://codex.wordpress.org/Plugin_API/Action_Reference/add_meta_boxes
