### ISSUE TITLE
Is there any problem with option type icon? 

### ISSUE THREAD

**Issue by priyomukul** [Codestar/codestar-framework#524]
Suddenly this is not working for me, i tried so many times to fix it with new updated cs framework files, but nothing changed. 

<img width="674" alt="screen shot 2017-11-22 at 11 50 51 am" src="https://user-images.githubusercontent.com/17237437/33112103-a4388cb2-cf7b-11e7-9cfa-c725cd633cdd.png">

**Comment by Codestar** [comment]
Ddi you check for console errors ? Maybe there is a error notice?

**Comment by priyomukul** [comment]
there is no notice in console, can you please check this again.

**Comment by Codestar** [comment]
Yes sure, actually if you send wordpress admin informations via routewp[at]gmail[dot]com i can check it quickly for you. if the site online :)

**Comment by priyomukul** [comment]
Site is not online. :(
