### ISSUE TITLE
Control like WP Menu Drag Parent Child

### ISSUE THREAD

**Issue by dhrutel** [Codestar/codestar-framework#525]
Hello, we just started exploring this framework, and it is so easy that we picked up like in a minute.
Excellent job.

I have one question, not sure if its already answer, but in the Controls/Fields is there any such similar to WordPress Menu which we can drag/drop/align as Parent Child relation?

I did find a similar field in the framework, but it only allows to drag/drop up or down like order, but not left and right to make parent / child.

Thank you.

**Comment by Codestar** [comment]
Hi,

Thanks for your opinions, I get happy.. Hmm, there is no similar field for drag/drop parent/child, but it is nice idea. I noted this request for next updates. I will try to add it.

Regards

**Comment by Codestar** [comment]
You're welcome ;)
