### ISSUE TITLE
Call to undefined function wp_get_current_user()

### ISSUE THREAD

**Issue by 3y3ik** [Codestar/codestar-framework#528]
https://github.com/Codestar/codestar-framework/blob/e3fc8764b73d62093a49590500981928499a0bb4/cs-framework-path.php#L27

i can see php error: Call to undefined function wp_get_current_user()
if not use sanitize_file_name() in cs_get_path_locate() i cannot see this error

LAMP, php 5.6

**Comment by Codestar** [comment]
Can you update this line like this:

```php
$located_plugin = ( preg_match( '#'. preg_replace( '/[^A-Za-z]/', '', $plugin_dir ) .'#', preg_replace( '/[^A-Za-z]/', '', $dirname ) ) ) ? true : false;
```

If it works, i will update the repo.

**Comment by 3y3ik** [comment]
it's working!
thanks
