### ISSUE TITLE
WordPress 4.9 - Customizer Color Picker Issue!

### ISSUE THREAD

**Issue by Ansif** [Codestar/codestar-framework#529]
Hi @Codestar - @Codevz,

### Following Triggers :
1. *When you pick a color* - **It's Working.**
2. *When you change a color from picked color* - **It's Working.**
3. *When you click empty from picked color* - **Not Working!**
4. *Click empty and save the Customizer settings* - **Not Saving/Working!**

### Versions i use : 
- Codestar Framework : 1.0.2 
- WordPress : 4.9.1

Regards,
Ansif

**Comment by Codestar** [comment]
I tested all and i do not seeing any issue.. hmm can you make a video explain ?

**Comment by Ansif** [comment]
Hi,

I've used old method. Like following. So, i changed code to latest version.

Now it's working! 👍 

`array(
				'name'      => 'topbar_text_color',
				'control'   => array(
					'type'    => 'cs_field',
					'options' => array(
						'type'  => 'color_picker',
						'title' => esc_html__('Text Color', 'twentyseventeen'),
					),
				),
			),`

Thanks!

**Comment by Codestar** [comment]
You're welcome :+1:
