### ISSUE TITLE
Extra css/js fields

### ISSUE THREAD

**Issue by Galibri** [Codestar/codestar-framework#531]
I think, it would be great to have two extra fields for extra css and extra js coding. Can you please show me how to add this? I would like to create myself but can't start.

**Comment by dhrutel** [comment]
Just read your question, and i think its worth to achieve it, as sooner or later i would need it too.
For a minute i thought on how would i achieve this, then quick solution which i can think of is.

1. Have two textareas one for each css & js
2. Let codestar save it the way it does in its settings.
3. In Functions.php, call that setting values and wrap it under wp_head hook

For e.g.
function add_custom_css(){
... call here the settings code via echo
}
add_action('wp_head', 'add_custom_css');

For js you can do similar and have it in footer too if required.
Hope thats easy way.

Now you can extend the textareas by replacing some free opensource textareas which shows line numbers and color codes, or use WP inbuilt editor if possible.

**Comment by Codestar** [comment]
@dhrutel thanks for comment bro.

**Comment by Galibri** [comment]
Thank you for your answer. It's a great solution I have created a new field for css so that I can customize this filed as I want. Here is the code snippet:

```
<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.
/**
 *
 * Field: CSS
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_css extends CSFramework_Options {

  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }

  public function output() {

    echo $this->element_before();
    echo '<textarea name="'. $this->element_name() .'"'. $this->element_class() . $this->element_attributes() .'>'. $this->element_value() .'</textarea>';
    echo $this->element_after();

  }

}
```

**Comment by Codestar** [comment]
@Galibri 

Why you do not using textarea field for css/js ? for eg:

```php
array(
  'id'             => 'heading',
  'type'           => 'heading',
  'content'        => 'Custom CSS',
),
array(
  'id'              => 'custom_css',
  'type'            => 'textarea',
  'attributes'      => array(
    'rows'          => '20',
  ),
),
array(
  'id'             => 'heading',
  'type'           => 'heading',
  'content'        => 'Custom Javascript',
),
array(
  'id'              => 'custom_js',
  'type'            => 'textarea',
  'attributes'      => array(
    'rows'          => '20',
  ),
),
```

Output: 

![832db6a9781a40_preview](https://user-images.githubusercontent.com/1313301/34006863-e3a8292e-e110-11e7-969f-7814e90bcf4f.png)

**Comment by Galibri** [comment]
@Codestar
Thank you! I wanted to use some more cool features for css and js. That's why extended the textarea field.

Here is the output which I have got so far:
![theme-options-css-and-js-extra](https://user-images.githubusercontent.com/16418430/34007464-bccecff4-e0f9-11e7-9a8a-23eb508635e5.JPG)

**Comment by Galibri** [comment]
@Codestar 
Thank you! I wanted to use some more cool features for css and js. That's why extended the textarea field.

Here is the output which I have got so far:
![theme-options-css-and-js-extra](https://user-images.githubusercontent.com/16418430/34007464-bccecff4-e0f9-11e7-9a8a-23eb508635e5.JPG)

**Comment by Codestar** [comment]
@Galibri Oh yes I understand now. Yes new field class is correct way ;) it is easy as you see :)

**Comment by girisagar051** [comment]
Hello @Galibri .

Could you please let me know what did you use for extending the text area field?

Thanks.
