### ISSUE TITLE
How to Fix Image Upload Issue ?

### ISSUE THREAD

**Issue by ZVGrys** [Codestar/codestar-framework#533]
Hi! I have problem with image upload issue. How to fix that?
https://shared-assets.adobe.com/link/1b22da6c-838b-47fd-6daf-8a85d7b044c0

**Comment by Codestar** [comment]
Hi,

Hmm yes i am seeing it is not working properly. Actually i need to see it detailed. Can you send me wordpress admin information via routewp[at]gmail[dot]com

Btw, why you do not ask this question for theme author ? or did you ? :)

Regards

**Comment by ZVGrys** [comment]
I send to you. I'll wait for your answer. Thanks.

**Comment by Codestar** [comment]
Done. https://github.com/Codestar/codestar-framework/commit/8e1caf9b9bb4f9db686a7250898a30743c27980a
