### ISSUE TITLE
WordPress Theme got soft rejected with Codestar Framework issue

### ISSUE THREAD

**Issue by Khaled56** [Codestar/codestar-framework#534]
I got 17th soft rejection with my ThemeForest WordPress Theme. 
I got another soft rejection with Codestar framework. Please, **see screenshots.**

1. Please use a unique prefix for all function names, custom images sizes, classes, constants, hooks, public/global variables, and database entries to avoid conflict issues with plugins and other themes. Ref: http://themereview.co/prefix-all-the-things/

Example(s): 
**http://envato.d.pr/jHwgkL** 
**http://envato.d.pr/lRwQ9g**

**What Should I do? Should I use Codestar Framework as plugin? It would be better??**

Then, at time of calling in templates should I use if_function-exist('cs_get_option')  in every time. like this:

if (function_exists('cs_get_option')):
	$header_iconic_boxes = cs_get_option( 'header_iconic_boxes' );	
endif;

**Please, help me.**

**Comment by varunsridharan** [comment]
@Khaled56 try to explain them that its a fallback 

if not you can remove this php file 

https://github.com/Codestar/codestar-framework/blob/master/functions/fallback.php

**Comment by pinethemes** [comment]
what is the result, can you explain exactly how to solve the problem in detail?
