### ISSUE TITLE
cs-tab-active

### ISSUE THREAD

**Issue by exL24** [Codestar/codestar-framework#535]
Hello,

I want have options hidden at opening menu and class cs-tab-active its added automatic after opening framework. There is any quick solution? Cannot find anything to help me in documentation

Thanks.

**Comment by varunsridharan** [comment]
@exL24 i am not sure why you want to do that. but you can still play around with JS  and get this done. :)

**Comment by exL24** [comment]
Thanks for answer mistake was from my side :) i declareted wrongly 'name' it has duplicates and that made every option make somekind of dropdown the same time

**Comment by Codestar** [comment]
You can write custom js code for this request.
