### ISSUE TITLE
Post type list

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#537]
Hi . 
I just want to know how to get the post type list metabox (select box or radio button) .
regards

**Comment by varunsridharan** [comment]
Hi,

You can use the below code to get checkbox with pages

```php
array(
  'id'             => 'unique_option_307',
  'type'           => 'checkbox',
  'title'          => 'Checkbox for Posts',
  'options'        => 'posts',
  'query_args'     => array(
    'orderby'      => 'post_date',
    'order'        => 'DESC',
  ),
),

```

**Comment by stivoox** [comment]
@varunsridharan I mean post types list foe example : page, post, portfolio, job etc..

**Comment by varunsridharan** [comment]
@stivoox 
Just replace the code below

```php
'options'  => 'posts',
```

To

```php
'options' => 'post_type',
```

**Comment by stivoox** [comment]
I mean post type list :  registered post type lists

**Comment by varunsridharan** [comment]
@stivoox 
if you use that it will provide you the resisted post type list 

check the code if you don't believe it

https://github.com/Codestar/codestar-framework/blob/ef60dab50b9c39f081e0cff185d65f4676a6e3fc/classes/options.class.php#L307-L323

**Comment by samjco** [comment]
#494
