### ISSUE TITLE
Customizer not supporting multiple checkboxes options

### ISSUE THREAD

**Issue by kwayyinfotech** [Codestar/codestar-framework#539]
Hello,

I tried to set multiple checkbox option in Customizer option but it's not working. Here is the code:

```
array(
'name'		=> 'checkbox_option_test',
'control'	=> array(
	'type'		=> 'cs_field',
		'options'	=> array(
			'type'		=> 'checkbox',
			'title'		=> 'Multi Checkbox',
			'choices'	=> array(
				'key1' 		=> 'value 1',
				'key2'		=> 'value 2',
				'key3'		=> 'value 3',
			)
		),
	),
)
```

Also I tried native WP checkbox element too but it is also not working. Here is the code:

```
array(
	'name'		=> 'checkbox_option_wp',
	'control'	=> array(
		'label'		=> 'Checkbox WP',
		'type'		=> 'checkbox',
		'choices'	=> array(
			'key1'		=> 'value 1',
			'key2'		=> 'value 2',
			'key3'		=> 'value 3',
		)
	),
),

```

Both of above code is not working. Please guide me how can I set it.

**Comment by Codestar** [comment]
Customizer not support multiple checkboxes. This feature will come with v2.

**Comment by kwayyinfotech** [comment]
Thanks for your reply.
Can we have access to v2 branch so we can download and check it on our system. Also it will make sure for compatibility.

**Comment by Codestar** [comment]
You can leave an email via routewp[at]gmail[dot]com I will noted you about v2  :)
