### ISSUE TITLE
Incompatibilty with Jetpack

### ISSUE THREAD

**Issue by macedonius** [Codestar/codestar-framework#54]
Hi,
Thanks for the great framework, its awesome! After fixing this problems I would purchase the paid version soon.
The 2.1.3 version which I use in my plugin has a compatibility problem with Jetpack. As soon as Jetpack is installed and activated JetPack, and connected it to the WordPress.com account - clicking on the plugin options will not set them as active(will not render the tab content). 
Only after you click on another tab the content of the other tab is shown and when you re-click the initial tab it shows its content(its selected).
I've checked the Console and it have this:
```
Uncaught TypeError: Cannot read property 'newURL' of undefined
    at jetpack-jitm.min.js:2
    at dispatch (jquery.js:3)
    at r.handle (jquery.js:3)
    at Object.trigger (jquery.js:3)
    at Object.a.event.trigger (jquery-migrate.min.js:2)
    at jquery.js:3
    at Function.each (jquery.js:2)
    at a.fn.init.each (jquery.js:2)
    at a.fn.init.trigger (jquery.js:3)
    at HTMLDivElement.<anonymous> (csf.min.js?ver=1.0.0:3)
```
And the main error points to line 243 of codestar-framework/assets/js/csf.js      
` }).trigger('hashchange');`

But I think its connected to the whole Options Navigation part.

Are you able to help (even with a hotfix)?

Thanks

**Comment by Codestar** [comment]
Hi,

I have installed Jetpack but didn't get this error. Is your website online ? Let me check on your website. You can send me details via routewp[at]gmail[dot]com

Regards

**Comment by macedonius** [comment]
Hi,
I had sent you an email.
The bug is present when only Jetpack is installed, active and connected to a WordPress.com account. Not only installed and active.

Thanks

**Comment by Codestar** [comment]
Hi,

It fixed now. Just updated the hashchange trigger like this: https://github.com/Codestar/codestar-framework/commit/8353573425dd880852ee4d5e921211264c8d6673

Thanks for report.
Regards

**Comment by macedonius** [comment]
I can verify that it works. Thanks again for making this and for being so helpful! :)

**Comment by Codestar** [comment]
You're welcome ;)
