### ISSUE TITLE
Issue with save redirecting to options.php

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#540]
I 've added CS to a fresh install of 4.9.1 of WordPress.
Initiated the sample framework to the menu area (..wp-admin/admin.php?page=cs-framework) clicked save, and it seems to save correctly, but redirects to the (wp-admin/options.php) whih show blank.

Is this a bug?

**Comment by varunsridharan** [comment]
@samjco Codestar uses WordPress Settings API.
Which requires all settings save methods to be redirected to options.php

**Comment by samjco** [comment]
Oh ok.
Question, is there a setting in CS that will redirect back to the admin framework page once fields are saved?

**Comment by varunsridharan** [comment]
Yes it will auto redirect to the same settings page.

**Comment by samjco** [comment]
@varunsridharan  Well, the issue is that it shows blank

**Comment by Codestar** [comment]
Hi,

Interesting,

You can try to change this line:

https://github.com/Codestar/codestar-framework/blob/8e1caf9b9bb4f9db686a7250898a30743c27980a/classes/framework.class.php#L306

to

```php
echo '<form method="post" action="" enctype="multipart/form-data" id="CSF_form">';
```

**Comment by anhdq1801** [comment]
@Codestar I have issue it work well when the admin link is "wp-admin/admin.php?page=cs-framework" it work well. But when i use plugin to changeadmin link to "my-admin/admin.php?page=cs-framework" it auto redirect to "my-admin/options.php" and can't save option.
