### ISSUE TITLE
Conditional on 2 option arrays based on values in one

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#541]
I am trying to figure out an issue in trying to use data from a text field in one option instance into another and hide the options1 array but show options2 array (and vice-versa), only if there is something in the textfield. But then send a $message back to the notice fields. I will get an error _txt_name field doesn't exist.....

So I am wondering should I do an Ob_start function or is the problem with the text field being null?
If there is a better way to accomplish what I am trying to do.. please let me know :)

```php
/**
 *
 * CSFramework Config
 *
 * @since 1.0
 * @version 1.0
 *
 */

// Top level Menu
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>',
);


$options1   = array();
$options1[] = array(
  'name'   => 'Settings',
  'title'  => 'Settings',
  'icon'   => 'fa fa-star',
  'fields' => array(

	array(
		'type' => 'notice',
		'class' => 'danger',
		'content' => $message,
	),

	array(
	  'id'    => '_txt_name',
	  'type'  => 'text',
	  'title' => 'Folder Name',
	  'desc' => 'Enter a desired name.',
        ),

    ),
);
		
$options2   = array();
$options2[] = array(
  'name'   => 'Options',
  'title'  => 'Options',
  'icon'   => 'fa fa-star',
  'fields' => array(

	array(
		'type' => 'notice',
		'class' => 'info',
		'content' => $message,
	),
    ),
);

//Conditional
$txtName = $cs_get_option('_txt_name');
if ($txtName != ''):
     $message = "You value of".$cs_get_option( '_txt_name' )." is saved";
     $options = $options2;
else:
     $message = "Please Enter a value in textfield";
     $options = $options1;
endif;


CSFramework::instance( $settings, $options );
```

**Comment by varunsridharan** [comment]
@samjco 

IN CS Framework it just save everything that posted from the Settings page
Which means you need to have all the fields in our settings array

if you want to do conditional array
Then you can make that field hidden. so that value dose not disappear

**Comment by samjco** [comment]
So Are you saying to store the value in a variable so it won't disappear?

**Comment by varunsridharan** [comment]
lets say i have 2 fields
1. Email ID
2. Website

but i want both value to be stored in DB with out the values getting blank.

So i will make 1 field hidden and other visible in this way the values wont get blank

**Comment by samjco** [comment]
Can i use: `apc_store();` (http://php.net/manual/en/function.apc-store.php)
or even `session_start();`

```php
$bar = 'BAR';
apc_store('foo', $bar);
var_dump(apc_fetch('foo'));
// returns: string(3) "BAR"
```

**Comment by varunsridharan** [comment]
@samjco now i am confused.
if you just want to keep the values of a field and dont want to show the field then you can make it hidde

like

```php
array(
	  'id'    => '_txt_name',
	  'type'  => 'hidden',
	  'title' => 'Folder Name',
	  'desc' => 'Enter a desired name.',
        ),
array(
	  'id'    => '_txt_name2',
	  'type'  => 'text',
	  'title' => 'Folder Name',
	  'desc' => 'Enter a desired name.',
        ),
```

**Comment by samjco** [comment]
@varunsridharan 
Basically what I was trying to do was I didn't want to show options2 unless the textfield in options1 is set.

**Comment by varunsridharan** [comment]
@samjco then you can use http://codestarframework.com/documentation/#how-to-use-dependency

Like 

```php
array(
	  'id'    => '_txt_name',
	  'type'  => 'hidden',
	  'title' => 'Folder Name',
	  'desc' => 'Enter a desired name.',
        ),
array(
	  'id'    => '_txt_name2',
	  'type'  => 'text',
	  'title' => 'Folder Name',
	  'desc' => 'Enter a desired name.',
'dependency'   => array( '_txt_name', '!=', '' ),
        ),
```

**Comment by samjco** [comment]
@varunsridharan I thought about that but, i have many fields in options2 that already have dependencies. The conditions work somewhat, if I can store a variable outside the Settings.

**Comment by varunsridharan** [comment]
@samjco still confused. 
i can help u only if you share the full code (Settings Array) I can't find where u merge those 2 options array

**Comment by samjco** [comment]
Well @varunsridharan basically I am trying to store a variable outside of both option arrays, but the initial store would come from a field in options1.

**Comment by samjco** [comment]
@varunsridharan 
I think I figured it out!
Just replicated the same fields in options2 as hidden (or readonly) with the same IDs.

**Comment by samjco** [comment]
@varunsridharan
PHP $_SESSION variables seems to do the trick. But I wish there were a cleaner way to access vars up and down the code. I know I can pass my vars through $_POST. I can also perhap set field dependencies, but that can be somewhat daunting, especially if I have alot of fields.

So I've made 2 option field groups, and render them based on conditions.
I wish that we can add dependencies to the field groups themselves, not just the fields... Maybe that might be what can solve my issue.
