### ISSUE TITLE
Cannot Add a Form element to the content field

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#543]
I'm trying to add a simple post form to the "content" field type.
But I believe CSF is Replacing or canceling the `<form>` tags out of the HTML code.

Any help?

**Comment by Codestar** [comment]
```<form>``` inside another ```<form>``` is not a valid HTML. (Web Stantards) HTML specification states that no FORM element should contain another FORM element.

Still you want to use it, you need to use jquery form get/post ideas...

**Comment by samjco** [comment]
Oh Duh.. I knew that! 🔢   :)
