### ISSUE TITLE
Offtopic: Get each category as sub section of accordion

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#55]
```
$options[]   = array(
  'name'     => 'accordion_section',
  'title'    => 'Accordion Sections',
  'icon'     => 'fa fa-bars',
  'sections' => array(),
);

$category_ids = get_terms('category');
foreach($category_ids as $cat_id) {
    $options[]['sections'][] = array(
      'name'     => 'sub_section_'.$cat_id->term_id,
      'title'    => __(get_cat_name($cat_id->term_id)),
      'icon'     => 'fa fa-minus',
      'fields'   => array(
        array(
          'type'    => 'content',
          'content' => 'This section is empty, add some options...',
        ),
      )
    );
}
```

**Comment by Codestar** [comment]
Yes ?

**Comment by sabuz** [comment]
I have done this with Option Tree. But this is not working with Codestar. These foreach loops are not generating inside 'sections'.

**Comment by sabuz** [comment]
$options['accs']   = array(
  'name'     => 'accordion_section',
  'title'    => 'Accordion Sections',
  'icon'     => 'fa fa-bars',
  'sections' => array(),
);

$category_ids = get_terms('category');
foreach($category_ids as $cat_id) {
    $options['accs']['sections'][] = array(
      'name'     => 'sub_section_'.$cat_id->term_id,
      'title'    => __(get_cat_name($cat_id->term_id)),
      'icon'     => 'fa fa-minus',
      'fields'   => array(

        array(
          'type'    => 'content',
          'content' => 'This section is empty, add some options...',
        ),

      )
    );
}

These are working! :smiley:

**Comment by Codestar** [comment]
Oh well done :+1:
