### ISSUE TITLE
dynamic fields

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#551]
Hi . i just want to know if we can create a field depends on other field variables for exemple . 
we have a select box witn taxanomies (colors , type , height ...) . and I want to create another select box of terms of each of those taxonomie 
best regards

**Comment by samjco** [comment]
Looks like you would have to use post form method.
Passing the value of your taxonomy select box and then retrieving it after submission.
```php
if (isset($_POST['exe'])):
    //Uncomment to check to see if correct values were passed
    /*
     print_r($_POST['name-of-taxonomy-field']);
     die();
    */
      
     //Load new select box here
endif;
```

**Comment by stivoox** [comment]
I mean without submission

**Comment by samjco** [comment]
Sorry, then you would need an Ajax solution.
