### ISSUE TITLE
Making addons plugins as submenus to main menu options

### ISSUE THREAD

**Issue by samjco** [Codestar/codestar-framework#554]
I am wanting to make an add-on plugin that once activated, it's options framework will show as a submenu under the main plugin's options panel. 

So how can I add code in the add-on that will detect the main CSF plugin?

```php
/*
 * Plugin Name: My ADDON plugin
 * Plugin URI: http://www#
 * Description: Plugin that does something.
 * Author: Samjco
 * Version: 1.0
 * Author URI: https://samjco.com
 */

defined('ABSPATH') or die("Restricted access!");

//First detect in CSF exist and is active
if( function_exists( 'cs_framework_init' ) && class_exists( 'CSFramework' ) ) {
 
// Add code to hook into Main Options as a submenu
 
}
```

**Comment by varunsridharan** [comment]
@samjco 
There are 2 ways

1. simple way is to add a hook in the below function
https://github.com/Codestar/codestar-framework/blob/master/classes/framework.class.php#L262-L294

And using that hook we can hook our addon page

2. or we need to write our own addon logic 
Like in this.
https://github.com/varunsridharan/vsp-framework/tree/master/class/addons
