### ISSUE TITLE
Type query args issue . 

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#556]
Hi friends .
I have an issue with this code : 
`array(
  'id'             => 'unique_option_512',
  'type'           => 'select',
  'title'          => 'Select Field for CPT Posts',
  'options'        => 'categories',
  'query_args'     => array(
    'type'         => 'any post type',
    'taxonomy'     => 'movies_taxonomy',
  ),
  'default_option' => 'Select a category',
),`

this code return terms list even if the type args is false . what's wrong ??

**Comment by samjco** [comment]
What are you try to get in the select field?

**Comment by stivoox** [comment]
List of terms attached to a post type and taxonomy .

**Comment by samjco** [comment]
You can try this:

```php
array(
 'id' => 'unique_option_512',
 'type' => 'select', 
 'title' => 'Select Field for CPT Posts',
 'options' => 'categories', 
 'query_args' => array( 
    'post_type' => 'Movies', 
    'taxonomy' => 'movies_taxonomy',
   ), 
 'default_option' => 'Select a category',
 ),
```

OR this:

```php
$taxonomy = "movies_taxonomy";

$term_options= array( '' => 'Select' );
$terms = get_terms( $taxonomy );
if ( ! empty( $terms ) && ! is_wp_error( $terms ) ) {
	foreach ( $terms as $term ) {
		if ( isset( $term->term_id ) ) {
			$term_options[ $term->term_id ] = $term->name;
		}
	}
}

// Check your dump
//echo "<pre>";
// print_r($term_options);
// echo "</pre>";
// die();

array(
 'id' => 'unique_option_512',
 'type' => 'select', 
 'title' => 'Select Field for CPT Posts',
 'options' => '$term_options', 
 'default_option' => 'Select a category',
 ),
```

I haven't tested them yet. =P

**Comment by samjco** [comment]
I hope I am understanding you correctly

**Comment by stivoox** [comment]
The first code doesn't work . 
the second one doesn't have any place to put the post type.
maybe it's a bug on the framwork . 
check this code in documentation : https://imgur.com/AZp8DKS
what's the purpose of the type args in this code ?

**Comment by samjco** [comment]
I think if you kinda explain what you are trying to accomplish this will help. :)
Like what are you doing? Is this for a Admin Settings or Post Area?

**Comment by stivoox** [comment]
No for admin settings . 
I have two loops (nested loops )one for post types and one for taxonomies .
I try the generate a select box via those two loops and populate it via terms obtained by this code : https://imgur.com/IeTHqDA

after that I'll hide fields with empty select using dependency .

**Comment by samjco** [comment]
```php
$customposttype ="Your CPT";
$taxonomy = "Your Tax";
array(
 'id' => 'unique_option_512',
 'type' => 'select', 
 'title' => 'Select Field for CPT Posts',
 'options' => 'categories', //Or Posts
 'query_args' => array( 
    'type' => $customposttype , 
    'taxonomy' => $taxonomy,
   ), 
 'default_option' => 'Select a category',
 ),
```

**Comment by samjco** [comment]
So you are saying, based on your code screenshot (thank you) that your ARE getting the results, BUT are also get results you don't want because it is defaulting out even if there isn't any pt or not?

**Comment by stivoox** [comment]
Yes that's what i'm trying to say .

**Comment by samjco** [comment]
Once again. Not 100% sure of this because I haven't tested it, but here you go!


```php
global $wp_post_types;
$posttypes = array_keys( $wp_post_types );
                     
// Remove any wp _builtins or others undesirables.
$pt_remove = array("attachment","nav_menu_item","custom_css","customize_changeset","revision");

foreach ( $posttypes as $val):
	if ( in_array($val, $pt_remove) ) continue;
	
//remove builtins
$args = array( 'public'   => true, '_builtin' => false ); 

$output = 'names'; // or objects
$operator = 'and'; // 'and' or 'or'
$taxonomyarray = get_taxonomies( $args, $output, $operator ); 
if ( $taxonomyarray ) {
  foreach ( $taxonomyarray as $k => $taxo ) {
    //Add field creation code here
  endforeach;
endif;

endforeach; //end posttype foreach
```

**Comment by samjco** [comment]
@stivoox did that work for you?

**Comment by stivoox** [comment]
No but I have made my own solution :
<pre>
function filter_terms_by_cpt_cs($taxonomy, $post_types = array())
{
    global $wpdb;

    $post_types = (array)$post_types;
    $key = 'wpse_terms' . md5($taxonomy . serialize($post_types));
    $results = wp_cache_get($key);

    if (false === $results) {
        $where = " WHERE 1=1";
        if (!empty($post_types)) {
            $post_types_str = implode(',', $post_types);
            $where .= $wpdb->prepare(" AND p.post_type IN(%s)", $post_types_str);
        }

        $where .= $wpdb->prepare(" AND tt.taxonomy = %s", $taxonomy);

        $query = "
          SELECT t.*, COUNT(*) 
          FROM $wpdb->terms AS t 
          INNER JOIN $wpdb->term_taxonomy AS tt ON t.term_id = tt.term_id 
          INNER JOIN $wpdb->term_relationships AS r ON r.term_taxonomy_id = tt.term_taxonomy_id 
          INNER JOIN $wpdb->posts AS p ON p.ID = r.object_id 
          $where
          GROUP BY t.term_id";

        $results = $wpdb->get_results($query);
        wp_cache_set($key, $results);
    }

    return $results;
}
</pre>

then 

<pre>

foreach ($posttypes as $val) {
        foreach ($taxonomyarray as $k => $taxo) {
            if (empty(filter_terms_by_cpt_cs($k, $val))) {
                continue;
            }
            $out[] = array(
                'id' => 'unique_option_' . $val . '_' . $k,
                'type' => 'select',
                'title' => $val . ' / ' . $k,
                'options' => 'termxon',
                'taxonomies_var' => $k,
                'post_types_var' => $val,
                'dependency' => array('posttype', '==', $val),
                'class' => 'chosen',
                'attributes' => array(
                    'multiple' => 'only-key',
                    'style' => 'width: 200px;'
                ),

            );
        }

    }
    return $out;
</pre>
