### ISSUE TITLE
Add filter for metabox sanitizion

### ISSUE THREAD

**Issue by bilalmalkoc** [Codestar/codestar-framework#56]
In metabox.class.php line 302, you set wp_kses_post_deep for sanitizing values. But it block some html contents like iframe. Can you add a filter for this?

like
`apply_filters( 'csf_main_post_meta_sanitizing', wp_kses_post_deep( $_POST[ $this->unique ] ) )`

And do you think create git master repo for pro version? So we can contribute for best.

**Comment by Codestar** [comment]
Hi,

Due to wordpress sanitize rules the **iframe** tag doesn't allows to save. But no worries there is a way pass that for custom project. for eg:

```php
function my_custom_allowed_html( $tags, $context ) {
  $tags['iframe'] = array(
    'src' => true,
    'width' => true,
    'height' => true,
    'allowfullscreen' => true,
    // you can add more attribute if needed
  );
  return $tags;
}
add_filter( 'wp_kses_allowed_html', 'my_custom_allowed_html', 10, 2 );
```

This filter will allow the **iframe** tag while save. Also you can add any html tag...

Does it work for you ?

Regards

**Comment by bilalmalkoc** [comment]
Yes i know but, some iframes could has different attributes. So this filter doesn't enough.

**Comment by Codestar** [comment]
Hi,

How to you planning to pass sanitize with "csf_main_post_meta_sanitizing" filter. Can you please explain me more in a clear way ?

Regards

**Comment by bilalmalkoc** [comment]
I don't know how to sanitize with iframe html for now. But i can use this filter for disabling sanitization.

**Comment by Codestar** [comment]
Yes, I wonder how to you will use this disable filter? That will inspiration to me.

Actually I mean, this filter will disable all sanitization. May be we can use like this:

```php
array(
  'id'       => 'opt-wp-editor-1',
  'type'     => 'wp_editor',
  'title'    => 'WP Editor',
  'sanitize' => false,
),
```

What you think ?

**Comment by Codestar** [comment]
I have sent an email about this subject to you. bi.........91[at]gmail[dot]com Let's continue via email.
