### ISSUE TITLE
how to use typography??

### ISSUE THREAD

**Issue by jahir07** [Codestar/codestar-framework#56]
i try to use like this:
<?php 
$font = cs_get_option('heading_fonts');

if(cs_get_option('heading_fonts')) { ?>
h1, h2, h3, h4, h5, h6 {
  font-family: '<?php echo $font['family'] ?>', sans-serif;
  font-weight: <?php echo $font['variant'] ?>;
}
<?php } ?>

but in $font['variant'] is echo regular.. But there is no css font-weight value is regular. it should be normal. is not it?? Am i in wrong way?? Is there any way to return perfect data.. 

By the way, can you another facilities is that- typography on view selection option?? 

Thanks for nice and light framework..

**Comment by Codestar** [comment]
Hi,

Now, you know we are using google-fonts and custom fonts, and google-fonts api giving weight/style both. for eg. 700italic 300italic regular etc. and we need to a custom parser for this field. you can use my parser.

```
//
// Helper for Typography Parser
// -------------------------------------
function cs_typography_parser( $typography ) {

  $out  = array();
  $font = cs_get_option( $typography );

  // family
  $out['family'] = $font['family'];

  // weight
  $weight = preg_replace( '/\D/', '', $font['variant'] );
  $out['weight'] = ( ! empty( $weight ) ) ? $weight : 'normal';

  // style
  $style = preg_replace( '/[0-9]/', '', $font['variant'] );
  $out['style'] = ( ! empty( $style ) && $style !== 'regular' ) ? $style : 'normal';

  return $out;
}

//
// Embed Typography
// -------------------------------------
$font = cs_typography_parser( 'unique_typography_1' );

if( ! empty( $font ) ) {

  echo 'h1,h2,h3,h4,h5,h6 {';

    echo 'font-family:'. $font['family'] .';';
    echo 'font-weight:'. $font['weight'] .';';
    echo 'font-style:'. $font['style'] .';';

  echo '}';

}
```

Tranks for your comment :) try and tell me if you need this...

**Comment by jahir07** [comment]
thanks.. let me try with parser..

**Comment by Codestar** [comment]
:+1:
