### ISSUE TITLE
DateTime Picker

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#560]
Hi friends .
I just want  to know if this framwrok come with a datetimepicker field ??
regards

**Comment by stivoox** [comment]
Any response !?

**Comment by wiljonbolten** [comment]
Hi @stivoox,
Codestar doesn't come with a datepicker, at least I didn't find it yet.

But you could try the following:
`array(
    'id'      => 'date_picker_demo',
    'type'    => 'text',
    'title'   => __( 'Datepicker', 'txtdm' ),
    'attributes' => array(
        'type' => 'date',
        ),
    ),`

This way the field is transformed to the HTML5 date field, wich works perfectly in my case.

Let me know how it works out for you! :)

**Comment by wiljonbolten** [comment]
Good to hear, thank you! 👍

**Comment by ShawnZeng1996** [comment]
@wiljonbolten Thanks a lot!
