### ISSUE TITLE
How can i show the list of all users in the framework with Select?

### ISSUE THREAD

**Issue by ShawnZeng1996** [Codestar/codestar-framework#563]
Hello everyone! Thanks for giving us such a wonderful framework first. I'm now creating a wordpress theme by this framework.I want to create a Select option which contain the list of all users but i didn't learn php in the past. Can you help me? Thanks a lot!

**Comment by samjco** [comment]
Ok, I will take a stab at this.
This code is untested... but I think it should work
Reference: https://codex.wordpress.org/Function_Reference/get_users

```php
    // Just get the display name of users (e.g John Smith)
    $user_names = array();
    $all_users = get_users( array( 'fields' => array( 'display_name' ) ) );

    // For test purposes to see if name are echoed. uncomment to test.	
    // echo "<pre>";
    // print_r($all_users);
    // echo "</pre>";
    // die();

   foreach ( $all_users as $user ):
        $user =  esc_html( $user->display_name ) 
	$user_names[ $user ] = $user; 
   endforeach;
```
Now add you field logic:

```php
array(
	'id'      => 'select_user',
	'type'    => 'select',
    	'debug' => true,
	'title'   => 'Select User',
	'options' => $user_names,
	 ),
```
Like I've said, I haven't tested it. But let me know if you recieve any error.

**Comment by ShawnZeng1996** [comment]
@samjco 
Wonderful! 
It's useful!
But you've missed out the ';' at `$user =  esc_html( $user->display_name )` .
Anyway, thanks a lot!

**Comment by samjco** [comment]
oops. But did it do what you want?

**Comment by ShawnZeng1996** [comment]
@samjco Yes, i achieve my goal with your function! Thanks a lot~
