### ISSUE TITLE
Default customizer settings edit form theme options

### ISSUE THREAD

**Issue by mrjam3s** [Codestar/codestar-framework#565]
Is that possible to edit few default customizer settings directly from theme options, including of which - the Site Title and Tagline and Custom css

**Comment by obiPlabon** [comment]
@mrjam3s By default that's not possible, you can't change or update customizer default option from theme options panel made using CSF.

**Comment by mrjam3s** [comment]
@obiPlabon thank you for your replay. 
Can you give me some hints that how i solve it. it's really helpful to me.
