### ISSUE TITLE
Multiple checkbox in Customizer not working properly

### ISSUE THREAD

**Issue by themestek** [Codestar/codestar-framework#567]
Hello,

I am developing Customizer options for my theme. I added a multiple checkbox option in customize.config.php but it's not working as expected. If I check any one checkbox than it will check all checkboxes, and if I uncheck one checkbox than it uncheck all checkboxes.

Here is the element code I am using:

```
array(
	'name'		=> 'show_elements',
	'control'	=> array(
		'type'		=> 'cs_field',
		'options'	=> array(
			'type'		=> 'checkbox',
			'title' 	=> 'Select elements that you like to show',
			'options'	=> array(
				  'infobar'	=> 'Information Bar',
				  'header'	=> 'Header',
				  'content'	=> 'Content Area',
				  'footer'	=> 'Footer',
			),
		),
	),
	'default'	=> array( 'header' ),
),

```

Please guide me on this.

**Comment by Codestar** [comment]
It will come in v2.
