### ISSUE TITLE
About Typography

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#569]
Hi . 
I want to use to typography field to add the possibility of typo customisation in my theme , and I want to know if we need to enqueuing google font before using this field our what, because I can't use the chosen font family in the front-end . 
Thanks

**Comment by stivoox** [comment]
Any reponse !!

**Comment by varunsridharan** [comment]
@stivoox codestar just provides options with list of Google fonts. you need to load the fonts based on the users selections.

**Comment by stivoox** [comment]
@varunsridharan any idea about enqueuing google fonts based on selection ?

**Comment by varunsridharan** [comment]
@stivoox 
Here is a code to add load google fonts  but you need to make some changes to it by getting the selected font from settings and making it fully dynamic 
```php
function wpb_add_google_fonts() {
 
wp_enqueue_style( 'wpb-google-fonts', 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,700,300', false ); 
}
 
add_action( 'wp_enqueue_scripts', 'wpb_add_google_fonts' );
```

For more info : http://www.wpbeginner.com/wp-themes/how-add-google-web-fonts-wordpress-themes/
