### ISSUE TITLE
Color picker issues

### ISSUE THREAD

**Issue by Alimir** [Codestar/codestar-framework#57]
I bought your premium version a few months ago. Is it possible to replace wp color picker with another framework such as spectrum in the next update?
I have already encountered the following error in console log and had to disable its code in your framework:
`TypeError: (new Color (...)). SetHSpace is not a function`

**Comment by Codestar** [comment]
Hi,

Thanks for purchasing. Yes sure, I can update. But please can you give me more details. Which plugin you used and where is the conflict exactly ?

Regards

**Comment by Alimir** [comment]
@Codestar  In general, color picker scripts have some problems and in many situations cause a lot of conflict. I already had this problem in my own framework and had to delete it. I mentioned an example of an error in the first topic.
But there were some points in your framework code. For example, it is better to change the following line as follows:
https://github.com/Codestar/codestar-framework/blob/652bb67a88165c2828cc14954fbc9b57f086bc24/assets/js/csf.js#L2771
`‍Color.prototype.toString = function () {`

Also, if you can add more hooks to the framework, for example, we can restrict the loading of functions such as add_admin_enqueue_scripts and csf_set_icons to certain pages. It's much better. e.g.
https://github.com/Alimir/wp-ulike/commit/b7442cf953fa7700f10f0e318691f1a0a60c0597#diff-ccc5b8c17f9fb5405d9abff5fad6af5e
https://github.com/Alimir/wp-ulike/commit/f8ce2682d2940a9e8fe16051dc821544d9ac6ccc#diff-ccc5b8c17f9fb5405d9abff5fad6af5e

**Comment by Alimir** [comment]
It's also great to be able to add this option to CSF_Options class:
https://github.com/Alimir/wp-ulike/blob/3efb57a29666f85c5a1ae7451b0807144d314713/admin/settings/classes/options.class.php#L428

**Comment by Codestar** [comment]
Hi,

:one: **Color Picker**

```js
TypeError: (new Color (...)). SetHSpace is not a function
```

I have searched this issue. but I think this conflict coming from WP Color Picker. <a href="https://www.google.com/search?source=hp&ei=W4qpXqHzO7yKjLsP-fCj2A0&q=TypeError%3A+%28new+Color%28...%29%29.setHSpace+is+not+a+function&oq=TypeError%3A+%28new+Color%28...%29%29.setHSpace+is+not+a+function&gs_lcp=CgZwc3ktYWIQAzIICAAQFhAKEB5QgQVYgQVg3QZoAHAAeACAAZEBiAGRAZIBAzAuMZgBAKABAqABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjhjMjb543pAhU8BWMBHXn4CNsQ4dUDCAc&uact=5">See google search</a> and for eg <a href="https://github.com/PopupMaker/Popup-Maker/issues/471">this</a>

As you know only I am adding a color prototype. This prototype can not cause that error.

https://github.com/Codestar/codestar-framework/blob/652bb67a88165c2828cc14954fbc9b57f086bc24/assets/js/csf.js#L2771

and thanks I have updated it like this. 

```js
Color.prototype.toString = function () {...
```

:two: **add_admin_enqueue_scripts**

Hmm yes, you can use like that. but I can't add that code. because as you know the framework using everywhere. posts, taxonomies, widgets, customizer etc. Maybe I can think to add a filter future.

:three: **csf_set_icons**

Yes I don't like to my include method for icons. I should to update it. I will think an idea for that.

Regards

**Comment by Alimir** [comment]
1- Yes, I think this problem is related to the original script that created Conflict. Now, if I add the color picker option, this error will occur and it will not work like the following image. That's why I suggest using another script for the color picker.
https://imgur.com/a/pDpBbWX
2- Yeah, I sent you this code as an example. I also mean adding a filter for this.
3- Yes, because if we disable scripts, its HTML tags will be added to the footer. It's better to call it as an AJAX content.

**Comment by Codestar** [comment]
**1.** Which plugin triggers this error ? A lot of framework users are using the wp color picker as smoothly. I have seen first time this issue.

**2 and 3.** Actually you do not need touch core files. Take a look this code example:

```php
//
// Scripts is only can be load on ulike pages.
//
function wp_ulike_admin_init() {

  global $pagenow;

  if( ! defined( 'WP_ULIKE_PRO_DOMAIN' ) || ! in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) {
    remove_action( 'admin_enqueue_scripts', 'CSF::add_admin_enqueue_scripts', 20 );
    remove_action( 'admin_footer', 'csf_set_icons' );
    remove_action( 'customize_controls_print_footer_scripts', 'csf_set_icons' );
  }

}
add_action( 'admin_init', 'wp_ulike_admin_init' );
```

It will inspire to you.

Regards

**Comment by Alimir** [comment]
@Codestar  Thanks for the great idea. I changed the code a bit and it worked fine.
And one more thing. In the new update, you have made changes to the set_options function that has caused problems. The following line:
https://github.com/Codestar/codestar-framework/blob/652bb67a88165c2828cc14954fbc9b57f086bc24/classes/options.class.php#L249

And the main problem is that in ajax request, if we add any custom filter on fields, it doesn't get the information. e.g.
https://github.com/Alimir/wp-ulike/blob/3efb57a29666f85c5a1ae7451b0807144d314713/admin/classes/class-wp-ulike-admin-panel.php#L94

I have added several filters above to be able to add options from the Pro version. Options are currently displayed, but are not saved. Do you have an idea for this problem?

**Comment by Alimir** [comment]
This was a problem with our Pro version and has now been fixed.

**Comment by Codestar** [comment]
Nice :wink:

**Comment by Codestar** [comment]
@Alimir 

Hey, A news about new version (2.1.6). You do not need to control admin scripts and styles. The framework files loads only when needed.

Regards

**Comment by Alimir** [comment]
@Codestar Good Job.
Also, please consider another very important issue in the next update:
There is an important bug in the "metabox-options.class.php" file and line 394. In this loop, if a post meta option does not have a value, it is still stored in the database, which increases the number of rows indiscriminately. It is better to use an empty condition in this line.

**Comment by Codestar** [comment]
@Alimir 

Actually it's not an issue. I had added a condition for empty value before but the users report me fields can not be cleared.

**Suppose** you have a text-field "Hello" If you remove this text the condition will detect it's empty and doesn't save. In this case we can not clear "Hello"

If it's a important issue for you. There is a "**action**" after save data.

```php
do_action( "csf_{$this->unique}_save_after", $data, $post_id, $this );
```

You can control the data and and make **delete_post_meta**. No worries about update and delete, it will be in seconds. It's backend already.

Regards
