### ISSUE TITLE
Multi Tabs Options

### ISSUE THREAD

**Issue by hyperionstudios** [Codestar/codestar-framework#570]
Hi, anyone can help here, how can I create a multi tabs options, like tabs on the left and each tab has its own options set. thanks

**Comment by varunsridharan** [comment]
@hyperionstudios are you looking for something like this ?
http://s.svarun.in/us

**Comment by hyperionstudios** [comment]
@varunsridharan yes my friend and thank you for the quick response.

**Comment by varunsridharan** [comment]
@hyperionstudios as of now there is no such option with codestar. but what you can do is that you can build your own field. or you can get the source which works with codestar from here

CSS / SCSS : https://github.com/wpsf/wpsf-dev/blob/master/assets/scss/vendor/fields/_tabs.scss
Javascript : https://github.com/wpsf/wpsf-dev/blob/master/assets/js/wpsf-framework.js#L1112-L1127
TAB FIELD CLASS : https://github.com/wpsf/wpsf-dev/blob/master/fields/tab/tab.php

**Comment by hyperionstudios** [comment]
@varunsridharan thank you but I can see if you stack the options the framework does that for you already, also you can add separators etc, I took it from the framework.config.php

**Comment by varunsridharan** [comment]
@hyperionstudios i am not sure what you mean by that. i forgot the show the config it. 
https://github.com/wpsf/wpsf-dev/blob/master/config/settings.php#L2961-L3057
