### ISSUE TITLE
Datepicker field issue

### ISSUE THREAD

**Issue by KolyaBiletskiy** [Codestar/codestar-framework#571]
Does not support multi-language.
Should be a field to select a date.
Thx.

**Comment by KolyaBiletskiy** [comment]
Can you fix it?

**Comment by Codestar** [comment]
We have not datepicker field yet?

**Comment by Codestar** [comment]
Hi,

Finally v2 released https://github.com/Codestar/codestar-framework/

Regards, Codestar
