### ISSUE TITLE
Codestar redirecting to options.php and failing to save

### ISSUE THREAD

**Issue by craigmartindale** [Codestar/codestar-framework#572]
Hi, I have recently updated my multsite to the latest Wordpress 4.9.6. Unfortunatley it seems to have broken the codestar framework. Whenever i try to save as an **admin** i get the following error:

![error](https://user-images.githubusercontent.com/6460276/40538944-1d7e8b2e-600b-11e8-900b-00838b4e2eec.png)

If i try to make changes using the **super admin**, it redirects to the options.php page, but doesnt save anything.

thanks,
Craig

**Comment by Codestar** [comment]
Hi,

It fixed in v2 https://github.com/Codestar/codestar-framework/

Regards, Codestar
