### ISSUE TITLE
How I Change Menu Icon

### ISSUE THREAD

**Issue by mianore** [Codestar/codestar-framework#573]
Hi everyone,

![framework](https://user-images.githubusercontent.com/39090697/40616149-9ab1e224-6292-11e8-94fa-2e431a27f599.png)

How i can change the menu icon in here? (Framework)

**Comment by obiPlabon** [comment]
@mianore Check this article https://bungeshea.com/change-wordpress-admin-menu-icons/ you'll get the idea of how to change the icon.
