### ISSUE TITLE
REQUIRED: Found add_meta_boxes in the file inc/cs-framework/classes/metabox.class.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.

### ISSUE THREAD

**Issue by nurulalam3s** [Codestar/codestar-framework#574]
After developing a WP theme using codestar-framework when I am checking it by Envato theme check plugin it's showing issue like below. Please check attached image for details.

![screenshot](https://user-images.githubusercontent.com/15118575/40777001-47e38198-64ee-11e8-8047-2993813ad420.png)

Could you please help how to fix that?

thanks

**Comment by varunsridharan** [comment]
@nurulalam3s Insteadof including this into your theme create a plugin for your theme which includes this codestar framework.

like

if your theme name is WCHELPER then create a plugin named wchelper-core and add cs to this. and force user using TMG Plugin installer.

**Comment by nurulalam3s** [comment]
Thanks @varunsridharan trying that

**Comment by nurulalam3s** [comment]
@varunsridharan 
I have tried that, there showing an error when trying to see live preview of the theme before plugin activation. i.e. **Fatal error: Uncaught Error: Call to undefined function cs_get_option()** 

thanks

**Comment by raajen** [comment]
@nurulalam3s 

You can use your own wrapper function inside your theme to retrieve the value from database. For example

`  function yourthemeslug_get_option( $option_name = '', $default = '' ) {
   defined( 'CS_OPTION') || define( 'CS_OPTION', 'your_database_slug' );
    $options = apply_filters( 'yourthemeslug_get_option', get_option( CS_OPTION ), $option_name, $default );
    if( ! empty( $option_name ) && ! empty( $options[$option_name] ) ) {
      return $options[$option_name];
    } else {
      return ( ! empty( $default ) ) ? $default : null;
    }
  }`

This will ensure that you don't need to rely upon the cs_get_option and your code won't break even if the plugin is not installed.
