### ISSUE TITLE
Can I embed the codestar-framework inside the theme?

### ISSUE THREAD

**Issue by egyflad** [Codestar/codestar-framework#575]
Can I embed the codestar-framework inside the theme?
Is this is ok with the themeforest rules ?!

**Comment by obiPlabon** [comment]
@egyflad you can embed Codestar Framework inside a theme but that won't be compatible with ThemeForest rules. That's why it's better to use as Plugin with TGMPA

**Comment by egyflad** [comment]
@obiPlabon 
Yes you are right, but when the theme first active without activating the codestart plugin the front page goes blank because it needs the options to set up the front page style and look, got it?

**Comment by raajen** [comment]
@egyflad 
As the default page view you get directly after installing the theme is your archive for blog posts.

So you can without worry use it. For theme options you can store the default options to the database. And then you can use your function to get your desired values.
