### ISSUE TITLE
preview for uploaded image

### ISSUE THREAD

**Issue by stivoox** [Codestar/codestar-framework#577]
Hi friends .
I just want to know how to add image preview for uploaded images with upload field .
regards

**Comment by stivoox** [comment]
Any response ?

**Comment by Codevz** [comment]
You should wait for v2 of codestar framework.

**Comment by stivoox** [comment]
any update?

**Comment by Codestar** [comment]
Hi,

Finally v2 release https://github.com/Codestar/codestar-framework/

Regards, Codestar
