### ISSUE TITLE
metabox product woocommerce

### ISSUE THREAD

**Issue by fmilansyah** [Codestar/codestar-framework#579]
I use metabox in woocommerce products but why it looks different

in product
![b](https://user-images.githubusercontent.com/33073897/41890407-94245906-7939-11e8-83bc-0d3d9302ede1.png)

in another post type
![c](https://user-images.githubusercontent.com/33073897/41890418-a1449c9a-7939-11e8-959a-2d2a3c1b518a.png)

**Comment by Codestar** [comment]
Yes looking some conflict with woocommerce styles vs jquery ui styles. I am using jquery ui there. i am not sure what can i do for this.

**Comment by fmilansyah** [comment]
Does CSF support Woocommerce? Please provide an example of how to print metabox data on the woocommerce product page

**Comment by raajen** [comment]
Obviously you can use Codestar to create fields for any post type. You've to modify the WooCommerce template or attach and function to any of the WooCommerce product page hook.
