### ISSUE TITLE
***Page selector item with multilang usage wrong running***

### ISSUE THREAD

**Issue by mertosman** [Codestar/codestar-framework#580]
I am using the Codestar framework page selector. However, when I select the page with the current language and save it with the other language, the value of all selectboxes is reset. Is there a way to use any object in other languages without being affected?

`array(
                    'id'      => 'box_page_id',
                    'type'    => 'select',
                    'class'   => 'chosen',
                    'options' => 'pages',
                    'multilang' => true,
                )`

**Screenshots for error:**

**Step 1:** I select the page with the page selector by default language option.
<img width="617" alt="bug1" src="https://user-images.githubusercontent.com/9094446/41973929-29913d48-7a1f-11e8-99e4-f015a8239f0b.png">

**Step 2:** This page is translated as "Workshops" page.
<img width="702" alt="bug2" src="https://user-images.githubusercontent.com/9094446/41973930-29c183b8-7a1f-11e8-8623-933f0ae3d7c1.png">

**Step 3:** When I select the English option from the top, the other setting is distorted.
<img width="632" alt="bug3" src="https://user-images.githubusercontent.com/9094446/41973931-29e7863a-7a1f-11e8-9aab-8b0f7453cbe0.png">

**Step 3:** When I save the value, when I return to the default language again, my first selected value is also distorted. At the same time this applies to all selectboxes.
<img width="626" alt="bug4" src="https://user-images.githubusercontent.com/9094446/41973932-2a153698-7a1f-11e8-868e-ceaf2d92ea21.png">

Because of this error, I have to reset the settings every time. Please help me how to solve the problem :(

**Comment by Codestar** [comment]
Hi,

Can you try this fixes, replace the your **/classes/options.class.php**

https://gist.github.com/Codestar/17ef87c79529fa66827d0e994b604e11

It works ? Report to me :+1:

**Comment by mertosman** [comment]
Hi,

Thanks for the answer. The problem seems to be solved when I change the code to the new one, but if I use the "multilang" parameter in the page selector, the values are not corrupted.


But if I do not use the "multilang" parameter, the default setting is broken as shown in the picture below.

![1](https://user-images.githubusercontent.com/9094446/42188447-95fce1ee-7e5c-11e8-87de-c299291df488.png)

But when I change the code in the image in **line 169** at **options.class.php**, the page selector works according to the standard language settings even if the language difference is changed. This was a temporary solution I found.

![2](https://user-images.githubusercontent.com/9094446/42188602-5640c2ae-7e5d-11e8-8bac-73c4ccad196f.png)
**('lang' => 'tr') is my default language.**

![3](https://user-images.githubusercontent.com/9094446/42188742-ed0449f4-7e5d-11e8-9931-e129afd9ff1f.png)


Polylang changes the link structure as the_permalink () even if there is no "Multilang" parameter. This solution was my job.

However, if the code you wrote is still "multilang" false, other page selector settings are broken when editing in other languages. They should not be activated. Another solution suggestion is that when I change the language, if the page has been translated, the existing page should be selected automatically.

**Comment by Codestar** [comment]
Hi,

Ops i saw a bug after your message in my coding here:

https://github.com/Codestar/codestar-framework/blob/761a59c1f586a1bbc2e89b3378b82803402a0ed2/classes/options.class.php#L346

Uh **( isset( $this->field['multilang'] ) )** this condition return **true** always, when you set **multilang => false**

Maybe you can try to update this line like this:

```php
return ( ! empty( $this->field['multilang'] ) ) ? cs_language_defaults() : false; 
```

**Comment by Codestar** [comment]
You're welcome,

#### About your last modification/solution

Actually best solution is set default lang via config array. Suppose you want to show all languages pages in selectbox, you can not it with your last modification. Take a look config array example for best way:

```php
// Select with Showing All Language Pages
array(
  'id'             => 'select_with_all_languages',
  'type'           => 'select',
  'title'          => 'Select with Showing All Language Pages',
  'options'        => 'pages',
  'default_option' => 'Select a page',
),

// Select with Multilingual 
array(
  'id'             => 'select_with_multilangual',
  'type'           => 'select',
  'title'          => 'Select with Multilangual',
  'options'        => 'pages',
  'default_option' => 'Select a page',
  'multilang'      => true,
),

// Select with Only [TR]
array(
  'id'         => 'select_with_language_tr',
  'type'       => 'select',
  'title'      => 'Select with Only [TR]',
  'options'    => 'pages',
  // this attribute will make same thing.
  'query_args' => array(
    'lang'     => 'tr'
  ),
  'default_option' => 'Select a page',
),

// Select with Only [EN]
array(
  'id'         => 'select_with_language_en',
  'type'       => 'select',
  'title'      => 'Select with Only [EN]',
  'options'    => 'pages',
  'query_args' => array(
    'lang'     => 'en'
  ),
  'default_option' => 'Select a page',
),
```

Why we do not using **query_args** param like this ? :)

**Comment by mertosman** [comment]
That's a great solution. Thank you very much for your interest. :)
