### ISSUE TITLE
Asking for upgrade

### ISSUE THREAD

**Issue by Tannwander** [Codestar/codestar-framework#582]
Hi! Greetings.
O got codestastar framework inside a theme package at Envato. Well, it's installed the 1.0.2 version
![codestar issue](https://user-images.githubusercontent.com/37716667/42406346-3ef0244c-817c-11e8-9e4b-b73ed3555f92.PNG)
 and asks for 1.0.9 and I see here that looks like there is not a new version.

However, no matter what I do. It keeks calling for the update, that I made a dozen times. So, I'm without a way to solve that without your help, that I say thanks in advance
Kindest regards

Cláudio Souza at https://soropositivo.org

**Comment by Codestar** [comment]
Hi,

Only click to update button... Because i think theme author making some changes on framework and updating it by yourself. it is normal... Sometimes i am fixing minor bug here and not updating framework for wait all fixes. said as me theme author adding this fixes for your theme...

Regards
