### ISSUE TITLE
Remove shortcode button

### ISSUE THREAD

**Issue by techtrekbd** [Codestar/codestar-framework#584]
hello, how can i remove "Add Shortcode" button from wordpress default Wysiwyg ?

http://prntscr.com/k3y813

**Comment by Codestar** [comment]
Add this code anywhere.

```php
define( 'CS_ACTIVE_SHORTCODE',   false );
```
or you can commented from cs-framework.php
```php
// cs_locate_template( 'config/shortcode.config.php'  );
```
