### ISSUE TITLE
Cant get values from cs_get_option()

### ISSUE THREAD

**Issue by murilozas** [Codestar/codestar-framework#587]
Hi,

Im using codestar as theme, and I don't know what I'm doing wrong. I read the documentation several times, and cant get values from echo cs_get_option() .

Test in many pages this default field 'section_1_text' from Page Metabox Options.

`<?php echo cs_get_option( 'section_1_text' ); ?>`

And not is printing.

**Comment by fmilansyah** [comment]
I also have the same problem

**Comment by raajen** [comment]
Metabox use case is different than that of theme options. The function you're trying only retrieves value from options table.. You can simply use::

`<?php
$meta = get_post_meta( get_the_ID(), '_custom_page_options', true );
echo $meta['section_1_text'];
?>`

Hope this will clear up.. 

BTW, Codestar doesn't provide any function to retrieve meta values for metaboxes. You can simply use the native `get_post_meta()`

**Comment by murilozas** [comment]
@raajen thank you.
