### ISSUE TITLE
Background Image Issue 

### ISSUE THREAD

**Issue by shanuak75** [Codestar/codestar-framework#589]
Hi Good work Codestar

My issue is not showing background image in style of div. plz reply 

**Codestar code here**

**My Code here**

`<section class="skillsarea" style="background-image:url('<?php echo cs_get_option( 'skills_background_image' ); ?>;');" id="skill">`

**Showing error in inspect element** 

`<section class="skillsarea" style="background-image:url('Array;');" id="skill">`

**Comment by raajen** [comment]
echo is for strings and number and Background gives you an array of options inside. 

Probably you should do `var_dump( cs_get_option( 'skills_background_image' );` to know the data that array is holding. So in you case it might be like this::

`<?php
$background = cs_get_option( 'skills_background_image' );
$image = isset( $background['image'] ) ? $background['image'] : false; 
<section class="skillsarea" <?php if( $image ) { echo 'style="background-image:url('.$image.');"; } ?> id="skill">`

Hope this will help you :)

**Comment by shanuak75** [comment]
Thanks Raajen

Very help full for me, it's working fine. thanks again.
