### ISSUE TITLE
Fontawesome 5 icons

### ISSUE THREAD

**Issue by Galibri** [Codestar/codestar-framework#593]
I am using font-awesome 5 in my theme and this is conflicting with the codestar framework icons. How will I replace the version 5?

**Comment by amitsarker89** [comment]
I am also facing the same issue. Maybe codestar will release new update.

**Comment by Galibri** [comment]
No update :(

**Comment by ashikur11** [comment]
any news for this?

**Comment by Galibri** [comment]
I did an update myself, but looking forward to the update from the author.

**Comment by Codestar** [comment]
Hi,

"Custom icon add" option added in v2. for eg see this: http://codestarframework.com/documentation/#/faq?id=how-to-add-custom-icons- Also this plugin version archived. Please continue from v2 https://github.com/Codestar/codestar-framework/

Regards, Codestar
