### ISSUE TITLE
How to create metabox without serialized meta key?

### ISSUE THREAD

**Issue by bilalmalkoc** [Codestar/codestar-framework#594]
I am trying integrate codestar framework to an old theme. But the theme has many meta keys and values. And all meta keys has unique id. For example:

Post 1:
'post_seasons' =>  '5'
'post_imdb' => '8'

But when i try create metabox it looks like this. I can't create single meta keys and meta values. 
<img src="https://i.imgur.com/ZhU33gE.png">

**Comment by Codevz** [comment]
Codestar framework saving meta box as an array, So for getting key's first you need to get whole meta box, then get any keys you want, e.g.

```PHP
$array = get_post_meta( $post->ID, 'postOptions', true ); // Get post meta

$post_seasons = $array['post_seasons']; // Get key value
$post_imdb = $array['post_imdb'];
```

**Comment by bilalmalkoc** [comment]
It is bad. Because i can't make a custom query by "meta_key greater than (>=)" with serialized meta values.
@Codevz

**Comment by bilalmalkoc** [comment]
Thank 👍 you saved my life 😄 @Codevz

**Comment by Codestar** [comment]
Hi,

Unserialized option added in v2 ? Also this plugin version archived. Please continue from v2 https://github.com/Codestar/codestar-framework/

Regards, Codestar
