### ISSUE TITLE
Image not inserted with 'cs_taxonomy_options'

### ISSUE THREAD

**Issue by dameer** [Codestar/codestar-framework#597]
The code...

```
add_action( 'cs_taxonomy_options', 'my_framework_taxonomy' );
function my_framework_taxonomy() {
	$options = array();
	$options[] = array(
		'id' => 'vh_taxo',
		'taxonomy' => 'category',
		'fields' => array(
			array(
				'id' => 'vh_taxo_bg_img',
				'type' => 'image',
				'title' => esc_attr__( 'Upload Image', 'domain' ), 
				'add_title' => esc_attr__( 'Add Photo', 'domain' ), 
			),
		),
	);
	return $options;
}
```

When you click on "Add Photo", Media Library modal is opened - which is OK. Once the image is selected and "Select" button pressed, Media Library modal doesn't get closed. Selected photo rather gets de-selected, "Select" button disabled and you get stuck - unless close button is clicked.

Any ideas what's going on?

**Comment by Codestar** [comment]
Hi,

Can you try this on v2 ? This plugin version archived. Please continue from v2 https://github.com/Codestar/codestar-framework/

Regards, Codestar
