### ISSUE TITLE
ID is not working

### ISSUE THREAD

**Issue by hmjobaer** [Codestar/codestar-framework#599]
$options[]      = array(
    'id'            => 'doctor_social_link_id',
    'title'         => 'Social Media group',
    'post_type'     => 'doctor',
    'context'       => 'normal',
    'priority'      => 'high',
    'sections'      => array(
  
      // begin section
      array(
        'name'      => 'Doctor option',
        'title'     => 'Doctor Option',
        'icon'      => 'dashicons-awards',
        'fields'    => array(
  
          // group
          array(
            'id'            => 'doctor_social_media',
             'type'  =>  'group',
            'title' =>  'add social link',
            'accordion_title' =>  '',
            'button_title'  =>  'add new Social link',
            'fields'  =>  array(
              array(
                'title' =>  'Socail Media Name',
                'type'  =>  'text',
                'id'  =>  'dr_social_media_name',
              ),array(
                'title' =>  'Socail link icon',
                'type'  =>  'icon',
                'id'  =>  'dr_social_icon',
              ),array(
                'title' =>  'Socal URL',
                'type'  =>  'text',
                'id'  =>  'dr_socail_url',
              ),
              )
          ),
          //end group

        ),
    ),
        // begin section
 
    ),
    //end section
  );

Query in page -> 

<?php $doctor = new WP_Query(array('post_type' => 'doctor', 'posts_per_page' => 8,)); ?>
	<?php if ( $doctor->have_posts() ) : while($doctor->have_posts()): $doctor->the_post();?>
	<?php $metador = get_post_meta(get_the_ID(), '_custom_meta_options', true ); ?>
					<div class="col-md-3 col-sm-6 col-xs-12">
						<div class="single-team-member">
		                    <figure class="img-box">
		                        <a href="#"><img src="<?php echo get_template_directory_uri(); ?>/images/team/team-1.jpg" alt=""></a>
		                        <div class="overlay">
		                            <div class="inner-box">
						<ul class="social">
						<?php 
							$post_meta = get_post_meta( get_the_ID(),'doctor_social_media', true );
							if ( !empty($post_meta) ) {
							foreach($post_meta as $meta_group ){?>
									<li><a href="<?php echo esc_url($meta_group['dr_socail_url']);?>"><i class="<?php echo esc_attr($meta_group['dr_social_icon']);?>"></i></a></li>
							<?php }	}?>
						</ul>
		                            </div>
		                                
		                        </div>
		                    </figure>
		                    <div class="author-info">
		                        <a href="<?php the_permalink(); ?>"><h4><?php echo get_the_title(); ?></h4></a>
		                        <p>

								<?php echo  $metador['_dr_designation']; ?>
								</p>
		                        <ul>
		                            <li><i class="<?php echo  $metador['_dr_degree_icon']; ?>"></i><?php echo  $metador['doctor_degree']; ?></li>
		                            <li><i class="<?php echo  $metador['doctor_contact_icon']; ?>"></i><a href="#"><?php echo  $metador['doctor_contact_way']; ?></a></li>
		                        </ul>
		                    </div>
		                        
		                </div>
					</div>
	<?php endwhile; endif;?>
	<?php wp_reset_query(); ?>

**Comment by stefan25w** [comment]
`$post_meta = get_post_meta( get_the_ID(),'doctor_social_media', true );` needs to be `$post_meta = get_post_meta( get_the_ID(),'doctor_social_link_id', true ); `. This will give you an array of fields
