### ISSUE TITLE
How can I change the the framework page header title?

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#6]
Hi, 
First of all it's a great work, All the features that I was looking for year , you guys make it true. Thank you guys. 

I read the all of the documentation and didn't find any option to change the option page header title. Am I permitted to doing that? If yes can you guys tell me how can I do that without change in the core file.

http://puu.sh/eWTRl/8b1c461afd.png

Filter reference will be great.

Thanks
Imran khan
WpBean.com

**Comment by Codestar** [comment]
Hi,

Yes, I did not put a filter for this, because this is my promotion. You can change it from php file directly. :)

**Comment by schiavassa** [comment]
Hi Codestar,

Are you Ok with people re-branding the framework if we give proper credits otherwise?

Cheers!

**Comment by Codestar** [comment]
Hi @schiavassa

Yes you can do it but please make sure you give proper credit to us.

**Comment by Codestar** [comment]
@schiavassa @wpbean 

Now you can change it from settings.. for eg:

```php
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>', // NEW PARAM
);
```
