### ISSUE TITLE
customize does not work

### ISSUE THREAD

**Issue by zhw2590582** [Codestar/codestar-framework#60]
In the Twenty Fifteen. if define( 'CS_ACTIVE_CUSTOMIZE',  true );  customize interface is empty.
 if define( 'CS_ACTIVE_CUSTOMIZE',  false ); It's ok.

**Comment by Codestar** [comment]
Hi, I tested it on TwentyFifteen now, it is working normally ? I am seeing customize panel.

![support_12-17-56](https://cloud.githubusercontent.com/assets/1313301/6992135/ae8ad34a-dac4-11e4-9d5f-204285aeb1a2.png)

**Comment by zhw2590582** [comment]
Strange, I tried three sites are not displayed properly. I will try to find out the cause of the error, thank you.

**Comment by Codestar** [comment]
Interesting.. if you give any error message, copy paste here ;)
