### ISSUE TITLE
How to enable to disable jquery codes

### ISSUE THREAD

**Issue by amitsarker89** [Codestar/codestar-framework#600]
Hello,

I am using switcher options for enable or disable a jquery code. The problem is I am unable to use on jquery file. 
```
if (cs_get_option('lora_active_backtotop')){
jquery code here....
}
```
How to fix it?

**Comment by JoeSz** [comment]
My framework has no "cs_get_option", you have to use the WordPress get_option('your-slug') <- this probably your plugin slug, to get the options. 
- for "menu" use:
Eg.:
`$my_options = get_option('my-plugin-slug');
if ( $my_options['lora_active_backtotop'] ) {
    // code...
}`
You can check if you get the right options with:
`var_export( $my_options, true );`

- for "meta" use:
`get_post_meta( get_the_ID(), 'my-plugin-slug', true );`

**Comment by amitsarker89** [comment]
Thank you @JoeSz 

So, how I can get value from switcher and then use it inside jquery codes?

**Comment by JoeSz** [comment]
Sorry I had misunderstud,
you could use/try:
```php
$my_options = get_option('my-options-slug');
if ( $my_options['lora_active_backtotop'] ) {
    // code...
}
```
You can check if you get the right options with:
```php
var_export( $my_options, true );
```

**Comment by amitsarker89** [comment]
I used this code in my jquery custom codes.
But getting this error http://prntscr.com/kq1ozu
http://prntscr.com/kq1pg7

**Comment by JoeSz** [comment]
get_options is PHP not JavaScript,

´´´php
$my_options = get_option('my-options-slug');
if ( $my_options['lora_active_backtotop'] ) {
    ?>
    // JavaScript code here, maybe you put this in the footer?
    <?php
}
´´´

As I understand, "JavaScript code" is a defuniction for a function to scolltotop not a function call.
LORA.scrollTop() <- here you already calling a function.

**Comment by JoeSz** [comment]
I can imagine the following:

herader.php
```php
$my_options = get_option('my-options-slug');
if ( $my_options['lora_active_backtotop'] ) {
    ?>
    <div id="scrolltotop" style="position:absoulte;bottom:100px;right:100px;background:red;border-radius:3px;z-index:100;">TOP</div>
    <?php
}
```
footer.php
```php
$my_options = get_option('my-options-slug');
if ( $my_options['lora_active_backtotop'] ) {
    ?>
    <script>
    $( '#scrolltotop' ).on( 'click', function() {
        $('html, body').animate({scrollTop:0}, 400);
    });
    </script>
    <?php
}
```

**Comment by amitsarker89** [comment]
Thank you for your excellent helpful suggestions.
Can you suggest me how I can active jquery codes from js file using codestar options (switcher) ?

**Comment by JoeSz** [comment]
If you want your options "see" in your jQuery/JavaScript file, you need to "transfer" your options, you could use the `wp_localize_script` https://codex.wordpress.org/Function_Reference/wp_localize_script or pass with a "data", like: 
```php
$my_options = get_option('lora-framework');
?>
<div id="scrolltotop" data-backtotop="<?php echo $my_options['lora_active_backtotop']; ?>">TOP</div>
<?php
```

then you can use it in your JavaScript file:
```javascript
var scrolltotop = $( '#scrolltotop' ).data( 'scrolltotop' ); // true/false or yes/no <- depends how you saved it.
```

**Comment by JoeSz** [comment]
after that, you colud use 
```javascript
if ( scrolltotop ) {
    // your JavaScript code in your JavaScript file
}
```

**Comment by amitsarker89** [comment]
Thanks @JoeSz 
Finally I fixed it http://prntscr.com/kq22z6.
You are very helpful.

**Comment by JoeSz** [comment]
Your welcome :)
