### ISSUE TITLE
how can i get output of select option

### ISSUE THREAD

**Issue by riponhossainchopol** [Codestar/codestar-framework#601]
// begin: a section
    array(
      'name'  => 'section_1',
      'title' => 'animation',
      'icon'  => 'fa fa-cog',

      // begin: fields
      'fields' => array(

        // begin: a field
        array(
          'id'    => '_post_animation',
          'type'  => 'select',
          'title' => 'select post animation type',
          'options'    => array(
                        'down'      => 'fadeInDown',
                        'right'     => 'fadeInRight',
                        'up'        => 'fadeInUp',
                        'left'      => 'fadeInLeft',
                      ),
        ),
        // end: a field

      ), // end: fields
    ), // end: a section

**Comment by Codevz** [comment]
Is this theme options or post meta box?

**Comment by riponhossainchopol** [comment]
metabox

**Comment by Codevz** [comment]
For getting meta box, first you need to get whole meta box value by primary ID then get inner keys for e.g.

```PHP
$meta_box = get_pot_meta( $post->ID, 'prefix_my_meta_box', true );
$post_animation = empty( $meta_box['_post_animation'] ) ? '' : $meta_box['_post_animation'];
```

**Comment by riponhossainchopol** [comment]
what if in theme option?

**Comment by Codevz** [comment]
Theme option you can get it like this: 

`echo cs_get_option( 'unique_option_name' );`

and in customize you can get like this: 

`echo cs_get_customize_option( 'text_option' );`

You can find all this functions and example's in documentation: http://codestarframework.com/documentation/#notice
