### ISSUE TITLE
Codestar framework export and using One Click Demo Import

### ISSUE THREAD

**Issue by amitsarker89** [Codestar/codestar-framework#602]
Hello,

I used Codestar framework for theme options. Now I want to make theme demo importer option using "One Click Demo Import" plugin.
I can not see any export option on codestar. So, what I will do?
Also, I am seeing that redux option can be exported and there is a option in one click demo import plugin-
http://prntscr.com/kq74o4
Please help me.

**Comment by Codestar** [comment]
Take a look this https://github.com/Codestar/codestar-framework/issues/471
