### ISSUE TITLE
Select2 posts with ajax

### ISSUE THREAD

**Issue by bilalmalkoc** [Codestar/codestar-framework#603]
Is it possible to using ajax for select2 posts? Because i am using this following code 10 times. So page loads too slow. Select2 dropdown has 1000+ post and it loads 1000+ posts 10 times.

> <?php 
array(
	'id'         => 'slider3Posts',
	'type'       => 'select',
	'title'      => 'Choose Posts',
	'options'    => 'posts',
	'class'      => 'chosen',
	'attributes' => array(
		'data-placeholder' => 'Please choose your own posts...',
		'multiple'         => 'multiple',
	),
	'query_args' => array(
		'sort_order'     => 'ASC',
		'sort_column'    => 'post_title',
		'posts_per_page' => -1,
	),
),
?>

**Comment by Codevz** [comment]
I had the same problem about 2 years ago and solved it by my own param  https://github.com/Codestar/codestar-framework/issues/389, I hope @Codestar add a built-in autocomplete param in the next updates.

**Comment by bilalmalkoc** [comment]
@codevz i am using your solution. Thank you. I think @codestar never update anymore.
