### ISSUE TITLE
connect with CSS

### ISSUE THREAD

**Issue by SamuvelRamesh** [Codestar/codestar-framework#604]
hello,
i could built a framework successfully  from my wordpress back-end but still i do not understand how can i set up or assign  with these css values to my site? anyone can help me to guide coding part ?
let me know i need to create .php file and assign these values using php to convert css styles? or do you know any other options ? 

Example code i post below, is this correct ? 
Framework.config.php
 array(
      'id'      => 'color_picker_1',
      'type'    => 'color_picker',
      'title'   => 'Color Picker',
      'default' => '#3498db',
    ),

style.php
$color_picker_1 = cs_get_option( 'color_picker_1' );
<style>
color:<?php $color_picker_1; ?>
<?php  ?>
</style>

please help me to solve this one, and i would like to know how to assign fonts style too.
thank you

**Comment by NeverDev** [comment]
So it's the way you need to use this inside template but there is a way to generate a css file when you save the options.

The dynamic css file way : #307 

<?php
$color_picker_1 = cs_get_option( 'color_picker_1' );
?>

<style> 
.element{
    color: <?= $color_picker_1; ?>;
}
</style>

**Comment by NeverDev** [comment]
`<?php $color_picker_1 = cs_get_option( 'color_picker_1' ); ?>

<style> color: <?= $color_picker_1; ?></style>`

**Comment by Codestar** [comment]
Hi,

I added custom css output feature in v2. Also this plugin version archived. please continue from v2 https://github.com/Codestar/codestar-framework/
