### ISSUE TITLE
font size, line height & color field in typography

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#61]
Hi, I found no font size, line height & font color field in typography option. These are very useful. You may consider to add these fields in typography

**Comment by Codestar** [comment]
Hi, Yes it will be useful but this is a lightweight framework. it is simple :) No complicated options.

**Comment by sabuz** [comment]
:disappointed:

**Comment by Codestar** [comment]
Ok ok :) I noted this. i will think this feature for next updates for you :+1:

**Comment by sabuz** [comment]
:smiley:
Thank You!

**Comment by sabuz** [comment]
How is this?

<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.
/**
 *
 * Field: Typography Extended
 *
 * @since 1.0.0
 * @version 1.0.0
 *
 */
class CSFramework_Option_typography_extended extends CSFramework_Options {

  public function __construct( $field, $value = '', $unique = '' ) {
    parent::__construct( $field, $value, $unique );
  }

  public function output() {

    echo $this->element_before();

    $defaults_value = array(
      'family'  => 'Arial',
      'variant' => 'regular',
      'font'    => 'websafe',
      'size'    => '',
      'height'  => '',
    );

    $default_variants = apply_filters( 'cs_websafe_fonts_variants', array(
      'regular',
      'italic',
      '700',
      '700italic',
      'inherit'
    ));

    $websafe_fonts = apply_filters( 'cs_websafe_fonts', array(
      'Arial',
      'Arial Black',
      'Comic Sans MS',
      'Impact',
      'Lucida Sans Unicode',
      'Tahoma',
      'Trebuchet MS',
      'Verdana',
      'Courier New',
      'Lucida Console',
      'Georgia, serif',
      'Palatino Linotype',
      'Times New Roman'
    ));

    $value         = wp_parse_args( $this->element_value(), $defaults_value );
    $family_value  = $value['family'];
    $variant_value = $value['variant'];
    $is_variant    = ( isset( $this->field['variant'] ) && $this->field['variant'] === false ) ? false : true;
    $is_chosen     = ( isset( $this->field['chosen'] ) && $this->field['chosen'] === false ) ? '' : 'chosen ';
    $google_json   = json_decode( cs_filesystem()->get_contents( CS_URI .'/fields/typography/google-fonts.json' ) );
    $chosen_rtl    = ( is_rtl() && ! empty( $is_chosen ) ) ? 'chosen-rtl ' : '';

    if( ! empty( $google_json ) ) {

      $googlefonts = array();

      foreach ( $google_json->items as $key => $font ) {
        $googlefonts[$font->family] = $font->variants;
      }

      $is_google = ( array_key_exists( $family_value, $googlefonts ) ) ? true : false;

      echo '<label class="cs-typography-family">';
      echo '<select name="'. $this->element_name( '[family]' ) .'" class="'. $is_chosen . $chosen_rtl .'cs-typo-family" data-atts="family"'. $this->element_attributes() .'>';

      do_action( 'cs_typography_family', $family_value, $this );

      echo '<optgroup label="'. __( 'Web Safe Fonts', CS_TEXTDOMAIN ) .'">';
      foreach ( $websafe_fonts as $websafe_value ) {
        echo '<option value="'. $websafe_value .'" data-variants="'. implode( '|', $default_variants ) .'" data-type="websafe"'. selected( $websafe_value, $family_value, true ) .'>'. $websafe_value .'</option>';
      }
      echo '</optgroup>';

      echo '<optgroup label="'. __( 'Google Fonts', CS_TEXTDOMAIN ) .'">';
      foreach ( $googlefonts as $google_key => $google_value ) {
        echo '<option value="'. $google_key .'" data-variants="'. implode( '|', $google_value ) .'" data-type="google"'. selected( $google_key, $family_value, true ) .'>'. $google_key .'</option>';
      }
      echo '</optgroup>';

      echo '</select>';
      echo '</label>';

      if( ! empty( $is_variant ) ) {

        $variants = ( $is_google ) ? $googlefonts[$family_value] : $default_variants;
        $variants = ( $value['font'] === 'google' || $value['font'] === 'websafe' ) ? $variants : array( 'regular' );

        echo '<label class="cs-typography-variant">';
        echo '<select name="'. $this->element_name( '[variant]' ) .'" class="'. $is_chosen . $chosen_rtl .'cs-typo-variant" data-atts="variant">';
        foreach ( $variants as $variant ) {
          echo '<option value="'. $variant .'"'. $this->checked( $variant_value, $variant, 'selected' ) .'>'. $variant .'</option>';
        }
        echo '</select>';
        echo '</label>';

      }

      echo '<label class="cs-typography-size">';
      echo '<input type="number" name="'. $this->element_name( '[size]' ) .'" value="'. $value['size'] .'" placeholder="size" style="width: 80px;height: 28px;vertical-align: middle;" />';
      echo '</label>';

      echo '<label class="cs-typography-height">';
      echo '<input type="number" name="'. $this->element_name( '[height]' ) .'" value="'. $value['height'] .'" placeholder="height" style="width: 80px;height: 28px;vertical-align: middle;" />';
      echo '</label>';

      echo '<input type="text" name="'. $this->element_name( '[font]' ) .'" class="cs-typo-font hidden" data-atts="font" value="'. $value['font'] .'" />';

    } else {

      _e( 'Error! Can not load json file.', CS_TEXTDOMAIN );

    }

    echo $this->element_after();

  }

}

And the parser:
function cs_typography_parser( $typography ) {

  $out  = array();
  $font = cs_get_option( $typography );

  // family
  $out['family'] = $font['family'];

  // weight
  $weight = preg_replace( '/\D/', '', $font['variant'] );
  $out['weight'] = ( ! empty( $weight ) ) ? $weight : 'normal';

  // style
  $style = preg_replace( '/[0-9]/', '', $font['variant'] );
  $out['style'] = ( ! empty( $style ) && $style !== 'regular' ) ? $style : 'normal';

  // size
  $out['size'] = $font['size'].'px';

  // line height
  $out['line-height'] = $font['height'].'px';

  return $out;
}

**Comment by Codestar** [comment]
Yes it is great ;) also you are on right way, use extended option fields for custom requests :100:

**Comment by sabuz** [comment]
Thank You @Codestar !
Google font is not enqueuing. How to do this?

**Comment by Codestar** [comment]
Hi, You mean this ?

```
if ( ! function_exists( 'cs_wp_enqueue_scripts' ) ) {
  function cs_wp_enqueue_scripts() {

    $enqueue_fonts  = array();
    $google_fonts   = array();
    $google_fonts[] = cs_get_option( 'unique_typography_1' );
    $google_fonts[] = cs_get_option( 'unique_typography_2' );

    if ( ! empty( $google_fonts ) ) {
      foreach ( $google_fonts as $font ) {
        if( isset( $font['font'] ) && $font['font'] == 'google' ) {
          $variant = ( isset( $font['variant'] ) && $font['variant'] !== 'regular' ) ? ':'. $font['variant'] : '';
          // $variant = ':300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'; // you can use this. here is including all variants
          $enqueue_fonts[] = $font['family'] . $variant;
        }
      }
    }

    wp_enqueue_style( 'cs-google-fonts', esc_url( add_query_arg( 'family', urlencode( implode( '|', $enqueue_fonts ) ) , '//fonts.googleapis.com/css' ) ), array(), null );

  }
  add_action( 'wp_enqueue_scripts', 'cs_wp_enqueue_scripts' );
}
```

**Comment by sabuz** [comment]
Yes!!!
Thank You @Codestar !

**Comment by Codestar** [comment]
You're welcome :+1:
