### ISSUE TITLE
create Customizer Live Preview not working 

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#610]
Hi,
I am trying to create customizer live preview. I followed fully documentation which you provided but it's not working.  when i add field then it say "This field class is not available!" i added field in metabox Below:

`	array(
									'name'          => 'codestar_color_picker',
									'default'       => '#3498db',
									'transport'     => 'postMessage', // Default Transport type for each setting is refresh, however, if you want to create live preview customization you can change it to 'postMessage'. Take a look at the example, we added trasport type to the color picker control.
									'control'       => array(
										'type'        => 'cs_field',
										'options'     => array(
											'type'      => 'color_picker',
											'title'     => 'Color Picker Field',
										),
									),
								),` 

But Showing in backend "This field class is not available!"
can you please help. its very need to create live preview in backend

**Comment by Codestar** [comment]
Actually this is old usage. I think you are using v1.4 pro but trying v1.0 config array?  Please check v1.4-pro customizer example file.
