### ISSUE TITLE
Fatal error: during Activating plugin. CF version  pro-1.4

### ISSUE THREAD

**Issue by codecans** [Codestar/codestar-framework#611]
Hi, I have created a plugin in localhost. its working fine in localhost. But when i upload plugin live then i got a error during activating plugin. 

This page isn’t working
wpcodestar.pressnews24.com is currently unable to handle this request.
HTTP ERROR 500

But After I set debug true in wp-config then i got Fatol error:

Fatal error: Uncaught Error: Call to undefined function wp_get_current_user() in /home/jtrpilcs/wpcodestar.pressnews24.com/wp-includes/capabilities.php:598 Stack trace: #0 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-includes/functions.php(2577): current_user_can('unfiltered_html') #1 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-includes/formatting.php(1821): get_allowed_mime_types() #2 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-content/plugins/ultimate-team-member/options/classes/setup.class.php(79): sanitize_file_name('homejtrpilcswpc...') #3 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-content/plugins/ultimate-team-member/options/classes/setup.class.php(27): CSF->constants() #4 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-content/plugins/ultimate-team-member/options/classes/setup.class.php(36): CSF->__construct() #5 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-content/plugins/ultimate-team-member/options/classes/setup.class.php(121): CSF::instance() #6 /home/jtrpilcs/wpcodestar.pressnews24.com/wp-content/plugins/ulti in /home/jtrpilcs/wpcodestar.pressnews24.com/wp-includes/capabilities.php on line 598

Both screenshot are attached 
![error](https://user-images.githubusercontent.com/17748939/47260806-0bc6a580-d4e4-11e8-95b8-9fec584257f8.png)
![fatal-error](https://user-images.githubusercontent.com/17748939/47260807-0bc6a580-d4e4-11e8-8f96-071c39ca14ee.png)

its a major issue that's why i can't work. i am using wordpress version 4.8.9
please give a solution.
thanks
Rakibur Rahman Sagar

**Comment by Codestar** [comment]
I've reply your email bro.. let's go there.

**Comment by Codestar** [comment]
As you know this plugin version archived. please continue via v2 https://github.com/Codestar/codestar-framework/
