### ISSUE TITLE
return value in empty field

### ISSUE THREAD

**Issue by groupunknown** [Codestar/codestar-framework#618]
how can I return a value when the field is empty, I tried to use the if else but it did not work.

Ex:
`<?php if($synopsis = get_post_meta($post->ID, 'description', true )) { echo $synopsis['synopsis']; } else { echo 'not found...'; } ?>`

the idea is simple, if during the query the field is empty, it adds the text from the else field.

**Comment by Codestar** [comment]
You can use like this.

```php
$synopsis = get_post_meta($post->ID, 'description', true );

if( $synopsis['synopsis'] ) {
  echo $synopsis['synopsis'];
} else {
  echo 'not found...';
} 
```
btw. V2 released: https://github.com/Codestar/codestar-framework
