### ISSUE TITLE
codestar framework compatibility gutenberg ? 

### ISSUE THREAD

**Issue by nuralamsiddikashik** [Codestar/codestar-framework#619]
**I really want to know. codestar framework compatibility Gutenberg?**

**Comment by Codestar** [comment]
Which part you need to compatibility Gutenberg? It is a option framework.

**Comment by Ansif** [comment]
Hi @Codestar, 

Hope you're doing good.

I've checked all are fine from Codestar to Gutenberg. But, only one thing is Add Shortcode button.

Previously it was:
![screenshot 2018-12-12 at 11 06 01 am](https://user-images.githubusercontent.com/5621180/49849114-1f183200-fdfe-11e8-9f05-536ba16c7667.png)

But, now:
![screenshot 2018-12-12 at 11 06 13 am](https://user-images.githubusercontent.com/5621180/49849121-24757c80-fdfe-11e8-8c87-d093f0107e9f.png)

Regards,
Ansif

**Comment by Codestar** [comment]
@Ansif Yes only shortcoder framework need to integration. Actually, as you know, Gutenberg is very new, yet. I am following the common ideas. It will be come soon :)

**Comment by Ansif** [comment]
@Codestar That's great! ❤️

**Comment by Codestar** [comment]
@Ansif You're welcome :)

**Comment by nriddhi** [comment]
Hello, @Codestar , when will be the next update, there is a bug in wysiwyg in group field and also there is no oembed field for video type input? when you will update it?

**Comment by nriddhi** [comment]
Hello, @Codestar  , when will be the next update, there is a bug in wysiwyg in group field and also there is no oembed field for video type input? when you will update it? will be very thankful

**Comment by Codestar** [comment]
V2 released: https://github.com/Codestar/codestar-framework
