### ISSUE TITLE
Codestar plugin conflicting with Post SMTP

### ISSUE THREAD

**Issue by jasonTol** [Codestar/codestar-framework#62]
I am getting the following error
"Postman: wp_mail has been declared by another plugin or theme, so you won't be able to use Postman until the conflict is resolved."

I am currently using your plugin which is required to edit the shopstore theme correctly. I have deactivated all my other plugins and found Codestar Framework version 1.0.1 is the cause. Is there some way of fixing this? I have tried a number of other SMTP plugins but none work like Post SMTP.

**Comment by Codestar** [comment]
**Codestar Framework version 1.0.1**

Are you sure for this version ? I think you are using older framework. Codestar Framework old version deprecated. We do not support old version, you should to move 2.0.

Regards, Codestar

**Comment by jasonTol** [comment]
Ah ok yes. I have downloaded the new version but it is not showing the options menu for the shopstore theme from athemeart. Not sure how to set that up so I'll have to message them i guess.
Thanks for your help

**Comment by Codestar** [comment]
Hi, v1 is not compatible with v2 totally. There is a major update. Yes contact the ShopStore owner, may be there is another conflict.
