### ISSUE TITLE
Saving theme options

### ISSUE THREAD

**Issue by gautamna** [Codestar/codestar-framework#620]
I have noticed that while saving the theme options, codestar saves all of the options including the one from other hidden tabs. I only want to save the options visible in the active tab. I am using 'ajax_save" set to false.

Also when you are not using the ajax_save setting, there is no way the user can be informed about if the options have been saved, ideally it should show a successful message.

Could you please show me how to achieve these two objectives? Thanks.

**Comment by Codestar** [comment]
Hi @gautamna 

This issue fixed in v2. and it released from main repo https://github.com/Codestar/codestar-framework also ajax_save is optional now. see the documentation.

Regards, Codestar
