### ISSUE TITLE
How to use Multiple Header and Footer and Layout? SOS

### ISSUE THREAD

**Issue by Muhendis85** [Codestar/codestar-framework#621]
Hi, I am new on Codestar framework. I want use and select  3 headers and footer from Theme Options.  I could not find any document,  anyone help me? thanx

**Comment by Muhendis85** [comment]
İ found already,  Codestar framework very  good, but  githup group not helping to new persons

**Comment by Codestar** [comment]
Hi sorry, it is not possible... btw v2 released: https://github.com/Codestar/codestar-framework
