### ISSUE TITLE
Any example to use "SELECT WITH POSTS"

### ISSUE THREAD

**Issue by asufian97** [Codestar/codestar-framework#623]
$metaboxes[] = array(
        'id'        => 'brifa-section-blog',
        'title'     => __( 'Sections', 'brifa' ),
        'post_type' => 'section',
        'context'   => 'normal',
        'priority'  => 'default',
        'sections'  => array(
            array(
                'name'     => 'brifa-page-sections-section-one',
                'icon'   => 'fa fa-image',
                'fields' => array(
                    array(
                        'id'    => 'blog_section',
                        'title'   => __( 'Select sections', 'brifa' ),
                        'type'    => 'group',
                        'button_title'    => __('New Section','brifa'),
                        'accordion_title' => __('Add New Section','brifa'),
                        'fields'=>array(
                            array(
                                'id'    => 'blog_post',
                                'type'  => 'select',
                                'title'=>'select a Post',
                                'options'=>'posts',
                                'query_args'     => array(
                                    'post_type'    => 'post',
                                    'posts_per_page'=>-1,
                                    'orderby'      => 'post_date',
                                    'order'        => 'DESC',
                                ),
                            ),
                        )
                    ),
                )
            ),

        )
    );

    return $metaboxes;

######
how can i show this on my custom page?

**Comment by asufian97** [comment]
no one? :-1:

**Comment by Codestar** [comment]
V2 released: https://github.com/Codestar/codestar-framework and you can see new documentation for select with posts.
