### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mehmetsarr** [Codestar/codestar-framework#624]
Hi, how can I show in the theme of codestar framework ta image? I wonder how the application?

**Comment by Muhendis85** [comment]
mehmet  kardeş, tam olarak  ne yapmak istiyorsun

**Comment by mehmetsarr** [comment]
Hocam çok şükür Türkçe bilen biri çıktı ☺️.
Ben codestar daki image(resimleri) leri tema da göstermek istiyorum. Kullanım diye bazı kodlar vermiş ama yapamadım M.

**Comment by Muhendis85** [comment]
2-  echoyu böyle yapıyorsun.

<?php 
	 
		$resim_1 = cs_get_option( 'aris_rst_m1_tab_bg' );
		$attachment_id_rst_m1_bg = wp_get_attachment_image_src( $resim-1, 'full' );
		echo 'background: url( '. $attachment_id_rst_m1_bg['0'] .');'	 
	 ?>

**Comment by mustafakucuk** [comment]
Merhabalar,

Öncelikle şu şekilde görsel alanınızın olduğunu varsayalım.

```array(
  'id'        => 'image_2',
  'type'      => 'image',
  'title'     => 'Image with Custom Title',
  'add_title' => 'Add Logo',
),
```

Image tipinden bize sadece görsel ID'si geldiği için `wp_get_attachment_image_src` fonksiyonuyla gelen görsel ID'sinin bağlantısını alıyoruz.

```
$image_id = cs_get_option( 'image_2' ); // ilgili alanın ID'si.
$attachment = wp_get_attachment_image_src( $image_id, 'full' ); // Gelen ID'ye göre görsel bağlantısını al
var_dump( $attachment ); // Ekrana yaz.
```

**Comment by Muhendis85** [comment]
kardeş php taglarının içine al. burad php tagını  siliyor githup
	 
		$image_id_rst_m1_bg = cs_get_option( 'aris_rst_m1_tab_bg' );
		$attachment_id_rst_m1_bg = wp_get_attachment_image_src( $image_id_rst_m1_bg, 'full' );
		echo 'background: url( '. $attachment_id_rst_m1_bg['0'] .');'

**Comment by Muhendis85** [comment]
aynen böyle

**Comment by mehmetsarr** [comment]
Tamam hocam bir deneyeyim sağolun

**Comment by mehmetsarr** [comment]
hocam denedim ama olmadı. Kodlar aşağıdaki gibi nerde hata yapıyorum.

		
      <div class="panel panel-default text-center hidden-xs" style="background-color:#0d7cda;">

<?php echo var_dump( $attachment_bg ); ?>
    <a href="<?=cs_get_option("mesaj_link")?>"> <img src="<?php $image_bg = cs_get_option( 'baskan_resim' ); ?>"  style="max-height:300px;" class="img-responsive"/></a>
    <?php $attachment_bg = wp_get_attachment_image_src( $image_bg, 'full' ); ?>

**Comment by Muhendis85** [comment]
array(
  'id'    => 'baskan_resim',
  'type'  => 'background',
  'title' => 'Başkan Resim Ekle',
),

sayfaya aşağıdaki kodu ekle

<img src= "<?php echo cs_get_option("baskan_resim"); ?>"
