### ISSUE TITLE
Page Preloader Switcher (On/Off) Value?

### ISSUE THREAD

**Issue by mohmadhabib** [Codestar/codestar-framework#63]
I Would like to ask if anybody could Let me know how to get Value of Switcher:
the Option in Option Panel is:
`array(
  'id'    => 'opt-switcher-1',
  'type'  => 'switcher',
  'title' => 'Switcher',
  'default' => 'true',
),`

and i want to get the Output to insert the Preloader Code in the Theme
Pure HTML Preloader Code:
`<div class="preloader">
        <div class="loader">
            <div class="ytp-spinner">
                <div class="ytp-spinner-container">
                    <div class="ytp-spinner-rotator">
                        <div class="ytp-spinner-left">
                            <div class="ytp-spinner-circle"></div>
                        </div>
                        <div class="ytp-spinner-right">
                            <div class="ytp-spinner-circle"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>`

I Tried this code but no Luck:

1. ` $my_options = get_option( 'opt-switcher-1' ); echo $my_options['opt-switcher-1'];`

In Simple Words
**I need the user to Enable or Disable the Preloader, if set to On that will Insert the Code to the theme, if Set to Off that will hide/Comment/Delete the Code from theme**

Thanks in Advance to your hard-working to answer our Questions :)

**Comment by Codestar** [comment]
Hi,

You should to read documentation as details. Ok Let me explain. All options are saving in database as one option. And you should to call this option group like this:

```php
$all_options = get_option( 'WRITE_HERE_YOUR_FRAMEWORK_PREFIX_ID' );
// for eg: $prefix = '_prefix_my_options'; this is demo database prefix id. "_prefix_my_options"
```

then, you can get any option like this:
```php
$all_options = get_option( '_prefix_my_options' );

echo $all_options['opt-switcher-1'];

// Another example for If condition.
if( ! empty( $all_options['opt-switcher-1'] ) ) {
?>
  <div class="preloader-thing">Do stuff.</div>
<?php
}
```
Regards

**Comment by mohmadhabib** [comment]
I Realy Appreciate Your Kind Response, You saved my Day, Actually, I'll take a deep look on the Documentations, I'm Really sorry for my Dump Questions :)

**Comment by Codestar** [comment]
You're welcome :)
