### ISSUE TITLE
Confusion about multiple dependency

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#63]
As i think, multiple dependency is working with "&&" operator. What to do if I want to work with "||" operator?

Consider the following code: 
```
array(
  'id'           => 'dummy_10',
  'type'         => 'notice',
  'class'        => 'info',
  'content'      => 'Done, Multiple Dependencies worked.',
  'dependency'   => array( 'dep_10|dep_11|dep_12', '==|==|==', 'true|true|true' ),
),
```
Here, if any condition goes to false, the field will not show up. If I want to show this field if any one condition goest to true.....then what to do?

**Comment by Codestar** [comment]
Hi,

```
array(
  'id'           => 'dummy_10',
  'type'         => 'notice',
  'class'        => 'info',
  'content'      => 'Done, Multiple Dependencies worked.',
  'dependency'   => array( 'dep_10|dep_11|dep_12', '==|==|any', 'true|true|true,false' ),
),
```

You mean this ? we are using ```any``` ```value1,value2,value3``` for any value check ? or i did not understand your question .?

**Comment by sabuz** [comment]
Hi!
My question is if any of dep_10, dep_11 or dep_12 goes true, I want to show this field. Then how to do it?

**Comment by Codestar** [comment]
Hi,
hmm, i understand. hmm no it is not possible :)
