### ISSUE TITLE
Group field without "add new" option.

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#64]
Hi!
Do you have any plan to add section like redux or vafpress? This is useful for premium themes( themeforest/mojo)

**Comment by Codestar** [comment]
Hi, Section ? I did not understand, You are talking about "Add Section" action for wordpress ? If you ask this, yes you can add new section, field etc. from plugin or theme. take a look action and filter list http://codestarframework.com/documentation/#hooks

**Comment by sabuz** [comment]
![capture](https://cloud.githubusercontent.com/assets/7956101/7005273/5c244494-dc98-11e4-9b63-eb1a598539cf.PNG)

I mean this. Keep some options in a group.

**Comment by Codestar** [comment]
Framework have a group option field. i think you can use it ;)

**Comment by sabuz** [comment]
Framework have a group option field for repetition. Here repetition is not required

**Comment by Codestar** [comment]
Hmmm, ok i can think an idea for this in the future. :wink:

**Comment by Codestar** [comment]
Hi,

I added this option, update your framework files, take a look here how to use new option ```fieldset``` 

```
array(
  'id'        => 'fieldset_1',
  'type'      => 'fieldset',
  'title'     => 'Fieldset Field',
  'fields'    => array(

    array(
      'id'    => 'fieldset_1_text',
      'type'  => 'text',
      'title' => 'Text Field',
    ),

    array(
      'id'    => 'fieldset_1_upload',
      'type'  => 'upload',
      'title' => 'Upload Field',
    ),

    array(
      'id'    => 'fieldset_1_textarea',
      'type'  => 'textarea',
      'title' => 'Textarea Field',
    ),

  ),
),
```

for more informations http://codestarframework.com/documentation/#fieldset

**Comment by sabuz** [comment]
Thank YOU!

**Comment by sabuz** [comment]
Thank YOU!
As add new button are not needed to fieldset field, some styling should be updated.
![capture](https://cloud.githubusercontent.com/assets/7956101/7091656/24091f5c-dfcd-11e4-91cd-c637ccf62318.PNG)
You can try something like this. Please consider it.....

**Comment by Codestar** [comment]
You're welcome :+1: Oh yes, i can add a title above fields. Ok, i will improve it :wink:

**Comment by Codestar** [comment]
hmm, i think so, what you think.

```
array(
  'id'        => 'fieldset_1',
  'type'      => 'fieldset',
  'title'     => 'Fieldset Field',
  'fields'    => array(

    // title fieldset, this is subheading option, why not use here ? :)
    array(
      'id'      => 'subheading',
      'type'    => 'subheading',
      'content' => 'Title of Fieldset',
    ),

    array(
      'id'    => 'fieldset_1_text',
      'type'  => 'text',
      'title' => 'Text Field',
    ),

    array(
      'id'    => 'fieldset_1_upload',
      'type'  => 'upload',
      'title' => 'Upload Field',
    ),

    array(
      'id'    => 'fieldset_1_textarea',
      'type'  => 'textarea',
      'title' => 'Textarea Field',
    ),

  ),
),
```

**Comment by sabuz** [comment]
Wow! It's great without fieldset title
![capture](https://cloud.githubusercontent.com/assets/7956101/7102569/be109f0c-e0a5-11e4-986a-d3e1a39141d9.PNG)

Offtopic: I would like to know what is the necessity of the id of fieldse?

**Comment by Codestar** [comment]
Hi,

ID was required before this idea. i made an update for this after this idea. you can use subheading, notice fields without ids. ( if you using latest framework files )

**Comment by Codevz** [comment]
This really helped me thanks @Codestar :+1:

**Comment by Codestar** [comment]
You're welcome @Codevz  :+1:
