### ISSUE TITLE
Can Not Use Static Methods as Sanitizer

### ISSUE THREAD

**Issue by lahmacun** [Codestar/codestar-framework#64]
CodeStar Framework Version: 2.1.6

I just wanted to use `\MyClass\Utilities::sanitize` method as sanitizer but because of `function_exists()` in `classes/admin-options.class.php:342`, I couldn't use my method as sanitizer. I had to create bare function which I don't want to use it this way.

It would be great if you can check if it's and array or not, or maybe you can use method_exist.

Have a nice day, thanks for you great work.

**Comment by Codestar** [comment]
Hi,

The sanitize/validate functions uses simply **call_user_func**. Class method call is complex a little. I advise use like this simply:

```php
function lahmacun_sanitize_thing( $string ) {
  return \MyClass\Utilities::sanitize( $string );
}
```

Thanks, have a nice day.
Regards

**Comment by lahmacun** [comment]
Hi,

Actually, it's not as complicated as you think. Maybe you could just replace `function_exists` with `is_callable`. It would work.

call_user_func is working with static methods like `"\Lahmacun\Utils::sanitize_meth"`.

Maybe you would consider changing this in the future versions.

Best Regards.

**Comment by Codestar** [comment]
Oh yes, I understood. If we are talking about for only static methods it's oke. You can update these lines.

https://github.com/Codestar/codestar-framework/blob/a5f6c6296be3ab50f63ab0e21eb5dc100a473c4f/classes/admin-options.class.php#L342

https://github.com/Codestar/codestar-framework/blob/a5f6c6296be3ab50f63ab0e21eb5dc100a473c4f/classes/admin-options.class.php#L353

as **is_callable**. No worries for next update. I have added that for all of frameworks type right now.

Warm Regards
