### ISSUE TITLE
Problem in slider control.

### ISSUE THREAD

**Issue by mehedidb** [Codestar/codestar-framework#65]
after se the floating value I can't select RESET SECTION, when i click reset section It say Please enter a valid value, the two nearest valid value are 0 or 1.

**Comment by Codestar** [comment]
Hi,

Oh Yes, Thanks for report.

Go to this line...

https://github.com/Codestar/codestar-framework/blob/d8e1d4f25fe1028b094c65032ca29baed15d8376/classes/admin-options.class.php#L541

and append "novalidate" attribute like this:

```php
echo '<form method="post" action="" enctype="multipart/form-data" id="csf-form" autocomplete="off" novalidate>';
```

as **temporary**.

I'll fix that in next update ;)

Regards

**Comment by mehedidb** [comment]
Hi,

Thanks for your quick response, By the way this problem I also found in spinner control, please NOTE: after the passing "novalidate" attribute  it's working fine in Option Framework, But when I am trying to Metabox Framework it's happened same problem in Metabox Option.

Thanks!

**Comment by Codestar** [comment]
Hi,

Yes it's a temporary solution, I'll find a permanent solution.

You're welcome ;)
