### ISSUE TITLE
Empty options default value issue!

### ISSUE THREAD

**Issue by Alimir** [Codestar/codestar-framework#66]
We have a major issue! ‌ When we remove the value in the select option, it puts the default value after saving.
https://github.com/Alimir/wp-ulike/commit/53149a1b4b2c80a85ed5ac7a99db173081e9912e

**Comment by Alimir** [comment]
@Codestar

**Comment by Codestar** [comment]
Sorry for delay, I was in holiday. Let me check it now.

**Comment by Codestar** [comment]
I found the issue. Looking for a solution :+1:

**Comment by Codestar** [comment]
In fact, this is a special case for **multiple select** only. If we remove all options it returns empty and gets default value. I'm sanitizing the main **multiple select** field, but nested fields usage ( fieldset, accordion, group, tabbed i.e ) are complex a little for **multiple select** sanitizing.

But no worries, there is a solution.

```php
// class-wp-ulike-admin-panel.php go to line 247 and append
'sanitize' => 'wp_ulike_sanitize_multiple_select',
```

then

```php
//  create this function for eg your admin-functions.php
function wp_ulike_sanitize_multiple_select( $value ) {

  $multiple_selects = array(
    'auto_display_filter',
    'auto_display_filter_post_types',
  );

  foreach ( $multiple_selects as $id ) {
    if ( ! isset( $value[$id] ) ) {
      $value[$id] = array();
    }
  }

  return $value;
  
}
```

and try it. I tested it works in my side.

Regards

**Comment by Alimir** [comment]
@Codestar Good Job.

**Comment by Alimir** [comment]
I also saw another warning message recently. This error log is created when the user enters the Elementor editor.

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'CSF_Field_icon' not found in test/public_html/wordpress/wp-includes/class-wp-hook.php on line 287

**Comment by Alimir** [comment]
I also saw another warning message recently. This error log is created when the user enters the Elementor editor.

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'CSF_Field_icon' not found in test/public_html/wordpress/wp-includes/class-wp-hook.php on line 287

**Comment by Codestar** [comment]
Can you send me a screenshot ? I can't see this error in my side.

**Comment by Alimir** [comment]
@Codestar 
This problem is caused by the following code. Because the class CSF_Field_icon has a $field parameter that is not passed in this hook.
`add_action ('elementor / editor / footer', array ('CSF_Field_icon', 'add_footer_modal_icon'));`

Please fix the problem of this line in the setup.class file.
```
       if (! empty (self :: $ args ['shortcode_options'])) {
         foreach (self :: $ args ['shortcode_options'] as $ argument) {
           if ($argument ['show_in_editor'] && $ wpscreen-> base === 'post') {
             $ enqueue = true;
           }
         }
       }
```
*** ! empty( $argument ['show_in_editor'] )

**Comment by Alimir** [comment]
By the way, do you have an API structure for updating the Pro version directly from your server? That we can enter the purchase key and receive updates without the need to download from codecanyon?

**Comment by Codestar** [comment]
- CSF_Field_icon I guess I fixed it. Please check it after my next update.

- Uh there is no option for update directly from my server. As you know all developers are using the framework a part of project. Maybe I can think it soon.
