### ISSUE TITLE
Add shortcode inserts shortcode into wrong editor

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#67]
Codestar-framework will add the "Add Shortcode" button to any wp_editor it finds which is great, except it only actually works for the page/post's main editor.  If an additional wp_editor has been added to the page the resulting shortcode will be inserted into the page/post's main editor, not the additional editor that "Add Shortcode" button is tied to.

**Comment by Codestar** [comment]
Hm, yes sometimes there is a conflict with wp_editor, but can you explain it more ? how you use it exactly ? you can show me a screenshot. where you using add shortcode button ? i can try to fix it. i did check it on my local now, i added multiple wysiwyg option and it is working normally.

**Comment by SteveS123** [comment]
I've just added a second editor to a custom post type below, you should see the bug.

```<?php
/**

Location Post Type

*/

if ( ! function_exists('location') ) {

function location() {

  $labels = array(
	'name'                => _x( 'Location', 'Post Type General Name', 'location' ),
	'singular_name'       => _x( 'Location', 'Post Type Singular Name', 'location' ),
	'menu_name'           => __( 'Locations', 'location' ),
	'parent_item_colon'   => __( 'Parent Location:', 'location' ),
	'all_items'           => __( 'Locations', 'location' ),
	'view_item'           => __( 'View Location', 'location' ),
	'add_new_item'        => __( 'Add New Location', 'location' ),
	'add_new'             => __( 'New Location', 'location' ),
	'edit_item'           => __( 'Edit Location', 'location' ),
	'update_item'         => __( 'Update Location', 'location' ),
	'search_items'        => __( 'Search Locations', 'location' ),
	'not_found'           => __( 'No Location found', 'location' ),
	'not_found_in_trash'  => __( 'No Location found in Trash', 'location' ),
  );
  $args = array(
	'label'               => __( 'location', 'location' ),
	'description'         => __( 'Location page', 'location' ),
	'labels'              => $labels,
	'supports'            => array( 'title', 'editor', 'thumbnail', 'revisions', ),
	'taxonomies'          => array( 'category', 'post_tag' ),
	'hierarchical'        => true,
	'public'              => true,
	'show_ui'             => true,
	'show_in_menu'        => 'edit.php',
	'show_in_nav_menus'   => true,
	'show_in_admin_bar'   => true,
	'menu_position'       => 0,
	'menu_icon'           => '',
	'can_export'          => true,
	'has_archive'         => true,
	'exclude_from_search' => false,
	'publicly_queryable'  => true,
	'capability_type'     => 'page',
  );
  register_post_type( 'location', $args );

}
add_action( 'init', 'location', 30 );
}


// Address Metabox
add_action( 'add_meta_boxes', 'custom_meta_location_address');
function custom_meta_location_address() {
	add_meta_box( 'meta_location_address', __( 'Address', 'textdomain' ), 'meta_callback_location_address', 'location','normal','high' );
}
function meta_callback_location_address( $post ) {
	wp_nonce_field( basename( __FILE__ ), 'nonce' );
	$stored_meta = get_post_meta( $post->ID );
	if ( isset ( $stored_meta['address_directions'] ) ) {$content =  $stored_meta['address_directions'][0];}
	$settings = array('wpautop' => true,'media_buttons' =>  true,'textarea_rows' => '5');
	wp_editor( $content, 'address_directions', $settings );

}

function meta_save_location( $post_id ) {
	$is_autosave = wp_is_post_autosave( $post_id );
	$is_revision = wp_is_post_revision( $post_id );
	$is_valid_nonce = ( isset( $_POST[ 'nonce' ] ) && wp_verify_nonce( $_POST[ 'nonce' ], basename( __FILE__ ) ) ) ? 'true' : 'false';
	if ( $is_autosave || $is_revision || !$is_valid_nonce ) {return;}
	if( isset( $_POST[ 'address_directions' ] ) ) {update_post_meta( $post_id, 'address_directions', $_POST[ 'address_directions' ] );}
}
add_action( 'save_post', 'meta_save_location' );```

**Comment by Codestar** [comment]
Hi,

hmm, i did copy-paste your code and try. It is working correctly, can you take a look this video https://www.screenr.com/tAJN Shortcodes inserting right editor here ? btw, i was try it on chrome you ?

**Comment by SteveS123** [comment]
Thanks for the video, that actually explained why you weren't experiencing the issue.  Try placing the top (main) editor in "Visual Mode".  CS will only insert the shortcode into the proper editor if the first editor is in "Text" mode.

**Comment by Codestar** [comment]
Hi, Oh yes, I saw problem in "Visual Mode". Ok, i made an update for this issue. can you update your files ? btw, update files [framework/assets/js/cs-framework.js](https://github.com/Codestar/codestar-framework/blob/master/assets/js/cs-framework.js) and [framework/classes/shortcode.class.php](https://github.com/Codestar/codestar-framework/blob/master/classes/shortcode.class.php) as we see e5558b384c3b4aac59c016170c28ce9967757575 try and tell me result :wink:

**Comment by SteveS123** [comment]
I gave it a whirl but I'm now seeing this PHP error:
Fatal error: Cannot redeclare class CSFramework_Option_fieldset in /wp-content/plugins/cs-framework/fields/fieldset/section.php on line 38

**Comment by Codestar** [comment]
Hi, Yes also i had updated fieldset option as you see https://github.com/Codestar/codestar-framework/tree/master/fields/fieldset change your section.php to fieldset.php but i advise update all framework ;) only save your config php files before update :+1:

**Comment by SteveS123** [comment]
Ah I see, I uploaded the updated framework but I didn't clear out the old files.

I tested the shortcode issue and it's now fixed, thank you!

**Comment by Codestar** [comment]
You're welcome :+1: thank you too for report issue :wink:
