### ISSUE TITLE
Typography field update required

### ISSUE THREAD

**Issue by dtgopal** [Codestar/codestar-framework#67]
Hi Team,

We have purchased this plugin pro version. We used the typography filed in our theme framework. We need a small improvement in that field.
Our Customizer Field : [https://prnt.sc/tuem6t](https://prnt.sc/tuem6t)
CS Customizer Field: [https://prnt.sc/tuei8p](https://prnt.sc/tuei8p)
We need additional layout options in "font-size", "line-height", "letter-spacing" sub fields.
We have a plan to purchase 10 additional license for our next 10 themes. Also we need this option in all our themes. Kindly update & assist me the needful.

Thanks
Gopal

**Comment by Codestar** [comment]
Hi,

10 purchases sounds good really. But can you further information via routewp@gmail.com

For eg. How you want to output array and config array for field. Do you using output_css feature or your custom css ? Please send me the details via email.

Regards, Codestar
