### ISSUE TITLE
Group accordion_title using the ID of the field

### ISSUE THREAD

**Issue by SteveS123** [Codestar/codestar-framework#69]
Is it possible to use one of the field entries for the accordion_title?  I tried using the ID of the field (i.e. a text type) and it almost works except it also includes the field title within the accordion_title.

**Comment by SteveS123** [comment]
I see now that the accordion_title is only used when the group is new and no fields have been filled in and then defaults to the first field content after that.  Any way to have more control of the accordion_title?

**Comment by Codestar** [comment]
Hi, Oh yes. also i need this option. i will improve group option. i am thinking same with you ```accordion_title``` can be using ID of the field. i will do it in next update ;)

**Comment by Codestar** [comment]
Hi, I made an update for this. can you try it, only download and update your [cs-framework/fields/group/group.php](https://raw.githubusercontent.com/Codestar/codestar-framework/dev/cs-framework/fields/group/group.php) if you say ok, i will update it on main repo :wink: 

usage: ```'accordion_title' => 'unique_group_4_text_2', // ID of the field```

**Comment by Codestar** [comment]
Hmm, i updated main repo, i think it is ok :smile:
