### ISSUE TITLE
Radio button Not working

### ISSUE THREAD

**Issue by WPsmart** [Codestar/codestar-framework#7]
hi i used this

array(
          'id'        => 'forum_thered_fixed',
          'type'      => 'radio',
          'title'     => 'forum_thered_fixed',
          'options'   => array(
            'open'    => 'open',
            'checked' => 'Checked',
            'closed'  => 'colsed',
            'fixed' => 'fixed',
          ),
          'default'   => 'open',
        ),

<?php $meta_data = get_post_meta( get_the_ID()(), '_custom_post_options', true );
        echo $meta_data['forum_thered_fixed'];

but its not working can you check it?

Thanks

**Comment by Codestar** [comment]
Hi,

Also did you check "_custom_post_options" ? please write your metabox array config. i mean here:

```
...
// this is your metabox config (for eg) see the ID _custom_meta_options
$metaboxes[]      = array(
  'id'            => '_custom_meta_options',
  'title'         => 'Custom Options',
  'post_type'     => 'page', // or post or CPT
  'context'       => 'normal',
  'priority'      => 'default',
  'sections'      => array(
...
```

**Comment by WPsmart** [comment]
hi 

Thanks very much for quick reply 

options[]    = array(
  'id'        => '_custom_post_options',
  'title'     => 'Custom Post Options',
  'post_type' => 'page',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => array(

I used this

Thanks

**Comment by WPsmart** [comment]
oh 

$metaboxes[]      = array( 

or 

options[] = array( ?

**Comment by Codestar** [comment]
metaboxes or options variables is not important, you can use $blabla=array(); hmm id is correct. hmm why not working hmm. i added a radio field on localhost, it is working normally.

hmm send me your metabox.config.php and where you used get post meta function. i will check it for you ;)

**Comment by Codestar** [comment]
btw your first message i am seeing "get_the_ID()()" maybe problem is this you need to use "get_the_ID()" btw this ge the id for front end post or page php files. you need to find id if you use it inside a function..

**Comment by WPsmart** [comment]
Send it using email

Thanks :)

**Comment by WPsmart** [comment]
Hi Code Star, 

I used Drop down list for this, and i fixed this bug, Radio buttons have small bug, 

Thanks

**Comment by Codestar** [comment]
Hi,

I just tested Radio buttons on my localhost, and result: <a href="https://db.tt/Q4CjYYuK">https://db.tt/Q4CjYYuK</a> it is working normally :1234:
