### ISSUE TITLE
Adding options page as submenu page

### ISSUE THREAD

**Issue by chromjak** [Codestar/codestar-framework#70]
Great work. Is there anyway to:

- add options page as submenu page eg Settings >> Framework, I was playing with menu_type but can seam to make it work
```
'menu_type'  => 'add_submenu_page',
```
- is it possible to disable the sections sidebar ie not defining sections at all and having a single page of options without sections sidebar. I am thinking of including the framework as settings page to a plugin.

Thank you.

**Comment by Codestar** [comment]
Hi, Thanks for your opinions.

**1.** You can use framework anywhere as submenu so:

```
// using Settings -> Framework
$settings      = array(
  'menu_title' => 'Framework',
  'menu_type'  => 'add_options_page', // this is meaning Settings tab inside.
  'menu_slug'  => 'cs-framework',
  'ajax_save'  => false,
);
```
```
// using Appearance -> Framework
$settings      = array(
  'menu_title' => 'Framework',
  'menu_type'  => 'add_theme_page', // this is meaning Appearance tab inside.
  'menu_slug'  => 'cs-framework',
  'ajax_save'  => false,
);
```

```
// WordPress Administration Menus
add_dashboard_page
add_posts_page
add_media_page
add_pages_page
add_comments_page
add_theme_page
add_plugins_page
add_users_page
add_management_page
add_options_page
```

for more informations https://codex.wordpress.org/Administration_Menus

**2.** Framework section sidebar creating automatically, i mean if you create only one fields section, it will not show. it will disable automatically. if you add multiple field sections it will show. did you try it ?

**Comment by chromjak** [comment]
Perfect, thank you for your help.

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by MishukAdhikari** [comment]
How can I use it to my custom post type options?
