### ISSUE TITLE
Font Awesome Icon

### ISSUE THREAD

**Issue by FazleRabbiRana** [Codestar/codestar-framework#70]
Font Awesome v4.7.0 is being used on my theme. When I was trying to use the "Icon" field it didn't work as the class names are in Font Awesome v5 syntax (fas/far). So then I've read your documentation and I find a solution given to use Font Awesome v4 by adding an "add_filter( 'csf_fa4', '__return_true' );" I used it in my "functions.php" file and it worked fine for the "Icon Library".

But the problem I'm facing now is the admin panel fields icons are gone, (ex: drag, clone, remove). As I've checked I found that they're still generating Font Awesome 5 classes.

So how can I fix this? Please help.
![fontawesome-icon-problem](https://user-images.githubusercontent.com/60033053/91051684-45b5e500-e642-11ea-8883-e95c5d33e80e.jpg)

**Comment by Codestar** [comment]
Hi,

Thanks for report. yes. I have fixed this issue in next update ;)

Regards
