### ISSUE TITLE
Is your any way import or export options data?

### ISSUE THREAD

**Issue by AminulBD** [Codestar/codestar-framework#72]
Hi,

Is there any way to import or export option panel data for backup and restore?

Thanks!

**Comment by Codestar** [comment]
Hi,

Did not you see ```backup``` option field ? usage:

```
array(
  'type'    => 'backup',
),
```

and more informations http://codestarframework.com/documentation/#backup

**Comment by AminulBD** [comment]
I don't how, How I miss this ;)

Thanks!

**Comment by Codestar** [comment]
You're welcome :+1:
