### ISSUE TITLE
Customizer controls and _.js

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#72]
Hi Codestar,

Thanks for this great plugin :)

Do you know WordPress recommended to use content_template() function instead of render_content() for adding new custom controls in customizer? 

You can read full story here: https://developer.wordpress.org/themes/customize-api/javascriptunderscore-js-rendered-custom-controls/

This way with Underscore.js will improve customizer page speed performance and also switching themes will load new controls without page refresh. 

Regards

**Comment by Codestar** [comment]
Hi Codevz, 

Yes I know, but:

**content_template** uses **JS Template thing**.

As you know this framework is multi-purpose. A field is used for all frameworks ( admin options, metaboxes, widgets, menus and more. ) How we can convert these fields for content_template (for js template) ?

Actually there is no performance loss to worry about. In demo I added all fields and loading fast.

Regards

**Comment by Codevz** [comment]
Thanks bro for the information,  Have you plan to add WP link popup field

![](https://cdn.wpbeginner.com/wp-content/uploads/2015/08/default-insert-link.png)

**Comment by Codestar** [comment]
Hi,

You're welcome, Yes I can add that field in the next update.

Output array is ok ?

```
array(
  'url' => 'https://google.com/',
  'text' => 'Google',
  'target" => '_blank'
)
```

Regards

**Comment by Codevz** [comment]
Yes this is great, thanks man 👍🏻

**Comment by Codestar** [comment]
![image](https://user-images.githubusercontent.com/1313301/94307906-51b4ff80-ff7e-11ea-8532-4bf016fa7a81.png)

**Yea, It looks like this. what you think ?** 🙃

**Comment by Codevz** [comment]
This is what I (and I'm sure others) exactly want, Link field is really helpful specially to find and set internal links. 

Thanks a lot bro 👍🏻💯

**Comment by Codestar** [comment]
You're welcome bro, I have added that for the next update :+1:
