### ISSUE TITLE
How to output <P> and <br> by textarea and wp_editor 

### ISSUE THREAD

**Issue by HUiTHEME** [Codestar/codestar-framework#73]
type  => textarea and wp_editor 
When using the above two types of fields, there is no `<p>` or `<br>` html tag wrap the output

<img width="1038" alt="QQ20200921-090921@2x" src="https://user-images.githubusercontent.com/25346902/93726735-38acf700-fbea-11ea-83ec-c8245fe13cd1.png">

**Comment by Codestar** [comment]
Hi,

You should to use wpautop function for field output. Like this:

```
echo wpautop( $opts['opt-wp-editor-1'] );
```

Regards

**Comment by HUiTHEME** [comment]
> Hi,
> 
> You should to use wpautop function for field output. Like this:
> 
> ```
> echo wpautop( $opts['opt-wp-editor-1'] );
> ```
> 
> Regards

Thank you very much, the problem has been solved.

**Comment by Codestar** [comment]
You're welcome ;)
