### ISSUE TITLE
Metabox data not saving .

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#73]
Metabox data not saving any one face this problem !!

**Comment by Codestar** [comment]
Uh, how? can you explain it more ? I checked it now, it is working normally in my local...

**Comment by devariya** [comment]
please give me your mail address i will send you live demo link and access .

**Comment by Codestar** [comment]
Yes, it will be great, i will check it for you, send your admin informations via info@codestarlive.com

**Comment by devariya** [comment]
done

**Comment by Codestar** [comment]
Nice, I got email. i am checking it now :wink:

**Comment by Codestar** [comment]
It is working now. what i made:

```
// cs-framework/classes/metabox.class.php
if( ! empty( $this->options ) ) {
  $this->addAction( 'add_meta_boxes', 'add_meta_box' );
  // $this->addAction( 'save_post', 'save_post' ); // commented this line
  $this->addAction( 'edit_post', 'save_post' ); // added this line
}
```

but why ? ```save_post``` vs ```edit_post``` i remember this issue for a client. i will check this again. what is the issue about this. ok now you can use it now ;) test and tell me.

**Comment by devariya** [comment]
Thank you .

**Comment by Codestar** [comment]
You're welcome :+1: 

btw, i am following WordPress Core as you see https://codex.wordpress.org/Function_Reference/add_meta_box there is using save_post ```add_action( 'save_post', 'myplugin_save_meta_box_data' );``` hmm maybe there is a conflict for any plugin. because you can try framework on a clean wordpress in your localhost :wink:

**Comment by devariya** [comment]
Yes ! it worked on a clean WordPress but some how this client face this issue ,No one report me about this issue without this one .So i think you are right maybe there is a conflict for any plugin .

BTW i do you have any plane for those field 
*Date field
*Date Time unix field
*Date unix field

**Comment by Codestar** [comment]
Yep, i was noted this fields, you will see it soon, i am busy a little in this days. :smile:

**Comment by nurulalam3s** [comment]
REQUIRED: Found add_meta_box in the file metabox.class.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
please help about that

 // run metabox construct
  public function __construct( $options ){

    $this->options = apply_filters( 'cs_metabox_options', $options );

    if( ! empty( $this->options ) ) {
      $this->addAction( '**add_meta_boxes**', '**add_meta_box**' );
      $this->addAction( 'save_post', 'save_post', 10, 2 );
    }

  }

  // instance
  public static function instance( $options = array() ){
    if ( is_null( self::$instance ) && CS_ACTIVE_METABOX ) {
      self::$instance = new self( $options );
    }
    return self::$instance;
  }

  // add metabox
  public function **add_meta_box**( $post_type ) {

    foreach ( $this->options as $value ) {
      **add_meta_box**( $value['id'], $value['title'], array( &$this, 'render_meta_box_content' ), $value['post_type'], $value['context'], $value['priority'], $value );
    }

  }
