### ISSUE TITLE
When creativeOptions set the type = gallery , How to output gallery ？

### ISSUE THREAD

**Issue by HUiTHEME** [Codestar/codestar-framework#74]
I can only get some IDs now, I can't get more information about gallery, I can't get the image URL in galley.

http://codestarframework.com/documentation/#/fields?id=gallery

I don't see the output description in the documentation.

I hope you can teach me how to output writing, thank you.

**Comment by Codestar** [comment]
Hi,

The gallery field returns image ids. for eg. 15,256,213,543 you can output like this:

```php
$gallery = $option['gallery-option']; // for eg. it returns 15,256,213,543

$gallery_ids = explode( ',', $gallery );

if ( ! empty( $gallery_ids ) ) {

  foreach ( $gallery_ids as $gallery_item_id ) {

    // echo wp_get_attachment_image( $gallery_item_id, 'full' );
    // echo wp_get_attachment_url( $gallery_item_id );
    // echo wp_get_attachment_image_src( $gallery_item_id, 'full' );
    // var_dump( wp_get_attachment_metadata( $gallery_item_id ) );

  }
  
}
```

Also I'll add this on documentation :+1:
