### ISSUE TITLE
Template wise metabox

### ISSUE THREAD

**Issue by ashawkat** [Codestar/codestar-framework#75]
Is there any way I can load the metaboxes template wise? I want to load different metabox for different templates. If it's possible or not? I'm in need of such things Please let me know.

**Comment by Codestar** [comment]
Hi, Sorry my english but if i understand your request, you want to "when change a page template" you will show different metaboxes ? actually you can use a basic javascript for hide/show metaboxes. for eg.

```
// this is a basic change function, you can improve it.
;(function ( $, window, document, undefined ) {
  'use strict';

  $(document).ready( function() {

    $('#page_template').change( function() {

      $('#metabox-id-1').hide();
      $('#metabox-id-2').hide();
      $('#metabox-id-3').hide();

      switch( $( this ).val() ) {

        case 'template-1.php':
          $('#metabox-id-1').show();
        break;

        case 'template-2.php':
          $('#metabox-id-2').show();
        break;

        case 'template-3.php':
          $('#metabox-id-3').show();
        break;

        default:
          $('#metabox-id-1').show();
        break;
      }

    }).change();

  });

})( jQuery, window, document );
```

Btw you can check here for how to add multiple metabox #13

**Comment by ashawkat** [comment]
thanks for the reply & yes that's what I've wanted. I'll surely check on that then .. :)

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by dangolprajwol** [comment]
where to use this ? I dont have any idea about this. Please Help Me Codestar...

**Comment by Codestar** [comment]
Hi,

You need to develop this example for your wordpress theme. and you will use this script in admin panel. hmm if you don't have any idea. i can adapt it on your theme as freelance work :wink:

**Comment by ZihadulIslam** [comment]
HI,
You can check this. its working great if you want to show metabox for specific page template. 
[Template wise metabox](https://github.com/Codestar/codestar-framework/pull/503)
