### ISSUE TITLE
Visual Editor broken in group field

### ISSUE THREAD

**Issue by mandava** [Codestar/codestar-framework#76]
wysiwyg field broken when added in group

![ve](https://cloud.githubusercontent.com/assets/125006/7327289/03d0aa2a-ea9a-11e4-91b5-d11f77c95fc7.PNG)

**Comment by Codestar** [comment]
Hi, Yes Visual Editor issue in group field, i am planing to integration this for next updates. because it is required some javascript. btw, we are talking about this here #30
