### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by UaDiamond** [Codestar/codestar-framework#77]
Hello. I'm developing Wordpress theme and after it submission, I've soft reject from ThemeForest, because Codestar framework has problems with sanitizing. After research errors, I can note, that these problems related with group fields. For example, when I have Group field with only one text field, and I put into input simple script "<script>alert(1);</script>", but it doesn't cleaned properly. After saving theme options I have popup with "1".
Can you help me with solving this problem? Or maybe you know about it and nearest will be a new version of CodeStar?

--
Thanks. Regards, Oleksandr.

**Comment by CodeExplore** [comment]
Hi, Yes sure i can help you. but can you explain the issue more ? let me check it. please send me an email via codestarlive@gmail.com for reviewer message and your wordpress admin information. or how i can help you more ?

**Comment by Codestar** [comment]
Hi, Yes sure i can help you. but can you explain the issue more ? let me check it. please send me an email via codestarlive@gmail.com for reviewer message and your wordpress admin information. or how i can help you more ?
