### ISSUE TITLE
Icon control and help icon issue

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#77]
Hi Codestar, 

When I choose icon from library, also its affect on the control help icon, I think in csf.js this

`CSF.vars.$icon_target.find('i')`

should change to this

`CSF.vars.$icon_target.find('.csf-icon-preview i')`

<img src="https://i.ibb.co/xfP97BJ/Screen-Shot-2020-10-13-at-12-34-37.png" alt="Screen-Shot-2020-10-13-at-12-34-37" border="0" />

Regards

**Comment by Codestar** [comment]
Hi,

Oh yes, it's a bug, thanks for report. I have fixed it now. :+1: 

Regards
