### ISSUE TITLE
Meta Feilds in Taxonomy

### ISSUE THREAD

**Issue by rahulincedia** [Codestar/codestar-framework#78]
Hi

I came across your framework today and immediately decided to use it in my next project. Thank you for creating such an easy-to-use yet robust framework. It is fantastic!

I couldn't find a way to add a meta box on taxonomy page using this framework? Is it possible? If not, do you plan to add this functionality in near future?

Or if there is a workaround which i can follow to achieve it please advice.

**Comment by santiagointeractive** [comment]
Hi,

If I understand right your needs, you could take a look on this discussion: https://github.com/Codestar/codestar-framework/issues/47
@Codestar explained how you can add some actions to achieve this kind of functionality.

Cheers! :smile:

**Comment by rahulincedia** [comment]
Thank you so much for pointing me in the right direction. I should have looked in the closed issues before creating a new one.

You guys rock! Keep up the good work!


PS: I have added some CSS styles and created Light theme for this framework. I didn't edit the original CSS file, I placed them in a different CSS file which is just 100 lines long. May be Codestar could add a light theme to the Framework. I'm sure there are other people out there who prefer light themes over dark themes.

![codstar-framework-light-theme](https://cloud.githubusercontent.com/assets/3503359/7385326/048211b4-ee61-11e4-887d-f9d38cd95f3c.png)

**Comment by zhw2590582** [comment]
wow, I like the light theme .

**Comment by Codestar** [comment]
@santiagointeractive thanks for help :smile: 

@rahulincedia wow also i like the light theme. hmm add the css styles on https://gist.github.com/ and share with us, i will try to add skin option for framework dark/light options. in next days. :+1: 

@zhw2590582 me too :)

**Comment by rahulincedia** [comment]
@Codestar First of all thank you for making such an awesome framework. Here's the CSS https://gist.github.com/rahulincedia/437629db8aa64be4e076. If even you like light theme how about making it framework's default theme?

For almost every client I created a WordPress theme, I add options for padding and margin. I have an field suggestion for Padding/Margin. As of now, if we need to add padding/margin options for all four sides of a HTML element, we need to add four different fields. How about having an option to add them in a single field like this
![untitled-8](https://cloud.githubusercontent.com/assets/3503359/7400497/f9b5585c-eeda-11e4-9508-b8b2a9cc5976.png)
I know you are aiming at making a a lightweight framework. But this would make UI of the framework as we would be merging four fields into one. We could have similar option for border.

**Comment by rahulincedia** [comment]
I have a better idea, how about covering padding, margin and border in a single field called Box Model as below
![untitled-9](https://cloud.githubusercontent.com/assets/3503359/7401254/4ff365ba-eee0-11e4-8ae4-aa24ffa25888.png)

**Comment by Codestar** [comment]
Hi, Thanks for share light skin css. i will try to add it in next framework updates. and about padding and margin idea. you can add it by yourself, codestar framework is extendable, so flexible. actually i am planing a lot of option fields but i am trying to keep it as a light-weight framework. but i noted this request :+1:
