### ISSUE TITLE
Remove id of fieldset

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#79]
I think the "id" of fieldset field should be removed, because the code goes too long when using the value in frontend. The main purpose of fieldset was make a group of some options. So, maybe there is no importance of using id.

**Comment by Codestar** [comment]
Hi, hmm, i am thinking hmm. yes you can be right. there is no required for id for fieldset. but i added it for no conflict with another option names ? what your final think ? we need to safe another option ids or user can check for ids conflict ? :smile:

**Comment by sabuz** [comment]
Your thinking was great! But, it is necessary to remove id. Or you can make it optional.

**Comment by Codestar** [comment]
Hi, hmm ok i will try to optional ids in next updates. :wink:
