### ISSUE TITLE
Is that has nav menu metabox?

### ISSUE THREAD

**Issue by bilalmalkoc** [Codestar/codestar-framework#8]
Is your framework has nav menu metabox option? Or will be released?

**Comment by Codestar** [comment]
Do you mean this ?

```php
array(
  'id'          => 'opt-menus',
  'type'        => 'select',
  'title'       => 'Select menu',
  'placeholder' => 'Select a menu',
  'options'     => 'menus',
),
```

Or you mean add to options on Apperance -> Menus ?

**Comment by bilalmalkoc** [comment]
Yes add options to Apperance -> Menus

**Comment by Codestar** [comment]
Hmm, No support to add option fields on nav menus, yet. maybe in the future. :)

**Comment by bilalmalkoc** [comment]
In wordpress 5.4 nav menu item custom field hook is added. You can make nav menu item metabox with using it. Check here please.

https://make.wordpress.org/core/2020/02/25/wordpress-5-4-introduces-new-hooks-to-add-custom-fields-to-menu-items/

**Comment by Codestar** [comment]
Hi,

Oh yes, I was waiting this really and will add this a few update later. Follow the next updates.

Regards
