### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LebCit** [Codestar/codestar-framework#8]
Hello,

First of all, thanks a lot for giving such a great work for free.

When i first installed the framework in twentyfifteen, i had a warning message saying that :
array_values() expects parameter 1 to be array in ...\twentyfifteen\cs-framework\classes\options.class.php on line 39
I've made the following change and the warning went off + everything was working :
initial - $value = array_values( $this->value );
changed to - $value = array ( $this->value );

Have a nice day/night :+1:

**Comment by Codestar** [comment]
Hi,

Ops, thanks for report :+1: and your opinion... i will fix it quickly ;)
