### ISSUE TITLE
Unable to access mextabox content

### ISSUE THREAD

**Issue by rahulincedia** [Codestar/codestar-framework#80]
Hi

I'm unable to access values of metabox using `get_post_meta()` and I'm not quite sure why. It is saving the data in the metabox though.

To demonstrate the issue, I have created a new WordPress install (http://dev.incedia.com/Zzz) and added cs-framework to Twenty Fifteen. To keep things simple, I'm using default fields that come with cs-framework. Following are the only changes in the code I have made
* Added `require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';` to line number 3 of functions.php.
* Added ```<?php $field_data = get_post_meta( $post->ID, 'section_4_text', true );
    echo 'Test Field: ' . $field_data; ?>``` to line number 31 of content.php.

I can access values of framework option fields using `cs_get_option()`. Its just the metaboxes I'm facing the issue with.

Am I doing something wrong? How can I correct it? I can give you wp-admin access if you need it, please give me your email address.

Thank you
Rahul

**Comment by santiagointeractive** [comment]
Hi,
The right way to echo meta fields of a post is this:

<pre><code>$field_data = get_post_meta( $post->ID, '_custom_post_options', true );</code></pre>
This loops into your metabox options id:
<pre><code>$options[]    = array(
  'id'        => '_custom_post_options',
</code></pre>

Then you could get every field meta value from that options array like this:
<pre><code>$field_echo = $field_data['section_4_text']; echo 'Test Field: ' . $field_echo;</code></pre>

Hope this will clarify your case.
Cheers!

**Comment by rahulincedia** [comment]
Thank you @santiagointeractive for helping me out :+1: 

There one more thing you could help me with. I would like to change cs-framework-override folder to something else (for example test-folder), but without editing cs-framework-path.php. I believe it is possible to change it using the `add_filter` `cs_locate_template`. Unfortunately, I can not figure out how to do it. I would really appreciate it if you could guide me.

**Comment by Codestar** [comment]
@santiagointeractive thanks for help :+1: 

@rahulincedia hmm, you are asking this for do not touch orginal framework files ? actually you can change it manually. but without editing cs-framework-path.php we need to a new filter for this. ok i will add this for you until Monday. noted this request.

Regards, Codestar

**Comment by santiagointeractive** [comment]
I think something like this will do the trick ?!?

Into <code>function.php</code> of your theme:
<pre><code>function my_custom_cs_locate_template( $template_name ) {
   ...
   $dir_override = '/my-new-override-folder/'. $template_name;
   ...
}
add_filter( 'cs_locate_template', 'my_custom_cs_locate_template' );</code></pre>

Haven't tested it.
@Codestar correct me if I'm wrong.

**Comment by rahulincedia** [comment]
@Codestar Exactly! I don't want to touch framework's files at all. This would make updating the framework in future much simpler :)

@santiagointeractive I tried the same thing but could not get it work. All metabox and options disappear. That's I posted it here.

**Comment by Codestar** [comment]
Hi @rahulincedia I added an filter on cs-framework-path.php for you. now you can change override folder name with add_filter take a look example:

```
// using override folder name as themename/my-override with this filter
if ( ! function_exists( 'new_cs_framework_override' ) ) {
  function new_cs_framework_override() {
    return 'my-override';
  }
  add_filter( 'cs_framework_override', 'new_cs_framework_override' );
}
```

so only update your framework files :wink:

**Comment by rahulincedia** [comment]
@Codestar I have just tested this filter. It works exactly how it needs to be. Thanks you!

**Comment by Codestar** [comment]
You're welcome :+1:
