### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by yevtukov** [Codestar/codestar-framework#80]
Hello. How I can fix mixed content error in admin panel?
![image](https://user-images.githubusercontent.com/43721510/97499108-5eae7f80-197e-11eb-8621-d6850f0e95e8.png)

**Comment by Codestar** [comment]
Hi,

Uh, interesting. I see this first time.
Actually I'm checking ssl protocol like this `$protocol_uri = ( is_ssl() ) ? 'https' : 'http';` 

Can you give me the wordpress admin information via routewp@gmail.com I want to check detailed.

Regards

**Comment by yevtukov** [comment]
Thanks. I solved the problem

` add_action( 'admin_enqueue_scripts', 'my_scripts_method', 99);
function my_scripts_method() {
	wp_deregister_script( 'cs-plugins' );
	wp_register_script( 'cs-plugins', 'https://terraschool.ru/wp-content/plugins/codestar-framework/assets/js/cs-plugins.js');
	wp_enqueue_script( 'cs-plugins', array(), '1.0.0', true );
}`
