### ISSUE TITLE
Sanitizer Removes Specific Styles

### ISSUE THREAD

**Issue by lahmacun** [Codestar/codestar-framework#81]
Hi,

Hope you're doing well. I have an interesting question. I'm not sure if it's WordPress related or CodeStar related.

I have a code_editor field. I added a code like this:
```
document.innerHTML += '<div style="width: 50px; position: absolute; left: 0; bottom: 10; background: rgb(0, 0, 0)"></div>';
```
After save, my code became to this:
```
document.innerHTML += '<div style="width: 50px"></div>';
```
I believe some sort of sanitizer does this but, I don't have any sanitizer and also I added `sanitize => false` parameter to my code field but It's still sanitizing my code.

It removes properties like background, position, left, bottom etc...

If you want to checkout the code, visit [https://github.com/optimocha/speed-booster-pack/blob/release/admin/class-speed-booster-pack-admin.php](url)

Here I have custom_codes field. That's where I face the issue.

Best Regards.

**Comment by Codestar** [comment]
Hi,

Thanks, Everything are well. I hope all is well for you too.

Yes I understand. It seems custom_codes is a group field and as you know all fields has own sanitize thing. You should to set `sanitize => false` for group field as well. For eg:

```php
'id'       => 'custom_codes',
'type'     => 'group',
'sanitize' => false,
```

_Note: You do not need to `sanitize => false` for every field of group. Parent parameter will affect all inner fields._

Regards

**Comment by lahmacun** [comment]
Hi,

That solved the issue. Thanks.

Best Regards.

**Comment by Codestar** [comment]
You're welcome :+1:
