### ISSUE TITLE
How to change CS title

### ISSUE THREAD

**Issue by morshedx** [Codestar/codestar-framework#82]
I want to replace this title
![screenshot_1](https://cloud.githubusercontent.com/assets/10260796/7441839/d277f190-f11a-11e4-8972-e756a0683fae.png)
 with my theme name. is it possible? If yes, then how?

I can't find it here http://codestarframework.com/documentation/#framework-configure

BTW, Thanks a lot for a Beautiful Option Panel :+1:

**Comment by Codestar** [comment]
Hi, You can change it from directly php file. i did not add a filter or action or a setting for this, because this is promotion for me :smiley: also take a look this issue #6

**Comment by developerbmw** [comment]
I think most users will replace it anyway so why not add an option to change it without modifying the framework? :)

**Comment by Codestar** [comment]
Oh ok guys, you won :D I will add this an option for this next update :+1:

**Comment by Codestar** [comment]
Now you can change it from settings.. for eg:

```php
$settings           = array(
  'menu_title'      => 'Framework',
  'menu_type'       => 'menu', // menu, submenu, options, theme, etc.
  'menu_slug'       => 'cs-framework',
  'ajax_save'       => false,
  'show_reset_all'  => false,
  'framework_title' => 'Codestar Framework <small>by Codestar</small>', // TAKE A LOOK HERE
);
```

**Comment by morshedx** [comment]
thanks for this update :) :+1:

**Comment by Codestar** [comment]
You're welcome :smiley:
