### ISSUE TITLE
Request: Menu locations as select options

### ISSUE THREAD

**Issue by Codevz** [Codestar/codestar-framework#83]
Hi,

If its possible for you in the next update, please add menu locations as options for select field. Thanks

```PHP
  case 'locations':

    $options = get_registered_nav_menus();

    $array_search = true;

  break;
```

I requested it because `get_registered_nav_menus()` not working directly in customizer page, but when it loads from CSF core, it works fine.

**Comment by Codestar** [comment]
Hi,

Oh, I forgot to write. I have added this 8 days ago.  :smiley:  You will see it in the next update. :+1: 

Regards
