### ISSUE TITLE
Proper way to use checkbox value(multiple)

### ISSUE THREAD

**Issue by sabuz** [Codestar/codestar-framework#83]
What is the proper way to use multiplecheckbox value?

array(
          'id'       => 'top_bar_elements',
          'type'     => 'checkbox',
          'title'    => 'Top Bar Elements',
          'options'  => array(
            'date'  => 'Date',
            'menu' => 'Menu',
          ),
        ),

<?php $topbar_elements = cs_get_option('top_bar_elements'); ?>
<?php if( $topbar_elements[0] == 'date' ) : ?>
	.................................
<?php endif; ?>

This is working....But showing  a warning message(Undefined Offset) when any element is not checked.

**Comment by santiagointeractive** [comment]
Hi,
Try using it like this:

<pre><code>$topbar_elements = cs_get_option('top_bar_elements');
if (!empty($topbar_elements)) {
   if( $topbar_elements[0] == 'date' ) {
   ...
   }
}</code></pre>

Or:

<pre><code>$topbar_elements = cs_get_option('top_bar_elements');
if ( isset($topbar_elements[0]) && $topbar_elements[0] == 'date' ) {
...
}</code></pre>

I think the second way it's the right one.
Please confirm if it works.

Thanks!

**Comment by sabuz** [comment]
Thank You @santiagointeractive !
Yes, this is working!

**Comment by santiagointeractive** [comment]
LOL... You say it's not working but your code it's the same as mine.

**Comment by sabuz** [comment]
:laughing:
Yes, it is same, and what I tried to say that this is not the right way(Including the code below)!


'options' => array(
    'date' => 'Date',
    'menu' => 'Menu',
),

if ( isset($topbar_elements[0]) && $topbar_elements[0] == 'date' ) {
...
}
if ( isset($topbar_elements[1]) && $topbar_elements[1] == 'menu' ) {
...
}

Now, if you check menu and unchecked date, then the array key of menu will be '0' and menu element will not appear. Because we are checking "menu" against array key "1".

Hope I'm clear to you.

**Comment by santiagointeractive** [comment]
That was pretty obvious that you need such clause on each element.
Peace!

**Comment by Codestar** [comment]
Hi, Another example for output:

```
$topbar_elements = cs_get_option('top_bar_elements');

if ( in_array(  'date', $topbar_elements ) ) {
  // do stuff for date
}

if ( in_array(  'menu', $topbar_elements ) ) {
  // do stuff for menu
}
```

**Comment by sabuz** [comment]
Hello @Codestar !
There is an error while no item is selected. How to solve it?

**Comment by santiagointeractive** [comment]
Hi,
Try this!

<pre><code>$topbar_elements = cs_get_option( 'top_bar_elements' );

if (!empty($topbar_elements)) {  // this checks if array has items then do other checks

     if ( in_array( 'date', $topbar_elements ) ) {
       // do stuff for date
     }

     if ( in_array( 'menu', $topbar_elements ) ) {
       // do stuff for menu
     }
}</code></pre>

Cheers!

**Comment by Codestar** [comment]
Oh yes, follow @santiagointeractive i forget to "a if for array" :+1:

**Comment by bewakez95** [comment]
array(
          'id'              => 'team',
          'type'            => 'group',
          'title'           => 'Team Members',
          'button_title'    => 'Add New',
          'accordion_title' => 'Add New Member',
          'fields'          => array(
           array(
            'id'         => 'team_specialist',
            'type'       => 'checkbox',
            'title'      => 'Specialized in :',
            'options'    => array(
              'web'      => 'Web',
              'ui' => 'UI',
              'ps'     => 'Photoshop',
              ),
            ),
How can I access the value of indivisual group of checkbox ?
Checkbox in group type ??
