### ISSUE TITLE
Dooplay <> Codestar 

### ISSUE THREAD

**Issue by docgonzo2015** [Codestar/codestar-framework#85]
Hi!
I have installed the Dooplay Plugin (https://doothemes.com).
It is designed with Codestar Framework.
I wanted to use the framework to edit the pages, but the framework plugin can't be installed, because it has been added to the theme manually.
Does anyone have a hint how I can edit it so that the code runs directly?

**Comment by Codestar** [comment]
Sorry, you should contact with theme/plugin author about this subject.
