### ISSUE TITLE
Meta fields are not edit able. Conflict with The Events Calendar PRO plugin.

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#86]
Hi, 
I develop a theme with Codestar. My client trying to use The Events Calendar PRO plugin with my theme. If The Events Calendar PRO is active our Codestar meta values are not editable. It's not save the changes.

I will also open a support ticket on Events Calendar support forum. If possible give me suggestion.

Thanks

**Comment by Codestar** [comment]
Hi,

Can you take a look this issue #73 and this answer #issuecomment-95174733 yes there is a conflict. but i am following wp core ```save_post``` advising this action for save meta. and alternative is ```edit_post``` hmm try my answer and tell me the result, edit_post will solve your problem ?
