### ISSUE TITLE
One Click Demo Install 

### ISSUE THREAD

**Issue by devariya** [Codestar/codestar-framework#87]
https://github.com/FrankM1/radium-one-click-demo-install

Redium One Click Demo Install Support Radium Framework & Option Tree , Do you have any plan to add support for codestar framerwork  . or your own demo importer functionality include with framework .

**Comment by devariya** [comment]
i like this one https://github.com/Webcreations907/WBC-Importer-extension

**Comment by Codestar** [comment]
Hi, hmm, yes why not, i can add it in next updates :+1: follow updates.

**Comment by devariya** [comment]
Wow , Great News :+1:

**Comment by cmwwebfx** [comment]
I would love to see this in this in the framework as well. The one that was posted here already would be incredible to have. Watching this like a hawk. #excited!
https://github.com/Webcreations907/WBC-Importer-extension

**Comment by Codestar** [comment]
Yea, Also i am planing my own importer for my next theme, i can share it here when i release it :smile:

**Comment by cmwwebfx** [comment]
Wouldn't it be easier to rebuild that WBC one into your own rather than recreate the wheel? Most likely you can build a better one anyways. :dancers:

**Comment by Codestar** [comment]
So i am planning yet, Let's see what will happen :)

**Comment by cmwwebfx** [comment]
Excited.. watching this space (y)

**Comment by Codestar** [comment]
Yea, follow it you will see new features asap :+1:
