### ISSUE TITLE
I want to fork CS Framework with my own brand

### ISSUE THREAD

**Issue by AminulBD** [Codestar/codestar-framework#88]
Hi Codestar,

I want to fork this awesome framework with my own brand and new name. This framework will be used in our theme and all themes will be paid themes. I want change your source and customize anything what I need.

Can you allow re-construct your framework with our brand?

**Comment by Codestar** [comment]
Yes, you can do whatever you like, as this framework is licensed under GPL, but please make sure you give proper credit to me, Thanks :+1:

**Comment by AminulBD** [comment]
Of course I will give you proper credit ;)

And thanks for the update.

**Comment by Codestar** [comment]
You're welcome :+1:
