### ISSUE TITLE
Transients query count

### ISSUE THREAD

**Issue by mandava** [Codestar/codestar-framework#89]
This is not an issue but more like a question. Transients set for sections and settings errors resulted in too many queries. I think we need to cut down the query count.

![transients](https://cloud.githubusercontent.com/assets/125006/7521663/c3183c9a-f4bd-11e4-8596-25e1ed867b96.PNG)

**Comment by Codestar** [comment]
Hmm Interesting, i am seeing only 62Query in my localhost ? and this is normal. i can not see too many queries from framework. maybe there is another thing.

![support_11-38-35](https://cloud.githubusercontent.com/assets/1313301/7533076/db6001e8-f576-11e4-8442-5f04df0bf8a6.png)

**Comment by Codestar** [comment]
Hi, I improved it now, can you check it ? re-download framework files and try fdde1f9506631109f55ccb1d6d3230f9e4eb7920

**Comment by mandava** [comment]
Alright, its good now. Thanks for the fix!

**Comment by Codestar** [comment]
You're welcome :+1:
