### ISSUE TITLE
Unable to clear color value

### ISSUE THREAD

**Issue by dejann** [Codestar/codestar-framework#9]
I don't have default values set for color options in customizer. Theme uses default color from theme style.css. With codestar framework I'm simply overwriting theme styles.

If I clear color value nothing happens in customizer. I don't have a live preview and option to publish new changes https://imgur.com/a/HaSEEDE

**Comment by Codestar** [comment]
Hi,

Oh yes right. I forgot to trigger refresh to page, when click to clear button. I fixed it now. You can get modified-version in support forum quickly or wait to update, if its not critical thing for you :)

Thanks for report, Have a nice day.
Regards, Codestar

**Comment by dejann** [comment]
@Codestar This issue reappears. Can you please check.
Thanks

**Comment by Codestar** [comment]
Hi,

Uh, It's interesting. I had fixed this issue. For eg you can see it in demo. Go to "Customizer -> Nested Panels -> Nested Panel 2" and try to color picker clear option. The page refreshing when you click to "clear"

Hmm, maybe cache ? try to clear your browser cache.

Regards, Codestar
