### ISSUE TITLE
New little bug

### ISSUE THREAD

**Issue by LebCit** [Codestar/codestar-framework#9]
Hello,

On admin side, all the upload examples in options have to be "exit" 3 times ?!
I mean that when you click on the upload button and try to exit the uploader, you have to click 3 times on the "X" to exit the uploader.

Have a nice day/night

**Comment by schiavassa** [comment]
I can confirm this happened to me as well as I was test-driving the framework the other day. Now it works correctly, I can't seem to reproduce that odd behavior.

Awesome work nonetheless, it sure will save me some time in the future. Thanks a bunch for sharing it!

**Comment by Codestar** [comment]
@LebCit hmm i will check it quickly ;)
@schiavassa oh thanks for your pretty words, and i will check it what happening ;)

**Comment by Codestar** [comment]
@LebCit hmm i checked it now, i can click upload and when i click "X" it is closing normally. hmm please check your chrome console log after click "X" maybe there is an javascript conflict with any plugin :)
