### ISSUE TITLE
Color Picker reload upon clone in group field

### ISSUE THREAD

**Issue by mandava** [Codestar/codestar-framework#90]
Using color picker in group fields and reloading it upon cloning. 
Not working right now, maybe we need a fix for that.

**Comment by Codestar** [comment]
Hmm, can you write your group config array here ? because, i added a color picker on group field, and it is working normally / cloning ? or show me a screenshot.

**Comment by mandava** [comment]
My bad its working fine! Thank you.

**Comment by Codestar** [comment]
Nice :wink:
