### ISSUE TITLE
Using this framework in a plugin

### ISSUE THREAD

**Issue by rahulincedia** [Codestar/codestar-framework#93]
Hi,

I'm creating a plugin in which I'm going to register a new post type. I'm planning to use this framework for meta fields and short-codes (I will disable customizer and theme options). Is it possible to use this framework in plugin just by including cs-framework.php, like we do in theme? I tried but I couldn't get it to work. Could you please guide me through it.

Thank you,
Rahul

**Comment by Codestar** [comment]
Hi,

Yes why not, you can use only metabox and shortcodes config. yes, only you will need to include cs-framework.php when init your plugin. yes i can guide you. what you need exactly ?

for eg:

```
.
|── wp-content
|   ├── plugins
|    |   ├── your-plugin-folder
|    |    |   ├── your-framework-init.php
|    |    |   ├── cs-framework
|    |    |    | ...
|    |    |    | ...
```

```php
// your-framework-init.php
define( 'CS_ACTIVE_FRAMEWORK',  false );
define( 'CS_ACTIVE_CUSTOMIZE',  false );
require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';
```

Is it not clear ? or explain your request more :wink: 

Codestar

**Comment by rahulincedia** [comment]
It is clear. Actually I'm new in the plugin territory. I'm not sure why isn't working.

For learning purposes, I'm creating a plugin called Testimonials. Here's what I did:

* Created a folder called _Testimonials_ in plugins and created _testimonials.php_ in it.
* Added plugin name, description, version, etc. and activated in WordPress Admin.
* Created a new folder called _cs-framework_ and add all framework files in it.
* Added `require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';`

After these steps, default theme options and metaboxes should show up but there is nothing there. Am I missing something?

**Comment by santiagointeractive** [comment]
Hi,
Look at this example for using require_once into plugins:

```php
define( 'MY_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );
require_once( MY_PLUGIN_PATH . '/cs-framework/cs-framework.php' );
```
Cheers!

**Comment by rahulincedia** [comment]
@santiagointeractive Thank you for responding :)

I'm working on WAMP. I tried it but it's not working. I'm not able to figure out why.

When I echo `MY_PLUGIN_PATH`, the result is `D:\Work Space\Server\www\Incedia\wp-content\plugins\testimonials/`, when it should be `http://localserver/Incedia/wp-content/plugins/testimonials/`. I googled about it (and also looked into Codestar Framework files), everyone is using `plugin_dir_path( __FILE__ )` to get the directory link. They all work fine on WAMP but for some reason mine isn't working :(

Do you have any idea why?

**Comment by rahulincedia** [comment]
Although this doesn't seem to do it the right way but I managed to get value of `MY_PLUGIN_PATH` to be `D:/Work Space/Server/www/Incedia/wp-content/plugins/testimonials/` using the following code:

```
$path = plugin_dir_path( __FILE__ );
$path = str_replace("\\","/",$path);
define( 'MY_PLUGIN_PATH', $path );
```

But still nothing :(

PS: If you know why `define( 'MY_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );` isn't working for me, please let me know :)

**Comment by santiagointeractive** [comment]
Because your path is <code>D:/Work Space/Server/www/Incedia/wp-content/plugins/testimonials/</code> you should try remove the slah (/) before <code>cs-framework</code> folder and see if it's working:

Replace:
```php
require_once( MY_PLUGIN_PATH . '/cs-framework/cs-framework.php' );
```
With:
```php
require_once( MY_PLUGIN_PATH . 'cs-framework/cs-framework.php' );
```

Hope this will work. Please confirm if it does. Maybe this will help other too.
Thanks!

**Comment by santiagointeractive** [comment]
You could try also directly this:
```php
require_once dirname( __FILE__ ) .'cs-framework/cs-framework.php';
```

**Comment by Codestar** [comment]
Also you can try this.

```php
define( 'MY_PLUGIN_PATH', wp_normalize_path( plugin_dir_path( __FILE__ ) ) );
```

```wp_normalize_path``` will replace from \ to / btw you can share your testimonials plugin with us if it is possible. maybe problem is not this. let's check it.

**Comment by rahulincedia** [comment]
I thought the issue is with the path and I'm not able to include framework in my plugin the right way. But now, as @Codestar pointed out, the issue seems to be somewhere else. Reason being, the code isn't working on a proper server as well. Initially, I thought there is some sort of conflict with my localserver. Plus, when the path is wrong I do get those nasty PHP errors. But when the path is correct nothing happens. Default metaboxes, theme options, etc don't appear. I think `require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';` seems to be doing it's job right. The problem is somewhere else.

I start the plugin yesterday. First thing I did was to include the framework. I have the following code so far:

```
<?php
/*
Plugin Name: Test Plugin
Plugin URI: http://incedia.com/
Description: A plugin that uses Codestar Framework
Author: Incedia Creative Agency
Version: 1.0
*/




// 1. Documentation
require_once dirname( __FILE__ ) .'/cs-framework/cs-framework.php';
$path = dirname( __FILE__ ) .'/cs-framework/cs-framework.php';



/*
// 2. santiagointeractive
define( 'MY_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );
require_once( MY_PLUGIN_PATH . 'cs-framework/cs-framework.php' );
$path = MY_PLUGIN_PATH . 'cs-framework/cs-framework.php';
*/


/*
// 3. Codestar
define( 'MY_PLUGIN_PATH', wp_normalize_path( plugin_dir_path( __FILE__ ) ) );
require_once( MY_PLUGIN_PATH . 'cs-framework/cs-framework.php' );
$path = MY_PLUGIN_PATH . 'cs-framework/cs-framework.php';
*/



// echo $path;

?>
```

In order to figure out the issue without any conflicts or complications, I have made a fresh WordPress install on my dev server and uploaded the plugin. The plugin includes the latest version of the framework.

@Codestar You must have received login info. Feel free to edit plugin code at **WP-Admin > Plugins > Editor**.

@santiagointeractive Please share your email address if you would like to have access to the Test Site.

**Comment by Codestar** [comment]
Hi @rahulincedia 

Today i tried it. Yes you are right. Not loading correctly. I improved path finder. only you will need to update framework file [cs-framework-path.php](https://github.com/Codestar/codestar-framework/blob/master/cs-framework-path.php)

Also, i updated this file on your wordpress. try it on a clean wp and tell me result.

**Comment by rahulincedia** [comment]
@Codestar Now it's perfect! Thank you for fixing it :+1:

**Comment by Codestar** [comment]
You're welcome :+1:

**Comment by sohan5005** [comment]
Hi,

Sorry to bother you again. The framework is not working as a plugin with the latest version of WordPress. Will you take a look @Codestar ?

Thanks

**Comment by NoahjChampion** [comment]
@sohan5005 

I created an issue ticket for you @ https://github.com/Codestar/codestar-framework/issues/354 continue there, please.

It's probably better not to add to this conversation so others don't get notified about something they may not be having an issue with and this is a new issue. Reply on the link above and I will see if I can help you. Codestar is going on holiday for awhile. He may not be able to respond. I'm not sure. So to help, see the issue link above. Thanks. Appreciate it. :)
