### ISSUE TITLE
Can't get all options from the Link field

### ISSUE THREAD

**Issue by pavliukpetro** [Codestar/codestar-framework#95]
Hello,

using the link field from here https://codestarframework.com/documentation/#/fields?id=link

After I echo the field it shows just a url. How can I get the text and target values?

Thank you

**Comment by Codestar** [comment]
Hi,

Uh, interesting. This fields returns like this in my side:

```php
'url'    => '',
'text'   => '',
'target' => ''
```

Also you can check it in the demo.

Regards

**Comment by petropavliuk-valtech** [comment]
Hi. Ok, I will try again and let you know.
Thanks

**Comment by pavliukpetro** [comment]
Still facing the same issue. I am adding the Link in the Customizer.
On you Demo I see the same issue. Please, take a look on the screenshot below.
![Снимок экрана 2021-03-22 в 20 19 58](https://user-images.githubusercontent.com/11602610/112038933-191c6a00-8b4c-11eb-9837-7c6b5c3a9d02.png)
So, the Link object print just this 'opt-link-1' => 'http://qweqwe'. But I added the text as well.

**Comment by Codestar** [comment]
Hi,

Ops, I have just remember. I missed something. It fixed now you can re-download and try it.

Regards

**Comment by Codestar** [comment]
Btw, If you don't want to touch code fields, you can use this filter until next update.

```php
if ( ! function_exists( 'csf_add_complex_fields' ) ) {
  function csf_add_complex_fields( $fields ) {

    $fields[] = 'link';

    return $fields;

  }
  add_filter( 'csf_customize_complex_fields', 'csf_add_complex_fields' );
}
```
