### ISSUE TITLE
Wysiwyg is not working in the group

### ISSUE THREAD

**Issue by hasinhayder** [Codestar/codestar-framework#95]
It just shows a blank white container, without the tinymce editor :(

**Comment by Codestar** [comment]
Hi, Yes Visual Editor issue in group field, i am planing to integration this for next updates. because it is required some javascript. btw, we are talking about this here #30 and #76

**Comment by hasinhayder** [comment]
Hi, 

I have fixed the wysiwyg issue in group repeater. Now it's working perfectly in group without any problem at all. I hope you will merge this pull request.

You can checkout my fork and see how it's working at https://github.com/hasinhayder/codestar-framework

![screen shot 2015-05-18 at 2 48 10 pm](https://cloud.githubusercontent.com/assets/490779/7677373/4959854a-fd6d-11e4-9166-02fb7b5fb72a.png)

**Comment by Codestar** [comment]
Thanks for contribute @hasinhayder coming this fixed in v1.1 :+1:

**Comment by jahir07** [comment]
@hasinhayder (Y)

**Comment by saqibali334** [comment]
Hi hasinhayder,
I have go through all of your code and replace it according to your code but it didn't work bro
How is it working on your side. Did you change visual to text or text to editor in WYSIWYG.
Any Idea about that??
Thanks

**Comment by girisagar051** [comment]
I have the same question as @saqibali334. Do you guys gave any update or fix @Codestar @hasinhayder ? 
Please answer if there is any fix or going to update the framework version with a fix.

Thanks.

**Comment by KaisarAhmmed** [comment]
I used your contributed codestar but group **wysiwyg** is't working.

https://github.com/hasinhayder/codestar-framework

**Comment by wiljonbolten** [comment]
Did you used it in the Theme Options or as a metabox? Because if you use it as a metabox and you will give it an ID of content, it will conflict with the page' content field.

**Comment by KaisarAhmmed** [comment]
Than how can i fix it ? Can you give me code please?
