### ISSUE TITLE
Using CodeStar in plugin

### ISSUE THREAD

**Issue by wpbean** [Codestar/codestar-framework#96]
Hi, 
I am trying to use CodeStar in a plugin and I want to make sure it's not conflict with the themes that are using CodeStar framework. 
Is there any way to do that. I already tried it, but it's not working properly.

Any advise will be helpful.

Thanks

**Comment by Codestar** [comment]
Hi, Please Follow this issue [Using this framework in a plugin #93](https://github.com/Codestar/codestar-framework/issues/93)
