### ISSUE TITLE
Google font is loading only home page

### ISSUE THREAD

**Issue by Khaledgy65** [Codestar/codestar-framework#97]
Hello, I updated Codestar Framework latest version(2.2.2) with my WordPress Theme. When I **select font for heading**, it loads only in Home page, not in others page like category, single post etc. I used such structure for my theme. **Kindly help me to solve this issue.**

            array(
                'id' => 'heading-one-typo',
                'type' => 'typography',

                'output' => 'h1',
                'default' => array(
                    'color' => '#1c1c1c',
                    'font-family' => 'Montserrat',
                    'font-weight' => '700',
		    'font-size' => '42',
                    'line-height' => '50',
                    'subset' => 'latin-ext',
                    'text-align' => 'left',
                    'type' => 'google',
                    'unit' => 'px',
                    'letter-spacing' => false,
                ) ,
                'extra-styles' => array(
                    '300',
                    '400',
                    '500',
                    '600',
                    '800',
                    '900'
                ) ,
            ) ,

**Comment by Codestar** [comment]
Hi,

I have just checked and it works all pages. Can you give more details ?

For eg. Try this color output, isn't work ?

```php
array(
  'id'          => 'opt-body-background',
  'type'        => 'color',
  'title'       => 'Body Color',
  'output'      => 'body',
  'output_mode' => 'background-color',
  'default'     => '#3498db',
),
```

Regards

**Comment by Khaledgy65** [comment]
Hello, I uploaded this. Kindly now check. I set **Poppins** font for menu, but   **does not loading**. show browser default fonts. Kindly check and Help me please.

Link: https://arielthemes.com/demo/recipe

https://i.ibb.co/wSJJTBP/Screenshot-1.png

Coding:
            array(
                'id' => 'nav-typography',
                'type' => 'typography',
                'output' => '.mainmenu ul li a',
	       'output_important'  => true,
                'default' => array(
                    'color' => '#ffffff',
                    'font-family' => 'Muli',
                    'font-weight' => '600',
		    'font-size'      => '18',
                    'line-height' => '23',
                    'subset' => 'latin-ext',
                    'text-align' => 'left',
                    'type' => 'google',
                    'unit' => 'px',
                    'letter-spacing' => false,
                ) ,
                'extra-styles' => array(
                    '300',
                    '400',
                    '500',
                    '600',
                    '800',
                    '900'
                ) ,
            ) ,

**Comment by Codestar** [comment]
Hi,

I have checked and the output generates every page. Didn't you check it in page source ?

But there is an issue, the framework has **csf-google-web-fonts-css** enqueue by default. I can't see this in your source. I guess you have disabled framework web fonts enqueue and using your own like this: **ennlil-fonts-css**

**ennlil-fonts-css** this enqueue loads Montserrat and Mulish but not Poppins. Problem can be this ?

Regards

**Comment by Khaledgy65** [comment]
Hello, I removed that my own CSS google font enqueue function...

https://arielthemes.com/demo/recipe/together-we-can-make-the-world-a-better-place/

But still same issue. I didn't touch Codestar framework hooks or change anything. Just configure it and use like others. Could you Please, **check my theme files please**. I need Your help as **You are the Honorable Author of Codestar framework**. I am sending You the file here. Kindly explore and check the Theme. I hope You will Solve this within few minutes when you see the actual theme files. **Just open main functions.php**, **inc folder -> theme options->###  _theme-options.php and there you get Typography Options** thats It. **Please, help me to fix this.**

**Comment by Khaledgy65** [comment]
**For now I set body font Open sans  and all heading font Rubik. Kindly help me..**

**Comment by Khaledgy65** [comment]
https://i.ibb.co/YR6Js0H/Screenshot-1.png

**Comment by Codestar** [comment]
![image](https://user-images.githubusercontent.com/1313301/113509790-1feda880-9560-11eb-93ae-3c44ee3ebbc2.png)

**Comment by Codestar** [comment]
![image](https://user-images.githubusercontent.com/1313301/113509892-a1ddd180-9560-11eb-9166-e16a6e2330db.png)

You must **remove** that parameter or set **true**

**Comment by Khaledgy65** [comment]
Hi, Thanks. It solved! I forget it to set true....thanks a lot. Best of Luck forever...

**Comment by Codestar** [comment]
You're welcome :)
