### ISSUE TITLE
Request: Date time picker

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#97]
Hello, 

I think <code>Date picker</code> would be really useful for event options.
Also add filter for dev's who need change date format: 

<pre>function date_format( $format ) {
	return 'yy-mm-dd';
}
add_filter( 'x_date_time_picker_date_format', 'date_format', 10, 2 );</pre>

One date picker has in the Optiontree that is really good.

Thanks

**Comment by devariya** [comment]
:+1:  yes ,i am also waiting for this .

**Comment by Codestar** [comment]
Hi, Ok guys, this option field coming in v1.1

**Comment by devariya** [comment]
Great Thank you :+1:  

Date Field
Time Field
Date (Unix) Field
Date & Time (Unix) Field

**Comment by Codestar** [comment]
Yes yes, also i had noted this :wink:

**Comment by devariya** [comment]
love you man :smiley:

**Comment by Codestar** [comment]
love you too :smile:

**Comment by Theme20** [comment]
Awesome, thanks :+1: I'm moving from Optiontree to Codestar :)

**Comment by Codestar** [comment]
Great, Welcome to Codestar Framework :wink:

**Comment by jahir07** [comment]
Still waiting for date and time picker..

**Comment by Codestar** [comment]
Yes we are trying to update our field on future updates, btw if you are in need asap then you can hire us for custom work or some donation would work.

**Comment by NoahjChampion** [comment]
@Codestar 

Just wanted to post a link to a **Date / Time Picker** I found and its Repo. 

It seems to have everything, but I'm not sure because I have never needed to use a date time picker.

Site @ http://trentrichardson.com/examples/timepicker/#tp-examples
Repo @ https://github.com/trentrichardson/jQuery-Timepicker-Addon

**Comment by Codestar** [comment]
Thanks for links... it will be helpful :+1:

**Comment by jahir07** [comment]
thanks a lot

**Comment by Codestar** [comment]
Coming soon... See screenshot:

![support_20160817115125](https://cloud.githubusercontent.com/assets/1313301/17730359/11759580-6471-11e6-99bc-188313100cfb.gif)

**Comment by NoahjChampion** [comment]
Not soon enough :( lol Nice!

**Comment by Codevz** [comment]
@Codestar Nice to see this feature :100:  I hope it does time select in the original code :zap:

**Comment by Codestar** [comment]
Thanks guys, i used jquery ui datepicker. I will send the v2 to yours for beta test. this Weekend.

**Comment by NoahjChampion** [comment]
this will be a GREAT Weekend!

**Comment by Codestar** [comment]
Yes this weekend :+1: i think you will have free-time for test it in weekend :)

**Comment by proscriptsell** [comment]
Great !

**Comment by wiljonbolten** [comment]
Looking forward to it! Just writed some bugfixes with multilangual fields and then I came across this topic!

**Comment by NoahjChampion** [comment]
@wiljonbolten AWESOME!!! Good to see and have you around!!!

**Comment by devariya** [comment]
Great News :+1:

**Comment by wiljonbolten** [comment]
I don't know if it's possible to be in the beta program but maybe i can contribute, I'm working on daily basis with your framework!

**Comment by Codestar** [comment]
@wiljonbolten Can you send detailed information (screenshot or video) about multilangual bugs? via routewp[at]gmail[dot]com

**Comment by wiljonbolten** [comment]
@Codestar No problem, but it's very easy to reproduce; Setup an multilanguage website (I was using WPML) and set 'multilang' => true of a 'group' option. The array will be build the wrong way and was a pain in the ass to fix it, although sometimes getting a wrong array back at the moment. Thinking about to fork the project and place the fix online.

**Comment by Codevz** [comment]
@Codestar Instead of jQuery-ui-datepicker, Please add this one for v2: https://plugins.jquery.com/datetimepicker/ Or  http://mugifly.github.io/jquery-simple-datetimepicker/

Thanks in advance.

**Comment by Codestar** [comment]
@Codevz Yes i understand, there is date and time picker.. i will try to add it :+1:

**Comment by riza** [comment]
Hey, where's datepicker :p

**Comment by mrinal013** [comment]
I try to make a date picker https://github.com/mrinal013/csf-d.

**Comment by hasinhayder** [comment]
Any update on this?

**Comment by quangpro1610** [comment]
@hasinhayder Currently, it's still not updated yet. But I have completed custom, it's very easy 👍

**Comment by mrinal013** [comment]
@quangpro1610, it's fix now.

**Comment by quangpro1610** [comment]
@mrinal013 Thank you, it's working fine 💃

**Comment by stivoox** [comment]
@Codestar Any update about date time picker ??

**Comment by Galibri** [comment]
@Codestar Any update on this feature?

**Comment by quangpro1610** [comment]
> @Codestar Any update on this feature?

It is not updated but you can customize it.
