### ISSUE TITLE
Remove unused options

### ISSUE THREAD

**Issue by pavliukpetro** [Codestar/codestar-framework#98]
Hello.
I have the next case. I added the new option. The text field for example. Added the text and saved it. And after I deleted it from the configuration file. Is it a way to cleanup the database after that?
Thank you

**Comment by Codestar** [comment]
Hi,

You know there is a prefix thing. for eg.

```php
$prefix = '_prefix_my_options';

CSF::createOptions( $prefix, array() );
```

**_prefix_my_options** this is the database option id. You can remove it like this.

```php
// functions.php
delete_option( '_prefix_my_options' );
```

Run this once and remove.

Regards
