### ISSUE TITLE
Add section to the existing panel

### ISSUE THREAD

**Issue by pavliukpetro** [Codestar/codestar-framework#99]
Hello,
is it possible to add section to the existing panel in the Customizer that was already defined by default in WP theme?
For example those sections come from the Woocommerce and I want to add my additional section there.

![Снимок экрана 2021-04-07 в 23 52 36](https://user-images.githubusercontent.com/11602610/113932511-5e06f880-97fc-11eb-918f-074176eb9b57.png)

Thank you.

**Comment by Codestar** [comment]
Hi,

Yes it's possible. for eg. Let's see this example:

```php
// Control core classes for avoid errors
if( class_exists( 'CSF' ) ) {

  //
  // Set a unique slug-like ID
  $prefix = 'my_framework';

  //
  // Create customize options
  CSF::createCustomizeOptions( $prefix );

  //
  // Create a section
  CSF::createSection( $prefix, array(
    'assign' => 'title_tagline', // the exists panel id
    'fields' => array(

      //
      // A text field
      array(
        'id'    => 'opt-text-1',
        'type'  => 'text',
        'title' => 'Text 1',
      ),

    )
  ) );

  //
  // Create a section
  CSF::createSection( $prefix, array(
    'assign' => 'static_front_page', // the exists panel id
    'fields' => array(

      //
      // A text field
      array(
        'id'    => 'opt-text-2',
        'type'  => 'text',
        'title' => 'Text 2',
      ),

    )
  ) );

}
```

As you see there is a "assign" parameter. It's allow to add custom field to exists panels.

Btw, WooCommerce section id's:

```php
'assign' => 'woocommerce_store_notice',
'assign' => 'woocommerce_product_catalog',
'assign' => 'woo-shop-single',
'assign' => 'woocommerce_product_images',
'assign' => 'woo-shop-cart',
'assign' => 'woocommerce_checkout',
```

Regards, Codestar

**Comment by pavliukpetro** [comment]
Hello,
yes it works for adding the new field to the WooCommerce section. But how can I add new section next to existing WooCommerce's sections? 
Thanks

**Comment by pavliukpetro** [comment]
Ok, I added.
I simple create the new section in WP like

`$wp_customize->add_section(
	'woo_single_product_page',
	array(
		'title'    => __( 'Product Page', 'understrap' ),
		'priority' => 10,
		'panel'    => 'woocommerce',
	)
);`
and assign the fields to it.

But I am wonder is I can create the section and add it to the 'panel'    => 'woocommerce' using Codestar Framework.

Thanks

**Comment by Codestar** [comment]
Unfortunately, that's not possible. maybe it can be possible in the next updates.
