### ISSUE TITLE
Metabox: undefined variable: request_key

### ISSUE THREAD

**Issue by Theme20** [Codestar/codestar-framework#99]
Hi, 

I have problem on post and any other post types when i want update post it will show error: https://docs.google.com/file/d/0B7q-ingsr5hKaXBpNlhhdG1tMDg

But in page its working.

Also is there any way to add multiple post type for one meta box, ex: 

<pre>'post_type' => array('portfolio', 'clients', 'post')</pre>

**Comment by Codestar** [comment]
Hi,

You can use same metabox so:
```php
$options      = array();

// only use a variable for same sections.
$sections     =  array(
  'name'      => 'section_1',
  'title'     => 'Section 1',
  'icon'      => 'fa fa-cog',
  'fields'    => array(

    array(
      'id'    => 'section_1_text',
      'type'  => 'text',
      'title' => 'Text Field',
    ),

  )
);

$options[]    = array(
  'id'        => 'page_options',
  'title'     => 'Page Options',
  'post_type' => 'page',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => $sections
);

$options[]    = array(
  'id'        => 'post_options',
  'title'     => 'Post Options',
  'post_type' => 'post',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => $sections
);
```

It is ok ? btw, i did not use **'post_type' => array('page', 'post')** because you know, there is title, id, priority etc. variable method is not diffcult you can use it easy ;) ( btw you can use same id, title )

**Comment by Theme20** [comment]
Hi, 

oh yes, Thanks, its an easy way :+1: 

But still i get error when i want update post but page update works fine. I checked it with default config file and default wordpress theme.

**Comment by Codestar** [comment]
Hi,

Ops, interesting. let's check it. can you send me your theme via codestarframework@gmail.com or write your config file here. :wink:

**Comment by Theme20** [comment]
Not sure why, but again checked it on <b>fresh wordpress installation</b> and everything working fine on all post types. 

Anyway thanks for your helps.

**Comment by Codestar** [comment]
Niceee, You're welcome :+1:

**Comment by Theme20** [comment]
Hi again, 

Today i got php errors again when WP debug is ON, i sent you email.

Thanks

**Comment by Codestar** [comment]
Hi,

Also i am using debug=true in framework developing. it is interesting. Let me check it now.

**Comment by Codestar** [comment]
Hi,

Oh, i found my code error and updated it. only updated your framework files. 46248ef8559768704d1ac937f21c863c6497b812

Thanks for report :100:

**Comment by Theme20** [comment]
It seems solved problem, Thanks a lot man :smiley:

**Comment by Codestar** [comment]
Nicee, you're welcome :smile:

**Comment by Codestar** [comment]
@Codevz 

Since: WordPress 4.4.0 The $screen parameter now accepts an array of screen IDs.

This is meaning we can use array for ```post_type``` from now on... like this:

```php
'post_type' => array('portfolio', 'clients', 'post')
```

Update is #224

**Comment by Codevz** [comment]
@Codestar Nice, Thanks :+1:
